### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by IOctaAdmin** [docker/for-win#10058]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by IOctaAdmin** [comment]
Tried fixing the issues but to no avail.

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.
If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
