### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Nishtha-Pradhan** [docker/for-win#10086]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
  - [ ] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Actual behavior
Docker failed to start
### Expected behavior
Docker running successfully
### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.0.4
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Using Lando

### Steps to reproduce the behavior

  1. Restarted and logged in the system
  2. started lando app

**Comment by Brini06** [comment]
I'm having the same issue but with WSL1 (last version on Docker Desktop on Windows 10).
Would it be because of the rights I changed on file .kube/config?
From WSL, I created a link to /mnt/c/Users/$USER/.kube.

`# Go to your WSL home dir
cd ~
 
# Link the .kube directory in WSL to the one in Windows home directory
ln -nfs /mnt/c/Users/$USER/.kube
 
# Change the rights to remove the following warning that appears whenever you run a helm command:
# WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /mnt/c/Users/$USER/.kube/config
chmod 600 ~/.kube/config`

**Comment by Brini06** [comment]
Restarting Docker Engine as Administrator solved the issue.

**Comment by Nishtha-Pradhan** [comment]
**Found the problem:** docker (3.0.4) was not compatible with lando version (v3.0.24)

My issue was solved like this:
-  uninstalled docker from programs
- restarted system after every weird error 
- re-installed docker compatible to lando
- restart again
