### ISSUE TITLE
cannot ping linux container by name on default network

### ISSUE THREAD

**Issue by minherz** [docker/for-win#1009]
### Expected behavior
Run two named linux containers. Execute `ping` command from one container to another. Ping command is expected to succeed.

### Actual behavior
Ping result is `ping: unknown host`

### Information
Docker for Windows version : Version 17.06.0-ce-win19 (12801) channel stable c98c1c2
Host: Windows 10 Enterprise Version 1703 (OS Build 15063.540)

### Steps to reproduce the behavior

  1. Launch container 1 by `docker run --rm -d --name instance1 centos:7.2.1511 /bin/sh -c "while true; do sleep 1; done"`
  2. Launch container 2 by `docker run --rm -d --name instance2 centos:7.2.1511 /bin/sh -c "while true; do sleep 1; done"`
  3. Run shell in container 1  by `docker exec -it instance1 bash`
  4. In the shell, try to ping container 2 by `ping instance2`

Same happens when pinging container 1 from container 2.
The content of `/etc/resolv.conf` file is
```
# Generated by dhcpcd from eth0.dhcp
# /etc/resolv.conf.head can replace this line
domain localdomain
search medcon.com
nameserver 192.168.65.1
# /etc/resolv.conf.tail can replace this line
```
### Workaround
When I launch above steps for a customer network that was created by `docker network create custom` then everything works and a content of the `/etc/resolv.conf` is different:
```
search medcon.com
nameserver 127.0.0.11
options ndots:0
```

**Comment by jasonbivins** [comment]
Hi @minherz   I can reproduce this - but I'm trying to find out if this is expected behaviour. I'll follow up as soon as I hear back on that.

It's pretty easy to workaround though, you'd need to create a new network for your containers, then join them to it. See below, I named it test for simplicity - 

``` Docker network create Test ```
```docker network connect instance1```
```docker network connect instance2 ```

**Comment by minherz** [comment]
Thank you, @jasonbivins. I also mentioned the workaround in the issue description. However, it requires changes to scripts that we share with automation and production deployment which makes things less desirable.
I will wait for your feedback.
Thank you, again.

**Comment by minherz** [comment]
ping @jasonbivins

**Comment by minherz** [comment]
hello @jasonbivins , is there any update on this issue?

**Comment by guss77** [comment]
As far as I understand, this is the expected behavior. On the default network (what used to be the **only** network), you're supposed to manually link containers using the `--link` option. See here for details: https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/

With the latest versions, linking on the default network is considered a deprecated feature and if you want hostname based discovery, you are encouraged to use user-defined networks.

**Comment by minherz** [comment]
@guss77, can you elaborate on where this expected behavior is defined? this behavior was observed for docker that runs on Windows host. I did not try it on Linux host and it is possible that Hyper-V networking created the problem.

**Comment by guss77** [comment]
@minherz The page I linked previously refers to the expected behavior by declaring it deprecated. See this page for more details about how name resolution inside containers on the default bridge work: https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/ 

Specifically, if you read this document carefully you'd see that there are several ways to configure a container's name resolution features, where by default a container only name resolution feature is to use the host's configured DNS servers (normally only useful to resolve public internet addresses) and the only way to allow a container to resolve other containers is using the `--link` option.

Finally, your Hyper-V comment makes me think that we have a misunderstanding on how "docker for windows" works. I suggest reviewing the Docker For Windows documentation here: https://docs.docker.com/docker-for-windows , but basically how Docker For Windows works (not to be confused with Docker On Windows which has a massively different architecture) is that it creates a single virtual machine on your host (originally using VirtualBox and not Hyper-V, though I understand that with current versions you can choose a different VM software, maybe even Hyper-V) that runs a Linux operating system with the docker service installed inside the Linux VMs. Then all containers are hosted on the Linux VM and all communications between hosts is done completely within the Linux stack - the VM host doesn't see it at all.

**Comment by minherz** [comment]
@guss77 thank you for pointing to that link. the link indeed does not address `--name` parameter and mentions only `--link` as the meaning of resolving container's address from another container on the docker host's default network. It can be assumed that the recent versions of docker has undefined use for the `--name` parameter in the default network. Due discontinuity of the support for `--link` feature, it makes virtually impossible to resolve container address from another one on the default network (without composing a service). If someone from docker core team can confirm the above conclusions, this issue can be closed.

**Comment by guss77** [comment]
@minherz - Please note that the `--name` feature is not a host name resolution feature: its a way to give containers meaningful names when viewed from the host, for example when listing running containers or addressing them in `--link` parameters. `--name` in no way exposes these names to containers (not even the container being named).

And yes, the default network is not considered a valid use case, at least for multi-container setups, and all features supporting container to container communications on the default network are deprecated. The default network is to be used for single-use isolated containers only (that **is** a networking feature - container isolation).

**Comment by thaJeztah** [comment]
This is indeed the expected behavior; name resolution only works for custom networks (for reasons described by @guss77)

**Comment by thaJeztah** [comment]
For the `--name` and `--link` question;

in a custom network, DNS based resolution is performed based on;

- the _name_ of the container (only if a custom `--name` is provided)
- the `--link` option; this option creates a container-scoped DNS entry; only the "linked" container can resolve this name/alias
- the `--network-alias` option allows you to set additional DNS entries for a container

**Comment by minherz** [comment]
OK. Let's close the issue then.
