### ISSUE TITLE
Docker Desktop Crash after installation

### ISSUE THREAD

**Issue by jmawebco** [docker/for-win#10233]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
[Docker-Crash.txt](https://github.com/docker/for-win/files/5882171/Docker-Crash.txt)
[log.txt](https://github.com/docker/for-win/files/5882174/log.txt)

  - [ ] I am using the Docker WSL2 Backend
  - [x ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker Desktop fails to complete load process making it unusable at this time.

### Expected behavior
Normal loading process to complete without error and application opens ready for use.
### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
The answer is at the top of the crash.txt: "In order to use this feature, the legacy console must be disabled."

WSL 2 can't run if you have enabled legacy console mode for your Windows consoles. (This is a Windows restriction, not a Docker restriction, so there's nothing we can do about it unfortunately).
