### ISSUE TITLE
Stuck On Pulling Docker Image cyberark/conjur

### ISSUE THREAD

**Issue by ravics09** [docker/for-win#10275]
### Actual behavior
I tried to pull conjur image using below command:
docker pull cyberark/conjur
It stuck while pulling and not responding. When I tried again to pull the image,  it gives me below error

> Error response from daemon: i/o timeout 

### Expected behavior
It should be pulled from server.
### Information
  - Windows Version: Windows 10
  - Docker Desktop Version: 3.1.0 and 2.5.0.1
  - WSL2 or Hyper-V backend?  HyperV
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:No

### What I have tried so far:

Setting DNS Server to 8.8.8.8 and reset
Disabled and completely uninstalled Firewall (Norton)
Reset Docker to factory defaults
Reinstalled Docker Desktop completely

### Steps to reproduce the behavior

  1. Run docker pull cyberark/conjur

**Comment by mattwelke** [comment]
It works for me, but I'm having the issue I reported a week ago where every image I pull has a delay: https://github.com/docker/for-win/issues/10247

I noticed more details output to the console when I did a build instead of a pull. I used the image in question as a base image for my build. You can see my issue for more details. Can you try that and see if you see docker build output like mine that shows the delay for the "get metadata" step?
