### ISSUE TITLE
Error on running container: "encountered an error during Start failed in Win32: The system cannot find the path specified. (0x3)"

### ISSUE THREAD

**Issue by devito** [docker/for-win#104]
### Expected behavior

Container created and running.
### Actual behavior

PS C:\WINDOWS\system32> docker run -it microsoft/windowsservercore powershell
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 7e2f0768c6e99524263520eca9bcfc70eadd21d1cb4d094d0258177bf40a2367 encountered an error during Start failed in Win32: The system cannot find the path specified. (0x3): Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
### Information
- Diagnostic ID from "Diagnose & Feedback" in the menu.

C95BDA14-020B-41C4-9BC7-CD9F75AB39B9/2016-09-26_16-44-56
- page URL if this is a docs issue or the name of a man page

Following instructions from https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/
- host distribution and version (Windows version, build number, etc)

Windows 10 anniversary (Version 10.0.14393)
PS C:\WINDOWS\system32> docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   c2decbe
 Built:        Tue Sep 13 15:12:54 2016
 OS/Arch:      windows/amd64

Log: [log.txt](https://github.com/docker/for-win/files/494328/log.txt)
### Steps to reproduce the behavior

Download "Docker for Windows" installer and installed
Switch to windows containers
docker pull microsoft/windowsservercore:10.0.14393.206
docker tag microsoft/windowsservercore:10.0.14393.206 microsoft/windowsservercore
docker run microsoft/windowsservercore hostname

**Comment by rneugeba** [comment]
@friism could you take a look?

**Comment by devito** [comment]
I did some more searching online and found this: http://stackoverflow.com/questions/38732280/windows-containers-on-windows-10-anniversary-update-not-working

where this failure came up in the 2nd update.  

I did the following from the top answer:

stop the dockerd service
docker network create -d nat MyNatNetwork (though this got the following failed: Error response from daemon: HNS failed with error : The parameter is incorrect.)

stop the deamon (ctrl-C in the dockerd -D window) 
then started again with:  dockerd -D --bridge "none"

Doing this allowed the container to be created.

So I am unblocked though is there a way to not hit this issue in the first place (or better error messaging on what I can do on my end to fix this)?
Thanks

**Comment by dgageot** [comment]
@devito Can you make sure you have all the latest Windows updates? See here: Microsoft/Virtualization-Documentation#358

**Comment by devito** [comment]
On top of getting the latest windows updates I also had to do the following:

```
 $KeyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList"
$keys = get-childitem $KeyPath
foreach($key in $keys) 
{
                if($key.GetValue("FriendlyName") -eq 'nat') 
                {
                                $newKeyPath = $KeyPath+"\"+$key.PSChildName
                                Remove-Item -Path $newKeyPath -Recurse
                }
}
remove-netnat -Confirm:$false
```
restart system
and then do this
```
net stop hns; del C:\programdata\Microsoft\Windows\HNS\HNS.data; net start hns;
restart-service docker
get-containernetwork
```

I believe when I was investigating this earlier I damaged my virtual network switch.  Doing this additional step corrected that.

Thanks

**Comment by JohnPAguirre** [comment]
Just wanted to say that after a few days this fixed the same problem I had.  Thank you very much!

**Comment by naeemsarfraz** [comment]
@devito thanks for the info you posted, helped me but I'm still not 100%.

I'm now running Win 10 build 14942. I can start a container without any problems except for when I try to use the -p 80:XXXX argument.

`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: failed to create endpoint furious_galileo on network nat: HNS failed with error : Unspecified error.`

 So I still believe there is an issue with the networking. Without the `-p` argument I am using `docker inspect` to get the IP address of the container and browsing to a site hosted in the container using the port I EXPOSEd.

**Comment by dgageot** [comment]
@naeemsarfraz Can you tell us if Beta31, released yesterday, fixes your issue?

**Comment by naeemsarfraz** [comment]
Yes, this is no longer an issue for me

**Comment by galvesribeiro** [comment]
@dgageot / @naeemsarfraz I just have the same issue:

```
docker run --rm -it microsoft/nanoserver powershell
docker: Error response from daemon: container f7c80c57aae47c43cc3c80f9df4f355f213b2d6b5a88151be32b7c8fcee89455 encountered an error during Start: failure in a Windows system call: The system cannot find the path specified. (0x3)
```
The diagnostic id: `0F6418D8-255D-4BCD-91E6-540721CC0C9D/2017-01-06_01-02-39`

I'm using latest Windows Insider update:
![image](https://cloud.githubusercontent.com/assets/4714040/21706107/b9c2e720-d3ab-11e6-86ae-7793fcc422b0.png)

And the `docker --info`: `Docker version 1.13.0-rc4, build 88862e7`

I'm unable to run any container while in Windows Container mode. If I switch to linux, everything works...

Any idea on what it can be?

Thank you

**Comment by gaya3chandran1** [comment]
I have installed docker on windows server 2016.
when I do docker pull microsoft/nanoserver I get the following error
**C:\Program Files\Docker\docker.exe: Error response from daemon: encountered an error during Start: failure in a Windows system call: This operation returned because the timeout period expired. (0x5b4).**

PS C:\Program Files\docker> docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 17.03.1-ee-3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 16 GiB
Name: ips-dev-app3
ID: Q7V3:TPZR:UXTZ:XANH:RUHH:L37J:7OVG:Z3TK:NXLT:73DP:BQAF:TIZE
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
PS C:\Program Files\docker> docker version
Client:
 Version:      17.03.1-ee-3
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ee-3
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   3fcee33
 Built:        Thu Mar 30 19:31:22 2017
 OS/Arch:      windows/amd64
 Experimental: false
PS C:\Program Files\docker>
