### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by gaetancollaud** [docker/for-win#1042]
### Expected behavior

Be able to use docker for windows more than one week after the installation.

### Actual behavior

I cannot start/build anything since I always have the "No space left on device" message. It seems like my MobiLinux disk is full (60/60 gig used)

### Information

 - Diagnostic ID 0DCAC250-7F6C-4EB3-AA58-BD33AD062218/2017-08-25_17-18-28
 - I have the same problem as #600 but this ticket was closed without any solution so I reopen a new one
 - I can see the MobiLinux virtual machine in the Hyper-V Manager, but no way to connect to it. It's like a black box. If someone has some insights on how I can gather more information about it would be helpful. 

I have already run `docker system prune -all` and I tried the commands in #600. Now I have no image and no container left. But I still cannot do anything.

### Steps to reproduce the behavior

Use docker on windows and build a lot of images. It tooks me less than a week since I installed docker for Windows. My images can be heavy: between 500mb and 2gb and I built a lot of them the last week (maybe 50 to 100). This could match the 60go of the MobiLinux VM.

**Comment by friism** [comment]
I agree that this is not a satisfactory situation - out of curiosity, if you do a factory reset, do you get back to a working system?

**Comment by gaetancollaud** [comment]
Thanks @friism it worked ! I just lost my settings, but that was expected and didn't took me long to configure them again.

I saved the hyper-v disk on an external drive if someone is interested on making some more investigations (I can send it by dropbox or other).

**Comment by hinell** [comment]
Next time run ``docker image prune -f`` to remove unused images.

**Comment by gaetancollaud** [comment]
@hinell As said in my ticket description, I already prune everything. the `-f` argument only skips the prompt.

**Comment by hinell** [comment]
@gaetancollaud Ohh yep sorry just missed that part.  Looks like the memory leak.

**Comment by vmarinelli** [comment]
I am encountering this limitation as well. For me the issue is that we are working with large Oracle images populated with test data. Why is it not possible to extend the disk on the MobyLinuxVM? If there's no UI for it, at least give us the ability to access the VM to extend the disk!

**Comment by hinell** [comment]
@vmarinelli I agree. Inability to access native mobyvm is frustrating. I'm forced to use stand-alone virtual machine.

**Comment by jasonbivins** [comment]
Hi @vmarinelli @hinell 
We do have an open enhancement request around the hard coded MobyLinuxVM size, but I don't have an ETA on when that will make it onto the roadmap. There are a few options we're looking at.
For the time being, we do have a manual way to extend the MobyLinuxVM. _Manual changes made to these scripts will be overwritten during upgrades or reinstalls though, so please keep that in mind._ 


Stop Docker
In Windows explorer go  to C:\Program Files\Docker\Docker\Resources and edit MobyLinux.ps1
It's in Program Files, so this will require admin privileges to edit - find line 86
``` $global:VhdSize = 60* 1024* 1024*1024 ```    Change the 60 to number of gb you want allocated to the drive.
Restart Docker

**Comment by gaetancollaud** [comment]
@jasonbivins Thanks for the tip.

But it seems like there is a memory leak somewhere. Increasing the disk has no use because we will reach the physical disk max size at some point.

Are you interested in having the hyper-v disk that I saved just before my reset factory ?

**Comment by Jamby93** [comment]
Even after editing MobyLinux.ps1 with VhdSize of 100GB nothing changed.
Inspecting VHD from Hyper-V correctly says "Current File Size 60GB" "Maximum Disk Size 100GB", but any docker container reports 100% disk usage with a size of 55G and isn't able to create any file.
I don't want to reset to factory default nor to lose downloaded images. How could anyone use Docker for Windows in production if you need to reset it from time to time to restore leaked space?

**Comment by vmarinelli** [comment]
@jasonbivins Thanks very much for that workaround. I was able to get the disk size increased, but I had to add one additional step to your instructions to make it work. After restarting Docker, I had to click "Reset to Factory Defaults". Then when the MobyLinuxVM was rebuilt, it came up with the larger volume.
![image](https://user-images.githubusercontent.com/370059/29976400-e553dd3c-8f07-11e7-9014-4839d9b8f16e.png)

**Comment by hinell** [comment]
@Jamby93 TIP: use ``docker save > foo.img`` and ``docker load < foo.img`` to import and export your images if you don't want do download the again after resetting.

**Comment by Jamby93** [comment]
@hinell Yes, and also backup modified containers, volumes, registry and swarm configuration, networks and so on. That's simply unaffordable on production environment (let's talk about CD infrastructure that builds ton of images a day). All for a bug that simply as no sense at all.

**Comment by 1605200517** [comment]
I have this as well with larger image content files. 

Here is an easy way to retest:

A bash script to create 2x8GB files

```
#!/bin/bash
dd if=/dev/zero of=file1.dat  bs=1M  count=8000
dd if=/dev/zero of=file2.dat  bs=1M  count=8000

```
Dockerfile:

```
FROM ubuntu:latest
WORKDIR /tmp
ADD . /tmp
```
Try to build image:
`docker build . -t foo`

**Output:**
```
Sending build context to Docker daemon  16.78GB
Error response from daemon: Error processing tar file(exit status 1): write /file2.dat: no space left on device
```


**Analysis**
- Why that reference to tar file?! I this setup, there are no tar files
- The  prune command did not help - it has reclaimed only 320 MB space, the error is still there. 
- In the logs, service.txt and the standard one you get via the systray, there is nothing suspicious
- in the MobyLinux.ps1 disk size set to 120GB. Probalbly I need to reset Docker to factory settings as told above.

**Diagnostic ID:** 99071758-71EE-4434-938A-45DEF36AD8C5/2017-09-05_07-54-59

**Docker version:**
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22
 OS/Arch:      linux/amd64
 Experimental: true

**Docker info:**

Containers: 267
 Running: 0
 Paused: 0
 Stopped: 267
Images: 150
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 22.99GiB
Name: moby
ID: MCC6:TLLN:GJGF:FFS7:XBYR:2JPF:OYK3:4CWU:ZHWB:HDQY:S3VP:TCZ2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2017-09-05T06:05:02.8221668Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by cybertk** [comment]
I managed too upgrade the disk size in Hyper-V GUI.

**Comment by e-rol** [comment]
@cybertk That did not work properly for me. Sure, the MobyLinuxVM reported a larger "max disk size" in Hyper-V manager afterwards, but the overlay inside of containers that were then created was still 60GB max:

`[root@db2server /]# df
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         61664044  3899176  54602808   7% /`

It wasn't until I modified MobyLinux.ps1 and "reset to factory default" as described by @jasonbivins and @vmarinelli that the overlay was increased.

**Comment by NdubisiOnuora** [comment]
@jasonbivins, what's the status of the enhancement mentioned at "https://github.com/docker/for-win/issues/1042#issuecomment-326416863"?

**Comment by jasonbivins** [comment]
@NdubisiOnuora   This has been added to the edge channel.  We are also working on some improvements to automatically reclaim space, but I don't have an ETA for those.

![image](https://user-images.githubusercontent.com/28021664/36047491-448d7738-0daa-11e8-8d41-5ec76f3996ce.png)

**Comment by imranrajjad** [comment]
having the same issue on Windows10, I am using oracle12c image hosted at https://hub.docker.com/r/sath89/oracle-12c/

everytime I do a commit or start the container again the MobyVM file keeps on increasing the size until it gets above 60GB. After that you cannot commit, save, load or even start a container.

**Comment by pavel-agarkov** [comment]
problem is still present on:
```yaml
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:42 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by rogierschouten** [comment]
What is the status of stopping the disk leak? This should be a rather high-priority issue given the impact, right?

**Comment by guyonroche** [comment]
Still no fix?
I'm running version 2.0.0.0-win81 (29211) from "stable". Engine is 18.09.0
I have 61.42GB used of 512GB but I can't even run a docker pull command without getting the "no space left on device" error.
Restarting docker gives some relief but not for long.

**Comment by guyonroche** [comment]
Actually - Restarting docker has just dropped all of the images!
Could this be an indication of corruption?
This means I have to rebuild them all which takes a very long time so this is not an adequate workaround.

**Comment by minusdavid** [comment]
I'm running Version 2.0.0.0-win81 (29211) from "stable". Engine is 18.09.0. 

I just resized from 60GB to 200GB via the "Advanced" settings, and everything looks fine for me. Containers are seeing the new space.

**Comment by sticker592** [comment]
@jasonbivins what is the solution on a cloud9 linux environment where I don't have access to the gui, just bash.

**Comment by sylvaingirardbe** [comment]
Fwiw: I debugged this issue using `docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh` followed by a `chroot /host`. You can then check out the filesystem of the moby linux host. All relevant data is in `/var/lib/docker`. I traced my issue to sql server transaction logs that kept filling up the volumes.

**Comment by mmisztal1980** [comment]
still happening in 2019

**Comment by njwest** [comment]
+1 still happening

**Comment by chmorgan** [comment]
I ran into this on OSX, docker 2.0.0.3. I was able to resolve it by restarting docker and quickly opening preferences, going to disk settings and increasing disk size from 64GB to 320GB and hitting apply. That startup failed after a minute but the next restart worked correctly.

I'm surprised this isn't handled more gracefully. I feel bad for the people that have blown away their images to resolve this issue.

**Comment by sahadat84** [comment]
on my mack  remove unused docker images  solved the issue for me. `docker image prune -f`

**Comment by alejandrorossi** [comment]
+1

**Comment by adamczykmichael** [comment]
What did help with my case was shortening the path of the "disk image location". I changed it to "C:\Docker\DockerDesktop.vhdx". Removing the disk image did not help, changing the path did the trick...

**Comment by kgotso** [comment]
+1 Still Happening

**Comment by shashank0033** [comment]
docker system prune -a -f is not fixing  it, I am running docker 
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 getting the error no space left of device 

docker: Error response from daemon: error creating overlay mount to /opt/app/k8s-docker/overlay2/bfbabf0ea0b47485fbabc0d5c43d5b5d72d247b7da42c72d5cd36ead59ac6cae-init/merged: no space left on device.
I am using /opt/app for writing docker data and it has a lot of space . 

Filesystem                 Size  Used Avail Use% Mounted on
/dev/mapper/app_vg-app_lv  3.1T  352G  2.8T  12% /opt/app
[enabler@zlp44493 etc]$ df -ih /opt/app
Filesystem                Inodes IUsed IFree IUse% Mounted on
/dev/mapper/app_vg-app_lv   313M  148K  313M    1% /opt/app

**Comment by rompic** [comment]
is this related to https://github.com/docker/for-win/issues/244
it also discusses some workarounds

**Comment by cpl** [comment]
Is there a clear and definitive solution to this?!

**Comment by baogorek** [comment]
Over in [Issue 244](https://github.com/docker/for-win/issues/244), @ThisIsABug just posted an interesting set of Powershell commands that shrunk my DockerDesktop.vhdx considerably:
```
docker system prune -a -f
net stop com.docker.service
taskkill /F /IM "Docker Desktop.exe"
stop-vm DockerDesktopVM
Optimize-VHD -Path "C:\Users\Public\Documents\Hyper-V\Virtual hard disks\DockerDesktop.vhdx" -Mode Full
start-vm DockerDesktopVM
start "C:\Program Files\Docker\Docker\Docker Desktop.exe"
net start com.docker.service
```
I did have to change the path in the Optimize-VHD step, as my DockerDesktop.vhdx is in C:\ProgramData\DockerDesktop\vm-data

**Comment by ThisIsABug** [comment]
Do not forget to execute my solution in an elevated console :)

**Comment by alexzobi** [comment]
> docker image prune -f

`Total reclaimed space: 40.66GB`  🤣

**Comment by Grynet** [comment]
Would be nice with a fix, as someone pointed out. If this is not a serious issue then what is? 

Makes this unusable in an enterprise environment.

**Comment by Grynet** [comment]
Would be nice with a fix, as someone pointed out. If this is not a serious issue then what is? 

Makes this unusable in an enterprise environment.

**Comment by cjancsar** [comment]
This issue is still occurring in 2020. 

What are the actionable steps to:
- Diagnose the root cause?
- Develop a resolution to the issue?

Since this issue makes docker for windows unusable, and since it has been open for many years, can any of the tagged contributors please make a comment? Is docker for windows actively maintained?
@mikeparker @rn @akimd @samoht @macdja38 @duglin @dave-tucker @akshaybabloo @MagnusS 

Links to hundreds of people have this same issue:
- https://stackoverflow.com/questions/31909979/docker-machine-no-space-left-on-device
- https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device
- https://unix.stackexchange.com/questions/203168/docker-says-no-space-left-on-device-but-system-has-plenty-of-space
- https://forums.docker.com/t/docker-no-space-left-on-device/69205
- https://forums.docker.com/t/no-space-left-on-device-error/10894
- https://forums.docker.com/t/building-container-no-space-left-on-device/13667
- https://forums.docker.com/t/docker-load-i-image-tar-no-space-left-on-device/76361
- https://stackoverflow.com/questions/31909979/docker-machine-no-space-left-on-device
- https://stackoverflow.com/questions/45812401/no-space-left-on-device-even-after-removing-all-containers
- https://stackoverflow.com/questions/48668660/docker-no-space-left-on-device-macos
- https://stackoverflow.com/questions/41227546/how-can-i-fix-no-space-left-on-device-error-in-docker
- https://github.com/docker/for-win/issues/4303

**The workaround to "nuclear option" wipe docker every-time this issue is encountered cripples productivity and is not a solution.**

**Comment by mikeparker** [comment]
Let me try to shed some light on this.

A VM hard disk is like any other disk. If its full, you can't put anything else on it. You can fill up your disk in many ways just like any other hard disk. This isn't a bug with docker, it's simply your containers, images and files/volumes filling up the hard drive.

The VM disk can be filled with multiple different types of things, the most likely is images, as per the OP. The 2nd most likely thing is a folder on disk which a container has been spamming large files (e.g. logs) to. This is a 'volume'.
Other things on disk include stopped containers themselves and networks.

If you want to clean your disk from the command line without checking what you're deleting, you can use `docker system prune`, this command also has many options, see https://docs.docker.com/engine/reference/commandline/system_prune/

Right now, we don't have any GUI to easily show you all the various things stored on your VM disk, so it's hard to tell what exactly your system has dumped on your disk. This is something we are exploring and may come in future (in particular, listing your local images and being able to delete them from the GUI has been discussed a number of times). However, if you are capable with a terminal, it's possible to investigate right now by logging into the VM and exploring the file system like any other linux file system.

An image we often use to do this directly is `docker run --privileged --pid=host -it justincormack/nsenter1` you can then use `du -hs` on various directories to find out whats taking up all the space. 

e.g.
```
/ # du -hs /var/lib/docker
860.0K	/var/lib/docker
```
(fresh install)
```
/ # du -hs /var/lib/docker
70.9M	/var/lib/docker
```
after pulling ubuntu

It's also possible there is a bug in docker taking up all the hard drive space, but given the high number of people (understandably) struggling with disk space management it's hard to conclude there is any bug here. If anyone has gone through their drive in detail as above and still thinks there is a bug causing the drive to fill up, please let me know.

**Comment by akshaybabloo** [comment]
@cjancsar I don't seem to have this issue at all. What virtual machine are you using? Is it Hypervisor or VirtualBox?

**Comment by cjancsar** [comment]
Thanks for the response @mikeparker, we really appreciate your time.

I am really motivated to get to the bottom of this issue, as it has been crippling our teams productivity the passed few weeks and is extremely frustrating. I just want to be able to program in peace :( It really seems to be potentially more than just a simple running out of space issue (based on the numerous highly thumbed up github issues--and if it is a running out of space issue, it is a very bad user experience at the moment as... I have a 2 TB HD why can't I just allocate all of that space to make the problem go away?). 

Can you please examine the diagnostics (CE47E764-D69E-4341-8037-4D9F978ECF6A/20200122200602) that we included to confirm that indeed the VM drive was at 100% capacity when the diagnostic was generated? As I have no way to interpret those files, and have extremely limited information / expertise to be able to reach a conclusion on the issue. **Because the docker desktop UI always shows significant remaining capacity when this issue is encountered and doing a `docker system df` also shows alot of space remaining.** Below is an image of the VM drive space when the issue is occurring: 

![image](https://user-images.githubusercontent.com/51799534/72944980-93830b80-3d48-11ea-9489-23872532fb3c.png)

When we encounter this issue every other day this is the typical workflow that recreates it:

1. Starting of from scratch we could do a `docker system prune --force --all --volumes` to clear the system.
2. We have a multi-service docker compose file, so we build all our containers: `docker-compose build` or `docker-compose up --build` (which take from 40 minutes to 2 hours or more)
3. The containers start correctly and **we get to develop in the environment successfully for a while**. 
4. We switch branches, or we add a new dependency to one of the services, so we need to rebuild that containers dependencies, so we do a `docker-compose down` followed by a `docker-compose build [THAT-UPDATED-SERVICE-NAME]`, then we bring the stack up again with `docker-compose up`
5. The above process repeats a few times, i.e.:

```
docker-compose down
docker-compose build [SOME-SERVICE]
docker-compose up
... we do some work
docker-compose down
docker-compose build [SOME-SERVICE]
docker-compose up -> FAILS: No space left on device error
... we get sad
nuclear option rebuild everything again -> 1 hour of waiting ... 
```
 
What could be the cause of this? The majority of the images are unchanged and are just going down and up. We are just using docker and docker-compose in what we assume is a normal way, but this normal way (for just 10 or so services) is causing extreme frustration. Are we using docker wrong? Are we not supposed to bring services down and up frequently? Are these down'd and upp'ed containers being orphaned or duplicated somehow?

We would also be open to contracting some time for someone with signification experience (like yourself @mikeparker ) to briefly review our stack and workflow to see if it is a usage issue--let me know if there is expertise available for that.

**Comment by mikeparker** [comment]
@cjancsar thanks for the detailed response.

Your diagnostic does indeed show 19.4GB of space left. I have chatted with one of the other engineers and there is another possibility: that your system has run out of inodes. This will likely result in the same error message.

To confirm if this is the case can you please run the following command and paste the output?
`docker run -it --privileged --pid=host justincormack/nsenter1 /bin/df -i /var/lib`

I will hold off advising how to fix until this is clearly the issue. For reference this is due to too many small files on disk. If this is the case its likely a problem with copying source files into images / not trimming intermediate images or a dockerfile ordering issue. Optimising the construction of images is a little difficult but lets check that result first.

**Comment by cjancsar** [comment]
@mikeparker yes, it looks like I am indeed out of inodes when this issue occurs. _I have seen this mentioned in a few of the SO issues I read, but don't know how to convert this into a resolution or find the reason that we are hitting the inode limit when others developers do not_:
![image](https://user-images.githubusercontent.com/51799534/73004892-143c1900-3dd6-11ea-943e-11cd97fe65e5.png)

I have, however, **had a suspicion that the way in which we do our hot reloading volume mounting contributes to this issue (somehow).**  Our anonymous volumes don't seem to get cleaned up between `up` / `down` cycles, but I don't have the expertise to dig deeper into this. In fact, when I did a `docker volume prune` the inode count returned to 35% capacity and **I was able to re-up containers successfully**

After `docker volume prune` operation:
![image](https://user-images.githubusercontent.com/51799534/73006786-33887580-3dd9-11ea-9d86-ef205bab74a1.png)

Then, after re-`up` of containers:
![image](https://user-images.githubusercontent.com/51799534/73007427-87e02500-3dda-11ea-89d3-98770516f22c.png)

`down` command again:
![image](https://user-images.githubusercontent.com/51799534/73007625-d68dbf00-3dda-11ea-818e-c0b8de407c4b.png)

`up` command again:
![image](https://user-images.githubusercontent.com/51799534/73008018-a266ce00-3ddb-11ea-9bac-f402b10ea558.png)

`down` command again:
![image](https://user-images.githubusercontent.com/51799534/73008219-1903cb80-3ddc-11ea-9040-5727f6e3e7d2.png)

`up` command again (**hit inode limit**):
![image](https://user-images.githubusercontent.com/51799534/73008862-70566b80-3ddd-11ea-9fe7-cf2d695b505a.png)

And another round of `down` / `up`, and we encounter the error:
![image](https://user-images.githubusercontent.com/51799534/73008987-a398fa80-3ddd-11ea-9ea8-66aa9c544a4e.png)

And again, can lower inode count with `docker volume prune`:
![image](https://user-images.githubusercontent.com/51799534/73009936-5ddd3180-3ddf-11ea-97c7-38a29cc15b53.png)

> **When I disable our volume mounting strategy the inode capacity stays consistently at 35% and we do not encounter the dangling anonymous volumes after each `up` / `down` cycle, and consequently we do not encounter the `no space left on device` error**. However, we need to be able to do hot reloading of our packages so that we can develop in the multi-service environment and watch our changes. 

Thoughts:
- How can I profile specifically what is consuming the inode count within these anonymous volumes? (Note: These are `NodeJs` services so I am anticipating that the `node_modules` folders are the culprit, and, again that would be necessary for the `watch` / `build` hot-reloading cycle.)
- Can we increase the amount of inodes which are possible? I saw a note from `justincormack` (from Docker) about this, but again, it would be more of a band-aid and wouldn't solve root issue:
![image](https://user-images.githubusercontent.com/51799534/73009529-c24bc100-3dde-11ea-85d0-04d711d3d80a.png)
- Is there a different hot-reloading strategy that we should be following?
- I have read through the `docker` and `docker-compose` cli commands, but, is there a way to ensure that dangling anonymous volumes are garbage collected when the containers they are attached to are `down`d, as what it the point in retaining them, can they somehow be re-attached when you `up` the same containers?

___

As reference, this is the way in which we share our volumes:

```
  some-service:
    container_name: some-service
    ...... other stuff
    volumes:
      - .:/app
      - /app/node_modules
```

**Comment by minusdavid** [comment]
Btw as an aside @cjancsar you can re-size the disk on your Docker host. As I noted above, you can use the Advanced settings in the GUI to increase the disk size. So that "Maximum Disk Size" is actually configurable. You could throw more of your 2TB disk at it.

**Comment by mikeparker** [comment]
@cjancsar great detail, thanks.

It looks like your up/down loop is creating 7GB of volume data every time instead of sharing the same volume for each loop. This is likely because you're using an anonymous volume instead of naming it so its recreated every time and never cleaned up.

Options:
1. Name the volume and reuse the same volume every time you do up/down
2. Remove the volume manually (`docker-compose rm .. -v`, see https://docs.docker.com/compose/reference/rm/)

Even if we raised the inode count you'd still hit the disk space limit before long so it's not really a fix. If this fixes your issue we need to think about how to provide tools to prevent other users hitting this or making it more clear whats going on and what the problem is.

I suppose in a good way its nice to know this isnt a docker bug, but the UI definitely needs some work, or maybe something in docker-compose we can change.

**Comment by mikeparker** [comment]
@cjancsar I spoke to the docker-compose team and they said that anonymous volumes are reused if you do `docker-compose up` again _without running docker-compose down_. 

So option 3 is to stop using `down` and simply re-run `up`.

**Comment by cjancsar** [comment]
@mikeparker yeah, I would recommend maybe throwing a different error when inode count is hit versus storage space being hit if that is possible--it would at least create a future separation in the similar issues (between actual disk storage space vs inode limit being hit). If I knew enough about docker internals I would try for a PR, but alas... I do not. I do however see some tests on the docker engine around the concept of the `No space left on device` error.

I think the main reason we do the `up` / `down` cycle is so we can rebuild the dependencies that are on the docker container (when adding a new dependency or when switching branches). Since our `node_modules` are not shared between host and container (windows to linux), the only way to 'refresh' the dependencies (hit the install stage of the `Dockerfile`) is to bring the container down and rebuild it. If we just do an up again, the re-install stage is not done--we can manually connect to each container and manually re-install dependencies however but generally have just tried to use `docker-compose` cli to manage the system. I think this is just something wrong we are doing with our workflow.

I guess for now, we will continue to see why our inode counts are so high and see if we can do anything to reduce it, as this issue also apparently bleeds into our published images (so if we pull images they also have extremely high `inode` counts). 

@mikeparker thank you for your help, I guess we will continue to try and manually clean our volumes until we can find root cause of why our `inode` count is high.

@minusdavid 
> Btw as an aside @cjancsar you can re-size the disk on your Docker host. As I noted above, you can use the Advanced settings in the GUI to increase the disk size. So that "Maximum Disk Size" is actually configurable. You could throw more of your 2TB disk at it.

Unfortunately, changing the disk size does not seem to effect the inode count, we had already tried this. It seems to be a hard-coded limit.

**Comment by mikeparker** [comment]
@cjancsar the reason your inode count is so high is likely twofold:

a) Each time you docker-compose up you end up with 7GB of volume data, probably with thousands of files
b) You are recreating this volume from scratch every time and not deleting the old one or reusing it.

Ultimately solving (b) is more important than (a), I personally wouldnt spend time on (a) because (b) will solve your immediate problem and the solutions are quick and simple. There are two basic routes to do this:

b1) Reuse the volume from the previous docker-compose up, by naming your volume in your compose file
b2) If you need 7GB of fresh data every time, delete the old one. Simply add -v to the docker-compose down command.

Both of these solutions seem fairly straightforward so I'd be interested if these don't solve the problem.

**Comment by cjancsar** [comment]
Thanks @mikeparker we will trial those suggestions out and monitor how it effects performance! I will keep detailed notes in case things don't work out.

**Comment by mikeparker** [comment]
For reference / clarity, if you want to dig around in the VM to find out where the inodes and space is used:

1. Open a terminal inside the linux vm: `docker run -it --privileged --pid=host justincormack/nsenter1`
2. Use `df -i <path>` to see the inode count or `df -i` to see overall (df = disk filesystem)
3. Use `du -hs <path>` to see the disk usage (du = disk usage)

**Comment by andreasdim** [comment]
Hello, 

What helped me is the following: Edit powershell Script under C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:
Line 86: Change 
`$global:VhdSize = 60*1024*1024*1024  # 60GB`
to whatever you want. In my case:
`$global:VhdSize = 12'*1024*1024*1024  # 120GB`

Then reset docker to factory defaults
![image](https://user-images.githubusercontent.com/48093580/73360252-d2faac00-42a2-11ea-9a18-906fe6ad1ac5.png)


For me that worked:
![image](https://user-images.githubusercontent.com/48093580/73360347-00dff080-42a3-11ea-9ef0-dfd9244d4111.png)

**Comment by mikeparker** [comment]
@andreasdim You can change the VM hard drive size in the settings UI (see https://github.com/docker/for-win/issues/1042#issuecomment-364548229), you dont need to edit powershell.

**Comment by andreasdim** [comment]
@mikeparker Thank you, but I cannot see that option. I'm running docker on Version 
![image](https://user-images.githubusercontent.com/48093580/73362952-11df3080-42a8-11ea-8b92-bfae3c2abad6.png)

**Comment by mikeparker** [comment]
@cjancsar any luck?

**Comment by tophers42** [comment]
@mikeparker I'm also having the problem some users have described. I've allocated 300Gb to the disk image: 
![image](https://user-images.githubusercontent.com/8508014/76355286-4267b080-62d1-11ea-8cdc-e89d3a65b600.png)
but when I look at the docker desktop vm, only ~60gb is allocated.
![image](https://user-images.githubusercontent.com/8508014/76355349-5f03e880-62d1-11ea-9007-73d0fb63e54e.png)
(I tried restarting dockerdesktop)
Our problem is that we actually need to unpack more than 60gb of data inside our build (true this could be done with a mount at run time, but this is the current setup I have to work with). So it's not an issue of cleaning up old volumes/containers. 

For others, I've found a workaround that doesn't require a factory reset by manually updating the image size in Hyper-V Manager:
![image](https://user-images.githubusercontent.com/8508014/76356144-ac348a00-62d2-11ea-87d3-a9a7d34f61d4.png)

I'm not sure if this change will persist through updates though.

**Comment by mat007** [comment]
@tophers42 there is a bug at the moment in Docker Desktop which makes it not resize the VM disk.
To work around this you need to resize it manually, e.g. from an admin powershell:
```
Resize-VHD -Path 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' -SizeBytes 300gb
```
Sorry for the inconvenience.

**Comment by tophers42** [comment]
Thanks @mat007, I also noticed it's marked as a known issue in the latest release notes. Is this the issue to track? https://github.com/docker/for-win/issues/4725

**Comment by Xortrox** [comment]
Seems I still experience this issue myself (v19.03.5 however), but it seems that manually setting my disk to 200GB in hyper-v, then setting it to 200GB in docker for windows AND changing my RAM from 8-4 GB, docker just accepts the new size. I was even able to change it back from 8GB RAM to 4GB and the disk still remained 200GB.

Seems like maybe the disk slider itself is just bugging out?

**Comment by AnushaErrabelli** [comment]
Hello team, did you find a solution for it?, I'm also experiencing the same issue in CI when running docker so it's failing every build!! it says no space left on device

**Comment by tnodet** [comment]
### Don't set both _graph_ parameter in JSON configuration file & _Disk image location_ in Settings ###

>Windows 10, 1809, 17763.1158 - Docker 2.3.0.2 (45183) - Linux containers

I had the **"No space left on device"** error for a totally different reason and wanted to share the solution to my specific problem.

I wanted to change the location of my docker images, and ended up setting both:
* `"graph": "/D/path/to/docker/images` in the engine's _JSON configuration file_ (Settings → Docker Engine)
* `D:\path\to\docker\DockerDesktop` as _Disk image location_ (Settings → Resources)

Then, when trying to pull images through docker-compose, I kept having errors:
```ERROR: for image_name write /D/path/to/docker/images/tmp/GetImageBlob<uid>: no space left on device```.

After removing the `"graph"` parameter (keeping only the _Disk image location_), I could pull images normally.

I was confused by the fact that on Windows, when using Linux containers, images are not actually on the Windows file-system but in the file-system of the *.vhdx Hard Disk Image File of the Mobby Virtual Machine. But apparently setting both parameters provokes a weird behavior in Docker.

**Comment by byt3pool** [comment]
I stumbled upon this problem for the first time today:
A `docker system prune -a` followed by `docker volume prune` did the trick for me.

Docker reclaimed nearly 55 GB.

**Comment by kwabena53** [comment]
> ### Expected behavior
> Be able to use docker for windows more than one week after the installation.
> 
> ### Actual behavior
> I cannot start/build anything since I always have the "No space left on device" message. It seems like my MobiLinux disk is full (60/60 gig used)
> 
> ### Information
> * Diagnostic ID 0DCAC250-7F6C-4EB3-AA58-BD33AD062218/2017-08-25_17-18-28
> * I have the same problem as #600 but this ticket was closed without any solution so I reopen a new one
> * I can see the MobiLinux virtual machine in the Hyper-V Manager, but no way to connect to it. It's like a black box. If someone has some insights on how I can gather more information about it would be helpful.
> 
> I have already run `docker system prune -all` and I tried the commands in #600. Now I have no image and no container left. But I still cannot do anything.
> 
> ### Steps to reproduce the behavior
> Use docker on windows and build a lot of images. It tooks me less than a week since I installed docker for Windows. My images can be heavy: between 500mb and 2gb and I built a lot of them the last week (maybe 50 to 100). This could match the 60go of the MobiLinux VM.

This helped me. On Ubuntu 18.04
docker system prune --all --force

**Comment by kwabena53** [comment]
Run `docker system df` to see what is taking up space on your docker

Then run:

`docker system prune --all --force`
to remove all hidden and unused containers. Now run

`docker volume prune`
docker system prune does not remove all unused containers.

**Comment by Bill0412** [comment]
> @NdubisiOnuora This has been added to the edge channel. We are also working on some improvements to automatically reclaim space, but I don't have an ETA for those.
> 
> ![image](https://user-images.githubusercontent.com/28021664/36047491-448d7738-0daa-11e8-8d41-5ec76f3996ce.png)

The error for me is
```
d532e87af17e: Loading layer  18.73GB/19.53GB
Error processing tar file(exit status 1): write /swapfile: no space left on device
```

Your solution works for me, thanks!

I increased the disk image size limit from 68GB to 144GB, memory from 2GB to 8GB and swap from 1GB to 4GB.

![image](https://user-images.githubusercontent.com/33972245/98317192-05e28500-2017-11eb-96dd-7895ee369afe.png)
