### ISSUE TITLE
E8D72681-CBE2-414A-9426-76345B717B96/20210225165151

### ISSUE THREAD

**Issue by ma-user** [docker/for-win#10478]
************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without a clear title, description, and diagnostics ID cannot be debugged,
and will be closed.
************************************************************************************

-->

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
