### ISSUE TITLE
address hard coded max size of hyper-v machine disk 

### ISSUE THREAD

**Issue by whyzdev** [docker/for-win#105]
### Expected behavior
- The max size of MobyLinux.vhdx is expected to be configurable during installation and reset. 
- User may want to grow/shrink the vhdx and docker host partition in Docker settings, on best possible effort basis.
### Actual behavior

Currently the max size of MobyLinux.vhdx is hard coded to 60GB in MobyLinux.ps1. As workaround, user may change MobyLinux.ps1 the size and reset in Docker settings for the change to take effect after re-initialization. (Other possible workaround without losing data may involve using powershell to resize the vhdx, and then somehow rooting into the host OS (Alpine?) and resize the partition.)
### Information

e.g. Windows 10
### Steps to reproduce the behavior

 See the actual behavior above.

Thanks!

**Comment by rneugeba** [comment]
Hi @whyzdev thanks for your suggestion. This is one of the features on our roadmap, but we don't have an ETA for it yet.

The VHDX is dynamically sized, so it only grows when in use. There is a potential way to shrink it once files are deleted, but we haven't implemented/tested it yet.

/cc @dgageot

**Comment by whyzdev** [comment]
yep, dynamical growth of vhdx and vm partition currently works till the preset maximum size is reached. When vhdx is manually resized larger, the vm partition also need manual resize.

**Comment by Renkas** [comment]
any update on this? How to increase the Hyper-V image size (and partition in it)?

**Comment by allustin** [comment]
Why this param so dirty ? May be put it into settings ?

![image](https://user-images.githubusercontent.com/55323/32644906-93af2fca-c5f5-11e7-833d-12492ad43a26.png)

**Comment by pgayvallet** [comment]
Available on latest edge, should be shipped in 18.03 stable.

**Comment by jonathanperret** [comment]
Unfortunately, the max size is limited to 256GB. As surprising as this may seem, I'm currently working on a scenario where I'd like to devote most of a 512GB SSD to Docker for Windows. And this is not a production workload, just a developer machine so I feel this should be within the scope of the product.

May I respectfully suggest that this slider should allow choosing a disk size as large as the host disk? The VHDX format apparently supports disks up to 64 TB so this should not be an issue.

Fortunately, directly resizing the VHDX in Hyper-V manager (while the VM is shut down) lets one work around the issue, since the VM seems to happily extend its filesystem to the new size upon boot.

Unfortunately, if you do this (resize the disk past 256GB) the Advanced settings panel becomes unusable because everytime you click Apply, it thinks you have reduced the disk size and wants to destroy the disk. I needed to change the RAM allocation and ended up hand-editing `%USERPROFILE%\AppData\Roaming\Docker\settings.json`.

**Comment by jasonbivins** [comment]
@jonathanperret   Can you please submit your request as a new issue ?

![image](https://user-images.githubusercontent.com/28021664/37614650-a956bb8a-2b81-11e8-8c3c-9e59fec0be1d.png)
