### ISSUE TITLE
27E30A34-EB9D-4FE9-B44A-203BF6D54122/20210301191128

### ISSUE THREAD

**Issue by robe1970** [docker/for-win#10508]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
27E30A34-EB9D-4FE9-B44A-203BF6D54122/20210301191128
### Information

  - Windows Version: widows 10 pro
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
