### ISSUE TITLE
docker.for.win.localhost deprecated without clear communication 

### ISSUE THREAD

**Issue by welja** [docker/for-win#10619]
Just a complaint and help for other who use docker.for.win.localhost on their development machine.

docker.for.win.localhost is removed, now you should use host.docker.internal.

I use it for communicating from a docker webdevelop container to MariaDB on the host.
To bad that Docker for Win doesnot show a changelog or other warning of REMOVAL of certain settings.

I am sorry for the rant, the update just installed (Docker version 20.10.5, build 55c4c88) and it is early, i have a deadline, i only drank one coffee and i forgot to NEVER UPDATE THINGS when you have deadlines.

**Comment by StefanScherer** [comment]
Thanks @welja for your feedback.

I hope you had your second cup of coffee ☕  and that you are able to finish your work now running with the latest Docker Desktop 3.2.1 release. 🙌 

Indeed, due to some refactoring in our code base we removed the long time deprecated DNS name `docker.for.win.localhost`. The process to collect the release notes didn't catch this change. I'll add a deprecation note to the [Docker Desktop 3.2.0 release notes](https://docs.docker.com/docker-for-windows/release-notes/#deprecation) soon.

We've introduced the DNS name `host.docker.internal` now nearly three years ago with the [Docker Community Edition 18.03.0-ce-win59 release](https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-18030-ce-win59-2018-03-26) and mentioned that the other experimental DNS names are deprecated.
> DNS name host.docker.internal should be used for host resolution from containers. Older aliases (still valid) are deprecated in favour of this one.

I'm glad you could find the solution.

**Comment by welja** [comment]
Yes i did have a second cup. And thanks for the explanation!
And i love Docker btw.
