### ISSUE TITLE
Docker failed to start.

### ISSUE THREAD

**Issue by azmisecure** [docker/for-win#10661]
After installing Docker, I get this error.

Docker failed to start.

![image](https://user-images.githubusercontent.com/62207733/111268003-b8c09080-8652-11eb-99c8-c1172953fcc1.png)

Please help.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by azmisecure** [comment]
Windows Version: 10 Home
Docker Desktop Version: 3.1.0
WSL2 or Hyper-V backend? WSL2
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Windows based laptop on Ubunto VM

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
