### ISSUE TITLE
Failed to upgrade due to docker-machine.exe was in use

### ISSUE THREAD

**Issue by adamsolymos** [docker/for-win#1069]
### Expected behavior
Auto-update dialog came up. I clicked to Run update without stopping the docker machine.
I expected to finish the update or at least warn me to stop docker machine before able to update.

### Actual behavior
It started the update, then gave me a "Failed to update" message with some back trace. When I closed this message, it fully disappeared from my system. In Program Files, Docker folder contained only the docker-machine.exe (probably because it was locked by windows, and this caused the fail) but nothing else. Docker or Docker update was not running, and I could not restart the process. I had to download and install again. (Perhaps I could find the downloaded new version in some temp dir, but I was not sure where to find.)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
43A128C2-4E9C-4C31-ABE2-992FD15973F4/2017-09-06_16-16-25

  - a reproducible case if this is a bug, Dockerfiles FTW
I was updating from previous stable version to 17.06.2-ce-win27 (13194) by the built-in update process.
Docker-machine was running and in use (at least an SSH open) during the update.
It failed to update, probably at the moment of removing previous version, because docker-machine.exe was locked by windows.

  - page URL if this is a docs issue or the name of a man page
N/A

  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro (64 bit)
VirtualBox version 5.1.14 r112924 (Qt5.6.2)
Docker version before the update: not sure, but a not too old version (since the last update)
Docker version to update to: 17.06.2-ce-win27 (13194)

### Steps to reproduce the behavior

  1. Docker-machine is running and in use (at least one SSH is open)
  2. Start update from previous stable version to 17.06.2-ce-win27 (13194) by Docker's built-in update process.
  3. It fails in the middle of to update process, probably because docker-machine.exe was locked by windows.
  4. Docker is gone, disappeared from start menu and disk too. Not running anymore. Did not even say good-by.

**Comment by jgraycs** [comment]
I had the same issue, and when I try to re-install Docker I get the following error:

> Access to the path 'C:\Program Files\Docker\Docker\resources\com.docker.9pdb.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
>

**Comment by rblanconeira** [comment]
Same as @jgraycs here.
Cannot use, remove or re-install Docker.

**Comment by spgriffin** [comment]
I had one machine upgrade successfully, but I had the same issue with another.  I fixed it by deleting all contents in the Docker directory under Program Files.  You will not be able to delete the resources directory containing com.docker.9pdb.exe, but this will be removed automatically after reboot.  Reinstall Docker using the latest version.

**Comment by jasonbivins** [comment]
Hi @adamsolymos 
Try deleting or renaming  this registry key - then reinstall.

SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker for windows\xxx

**Comment by jgraycs** [comment]
Thank you @spgriffin! Your suggested workaround was successful for me, as well. I have Docker running again.

**Comment by adamsolymos** [comment]
@spgriffin @jasonbivins Thanks for the tips. Actually, I was able to reinstall Docker the same way, just wanted to file a bug.

**Comment by jgraycs** [comment]
And now the next Auto Update failed.... 17.09.0-ce-win33

> Access to the path 'C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__23.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()

Actually both docker.exe and docker-compose.exe are left behind by the update.  This one is worse than the one before, because I'm not able to manually delete the file, even when running as an Admin. reboot didn't help either.

I haven't seen any feedback from Docker on the prior issue. Is anyone from Docker looking at how their Windows 10 updates work? Since it's happened to me two times in a row, I'm concerned about ever trying to update again, assuming I can even install it again....

**Comment by ElLeopard** [comment]
I've the same issue: "Fail to upgrade to 17.09.0-ce-win33 (13620) from version 17.06.0-ce-win19 (12801)."
Added the exception below. I have tried rebooting etc, but still end up with the same problem. I'll try the workaround suggested above.
---

The process cannot access the file 'C:\Program Files\Docker\Docker\com.docker.service' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()

**Comment by ElLeopard** [comment]
Unfortunately, the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker for Windows" is not present at all on my computer (but I'm still not able to upgrade).

**Comment by ElLeopard** [comment]
I can confirm that @spgriffin approach works. I killed the com.docker.service process, and then removed the "c:\Program Files\Docker" directory, and did a new install.

**Comment by GrzegorzKozub** [comment]
Same issue here

**Comment by konstantinblaesi** [comment]
Stopping the HyperV VM was enough for me
