### ISSUE TITLE
Docker images are not accesible on windows.  

### ISSUE THREAD

**Issue by brrr123** [docker/for-win#10766]
The virtual ip for the docker doesn't forward ports and the docker  image is not accessible

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
