### ISSUE TITLE
My Instance's TCP Ports are not working!

### ISSUE THREAD

**Issue by AbacusCdilla** [docker/for-win#10803]
My Instance's TCP Ports are not working!?

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
