### ISSUE TITLE
Recurrent crash at startup

### ISSUE THREAD

**Issue by ssauvage-git** [docker/for-win#10811]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 97179733-A718-407D-958F-8160C4E9227B/20210402072443

### Information

  - Windows Version: 20H2
  - Docker Desktop Version: 3.2.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
