### ISSUE TITLE
Diagnostic ID A34FF21E-3649-465C-A0B4-1764008CC871/20210402112722

### ISSUE THREAD

**Issue by andreotti69** [docker/for-win#10815]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: A34FF21E-3649-465C-A0B4-1764008CC871/20210402112722

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by andreotti69** [comment]
A34FF21E-3649-465C-A0B4-1764008CC871/20210402112722

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
