### ISSUE TITLE
Shared memory between containers does not work as it should: --ipc=host --isolation=process --user ContainerAdministrator

### ISSUE THREAD

**Issue by wbudd** [docker/for-win#10862]
Duplicate of: https://github.com/docker/for-win/issues/2208

Steps to reproduce:

1) Create a file mapping in a process (as admin) on the host with:
`HANDLE fm = CreateFileMapping(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE, 0, BUF_SIZE,  L"Global\\MyFileMappingObject");`

2) Run a container with `docker run -it --rm --isolation=process --ipc=host --user ContainerAdministrator ipctest:latest`

3) Try to open said file mapping in a process (as admin) within the new container with `HANDLE fm = OpenFileMapping(FILE_MAP_ALL_ACCESS, FALSE, L"Global\\MyFileMappingObject")`: this fails with a GetLastError() value of 2 (File Not Found).

(I'd rather not create a duplicate issue, but because your trigger-happy docker-desktop-robot closed that issue and disallowed any comments before any of you bothered to reply to it, I don't see what other option I have. Correct me if I'm wrong though.)

**Comment by stephen-turner** [comment]
Thanks for the ticket. Unfortunately this is the wrong repository for it. The Windows container implementation is just an upstream to us, which we expose in Docker Desktop. (And it was not written by Docker employees).

The correct repository is https://github.com/moby/moby, so you could try opening a ticket there. (I would move the ticket for you if I could, but it's not possible because moby/moby is not even part of the docker org). What I'm not sure about is whether shared memory across containers is even supposed to work.

**Comment by wbudd** [comment]
@stephen-turner 
I see... In that case I will open a ticket over at moby. Thanks for the quick pointer.

> What I'm not sure about is whether shared memory across containers is even supposed to work.

If not, I'm not sure what the point is of the `--ipc` flag then?
Quoting the ohe official docs at https://docs.docker.com/engine/reference/run/#ipc-settings---ipc : 
> Shared memory segments are used to accelerate inter-process communication at memory speed

If you mean you're not sure about memory sharing between _Windows_ containers and/or hosts, then Docker Desktop should throw an error whenever the --ipc flag is specified on a Windows host: silently accepting flags that are not supported is a bug.
