### ISSUE TITLE
Vmmem consuming large amount of cpu and memory with out even using docker or wsl 

### ISSUE THREAD

**Issue by gokuljs** [docker/for-win#10874]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:10.0.19042 Build 19042

  - Docker Desktop Version: 20.10.5
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

![Screenshot (233)](https://user-images.githubusercontent.com/51263906/114125646-82ee8f00-9914-11eb-992b-a5cafa16c7f7.png)

**Comment by gokuljs** [comment]
For time being I have done wsl--shutdown . Is there any way to restart it

**Comment by madalinignisca** [comment]
https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig

Set your memory limits lower for WSL2. This has nothing to do with Docker. Microsoft allowed 80% ram allocation by default, and fixed this in future build (not stable yet).

You can manually control WSL2 from the above suggestions and get your vmmem nice.

Example, I set it up to 8GB as I have 16GB and works really nice since than. Tweak memory to your needs, even if you have 32 or 64GB or ram.

The real problem is caused of aggressive caching, something easy to tweak by Microsoft in a next wsl2 kernel release I think (I know I can tweak caching on my Ubuntu installation).

**Comment by madalinignisca** [comment]
PS: for the feature when they release the fix for Windows 10 (it's not separated), they intend to limit to max 8GB even if you have larger amounts of ram. If you have for example 64GB of ram and want 32GB allocated to WSL2, than you still need to do the .wslconfig as I suggested in my previous comment, if not, it will be limited to 8GB and you'll not understand why.

**Comment by gokuljs** [comment]
Thanks
