### ISSUE TITLE
Docker reinstall removes existing containers.

### ISSUE THREAD

**Issue by jTiKey** [docker/for-win#10895]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
After an update, docker stopped starting. I reinstalled it using the docker uninstall. It removed all existing containers.
### Expected behavior
Have a prompt to not remove existing containers when reinstalling/uninstalling.

**Comment by stephen-turner** [comment]
I believe Uninstall completely removes everything (and is what I would expect), but reinstalling over an existing installation retains the containers. Does that match what you're seeing?

**Comment by jTiKey** [comment]
> I believe Uninstall completely removes everything (and is what I would expect), but reinstalling over an existing installation retains the containers. Does that match what you're seeing?

Yeah, great that there's an option to save the containers. Would be good for it to be more obvious, since reinstalling on existing installation rarely work for software, and most people would just clean install it. Though a warning would be appropriate. When I was the "removing containers/images" it was too late :D I think Vagrant doesn't remove the images unless you explicitly say so.

**Comment by karlmacklin** [comment]
Does anyone know how to not remove the containers when trying to install an older version?

I have the same problem as issue author here. Latest Docker Desktop just wont start (as many separate issues have mentioned).
I have downloaded the previous version.

But it simply show that it is up to date:

![image](https://user-images.githubusercontent.com/353806/114515674-e5110200-9c3c-11eb-9f70-d4af222759d7.png)

There is no option to reinstall. I'm basically locked now since I can't uninstall Docker Desktop without losing my containers, and I can't install an older working version.

**Comment by jTiKey** [comment]
> Does anyone know how to not remove the containers when trying to install an older version?
> 
> I have the same problem as issue author here. Latest Docker Desktop just wont start (as many separate issues have mentioned).
> I have downloaded the previous version.
> 
> But it simply show that it is up to date:
> 
> ![image](https://user-images.githubusercontent.com/353806/114515674-e5110200-9c3c-11eb-9f70-d4af222759d7.png)
> 
> There is no option to reinstall. I'm basically locked now since I can't uninstall Docker Desktop without losing my containers, and I can't install an older working version.

I don't think you can install an older version. It would automatically install the newest.
Maybe make a copy of the container folder?
