### ISSUE TITLE
Docker Desktop is not starting up after restart. 

### ISSUE THREAD

**Issue by spacefuntus** [docker/for-win#10918]
Docker desktop is not starting up after restart. Every time i have to reset to factory default to make it work. Anyone else facing the issue ? also the menus are gone to restart docker and other stuff

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
