### ISSUE TITLE
Error on start every time, even after reset to default

### ISSUE THREAD

**Issue by p5harma** [docker/for-win#10925]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by p5harma** [comment]
DiagnosticID : C4C5F7DD-057A-44D7-8EBA-6CF42BF365BC/20210414172455

**Comment by stevenobird** [comment]
Same for me - the Desktop Client seems to start, but com.docker.service seems to hang up on something.
When closing & re-opening Docker Desktop Client and restarting said service, everything seems normal.

Logs don't help that much (and I cannot send diagnostics since I do not get any kind of error pop-up)
