### ISSUE TITLE
Installer rollback is incomplete

### ISSUE THREAD

**Issue by jochenw** [docker/for-win#10986]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior

If the Installer encounters an error (in my case the "The handle is invalid", see #10984), then it will attempt a rollback: It removes the directory c:\Program Files\Docker\Docker). As far as I can tell, this rollback is incomplete:

  - There are entries left in the registy: If I start the installer again, I get messages like "Docker is already installed", effectively preventing me from running the installer. Besides, launching the Installer with "uninstall" gives the message

        [12:04:10.975] [Program] Existing installation found: version=62916, displayVersion=3.3.0, basePath=C:\Program
        Files\Docker\Docker, channelUrl=https://desktop.docker.com/win/stable/amd64/appcast.xml

  - The directory c:\Program Files\Docker is kept. (The directory is empty, so not a real problem.)
  - Although the Installer didn't complete, Docker is present in "Add or remove programs". (Of course, the uninstall cannot be launched, because the file c:\Program Files\Docker\Docker\Docker Desktop Installer.exe has been removed by the rollback.)
  - 

### Expected behavior

All of the above installation fragments should be removed by the rollback. Starting the installer again should run just like it
was never started.

### Information
  - Windows Version: Windows 10 Enterprise, OS build 19041.928
  - Docker Desktop Version: 3.3.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by stephen-turner** [comment]
Thanks, I've raised an internal ticket for this.

**Comment by wouterpotters** [comment]
Same issue here (win10):
1) new installation does start (3.3.1), however it fails because for some reason the internet connection dropped.
2) rerunning the reinstallation states "3.3.1" is already up to date (although there is nothing in the C:\program files\Docker folder and no shortcuts are added and no docker services are running)
3) uninstalling does not work, because the uninstaller could not be found in the C:\program files\Docker\Docker Desktop Installer.exe (which is not there, because the installation failed?)
4) manually dropping the installer (Docker Desktop Installer.exe) in that program files folder results in the same uninstaller not found error

**Comment by stephen-turner** [comment]
As a lesser workaround, I think just changing HKLM/software/Microsoft/Windows/CurrentVersion/Uninstall/Docker Desktop/Version to a lower number should work.
