### ISSUE TITLE
Volume mounts do not work on windows 10 until I provide full path

### ISSUE THREAD

**Issue by Scaum** [docker/for-win#11000]
This isn't documented anywhere, and the issue reporting this has been closed with no answer / no action plan / nothing...

https://github.com/docker/for-win/issues/3885

At the very least, keep the issue open so that people don't loose hours trying to understand what is wrong....

**Comment by stephen-turner** [comment]
In the original ticket, the reporter tried to use
`docker run --rm -v dockertest:/data alpine ls /data`
which will attempt to mount a named volume called `dockertest` rather than a directory. This is the same on all platforms and is documented at https://docs.docker.com/storage/volumes/.

I agree that the `-v` syntax can be a bit confusing, which is why it's simpler to use the more verbose `--mount` syntax instead of `-v`, as the latter is overloaded. If you do that, you will get the message `invalid mount path: 'dockertest' mount path must be absolute`.
