### ISSUE TITLE
Docker desktop uses a lot of cpu

### ISSUE THREAD

**Issue by GautierDele** [docker/for-win#11085]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics (no diagnostic)
  - Diagnostics ID:

### Actual behavior

Docker uses a lot of cpu and is actually making environments pretty long

### Expected behavior

Normal fonctionning

### Information

  - Windows Version: 10
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GautierDele** [comment]
Plus it keep crashing, really something is wrong i never had that before, i can't work right now

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
