### ISSUE TITLE
Error invoking remote method 'desktop-go-backend': Error: Internal Server Error

### ISSUE THREAD

**Issue by alexmro** [docker/for-win#11131]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When I click Open in Visual Studio Code button I get this error in a red banner on top of the window.

![image](https://user-images.githubusercontent.com/74217337/117316192-0908e180-ae91-11eb-9ece-19e7554c6d29.png)

### Expected behavior

It should open the Visual Studio Code app (which is installed along with the WSL extension.

### Information

  - Windows Version: Windows 10 Pro (19042.928)
  - Docker Desktop Version: 20.10.6, build 370c289
  - WSL2
  - Running inside a virtualized Debian from Microsoft Store
  - Trying to open a Laravel (with Sail) codebase (the container runs properly)

### Steps to reproduce the behavior

  1. Open application
  2. Click Open in Visual Studio Code

**Comment by Pawel-Kranzberg** [comment]
same here

**Comment by haakastadir** [comment]
I also have the same issue

**Comment by markponce** [comment]
same here

**Comment by MeatWant** [comment]
Same also here. Found Solution:

i delete the directory:  `/home/xxxxx/.vscode-server/` in the WSL/Distribution

because the directory `/home/xxxxx/.vscode-server/bin/xxxxxxxxxxxxxxxxxxxxxxxxxx/`  was empty

i come there because console Output in VSC say:

`/home/xxxxx/.vscode-server/bin/xxxxxxxxxxxxxxxxxxxxxxxxxx/bin/code: not found`

After deleting the directory and restart VS Code the needed files are reinstalled
