### ISSUE TITLE
Unable to launch cmd in docker linux container  using dot net core

### ISSUE THREAD

**Issue by kishorekittu76** [docker/for-win#11227]
I'm trying to run CMD through a docker container that contains c# code that runs cmd.exe and does a simple echo command. The problem I keep on getting is when I call docker run I get a weird error that I have found online but no solution to my issue. Any help will be appreciated!
 - I want to run BCP command using cmd in linux container please help me out its urgent .

 
Code:

capture

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
