### ISSUE TITLE
Docker Error Cannot Start Multiple Services - mkdir /run/desktop/mnt/host/c: file exists'

### ISSUE THREAD

**Issue by koitoror** [docker/for-win#11245]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
![Annotation 2021-05-19 023026](https://user-images.githubusercontent.com/35098691/118736236-c4932380-b84a-11eb-8f45-0852e570f6df.png)

### Expected behavior
It'd be nice if Docker wouldn't crash and throw errors under these circumstances.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - running inside a virtualized Windows 10 (improved docker ui thats faster) with gpu

### Steps to reproduce the behavior

  1.  run "C:\Program Files\Docker\Docker\Docker Desktop.exe" and open both windows bash and wsl Ubuntu
  2. Using the CLI, attempt to start a multi-service docker container 
  3. runs "C:\Program Files\Docker\Docker\Docker Desktop.exe" .
  4. This exception is thrown. 'Cannot start service nginx: error while creating mount source path '/run/desktop/mnt/host/c/Users/Adm/Desktop/coding/DEGEM/LMS/nginx/default.conf': mkdir /run/desktop/mnt/host/c: file exists'

**Comment by djs55** [comment]
@koitoror Thanks for your report. Could you follow the troubleshooting guide [here](https://docs.docker.com/docker-for-windows/troubleshoot/#in-app-diagnostics) to upload a diagnostic report and then quote the ID here? This will allow us to look at the logs.

Could you also provide a small repro example `docker-compose.yml` which we could test?

**Comment by LouNogueira** [comment]
Same type error with jekyll-serve...

1. First time, I'd ran a `$ docker run -p 8080:4000 -v $(pwd):/site bretfisher/jekyll-serve` and it worked out fine. 
2. Shutdowned Docker Desktop. 
2. Reboot. 
3. Restarted Docker Desktop.
4. Removed all containers and volumes.
5. When I'd ran again the same `docker run -p 8080:4000 -v $(pwd):/site bretfisher/jekyll-serve`.
6. Received the error message: "docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/c/Users': mkdir /run/desktop/mnt/host/c: file exists."

I suspect I should kill some particular file(s) / directory(ies) in order to free up that location. But as I use Windows 10 Pro and only in Linux one can find "/run/desktop/mnt/host/", I'm not able to do that.

Please, help me!

**Comment by koitoror** [comment]
what version of docker-desktop ? have you tried updating to the latest docker-desktop before troubleshooting and purging data on wsl2 .. I think the update resolved the issue for me.
run also update on dependencies like the latest like .net >5-6 and having windows 10 updates; before finally restarting docker
