### ISSUE TITLE
The docker desktop starts when windows starts, but the docker service is not started, so Troubleshoot's Restart Docker Desktop cannot be executed. 

### ISSUE THREAD

**Issue by juner** [docker/for-win#11292]
The docker desktop starts when windows starts, but the docker service is not started, so Troubleshoot's Restart Docker Desktop cannot be executed. 

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `535AFA91-6817-4715-9B13-9E8E41D66AC5/20210525065938`

### Actual behavior

The docker desktop starts when windows starts, but the docker service is not started, so Troubleshoot's Restart Docker Desktop cannot be executed. 

Executing "Clearn / Purge data" seems to start the docker service, and you can use the docker command. 

### Expected behavior

The docker service is also started when windows starts. 

### Information
  - Windows Version: windows10 Pro 21H1 build 19043.985
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend: no
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

**Comment by fatihdogmus** [comment]
I have the same issue. The docker desktop is started, but I can't access the docker itself. 

The docker tray is stable in this form:
![image](https://user-images.githubusercontent.com/16986743/119461249-2f12fa80-bd48-11eb-945b-9aa7b5163bab.png)

It is not moving, and I can't open the context menux by right clicking on tray.

When I try to run any docker commands, ıt gives me this error:
```
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: 
Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
```

As mentioned above, purging the data seems to fix the problem, but get's really annoying when I have to restart all of my containers every time I open by PC and I have containers that I do not want to delete each time ı boot up my PC. This was not an issue like 3 months ago. I don't know if windows or docker broke something, but I think it is windows related.

My spec is same as above: 
windows 10 enterprise 21H1, 
docker version 3.3.3
WSL2 back-end

Diagnostic ID: `857A9F7B-7D2F-4A44-B623-C3374087D1D1/20210525080052`

**Comment by juner** [comment]
> The docker tray is stable in this form:
>  ![image](https://user-images.githubusercontent.com/16986743/119461249-2f12fa80-bd48-11eb-945b-9aa7b5163bab.png)

mee too!

**Comment by fatihdogmus** [comment]
I first downgraded to 3.2.2 which is the last working version for me, both 3.3.1 and 3.3.2 was broken. But I couldn't stay on 3.2.2 because automatic updates are forcing me to download 3.3.3(Thanks docker!). So I downgraded to 2.5.0.1, which is the last version that the forced automatic updates were not present. Everything seems to be fine, but I had to do one last data purge for everything to work. Now, there seems to be no problem and since there are no major changes from 2.5.0.1 to 3.3.3, and more importantly, it works, I think I'm going to stick on that version for a while 🙂

To donwload 2.5.0.1, you can find it in [here](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2501)

**Comment by juner** [comment]
It hasn't happened since I updated to Docker Desktop 3.4.0, so close it.
