### ISSUE TITLE
Unpack failure on windows

### ISSUE THREAD

**Issue by mikebourgeois** [docker/for-win#1129]
### Expected behavior
Running this command:
docker pull microsoft/windowsservercore 
Should download and unzip the image.

### Actual behavior
Trying to pull windows images produces this error.
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\e8d7ce95cb4275547569a7e52d04db8e63fe834f8a7a4ec3388e675bcd936c12\UtilityVM: The process cannot access the file because it is being used by another process.

I can however download and unpack any linux based image.

### Information

 PS C:\Users\n0277946> docker version -f '{{.Server.Experimental}}'
true
PS C:\Users\n0277946> docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:47 2017
 OS/Arch:      windows/amd64
 Experimental: true
PS C:\Users\n0277946>

**Comment by friism** [comment]
You most likely have misconfigured or poorly implemented antivirus software installed on your machine. Is that the case?

Here's another example with more details: https://github.com/docker/for-win/issues/657#issuecomment-296861084

**Comment by mikebourgeois** [comment]
I am certain I do!  I've disabled symantec, but it's still happening.  Corp won't allow me to uninstall it.  Why just windows images?  Are the linux images managed in the moby linux vm?

**Comment by JanneRantala** [comment]
@friism Just curious, how are we supposed to deal with these "poorly" implemented antivirus softwares? Is Docker/Microsoft expecting us to contact the vendors and ask them to fix their software or has Docker/Microsoft contacted them? I find it amazing, that month after month we're seeing these same comments but nothing seems to happen about it. At least that's how it looks to me.

**Comment by friism** [comment]
@JanneRantala I think everyone and their mom has contacted the antivirus vendors to complain about this. Ultimately, you contacting them works better than me doing so (I work at Docker) since you're paying them money and I assume that the antivirus vendor would like for you to keep giving them money. To them, I'm just another dude at a random software company with a complaint.

Fwiw, I think Symantec fixed this in version 14. I forget what the status is for the other vendors.

**Comment by JanneRantala** [comment]
Thanks @friism, that's what I was afraid of. I know that McAfee hasn't done anything, and obviously it cannot be uninstalled due to a corporate policy. I guess I'll have to start digging some "grant number" from  our IT department to open an issue to McAfee.

**Comment by mikebourgeois** [comment]
ResourceMonitor shows only dockerd with open handles on the file that it's complaining about.  Also, this does not happen when I pull linux images.

**Comment by friism** [comment]
Note that this might also be caused by BitLocker: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/355#issuecomment-284025671 @mikebourgeois are you using that?

@mikebourgeois Linux containers are run within a minimal Linux Hyper-V VM so filesystem operations happen mostly out of sight of AV and BitLocker.

**Comment by DavidHaitch** [comment]
I believe I've discovered a cause besides anti-virus problems or similar. In my case, it was one particular file that was always locked:
`PS Q:\> docker pull microsoft/windowsservercore
Using default tag: latest
latest: Pulling from microsoft/windowsservercore
3889bb8d808b: Already exists
da87b55a9b63: Extracting [==================================================>] 1.266GB/1.266GB
failed to register layer: re-exec error: exit status 1: output: remove \\?\D:\DockerData\windowsfilter\9c420937b1d524adbaefdbf7d1b9f6af927baff9680ea3587861656b70952645\UtilityVM\Files\Windows\servicing\Packages\
Microsoft-NanoServer-Win32Compat-Package~31bf3856ad364e35~amd64~en-US~10.0.14393.0.cat: The process cannot access the file because it is being used by another process.
`

It was always that one NanoServer-Win32Compat package. Disabling antivirus had no effect. What did fix this was going to C:\Windows\Temp, and deleting every folder that began with "hcs".

It looks like these folders are created by the Host Compute Service during the image creation process. They're supposed to be cleaned up at the end of the build, but mine weren't. Apparently they were holding some kind of lock, and that lock was interfering with both the extraction process, and the Temp cleanup process.

I hope this info helps anyone else who has this issue!

**Comment by friism** [comment]
cc @darrenstahlmsft

**Comment by danjagnow** [comment]
To add another data point, I'm experiencing this as well.  I'm on Windows 10 Enterprise, Version 1607 (OS Build 14393.1884) running Docker Community Edition Version 17.11.0-ce-win40 (14328) from the edge channel.  I was experiencing the same problems that I describe below while on the stable channel.  Here's what happens when I'm running Windows containers:

```
PS C:\windows\system32> docker run hello-world:nanoserver
Unable to find image 'hello-world:nanoserver' locally
nanoserver: Pulling from library/hello-world
bce2fbc256ea: Extracting [==================================================>]  252.7MB/252.7MB
53a0ccfb7e6f: Download complete
c670cf2136e6: Download complete
4f90690e9a8d: Download complete
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: failed to register layer: re-exec error: exit status 1: output:
 ProcessUtilityVMImage C:\ProgramData\Docker\windowsfilter\2a00e1e817110950b65e13e8f328fb85dbcfbdd03e41144895ba59b100c7c
edf\UtilityVM: The process cannot access the file because it is being used by another process.
```

If I switch to Linux containers, all is well:

```
PS C:\windows\system32> docker run hello-world:linux
Unable to find image 'hello-world:linux' locally
linux: Pulling from library/hello-world
Digest: sha256:27f70fe1ab54eebd2569a33f0b86e5db42b8ebda65d0647d8eceb87d34462efd
Status: Downloaded newer image for hello-world:linux

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

Version details:

```
PS C:\windows\system32> docker version
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:30:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:39:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
PS C:\windows\system32>
```

My machine is running Symantec Endpoint Protection Version 12.1.6 (12.1 RU6 MP6) build 7061 (12.1.7061.6600).  My IT folks added an exclusion for **C:\ProgramData\Docker** and subfolders, but that did not help.  Symantec does have some documentation related to Symantec Endpoint Protection 14 RU1 on Windows Server 2016, but I haven't been able to find much for older versions of Symantec Endpoint Protection or Windows 10.

https://support.symantec.com/en_US/article.TECH246815.html

Symantec does have a general statement that Docker is supported with Symantec Endpoint Protection version 14:

https://support.symantec.com/en_US/article.TECH236867.html 

Perhaps this is relevant, too.  Version 1607 puts me at the Anniversary Update for Windows 10.  According to Docker, that's supported.  According to Symantec, I have "basic compatibility", which comes with some requirements:

https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows
https://support.symantec.com/en_US/article.TECH235458.html

> Basic Compatibility indicates that Microsoft Hypervisor Code Integrity (HVCI) and Microsoft Device Guard (including Credential Guard) must remain disabled to avoid compatibility issues. These two technologies are disabled by default in most configurations. Refer to Microsoft's Device Guard deployment guide for more information.

**Comment by darrenstahlmsft** [comment]
@danjagnow as far as I am aware, Symantec Endpoint Protection versions less than 14 do not support Windows containers, even with adding any sort of exceptions. You will need to upgrade to version 14, or get an exception to uninstall it (disabling it is not enough to get Windows containers to work, it must be uninstalled).

Linux containers are handled in a very different way (they run inside a VM, so entirely hidden from AV), so them working is unrelated to failures caused by AV.

**Comment by danjagnow** [comment]
Thanks, @darrenstahlmsft!  I'll see how soon it might be possible to get our Symantec Endpoint Protection upgraded.  It's helpful to have some confirmation that upgrading is probably required.

**Comment by danjagnow** [comment]
I can confirm that upgrading to Symantec Endpoint Protection 14 resolved the issue for me.  Thanks!

**Comment by JoshSchreuder** [comment]
I tried in a fresh Windows 10 Enterprise N 1709 VM and installed McAfee Endpoint Protection 10.5.3.3178.

Out of the box the `docker pull` command worked fine.

Running 10.5.1 elsewhere and it has this issue, not 100% if it's McAfee or some other environmental issue.

**Comment by shoneworn** [comment]
I have fixed this issue by myself , Look here https://blog.csdn.net/shoneworn/article/details/80621120 . I have mark it with my blog .

**Comment by shoneworn** [comment]
I have fixed this issue by myself , Look here https://blog.csdn.net/shoneworn/article/details/80621120 . I have mark it with my blog .
