### ISSUE TITLE
docker crash report

### ISSUE THREAD

**Issue by 1Blackdiamondsc** [docker/for-win#11333]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by 1Blackdiamondsc** [comment]
needs attention

**Comment by ManfredLange** [comment]
@1Blackdiamondsc If you have a look at your issue after you submitted it, you will find that there is no information in it other than the labels provided by the issue template. This makes it impossible for other to assist.

In case you added information in the template, make sure you do so outside of any comment `<!-- -->` section. Those comment sections will not be shown when rendered.

**Comment by 1Blackdiamondsc** [comment]
@ManfredLange Thanks for the response and I’ll make sure I do that 👍🏾

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
