### ISSUE TITLE
Only connect one virtual network adapter with virtual switch during creation 

### ISSUE THREAD

**Issue by github-seanli** [docker/for-win#1140]
### Expected behavior
Only connect one virtual network adapter with virtual switch during creation

### Actual behavior
In additional to default DockerNAT network adapter, I added a new network adapters (named as extnet with Connection Type as External Network) in MobyLinuxVM hardware. During docker start, my new network adapter (extnet) gets changed to DockerNAT, i.e.  In Hyper-V Manager -> Settings -> Hardware, it shows two DockerNAT network adapters.

### Information
In MobyLinux.ps1, can we always assume the first adapter to be DockerNAT and leave the others as it is? 
e.g. the code can be changed like this?
    Write-Output "Connect Internal Switch $SwitchName"
    $vmNetAdapter[0] | Connect-VMNetworkAdapter -VMSwitch $(Get-VMSwitch -ComputerName localhost $SwitchName -SwitchType Internal)

### Steps to reproduce the behavior
1. Follow steps in https://docs.docker.com/machine/drivers/hyper-v/#2-set-up-a-new-external-network-switch-optional to create one virtual switch with external network connection type. The reason of creating external network type is to allocate this adapter dedicated for Linux container. Say the adapter is named as extnet.
2. Go to Hyper-V Manager -> Settings -> Hardware to add network adapter hardware and select extnet. This way, I can allow Linux container to control this adapter with static IP. docker-machine seems to always requests DHCP during creation which doesn't meet my need.
3. Start Docker for Windows and observe the extnet added in  Hyper-V Manager -> Settings -> Hardware got changed to DockerNAT

**Comment by friism** [comment]
@github-seanli you don't need to mess with Docker Machine if you're just using Docker for Windows and the default setup.

Is there something that's not working?

**Comment by github-seanli** [comment]
Thanks for your response.

The env I want to build up is WiFi sniffer tool
[WiFi sniffer hardware with 192.168.100.100 static IP] <------ETHERNET------> [Win10 with Ubuntu docker container. The Ubuntu inside the container needs a static IP in 192.168.100.x subnet, has to send command to WiFi sniffer hardware and receive Multicast UDP packet 233.1.2.3 at port 12345 from WiFi sniffer]
I prefer to have a dedicated Ethernet port on Win10 (USB to Ethernet adapter in my case) for WiFi sniffer capture so that I can continue my regular work with internet connection on other ports.

I tried following two methods and none of them works to me
1. add -p 12345:12345 parameter in docker run and route add 233.1.2.3 into Windows routing table. From wireshark capture, packets coming into vEthernet(DocketNAT) as correct format but got "distorted" in Ubuntu docker container eth0 interface, the packets can't be decoded - I didn't debug further as the issue seems to be in Windows network stack and is a blackbox to me. 

2.  follow https://docs.docker.com/machine/drivers/hyper-v to add external network adapter and create docker-machine. The problem is, the docker-machine always look for DHCP IP and internet connection during creation as well as after created and during starting, which is not feasible in my case

I then figured out a solution by setting up dedicated USB-Ethernet adapter as external-type network adapter, added it in MobyLinuxVM and use --network=host in docker run to give full USB-Ethernet port/WiFi sniffer hardware control to Ubuntu container. This also gives internet connection to container via other interfaces.
The setup runs pretty well except the external-type network adapter (extnet) I added in vm always got changed to DockerNAT during initialization.
I have to modify MobyLinux.ps1 script to avoid overridden

Hope it doesn't make you more confused after long reading...

**Comment by friism** [comment]
You should probably create a separate hyper-v VM for your use: https://docs.docker.com/get-started/part4/#create-a-cluster

**Comment by friism** [comment]
(don't follow all of that guide to create a swarm, just create a single hyper-v docker-machine VM)

**Comment by github-seanli** [comment]
Thanks for the information but what's the benefit of creating separate VM?  The current method I did works pretty well after script change.
Any issue or restriction on adding new adapter?

**Comment by jonathanperret** [comment]
Hi Docker friends, I would like to second this request. There are a couple similar issues in this repo such as #594, #1644, #551 (and #221, somewhat) where people are trying to connect their `MobyLinuxVM` to the external, physical network, so that it obtains its own IP address distinct from the Windows host.

This is certainly not applicable to every situation (e.g. running on a laptop in a coffee shop, having the Linux VM behind `vpnkit`'s NAT is certainly more convenient), but some scenarios are definitely easier when you have the option of connecting the VM to the LAN. Here are a couple from recent experience:
* mounting NFS volumes from NFS servers which do not set the `insecure` option (good luck selling a flag named `insecure` to your average sysadmin), and hence require connecting from a "privileged" (<1024) port;
* running a Samba container to export SMB shares from Linux: exposing port 445 on the Windows host is a non-starter as Windows' SMB server is already sitting on it (see #3), so the only reasonable option is `--net=host`;
* applications which, for better or for worse (OK, worse) listen on random, unpredictable ports (in my case, Java RMI services): again, `--net=host` is a life-saver here;
* applications which advertise their "own" IP address to other computers expecting it to be reachable: smart ones (e.g. Kafka) have settings to override the advertised IP, but legacy apps may not have them : `--net=host` to the rescue again.

The answer I generally see here to such requests is "if you want more control, go and use `docker-machine` and create your own VM". While this does allow more control, it's not without its downsides:
* `docker-machine` uses the legacy `boot2docker` ISO instead of the shiny `linuxkit`-based image you have here. And the general feeling I get from the Docker documentation is that `boot2docker` is deprecated - in fact it practically says so on https://github.com/boot2docker/boot2docker .
* The Docker for Windows user experience is obviously superior in many respects to the DIY `docker-machine` approach.

The ideal situation from my point of view would be to have a new setting in the Docker for Windows UI allowing to pick a network adapter to which the Linux VM would be connected.

But I'd be happy with just a less hacky way of making it work than what I have currently. As @github-seanli mentioned, to get the `MobyLinuxVM` connected to an external switch currently you have to edit `MobyLinux.ps1`.

To be more specific, here's what I had to change. In the `New-MobyLinuxVM` function, there's a line that retrieves the machine's network adapter:

```powershell
$vmNetAdapter = $vm | Hyper-V\Get-VMNetworkAdapter
```

The function then goes on to make sure this network adapter is connected to the `DockerNAT` switch. So far, so good: I'm trying to add a network adapter connected to an external switch, not replace the `DockerNAT`-connected one.

But because of how PowerShell objects work, if you added an extra network adapter to the `MobyLinuxVM`, the `$vmNetAdapter` variable will contain references to _both_ adapters, and both will end up connected to `DockerNAT`.

So here's how I modified that line:

```powershell
$vmNetAdapter = $vm | Hyper-V\Get-VMNetworkAdapter | Select-Object -First 1
```

This ensures only the first network adapter gets connected to `DockerNAT`. With this patch in place, all the scenarios I described above work, with no apparent ill effects on the functioning of the rest of Docker for Windows (e.g. sharing files from Windows still works).

Would you be open to adding this simple patch, or something equivalent, to Docker for Windows ?

**Comment by mew1033** [comment]
Any updates on this? I'd love for this to work as @jonathanperret described.

**Comment by MythreyaK** [comment]
I have the same issue. I want to expose my VM to my local network and to achieve this, I set up an external switch to the MobyLinuxVM. But every single time the VM reboots, both the network adapters are set to DockerNAT. I have to manually set the second one to my external switch. 

Also, after manually changing the redundant switch to my external switch, for some reason, IP isn't allocated automatically to the VM (DHCP is enabled, works on the network). I'm having to manually set the IP for the VM (by using a privileged container, `chroot`-ing to the Linux host, and then `ip address add <no.collide.ip.addr>/<mask> dev ethx` [more here](https://forums.docker.com/t/how-can-i-ssh-into-the-betas-mobylinuxvm/10991/7)) to expose it to the network. Is there no straight forward way to set this up more 'just-works-like-you-expect-it' way?
