### ISSUE TITLE
windows update 1809 came, restart required

### ISSUE THREAD

**Issue by moudrick** [docker/for-win#11417]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: C9CCFC2C-4263-4AE6-9DB6-9A3B1E06BC79/20210609193904

### Information

  - Windows Version: Microsoft Windows [Version 10.0.17763.1971]
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by stephen-turner** [comment]
Also Windows 1809 is no longer supported.
