### ISSUE TITLE
Docker Desktop for Windows Dashboard runs but not Docker

### ISSUE THREAD

**Issue by Quang-PHP** [docker/for-win#11431]
- [ X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:21H1, Windows 10 Pro, OS Build 19043.1052, Windows Feature Experience Pack 120.2212.2020.0
  - Docker Desktop Version:v20.10.6
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Windows 10 Pro

### Steps to reproduce the behavior

  1. Install the Docker for Window version 20.10.6
  2. Create some containers
  3. Let your device runs for 2 or 3 days
  4. Docker become inaccessible to the container as described in this post https://stackoverflow.com/questions/67176416/docker-desktop-for-windows-dashboard-runs-but-not-docker-itself
  5. From here I just uninstall the Docker from my Desktop and reinstall and docker start to work again but all of the images that were previously created got erased
  6. After installing the Docker, it starts to work again, but only for a couple of days then I have to perform the same step 5 to get Docker to work again.

**Comment by Koed00** [comment]
I have something similar: Dashboard starts but not Docker.  

So every time I restart my laptop I have to go the Troubleshoot panel and then through Clean/Purge data delete either of the three data sets. This will restart the docker backend immediately , even before the purge is complete. 

I am assuming that somehow the docker service never starts because of some windows settings or security scanner.
