### ISSUE TITLE
Docker crashes when I enable WSL2

### ISSUE THREAD

**Issue by pnarsina** [docker/for-win#11435]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Whenever I enable WSL2 on my windows 10 machine, Docker crashes/
### Expected behavior
Expected to allow me to deploy linux based containers

### Information

  - Windows Version: windows 10
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Windows laptop

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
