### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by WMD001** [docker/for-win#11448]
Component CommunityInstaller.ShortcutAction failed: 需要绝对路径信息。
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
![image](https://user-images.githubusercontent.com/35905864/122024291-de4c6a00-cdfa-11eb-826e-9618a956663d.png)

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
