### ISSUE TITLE
Docker compose up with one or more volumes failed to start

### ISSUE THREAD

**Issue by MassimoTambu** [docker/for-win#11449]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 892DDA93-410C-4D6A-9A59-4DC24DD30944/20210615140824

### Actual behavior

When I execute the command `docker compose up -d` it gives me the following error: 

`Error response from daemon: hcsshim::CreateComputeSystem 690966fdad9e4b447fd930354a2a7d6430f7f22d12979f304db99e4fc6cb7c39: The request is not supported.`

**This happens only if the docker compose file has one or more volumes and after updating to Docker Desktop 3.4.0, previous was 3.3.3 (and probably only on Windows Container, not tested on Linux).**

With no volumes the container starts.

### Expected behavior

The container should start as always.

### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: 3.4.0
  - WSL2 or Hyper-V backend?   WSL2, but tried with Hyper-V, same error.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Switch to windows Container 
  2. Add to docker compose a volume 
  3. docker compose up -d

**Comment by stephen-turner** [comment]
Thanks for the ticket. `hcsshim` errors are actually generated by the Windows container code in the upstream engine. That code was not written by Docker engineers, so could I ask you to file the ticket in the upstream repository, https://github.com/moby/moby? Sorry, I would just move the ticket, but it's not possible because it's not part of the docker org.

**Comment by MassimoTambu** [comment]
Okay, thank you, I will do
