### ISSUE TITLE
Can't read property  'db' of null

### ISSUE THREAD

**Issue by mahdi302** [docker/for-win#11456]
Hi, 
I've tried to use docker-compose up command to run a project on Docker, but I got (unable to connect to database) error.
could you help me please.
![Screenshot (13)](https://user-images.githubusercontent.com/44195039/122194965-2d51d800-ceab-11eb-88c8-b71fa929665f.png)

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
