### ISSUE TITLE
already in cache

### ISSUE THREAD

**Issue by ccb1900** [docker/for-win#11465]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: win10
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
![image](https://user-images.githubusercontent.com/3932305/122321488-84f94d80-cf56-11eb-9cce-f9fd82075d2e.png)

i have reset it.no use

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
