### ISSUE TITLE
Docker failed if Windows Firewall stopped

### ISSUE THREAD

**Issue by Alex-Anisov** [docker/for-win#11478]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E675ED81-72DA-48F4-B958-E2B5754D1148/20210618082113

### Information

  - Windows Version: 20H2 (Build 19042.1052)
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Phisical machine

E675ED81-72DA-48F4-B958-E2B5754D1148/20210618082113

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
