### ISSUE TITLE
Docker Desktop Installation Issue

### ISSUE THREAD

**Issue by jaygandhi129** [docker/for-win#11491]
![Capture](https://user-images.githubusercontent.com/57639468/122666226-c2194600-d1c9-11eb-95bc-990135478fef.JPG)
This error is shown again and again. Please help me with this.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
