### ISSUE TITLE
docker failed to initialize

### ISSUE THREAD

**Issue by derekbay20** [docker/for-win#11503]
Here am having a problem regarding opening docker desktop. 
And having connection error like 
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
PS C:\WINDOWS\system32> net start com.docker.service
The requested service has already been started.

More help is available by typing NET HELPMSG 2182.
![{B15F7691-FA98-4461-9C94-B43197093501} png](https://user-images.githubusercontent.com/77827806/122905256-c895f200-d370-11eb-9c8b-d0ecdd900dd1.jpg)

**Comment by gtardif** [comment]
Hi, I'm moving this to /docker/for-win as it does not seem related to dev-environments, rather a Docker Desktop startup issue on windows

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
