### ISSUE TITLE
Docker is not starting on my windows

### ISSUE THREAD

**Issue by skumar568** [docker/for-win#11508]
Diagnostic ID: 3F8EFFDB-3D69-469C-8A32-D05081B62303/20210623104132

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
