### ISSUE TITLE
Upgraded Windows Desktop Docker from 2.5 to 3.4 and it now does not start up. 

### ISSUE THREAD

**Issue by dmorri** [docker/for-win#11529]
Here is the Diagnostic ID: 

DC30BE00-F617-4576-8740-852E069662E1/20210625164854

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
