### ISSUE TITLE
Install instructions regarding...don't....

### ISSUE THREAD

**Issue by JadianRadiator** [docker/for-win#11535]
Install instructions regarding Git and Docker Desktop's Dev Environment don't say you have to restart to finish installing Git.
This was the cause of https://github.com/docker/for-win/issues/11533

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
