### ISSUE TITLE
Docker enable to start

### ISSUE THREAD

**Issue by Mohsin0911** [docker/for-win#11820]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Edition	Windows 10 Pro
  - Version	21H1
  - Installed on	‎1/‎14/‎2021
  - OS build	19043.1110
  - Experience	Windows Feature Experience Pack 120.2212.3530.0
  
  - Docker Desktop Version: 3.5
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Mohsin0911** [comment]
yes , i am using VM

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
