### ISSUE TITLE
unable to expose docker api on 127.0.0.1:2375

### ISSUE THREAD

**Issue by easygoto** [docker/for-win#11821]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
    - [x] Use Docker Compose V2
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

- 每次启动会报此类信息

![image](https://user-images.githubusercontent.com/29568241/128111833-afd4896e-9e55-470c-afcf-aa7267a5aefd.png)

### Information

  - Windows Version: Windows 10 专业版 19043.1110
  - Docker Desktop Version: Docker version 20.10.7, build f0df350
  - WSL2 or Hyper-V backend?  I use Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, only windows 10 hyper-v

### Steps to reproduce the behavior

  1. 开机
  2. 启动 docker desktop

**Comment by icefery** [comment]
I have found the same problem. It has lasted for at  least 3 updates.

and I have checked `netstat` and `ps`.  there is no other process taking up my port 2375.

I found some information at log(`C:\Users\icefery\AppData\Roaming\Docker\log\host\com.docker.proxy.exe.log`):
```log
time="2021-08-07T16:11:56+08:00" level=info msg="starting Docker API TCP listener on 127.0.0.1:2375"
```
```log
time="2021-08-07T16:11:56+08:00" level=error msg="unable to start Docker API proxy on 127.0.0.1:2375: listen tcp 127.0.0.1:2375: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
```

I guess the reason is that IPv4 and IPv6 seem to be conflict.

Now though it is able to work, it takes more time to launch. I remember several versions or updates ago, hypeV backend are quick enough. 

I dont know why, hope officials can fix it.
