### ISSUE TITLE
wls 2 terminal ubuntu 20.04

### ISSUE THREAD

**Issue by jamesson-dev** [docker/for-win#11857]
check status
`service doceker status`

start 
`service docker start`

docker service running
`docker run -it centos`

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
