### ISSUE TITLE
Clean / Purge data crashed docker for windows

### ISSUE THREAD

**Issue by frederik-b** [docker/for-win#11872]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 69E92369-5EF0-4D83-89D5-68B18E3AC158/20210811114709

### Actual behavior

Clean / Purge data => crashes

### Expected behavior

Clean / Purge data => does not crash

### Information

  - Windows Version: 10.0.19043 Build 19043
  - Docker Desktop Version: 3.5.2(66501)
  - Docker Engine Version: v20.10.7
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. got some failed builds where it apparently couldn't mount the Dockerfile or something
  2. press Clean / Purge data button

no I can't make this reproducible, yet

**Comment by StefanScherer** [comment]
Maybe a reset to factory defaults would help?
Maybe unrelated, but I saw `[13:21:30.130][ApiProxy          ][Error  ] msg="mount denied:\nthe source path \"\\\\dev-secure\\\\visitour-docker-compose\\\\roadnet:C:\\\\FLS_VISITOUR\\\\Server\\\\roadnet:rw\"\ntoo many colons"` in the diagnostics.

We're closing this issue because it doesn't contain enough information for us to investigate the problem and it seems out of scope of the free support. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
