### ISSUE TITLE
Docker Desktop is not running

### ISSUE THREAD

**Issue by sharif2008** [docker/for-win#11906]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Timeout to start
### Expected behavior
Normall startup
### Information

  - Windows Version: 10
  - Docker Desktop Version: 3.3.3
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Windows 10

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
