### ISSUE TITLE
Closed issues are locked after 30 days of inactivity.

### ISSUE THREAD

**Issue by biswajeetbehera** [docker/for-win#11902]
Closed issues are locked after 30 days of inactivity.
This helps our team focus on active issues.

If you have found a problem that seems similar to this, please open a new issue.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle locked

_Originally posted by @docker-desktop-robot in https://github.com/docker/for-win/issues/1825#issuecomment-689945904_

**Comment by StefanScherer** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
