### ISSUE TITLE
--restart=always breaks mounted folders on Docker for Windows' startup

### ISSUE THREAD

**Issue by hyperknot** [docker/for-win#1192]
### Expected behavior
A docker container with `--restart=always` should auto-restart and mount all shared folders upon starting docker.

### Actual behavior
The container gets started without the shared folder being mounted.
If I manually `docker stop` and `docker start`, it does get mounted correctly.
If I quit docker and start docker from the Start Menu, the shared folder is not mounted.

`mount | grep shared`
good:
```
//10.0.75.1/C on /shared type cifs (rw,relatime,vers=3.02,sec=ntlmssp,cache=strict,username=x,domain=x,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0755,iocharset=utf8,nounix,serverino,mapposix,nobrl,mfsymlinks,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
```

bad:
```
tmpfs on /shared type tmpfs (rw,relatime)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
3481BAE4-F0D3-45EC-A836-22261F06EE04/2017-10-09_15-53-53
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro, 15063

### Steps to reproduce the behavior

```
docker run --detach --restart=always ^
        --name app ^
        -v "%USERPROFILE%/docker_shared":/shared ^
        repo/app

# works

quit docker from system tray
start docker via start menu

# mounted folder is not working

docker stop app
docker start app

# mounted folder is working

# quitting and starting via start menu again breaks it

```

**Comment by WKHarmon** [comment]
Just a quick note that I'm seeing the same behavior on Docker Version 17.09.1-ce-win42 on Windows Server 2016.

I've uploaded a diagnostic under ID 0D6F2135-FA6B-479F-BA91-1846FD050892/2018-01-06_08-45-54

**Comment by thaJeztah** [comment]
This looks like a race condition; the problem here is that, when using the `-v <host-path>:<container-path>` option, docker will automatically create `<host-path>` if the path does not exist. This functionality was marked for deprecation at some point (exactly because of these issues), but it was considered too much of a breaking change to change (see https://github.com/moby/moby/pull/21666, and issues linked from that issue).

Docker for Windows (when running Linux containers) runs the docker daemon in a VM. Files/directories shared from your local (Windows) machine are shared with the VM using a shared mount, and I suspect that mount is not yet present when the container is started.

Because of that, the `%USERPROFILE%/docker_shared` directory is not found inside the VM, so the daemon creates that path (as an empty directory). Later, when the shared mount (from the Windows host) is present, it's mounted "on top" of the `%USERPROFILE%` directory inside the VM, but at that point, the container is already started.

Restarting (`docker stop`, `docker start`) resolves the situation because at that point, the shared mount _is_ available, and the container will mount the correct path.

One way to resolve this is to use the `docker run --mount` option when creating the container (instead of `docker run -v`); the `--mount` option requires the `<host-path>` to exist, and will not create the path if not found (instead; it will produce an error, and make the container fail to be created).

However; there's a bug in current releases, where _starting_ the container after it was created still creates the path (fixed in "master" through https://github.com/moby/moby/pull/35833).

Alternatively, Docker for Windows should wait with starting the docker daemon (and containers) until the shared mount is available (but not sure if that's possible).

**Comment by hyperknot** [comment]
@thaJeztah thanks for the detailed explanation. So are you saying that simply changing the syntax to `--mount` would fix the autostart bug, or we'd need to way for one more release to have https://github.com/moby/moby/pull/35833 fixed?

**Comment by thaJeztah** [comment]
I _think_ that fix would still be needed, but it wouldn't hurt to switch to using `--mount`

(I'm not in the Docker for Windows team, so don't know if there's something on their side they can do to reduce the race condition)

**Comment by hyperknot** [comment]
Just to report, with version 17.12.0-ce-win47 (15139), using the new `--mount` option it's still not working.

**Comment by hyperknot** [comment]
For anyone looking for a workaround, we settled on removing `--restart=always` from the docker run command and instead created a Desktop Shortcut.lnk to allow one-click docker start.

Here is a way to create that shortcut from command line:
```
powershell "$s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Desktop\Start My App.lnk');$s.TargetPath='%comspec%';$s.Arguments='/c docker start my_app';$s.Save()"
```

**Comment by makamekm** [comment]
Does anybody know how to fix the issue?

**Comment by jasonbivins** [comment]
I can repro this for Linux containers only - Windows containers seem to be fine

**Comment by jasonbivins** [comment]
@makamekm 
LCOW might be a possible workaround, but it's an experimental feature.  I havent been able to repro this issue using it though.  In Windows container mode, you have to add the `--platform=linux `

```
docker run --platform=linux --detach --restart=always ^
        --name app ^
        -v "%USERPROFILE%/docker_shared":/shared ^
        redis
```

**Comment by vitr** [comment]
@Cyrus-d thanks for the idea, I like your approach. Moreover I want to restart not all the containers,  but only with 'always' restart policy. I'm using bash in cmder on windows, so, here is my ugly workaround

`docker restart $(docker ps -a -q | grep -v CON|awk '{print $1}'|while read line; do  docker inspect -f "{{ .HostConfig.RestartPolicy.Name }}" $line | xargs echo $line ;done | grep always | awk '{ print $1 }')`

**Comment by OrionDevelopment** [comment]
Can this be marked unstale? The issue still exists.

**Comment by AceCoderLaura** [comment]
Issue still exists on Windows 10 Professional using Linux containers.
The `jetbrains/teamcity-server` docker image reproduces this problem every time without fail.

Docker Version:
```
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
```

**Comment by vitr** [comment]
hey, don't remove, the issue still exists.

**Comment by ribab** [comment]
This is an issue for me as well.

Adding "--restart=always"

and a "-v" volume mount

and then simply "systemctl restart docker"

The container does not automatically remount the volume and instead errors out.

**Comment by OrionDevelopment** [comment]
Any information from the docker team from this?
This issue is from 2017.

**Comment by guillaumerose** [comment]
We worked on this issue last month and it will be fixed in the next edge release. 

Previously, docker and samba mount were done at the same time. Now, we are mounting samba and then, starting docker.

**Comment by OrionDevelopment** [comment]
@guillaumerose Thanks for this. It is good to know that this is finally getting looked at. Right now i ssh into the vm and set docker to delayed starting my self, allthough that works 95% of the time, if it takes a bit longer to mount the samba or i update docker i have todo it all over again.

Since this runs in our testing environment it would be nasty to have todo this every month over and over again.

**Comment by vitr** [comment]
I believe, you do check that it has been mounted before starting docker and don't just start mounting  before running docker, in hope that it will be mounted earlier than docker actually needs it.

**Comment by c-ed** [comment]
I just tried with the latest edge version (2.0.3.0) and it appears that issue has not been fixed yet.

**Comment by urbandroid** [comment]
Could guys just tell us that we are not going to fix this so we can move on with our lives.

**Comment by OrionDevelopment** [comment]
@guillaumerose How is it looking? Any information on how we can help?

**Comment by johanbcn** [comment]
> I just tried with the latest edge version (2.0.3.0) and it appears the issue has not yet been fixed.

@guillaumerose was talking about version 2.0.4.0, which wasn't yet released when you made this comment.

**I have just upgraded from stable to 2.0.4.0 edge and can confirm it's working correctly.**
I have set --restart=unless-stopped, have powered off the computer, turned it on again, and accessed the container as soon as the docker notification reported it was on.

**Comment by OrionDevelopment** [comment]
@johanbcn Perfect, thanks for the reply!

**Comment by guillaumerose** [comment]
It's now fixed in stable
