### ISSUE TITLE
docker wont workk

### ISSUE THREAD

**Issue by 2012loluke** [docker/for-win#12019]
- [Yes] I have tried with the latest version of Docker Desktop
  - [Yes] I have tried disabling enabled experimental features
  - [No] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
opens some errors pressed continue failed to start engine

### Expected behavior
enable to export a os I'm making

### Information

  - Windows Version: 21H1
  - Docker Desktop Version: newest
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: actual machine

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
