### ISSUE TITLE
Docker service fails to start

### ISSUE THREAD

**Issue by bderagon** [docker/for-win#1218]
### Information

Diagnostic ID: D5AF4716-BCBF-44A8-936E-7D877FCD2915/2017-10-17_16-21-02
Windows 10 version 1607, Build 14393.1770

### Steps to reproduce the behavior

  1. Attempt to start docker service, docker service fails to start with cryptic message:
fatal: Could not load X509 key pair (cert: "", key: ""): open : The system cannot find the file specified.

**Comment by bderagon** [comment]
Turns out the issue was I needed to specify a proxy for Linux containers, and for a Windows container, you can use the system proxies, and don't need to specify one, the error message didn't let me know that at all though.

**Comment by JamesCullum** [comment]
I've encountered the same error.
It was caused by the `tlsverify` environment variables being set (for me it was in the `config.toml` of the gitlab-runner, but could be on other places as well).
No matter the value, this will always enable TLS.
The DIND service does not support TLS.

Remove it completely from all environment variables and you should be good to go.
