### ISSUE TITLE
openremote

### ISSUE THREAD

**Issue by DarshanaRJ** [docker/for-win#12219]
ERROR: for openremote_proxy_1  Cannot start service proxy: Ports are not available: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
