### ISSUE TITLE
Docker fails to start with Linux containers support on Windows 10 Pro 1709

### ISSUE THREAD

**Issue by rvprasad** [docker/for-win#1224]
### Expected behavior
Upon starting Docker on Windows 10 Pro (at least prior to Version 1709), Docker starts with no issues -- displays message "Docker is up and running!" 

### Actual behavior
Upon starting Docker on Windows 10 Pro Version 1709, Docker displays a window with following error message.  

> Unable to create: The running command stopped because the preference variable  ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MYCOMPUTERNAME' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
> at New-MobyLinuxVM, <No file>: line 192
> at <ScriptBlock>, <No file>: line 385
>   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
>   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
>   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
>   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Issuing `docker version` command from the command line results in the following error message

> error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information
  - Diagnostic ID: 17A5BBF0-D955-4DB7-A538-CEF004DD5BA1/2017-10-19_11-19-25
  - Windows 10 Pro -- Version 1709, Build 16299.19
  - Docker -- Version 17.09.0-ce-win34 (13622), Channel: edge, 9171a03
  - Same is true with latest version of Docker available from stable channel
  - Only happens with Linux containers

### Steps to reproduce the behavior
  1. Start Windows 10 Pro
  2. Start Docker -- Make sure Docker is configured to support "Linux containers"

**Comment by MosterAndMonk** [comment]
About the second steps 
how I can do that?
'''Start Docker -- Make sure Docker is configured to support "Linux containers"'''

**Comment by rvprasad** [comment]
Once you start on "Docker for Windows", right click on the the docker icon in the system tray.  If you see "Switch to Windows Containers" in the popup menu, then Docker is supporting in Linux containers.  If you instead see "Switch to Linux Containers", then Docker is supporting Windows containers and you will need to click on this menu option to switch over to the support for Linux containers.

**Comment by MosterAndMonk** [comment]
Thanks you so much for explaining in detail! But seems that I suffered a different problem.
The docker version command error message is same as yours. Maybe I should open  a new issue to solve the problem， but now I have no ideas.
When I clicked on "Switch to Linux Containers",  my error info is 
"Binary stream "0" does not contain valid BinaryHeader. This may be due to invalid flow, or due to changes in the object version between serialization and serialization.           In Docker.Core.Pipe.NamedPipeClient.Send (String action, Object[] parameters) position C:\\gopath\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Core\\pipe\\NamedPipeClient.cs: line 36           At Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0 () position C:\\gopath\\src\\github.com\\docker\\pinata\\win\\src\\Docker.Windows\\Actions.cs: line 285           At Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1 () position C:\\gopath\\src\\github.com\\docker\\pinata\\win\\src\\Docker.WPF\\TaskQueue.cs: line 59 "

**Comment by rvprasad** [comment]
I'd say so.  Please make sure you document all the steps that you took and all the errors encountered.  I think this will help folks figure out if the issues are related.

**Comment by randomvariable** [comment]
No joy for me, but for different reasons:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-10-20
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.4
 Git commit:   ab0eb8f
 Built:        Fri Oct 20 23:50:34 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

fails with
```
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: no matching manifest for windows/amd64 in the manifest list entries.
```


[docker.log](https://github.com/docker/for-win/files/1404016/docker.log)

**Comment by rvprasad** [comment]
This failure does not occur when Docker 17.10.0-ce-win36 (13788) from edge channel is used with "Linux containers for Windows" support.  https://github.com/docker/for-win/issues/1221#issuecomment-339575508 works with

**Comment by john-thomas-dotcms** [comment]
I'm getting the exact same error on 18.3.1-ce when I try to use Linux containers.  The error comes up on a cold start, and any time I switch from Windows containers to Linux containers.

**Comment by john-thomas-dotcms** [comment]
I tried with edge 18.05.0-ce and I get the same error.  Here is the full text of the error with the edge install:

**Comment by john-thomas-dotcms** [comment]
@rvprasad I'm seeing this issue with 18.03.1 and 18.05.0, on Win 10 Pro with the latest Windows Updates.  Will this issue get re-looked at, or should I open another issue or ?????

**Comment by rvprasad** [comment]
Since this issue has been closed, I suggest opening a new issue.  For me, Linux containers were failing on the latest version of Docker for Windows.  So, if you create an issue and I will chime in with my observations.

**Comment by nlata15** [comment]
Is the issue resolved? Do we have another thread to followup on this?

**Comment by rvprasad** [comment]
I suggest you could create a new issue and/or follow #1221.

**Comment by cosloli** [comment]
Same with me.

**Comment by john-thomas-dotcms** [comment]
I had this issue for a while, but the issue went away after I did a major Windows Update (which incidentally wiped out most of my custom registry settings) and then installed v2.0.5.0.

Whether the fix happened because of the registry wiping Windows so kindly did for me, or the new version of Docker, I don't know.  But if you haven't already, I'd suggest a complete uninstall of both Docker and Hyper-V (including clearing out any left-over registry entries for both), and then re-installing Docker v2.0.5.0 or later.
