### ISSUE TITLE
build with Dockerfile FROM local image still fetch/pull remote images in qemu-user-static

### ISSUE THREAD

**Issue by zxj5470** [docker/for-win#12302]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
(Sorry I can't find the way to generate diagnostics.)

### Actual behavior
1. (WRONG) docker build force to pull remote images in Windows.
2. (OK) I try it in Linux(Deepin 20, base Debian 10) but never reproduce it. 
3. (OK) And FROM x64 images is also OK.(like `docker pull ubuntu` then rename TAG and build) 

### Expected behavior
Not to pull images from remote !!!

### Information

  - Windows Version: 11 (build 22000)
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

And I make a minimise reproducible in my PC.
  1. `docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes` enable arm64 images support
  2. pull base image(ARM64 version) `docker pull arm64v8/centos:centos7.9.2009` 
  3. `docker build -t buildtest .`
  4. It's ok when using official images because it can be pulled from `docker.io/` ![image](https://user-images.githubusercontent.com/20026798/138554346-f6200d2a-e1a3-4de5-873f-340bbbc5c59f.png)
  5. but fail when using my custom tag (`docker tag dfc30428e163 arm64centos7:7.9`) ![image](https://user-images.githubusercontent.com/20026798/138554415-7d63f242-9c0d-451a-9fad-7e8a149e4364.png)
  7. Is there something wrong in my docker settings? I try `docker build` with `--pull=false` but doesn't work.
  8. idk it's due to qemu-user-static or Docker for-win.

**Comment by lanniu** [comment]
Any good news?

**Comment by thaJeztah** [comment]
I don't think this is a bug, but the error message could definitely be improved (work is being done on that).

The problem in this case is that the image is a `linux/arm64` image, but the host's native architecture is x86 (`linux/amd64`).

If no platform is explicitly specified when building an image, the builder will default to the native platform. The local image cache (currently) only supports a single architecture per image, so when you start the build and the builder finds that the image in cache does not match the architecture, it will connect to the registry to request the desired architecture.

In the "use the original name" (`arm64v8/centos:centos7.9.2009`) case you can see that it also connects to the registry (see the `[auth] ...` and `resolve docker.io ..` steps);

```bash
echo -e 'FROM arm64v8/centos:centos7.9.2009\nRUN echo "test hello"\n' | docker build -
[+] Building 3.0s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                     0.0s
 => => transferring dockerfile: 100B                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                        0.0s
 => => transferring context: 2B                                                                                                          0.0s
 => [internal] load metadata for docker.io/arm64v8/centos:centos7.9.2009                                                                 2.6s
 => [auth] arm64v8/centos:pull token for registry-1.docker.io                                                                            0.0s
 => CACHED [1/2] FROM docker.io/arm64v8/centos:centos7.9.2009@sha256:864a7acea4a5e8fa7a4d83720fbcbadbe38b183f46f3600e04a3f8c1d961ed87    0.0s
 => => resolve docker.io/arm64v8/centos:centos7.9.2009@sha256:864a7acea4a5e8fa7a4d83720fbcbadbe38b183f46f3600e04a3f8c1d961ed87           0.0s
 => [2/2] RUN echo "test hello"                                                                                                          0.3s
 => exporting to image                                                                                                                   0.0s
 => => exporting layers                                                                                                                  0.0s
 => => writing image sha256:68bce7bd1ac3f73bcbcc73500f9ecae26faf493cf9afff73f981f7d399ecbd80                                             0.0s
 ```

While that image does not match the expected platform, BuildKit (the builder) was able to check if alternative platforms were available. When doing so, it found that the image is a single-arch image; this is a special case for which a fallback is in place (for backward compatibility, and to work around some older images having incorrect metadata).

(Ideally, a warning should be printed to notify the user that the image does not match the expected architecture, but this has not yet been implemented; see https://github.com/moby/buildkit/issues/2457)

In the "custom name" (`arm64centos7:7.9`) case, the same happens; BuildKit detects that the architecture of the image in the local image cache does not match, so it checks with the registry to look for the correct architecture;

```bash
docker tag dfc30428e163 arm64centos7:7.9

echo -e 'FROM arm64centos7:7.9\nRUN echo "test hello"\n' | docker build -

[+] Building 1.6s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 87B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/arm64centos7:7.9  1.5s
 => [auth] library/arm64centos7:pull token for registry-1.docker.io        0.0s
------
 > [internal] load metadata for docker.io/library/arm64centos7:7.9:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

However, this time it tries to do so using the custom name (`arm64centos7:7.9`, or "canonical": `docker.io/library/arm64centos7:7.9`). That fails, because that image either doesn't exist, or the image _exists_ but may be a private image and it doesn't have the right credentials to access it.
Because of that, the build is marked as "fail", as it cannot automatically resolve that situation;

- The request was to build an image for the "native" (`linux/amd64`) platform
- The image in the local cache does not match that platform (the cached image is `linux/arm64`)
- It's unable to check if a variant of the image with the correct platform exists, either because the image doesn't exist, or because credentials are incorrect or missing.

To resolve this, you can explicitly tell docker to use the platform that you want to build for using the `--platform` flag. When doing so, docker will look in the image cache, find that the image has the correct platform (architecture), and will be able to use the local image:

```bash
echo -e 'FROM arm64centos7:7.9\nRUN echo "test hello"\n' | docker build --platform=linux/arm64 -

[+] Building 0.1s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 87B                                                               0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 2B                                                                   0.0s
 => [internal] load metadata for docker.io/library/arm64centos7:7.9                               0.0s
 => [1/2] FROM docker.io/library/arm64centos7:7.9                                                 0.0s
 => CACHED [2/2] RUN echo "test hello"                                                            0.0s
 => exporting to image                                                                            0.0s
 => => exporting layers                                                                           0.0s
 => => writing image sha256:d9e0a7b8b72942919485898e83778053faab6f4944a642354be851374e57d0aa
 ```
