### ISSUE TITLE
Information on named-pipe or changing default-linux context

### ISSUE THREAD

**Issue by icsy7867** [docker/for-win#12397]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
N/A
### Expected behavior
N/A
### Information

This is an addition to my last issue.  Due to policy issues we cannot use WSL2 and our VMs require a certain level of settings and compliance as well.  Namely FIP 140-2, however there are others as well. I am testing deploying a custom VM as the DockerDesktopVM and I have this working.  Starting/Stopping correctly boots/stops/changes via the settings in Docker Desktop.  However the engine cannot connect to it successfully.  If I set "DOCKER_HOST" Docker Desktop will connect without an issue, but it still runs the default DockerDesktopVM and connects via:

> desktop-linux       moby         npipe:////./pipe/dockerDesktopLinuxEngine

I have found I can force the desktop-linux the a tcp socket instead of an npipe.  But looking at the logs, it looks like things still want to connect via this named pipe.

So I mainly have a few questions (And I am sorry they are odd)

1.  Is there a way to change all the connections to use TCP instead of a named pipe?

2. If not, is there any directions or instructions on how this named pipe is facilitated in the default DockerDesktopVM?

3. Or is there are documentation about running your own custom docker host instead of the default MobyLinux/LinuxKit?

**Comment by stephen-turner** [comment]
Thanks for your questions, @icsy7867.

I'm not sure we have any very good advice for you because the LinuxKit VM is not designed to be swappable. Our philosophy is in some sense the opposite: to try and make the whole system as much of a black box as possible, not with the aim of deliberate obfuscation, but rather because that's the way we achieve transparent, seamless operation between the host and the VM. We want the user to feel like they are running containers natively on their laptop, so we hide the implementation details such as the VM, and the networking and file sharing across the VM boundary. Because of this, it's not going to be easy to swap out different components or change the communication paths between them. Sorry, I realise that's not the answer you were looking for.
