### ISSUE TITLE
Load metadata hangs infinitely

### ISSUE THREAD

**Issue by speller** [docker/for-win#12399]
My Docker Desktop just stopped building anything and hanging infinitely on pulling metadata:

```none
[+] Building 1610.3s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                             0.1s
 => => transferring dockerfile: 38B                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                0.1s
 => => transferring context: 34B                                                                                                                 0.0s
 => ERROR [internal] load metadata for docker.io/library/node:14.17.4-alpine                                                                  1610.2s
------
 > [internal] load metadata for docker.io/library/node:14.17.4-alpine:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
```

This was cancelled by Ctrl+C after 1610 seconds of waiting. Internet is accessible, the `index.docker.io` domain is accessible.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (I don't know how to make and upload diagnostics)

I tried to shutdown WSL but it didn't help.

  - Windows Version: Microsoft Windows [Version 10.0.22000.346]
  - Docker Desktop Version: 4.2.0 (70708)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by speller** [comment]
Only system reboot helped

**Comment by EricHripko** [comment]
Observed something similar after upgrading to `4.2.0`. This seems to be caused by `~/.docker/config.json`, which points back to Windows for the credential store. If Docker Hub is for any reason inaccessible (e.g., is blocked or proxies are needed to access), `docker` CLI in WSL hangs for a long time (about 5 minutes) before doing anything. Removing `~/.docker/config.json` seemed to work.

**Comment by mattwelke** [comment]
Maybe this is related to https://github.com/docker/for-win/issues/10247? We've been tracking an issue that came up in late 2020/early 2021 where it was a 10 second delay but with it always working once the delay passed. And not helped by a reboot. Sounds like this problem is different, but since they both involve "load metadata" hanging, maybe they share a root cause.

**Comment by speller** [comment]
The issue happened on my machine again a couple of hours after rebooting the system. None of the operations that require internet connection work metadata load, authentication, pull command hang for forever. Dockerhub website is accessible:

```none
curl  https://index.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

The removal of the `"credsStore": "desktop.exe"` config from the `~/.docker/config.json` helps.

**Comment by DavidBurela** [comment]
> Removing `~/.docker/config.json` seemed to fix the issue.

Thanks @EricHripko removing that file resolved the issue for me
