### ISSUE TITLE
Docker installation causing Windows to not load properly

### ISSUE THREAD

**Issue by Ascendus** [docker/for-win#12411]
Not sure if this is the right place, but I installed the Docker extension on Visual Studio Code, and after pressing the Docker icon on the left it said Docker was not installed, and asked if I wanted to install it. I pressed yes and went through the installation process. Afterwards to said I needed to restart my laptop. After that now I get the blue screen of death and this error:
![C3598763-F4B2-4B53-81C2-D1544CCC6FEC](https://user-images.githubusercontent.com/72182515/144495300-b7bc65f8-cc4d-47e2-9f68-23ca52c7e852.jpeg)

My laptop won’t work now and is my only device apart from my phone, so I need help urgently.

**Comment by StefanScherer** [comment]
Maybe your computer is not compatible with WSL2. The installer selects both `Virtual Machine Platform` and `Windows Subsystem for Linux Windows` optional features when a reboot is required. You may have to uninstall these features. Other than that we can't really help here, because that are basic Windows 10 features. 😢

**Comment by Ascendus** [comment]
I've managed to restore the system, and I'm back on my laptop now.

**Comment by Ascendus** [comment]
I did have WSL previously installed, too.

**Comment by Ascendus** [comment]
Looks like it's using WSL1, however.
