### ISSUE TITLE
Docker for Windows fails to use a local NFS share

### ISSUE THREAD

**Issue by ArvinB** [docker/for-win#1241]
### Expected behavior
Using the -v option I wish to map a local NFS share on the Docker host with a destination folder in my Ubuntu Docker image.

### Actual behavior
Nothing...no error...no nothing. When I run the docker run... it sits there for a long time and then times-out. It's as if there is something blocking between the Docker for Windows and the NFS share. My firewall and Anti-virus all seem ok.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
E42E0A20-3ED8-49C5-A58D-60E389FA7FD0/2017-10-24_10-33-24

  - a reproducible case if this is a bug, Dockerfiles FTW
Yes it is reproducible

  - page URL if this is a docs issue or the name of a man page
N/A

  - host distribution and version (Windows version, build number, etc)
Windows 2016 Server
Docker 17.09.0-ce

### Steps to reproduce the behavior

  1. Install Active Directory on the windows host
  2. Install NFS Server and Client on the windows host
  3. Install Docker for Windows on the windows host
  4. Create an NFS share with permissions to the world
  5. docker volume create --opt type=nfs --opt device=:/myNFSShare --name myNFSShare
  6. docker run -it --name myImage -v myNFSShare:/var/nfsmount -e LICENSE=accept --entrypoint=/bin/bash ubuntu -i

**Comment by Yivan** [comment]
@jasonbivins is this issue going to be considered and have some answer/way to go please ? (opened 3 months ago)
@ArvinB do you manage to get it works ?

We swithed from Docker Toolbox + NFS (using HaneWin NFS Server on Windows) wich give a very good perfs even with Symfony 3 projects to Docker for Windows. As it uses Samba, we had a performance degradation, and we wish to mount NFS volume too as it is documented and officially supported here at the bottom of this page: https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options

We had the exactly same problem than @ArvinB 

```
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.75.1,rw --opt device=:/server-dev mynfs
docker run -it --rm --v mynfs:/server-dev alpine sh
```
Timeout after several minutes...

Share work great because if we do it manually:
```
docker run -it --rm alpine sh
mkdir /server-dev
mount -t nfs -o rw,hard,nolock 10.0.75.1:/server-dev /server-dev
```
It works great (but not usable for our team, we want nfs volume as it will be mounted to several docker container).
@ArvinB so this don't seems a firewall problem.

Questions:
- is it a bug ?
- is the used IP in my example ok ? (how can i know the IP to use, no clue is given in the documentation). I tested 10.0.75.1 and 192.168.65.2, both work with manual mount methods but the second one get trougthput speed 4x time slower (because this virtual network is slower is think - i benchmarked with `dd if=/dev/zero of=./output bs=8k count=10k; rm -f ./output`)

Actually Docker for Windows with Samba is a lot more slower (10x...) for short request (multiple ajax for instance). We get 1 sec for ajax request using shared code library where NFS make the request in 120 ms...

We tried to going into the MobyLinuxVM in Hyper-V but it seems you hardened it more and more, all ways works no more (https://github.com/vipconsult/dockerfiles/tree/master/moby-nfs-mount don't work has iso is not writable, and the other way using privilegied/noseccomp in sub docker exec don't work too...).
Is there a way to mount or at least set an export in the LinuxMobyVM ?

**Comment by Yivan** [comment]
For those getting the same problem, it seems the nolock option did the trick:

The following work great:
```
docker volume create --driver local --opt type=nfs --opt o=addr=10.0.75.1,hard,nolock,rw --opt device=:/server-dev mynfs
docker run -it -v mynfs:/server-dev alpine sh
```

**Comment by GuiOliveira98** [comment]
If you are still getting this error, try using "nfs4" instead of "nfs" on type and if that doesnt work, try adding "insecure" on the "/etc/exports" in the nfs server host
