### ISSUE TITLE
3EDA7B3A-BC96-4CDE-B172-43FA491B1BCC/20211208081338

### ISSUE THREAD

**Issue by vikrams1** [docker/for-win#12426]
Kubernetes not starting in docker desktop

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
