### ISSUE TITLE
Unable to uninstall dokcer from windows 10 system..

### ISSUE THREAD

**Issue by DevOpsBT** [docker/for-win#12476]
**log details**
[log.txt](https://github.com/docker/for-win/files/7800471/log.txt)

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
