### ISSUE TITLE
Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by byronv5** [docker/for-win#12481]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:25E73124-BF39-4383-B050-52398FBE278F/20220106014831

### Actual behavior
Docker Desktop is not starting
### Expected behavior
Docker Desktop is expected to start
### Information
  - Windows Version:Win 10 20H2 19042.1415
  - Docker Desktop Version:4.3.1
  - WSL2 or Hyper-V backend: yep
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[FAIL] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
Please investigate the following 1 issue:

1 : The test: are WSL distros installed?
    Failed with: WSL Distribution docker-desktop-data is missing
The Docker engine uses several WSL distributions. Therefore these must be installed.
### Steps to reproduce the behavior

  1. I have tried to uninstall the old version
  2. Start Docker Desktop after installed the latest version

**Comment by jpvincent** [comment]
Hi 
I have the same problem. Since several months, the docker desktop GUI is not launching at all. I unistalled, reinstalled, even as an admin, I tried to execute the GUI as an admin, without success.

 The docker desktop seems to be running in the background because it appears in the task manager so I guess it's not crashing, but 
* I can not access it from my Ubuntu WSL2 like before 
*  at the end of the diagnosis check, it tells me docker-desktop is missing to WSL.

```
1 : The test: are WSL distros installed?
    Failed with: WSL Distribution docker-desktop is missing

The Docker engine uses several WSL distributions. Therefore these must be installed.
```


As a matter of fact, the `wsl.exe -l` command only list my Ubuntu subsystem :
```
Distributions du sous-système Windows pour Linux :
Ubuntu (par défaut)
```

I can not install it manually as it's not listed "online", so I guess Microsoft dont reference it. See ` wsl --list --online`

```
Voici la liste des distributions valides qui peuvent être installées.
Installer à l’aide de « wsl --install -d <Distribution> ».

NAME            FRIENDLY NAME
Ubuntu          Ubuntu
Debian          Debian GNU/Linux
kali-linux      Kali Linux Rolling
openSUSE-42     openSUSE Leap 42
SLES-12         SUSE Linux Enterprise Server v12
Ubuntu-16.04    Ubuntu 16.04 LTS
Ubuntu-18.04    Ubuntu 18.04 LTS
Ubuntu-20.04    Ubuntu 20.04 LTS
```

WSL2 seems to be running fine, as I can still use my Ubuntu. The docker executable is available from Powershell, but I need it to start it from the Ubuntu distro, as before.
