### ISSUE TITLE
com.docker.wsl-distro-proxy.exe crashes on startup

### ISSUE THREAD

**Issue by JanWaller-FHKiel** [docker/for-win#12489]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E07ABAD6-29D7-4725-9CEA-ECF5E1787F01/20220109151822

### Actual behavior
Since two days, com.docker.wsl-distro-proxy.exe crashes on startup!
Last lines of relevant log file:
[009:16:03:02.606][I] wsl.exe -d Ubuntu -u root -e /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Ubuntu --docker-desktop-root /mnt/wsl/docker-desktop
[009:16:03:02.828][F] Proxy error: exit status 1
[main.main()
[	win/backend/cmd/com.docker.wsl-distro-proxy/main.go:187 +0x163a

Further debugging:
sudo /mnt/wsl/docker-desktop/docker-desktop-proxy --distro-name Ubuntu --docker-desktop-root /mnt/wsl/docker-desktop
[009:16:12:14.332][I] mounting /var/run/docker.sock to /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/71329c4cc6e32171553fa81d044eb31d1a3aac52ba9376c4a99f4505c494cf5b
[009:16:12:14.332][W] restoreMounts: ensure ready failed: not a directory
[009:16:12:14.332][F] not a directory
[main.main()
[       docker-desktop-proxy/main.go:149 +0xa94

### Expected behavior
normal startup

### Information
Reinstalled once, taht fixed it for the day. Next day, I had the same problem again!
  - Windows Version: 11
  - Docker Desktop Version: newest
  - WSL2 or Hyper-V backend?  wsl2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

Any idea on how to fix this problem?
I worked three days ago. Afterwards no longer working. With no known changes on my side.

**Comment by DavidCozens** [comment]
I've had very similar if not the same, after a lot of hunting around I found some hints that this could be caused by a firewall. I have McAfee livesafe, turning off the firewall helped, the proxy now runs after a restart.

The impact of the proxy not running was that the WSL distro integration failed, looking in /usr/bin in my ubuntu distribution I found that none of the expected softlinks to the dockerexecurables existed. This is now _almost_ working, all of the links are in place apart from docker itself. There is no link to docker, but there is a folder /usr/bin/docker. 

I've managed to remove the /usr/bin/docker directory using sudo rmdir, but when I restart docker it recreates an empty folder rather than a link
