### ISSUE TITLE
No way to increase available RAM for linuxkit based workloads

### ISSUE THREAD

**Issue by bartverstrynge** [docker/for-win#1254]
### Expected behavior
When running images that require a lot of RAM, i.e. microsoft/mssql-server-linux, the container immediately stops with a notification that more RAM should be made available to the running container.

### Actual behavior
There is no option to configure the RAM used by linuxkit based workloads, for as far as I can see

### Steps to reproduce the behavior

  1. docker run microsoft/mssql-server-linux on Windows 1709 + LCOW Docker for Windows edge 17.10.0-ce-win36 (13788)

**Comment by thomasmaurer** [comment]
Yep same here.
"sqlservr: This program requires a machine with at least 3250 megabytes of memory."

**Comment by thaJeztah** [comment]
Did you increase the amount of memory in the configuration panel? https://docs.docker.com/docker-for-windows/#advanced

![settings-cpu-ram](https://user-images.githubusercontent.com/1804568/32165001-8702b96e-bd61-11e7-82ab-f023e6bcb43b.png)

**Comment by thomasmaurer** [comment]
With the new linuxKit option where you run Linux Container directly on Windows and not in the mobyVM, dies setting panel is not there anymore.

**Comment by rn** [comment]
I don't know if this is wired up in LCOW yet, and currently don't have a system at hand, but could you try `docker run --memory <size>`?

**Comment by rn** [comment]
@thaJeztah just pointed me at https://github.com/docker/for-win/issues/1137 suggesting that this has not been hooked up yet

**Comment by thaJeztah** [comment]
Sorry, it wasn't clear you meant the experimental LCOW (Linux Containers On Windows) feature (as the "regular" Linux containers now also use LinuxKit since docker 17.10.

This feature is not feature-complete yet, and additional features will be added in future; see the issue that @rn linked above; https://github.com/docker/for-win/issues/1137

Let me close this issue to not have the discussion diverge
