### ISSUE TITLE
Docker loading forever

### ISSUE THREAD

**Issue by KnownAsMomoVV** [docker/for-win#12577]
@askareija 

+1 same here i cant even run my Diagonstics

![image](https://user-images.githubusercontent.com/74142294/155107208-1d473aec-6dde-4836-b8aa-b4e91a20ae51.png)

OS : Windows 11

Edition	Windows 11 Pro
Version	21H2
Installiert am	‎31.‎01.‎2022
Betriebssystembuild	22000.493
Leistung	Windows Feature Experience Pack 1000.22000.493.0

And these are the Logs
![image](https://user-images.githubusercontent.com/74142294/155108517-35a0545c-681a-4621-9459-e3823949033e.png)

_Originally posted by @KnownAsMomoVV in https://github.com/docker/for-mac/issues/6048#issuecomment-1047614431_

**Comment by laurazard** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
