### ISSUE TITLE
Can't Install Docker Desktop for Windows

### ISSUE THREAD

**Issue by jmcgroar** [docker/for-win#12627]
Here's my tale of woe when trying to install Docker Desktop for Windows on a machine with Windows Pro machine.

1. First installed Docker Desktop for Windows using the Docker Desktop Installer.exe.  That seemed to work, but it ate up too much space on my C drive which I reserve for the OS.  So, I uninstalled it and looked for a way to specify an alternate install path using Docker Desktop Installer.exe.
2. Had no luck finding a way to specify an alternate install path using Docker Desktop Installer.exe, but found instructions for installing Docker Desktop for Windows using DockerDesktop.msi and specifying the install location using the INSTALLDIR command line option.  That also seemed to work, but when I tried to open Docker Desktop, it complained about a missing license file. Checked my entire system, the license file is nowhere to be found.  Maybe this installer is strictly for the pay version of Docker Desktop?
3. I decided to uninstall this version and go back to the version installed using Docker Desktop Installer.exe.
4. Now, when I double click the Docker Desktop Installer.exe from Explorer, I get the "Do you want to allow this app to make changes to your device?" dialog box.  When I click "Yes" to proceed, the installer dies.
5. I next tried executing Docker Desktop Installer.exe from a command prompt to see if I could get some feedback as to what is happening.  That approach did provide me some feedback information which I've attached.  The information in the attached file is console output from the command prompt window.  I tried executing the Docker Desktop Installer.exe from both an Administrator command prompt window and from a regular old command prompt.  The attached file contains the console output from both attempts.

Hope this helps

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

[install-log.txt](https://github.com/docker/for-win/files/8358405/install-log.txt)

  1. ...
  7. ...

**Comment by Dizirgee** [comment]
I've run into "similar" problem. My first time with docker I admit, but it is very frustrating its not possible to select storage location with installer ...also there wasnt option to select installdir at all.
After my C: getting filled I was trying to figure out how to move data, but not much luck.

Win10 enterprise 21H2 19044.1645
Docker Desktop 4.7.0 (77141)  (installed today 20220419, should be latest)
WSL2 enabled (didnt test hyperv yet, as wsl2 seems to be suggested option)
I'm using nonadmin user, added into docker-users group

According to https://docs.docker.com/engine/reference/commandline/dockerd/ data-root should be able to move it (but only for new images/data, according some posts) , however i have two issues with that docu page (maybe not supposed to complain here but)
1. should mention correct syntax on windows hosts for "data-root": "",  after testing i assume it is like this "C:\\\temp\\\dockerdata"
2.  `On Windows
The default location of the configuration file on Windows is %programdata%\docker\config\daemon.json`  However this was either changed or for some reason i have no "docker" in C:\programdata (there is only C:\ProgramData\DockerDesktop) , though i found it under C:\Users\username\\.docker\

Now, seems there is BUG, if i add data-root to config file, "docker desktop" just wont start (stuck in starting) , and vmmem sits at  20% cpu util (on 6c12t cpu) , there is no disk IO activity , have to stop "docker desktop service" and kill docker desktop processes to make vmmem calm down

I thought this may be due to using non system drive, as photoprism devs https://docs.photoprism.app/getting-started/docker-compose/ says that WSL2 shouldnt be used if i want to use non system drive (apply for containers/apps i assume) , If this is true it could be mentioned in docu, or in otherwise good docker101tutorial app when discussing volumes/binds
So i tried with two folder on C: but no luck.

I didnt test with enabling hyperv setting yet

diagnosticID (when its able to start, ie no data-root in config) 410C6451-1258-4C8E-B973-14CDD42BC6A1/20220419192816
attaching output of above requested diagnose.exe and dockerd.log (C:\Users\username\AppData\Local\Docker\log\vm) as hinted by diagnose output when data-root is added/its hung, these are last errors:
`time="2022-04-19T20:04:06.510910869Z" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir="C:\\temp" error="error getting daemon root's parent mount: Can't find mount point of C:\\temp"
[2022-04-19T20:04:06.512183091Z][dockerd][I] 
time="2022-04-19T20:04:06.512003145Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
[2022-04-19T20:04:06.513272455Z][dockerd][I] 
time="2022-04-19T20:04:06.513166586Z" level=warning msg="could not change group /run/guest-services/docker.sock to docker: group docker not found" `


**Steps to reproduce the behavior:**
add "data-root": "", into C:\Users\username\\.docker\daemon.json
[com.docker.diagnose.exe.log](https://github.com/docker/for-win/files/8516265/com.docker.diagnose.exe.log)
[dockerd.log](https://github.com/docker/for-win/files/8516266/dockerd.log)

Sorry for hijack but didnt want to spam with new issue.
