### ISSUE TITLE
The latest version of docker is harmful says edge after downloading

### ISSUE THREAD

**Issue by Joel-Nickson** [docker/for-win#12659]
- [x] I have tried with the latest version of Docker Desktop

### Actual behavior
The MS edge gives a warning and shows that it is a harmful product

### Expected behavior
The installer should not show this warning on windows 11

### Information

  - Is it reproducible? : Edge only reported it once, the second installation did not show any warning.
  - Is the problem new? : Yes
  - Edge Version : 100.0.1185.36 (Official build) (64-bit) 
  - Windows Version: 21H2 (OS Build 22000.556)
  - Docker Desktop Version: 4.7.0
  - WSL2 or Hyper-V backend? 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
![image](https://user-images.githubusercontent.com/61058781/162637591-f3006e8c-a315-42c7-9d1c-c1c5169989fa.png)

### Steps to reproduce the behavior

  1. Open Edge Browser
  2. Install the Docker from this official image : https://docs.docker.com/desktop/windows/install/

### Problems After Installation and use

- PC did not restart Correctly. Automatic repair Failed

**Comment by mat007** [comment]
Hi, thanks for reporting.
I have Version 100.0.1185.36 (Official build) (64-bit) as well but I can’t reproduce it.
Manually making Windows Defender scan the file doesn’t turn up anything either.

What happens if you tell Defender to scan the file?
(right mouse button then «Show more options» and «Scan with Microsoft Defender...»)
