### ISSUE TITLE
Desktop for Windows/Mac - Signing in and Signing out automatically 

### ISSUE THREAD

**Issue by benlumia007** [docker/for-win#12739]
I found myself in a situation where you sign in to the docker desktop on Mac or Win, It keeps logging you out after a while. I have never had this issues and is getting annoying.

**Comment by laurazard** [comment]
Hi @benlumia007 , thanks for your report. We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
