### ISSUE TITLE
WSL2 installation is incomplete

### ISSUE THREAD

**Issue by Fish19871987** [docker/for-win#12791]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Diagnose Failed

### Actual behavior
Installed new software and get WSL2 installation is incomplete
### Expected behavior
Software to work properly
### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: V4.9.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...
![Untitled](https://user-images.githubusercontent.com/107993676/175001727-b34a5dde-85d8-4f0c-aefb-f15109578a71.png)

**Comment by rfay** [comment]
I strongly recommend that you use `wsl --install` to install WSL2 and do not rely on Docker to do it for you. I don't think this always works out. In the situation you're in, you may have to uninstall WSL2 completely to be able to do that. 

You're not really very clear on what your problem is, so if you could edit the original post to say what actually happens to you it would help people to help you. 

If you need to uninstall WSL2 to start the process over, uninstall Docker Desktop and then follow these instructions to uninstall WSL2 completely, https://pureinfotech.com/uninstall-wsl2-windows-10/, then `wsl --install` and then install Docker Desktop again. Note that lots of people are having trouble with the current 4.9.1  on Windows, so you may need to install an earlier version like 4.8.2 or 4.8.0
