### ISSUE TITLE
sconfig hangs in windowsservercore

### ISSUE THREAD

**Issue by douglaswaights** [docker/for-win#128]
Hi,

### Expected behavior
sconfig brings up the interface and options as expected

### Actual behavior
In a running windowservercore container typing sconfig causes the system to hang on inspecting system and never shows the options...

### Information
I'm running on Windows 10 anniversary edition
the imageid is f20579da8e4e
The reason for using sconfig is to try and install the latest windows updates so i can try and fix https://github.com/docker/for-win/issues/124

### Steps to reproduce the behavior

docker run -it microsoft/windowsservercore powershell
sconfig

Thanks
Doug

**Comment by jhowardmsft** [comment]
@patricklang can you confirm. I don't think this is expected to work.

**Comment by friism** [comment]
Yeah, I don't think it's expected to work.

**Comment by douglaswaights** [comment]
OK thanks for the replies, so how then do i do a windows update for a running servercore container with regards #124 ?

Thanks
Doug

**Comment by PatrickLang** [comment]
Sorry for the slow response here. @friism just pinged me again on this today and I got some more info

@douglaswaights - all of Microsoft's fixes will come down in a Windows Update package on the host machine, in an updated container image such as `microsoft/windowsservercore`, or both depending on the fix. You shouldn't need to run sconfig/wusa/other tools in the container to get a fix inside the container.

If you need to patch a container later because you can't rebuild off the latest `microsoft/windowsservercore` image for some reason such as not having the original Dockerfile and binaries - we're working on a solution for that and will share it on the [Windows Container doc site](http://aka.ms/windowscontainers) when its available.

**Comment by rneugeba** [comment]
@PatrickLang thanks for the details

@douglaswaights I'm closing this issue, as I think your question is answer. Please re-open if this is not the case.

thanks for reporting

**Comment by douglaswaights** [comment]
Thanks for the update!
Doug

**Comment by wickstargazer** [comment]
How do we solve problems with latest containers not being able to install stuff like build_tools in the latest version and have to wait for no fixed dates for the release with latest patches? Or where can i follow the news and dates of release?!!

**Comment by rdebath** [comment]
Just as a matter of interest does anyone (preferably Microsoft) have a version of the `sconfig.vbs` script that doesn't do stupid things like "popping up a `msgbox` if it's running on docker".
