### ISSUE TITLE
Docker failed to initialize - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Drummond-Dev** [docker/for-win#12829]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
When I start Windows, a dialog box always appears with the message (Docker failed to initialize - Object reference not set to an instance of an object.) and I can't do anything with Docker.
I've tried uninstalling it and it won't work either.
### Information

  - Windows Version: 11 Pro
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
