### ISSUE TITLE
Error: MUI: The path returned by getTreeDataPath should be unique

### ISSUE THREAD

**Issue by aeroschmidt** [docker/for-win#12844]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Ive tried to execute docker when this happened
![image](https://user-images.githubusercontent.com/8289587/179382507-01b7d840-d83c-4e94-b985-de4e6f1fa446.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/8289587/179382559-78bac4a8-f649-45a2-8380-222d12f56870.png)

### Information

  - Windows Version: Windows 10 pro 10.0.19044
  - Docker Desktop Version: v4.10.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Just open e close quickly

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
thanks for reporting! I have a hunch on what this is, but I have to ask someone to be sure. Might need to ask you more questions about the containers you're running, stay tuned!

**Comment by joeklin** [comment]
Same issue here after upgrading
![image](https://user-images.githubusercontent.com/3605836/179522120-7e7aa3ad-564d-40ef-a77d-7112cf14f7ea.png)

**Comment by trungutt** [comment]
@joeklin @aeroschmidt Could you please give us a reproduction case? Such as a minimal `docker-compose.yml` file

**Comment by aeroschmidt** [comment]
Hi, im attaching a file with instructions, hope this helps
[docker-compose.zip](https://github.com/docker/for-win/files/9136147/docker-compose.zip)

**Comment by trungutt** [comment]
Hi @aeroschmidt Could you please try out this custom build to see if the problem still persists?

https://desktop-stage.docker.com/win/main/amd64/83245/Docker%20Desktop%20Installer.exe

I tried the above build with docker-compose.zip above, a dummy Dockerfile (content `FROM nginx:alpine`), `docker-compose up -d` and somehow I couldn't reproduce this screen 

<img width="954" alt="Capture d’écran 2022-07-22 115610" src="https://user-images.githubusercontent.com/18528548/180415093-70cd48e7-27a9-4ed8-aaf9-ef9381eb02da.png">

Hope to hear from you

**Comment by aeroschmidt** [comment]
Hi @trungutt, i'm sorry but the error doesnt happen anymore.

**Comment by trungutt** [comment]
@aeroschmidt No problem. We're making a new release this week, feel free to try it out. I close this ticket but if something wrong happens again, feel free to open a new ticket

**Comment by kallesommernielsen** [comment]
I just experienced this error myself, after I had restarted Docker Desktop due to the latest update. When I clicked on the play-button to start project of 7 containers, it had to recreate them (I assume due to the upgrade) and I saw the number of containers grow from 7 to 15 (likely due to the `<hash>_<container name>-1` names), once it hit the 15th, the user interface changed as seen from the previous post here:
https://github.com/docker/for-win/issues/12844#issuecomment-1187432803

This rendered docker entirely unusable except if I was talking to docker via the CLI, at least add an option or similar to refresh the user interface as it is impossible to recover from it.

My theory is that this happens during these container recreations that may cause a duplicate unique identifier when deleting the temporary container or similar (or however it is implemented)

**Comment by nicks** [comment]
thanks @kallesommernielsen , let's re-open this.
