### ISSUE TITLE
docker desktop has memory leaks?

### ISSUE THREAD

**Issue by ash-hashtag** [docker/for-win#12843]
# clear information
No containers running, just built a small image a long time ago.
Docker desktop been running in the background for 6 hours i think, i don't know. My pc started lagging, opened task manager and seen docker desktop hogging up my memory, about 3GB RAM. That's only I got. Is it caching my previous build dependencies?

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
