### ISSUE TITLE
Pi node unable to update availibility time and bonus awards are zero

### ISSUE THREAD

**Issue by sureshjkb** [docker/for-win#12858]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Ranald236** [comment]
Same here. Node bonus in the app is 0. Running Windows 10, latest docker version. All ports are open. Uptime is now 82,69% for a couple of days.

**Comment by Ranald236** [comment]
What i also can see that the "Availability" is stuck mine says from 2022-07-13 (correct) to 2022-07-20 (incorrect) because today is 2022-7-22. So something is wrong on there side i think.

**Comment by eogextreme** [comment]
Same here for 4 days and availability is going down:

Diagnostics Info
Container
Consensus container enabled: Yes

Node switch on: Yes

PortsChecker container: exited

Consensus container: running

Consensus
State: Synced!

Protocol version: Latest

Latest block: a few seconds ago

Outgoing connections: 8

Incoming connections: 2

Supporting other nodes: Yes

Other
Pi Node version number: 0.4.5

Operating system: WINDOWS 10.0.19044 (Microsoft Windows 10 Pro for Workstations)

Using Docker Toolbox: No

Node installation date: xxxx-xx-xx

Availability (up to 90 days): 88.15% from 2022-04-25 to 2022-07-24

**Comment by Ranald236** [comment]
Still i have the same. Do you see the "node bonus" in the pi app? Mine is still zero. Availability also dropped but the date is now oke.

**Comment by Macromart** [comment]
When you setup the node, you put a linking code into your phone. This link code joins your node to your phone pi account. Something changes on your computer that Pi Network is using to identify your computer. It loses sync and you don't get pi paid for your time and effort. When the link is broken and your Pi remuneration stops. This has been going on since 2020. (I looked at an announcement on the Developers chat room they were talking about it back then) I've tried to get a fix for this but no one seems to listen. The only way to fix it is to reinstall from a bare windows system. The node doesn't have an uninstaller program. If you try and reinstall without cleaning house, you cant put in a new linking code. No one seems to be working on the node software. It has vulnerabilities that are critical according to programs I've run on Docker. This I DON'T LIKE!!!!

So, fellow Node runners......your are not alone. And it isn't very professional. Not good!!!

I've been reinstalling every 3 to 4 days for months. Gets to be too silly eventually.
