### ISSUE TITLE
Windows 11 WSL Docker Desktop publish http ports and does not publish https ports

### ISSUE THREAD

**Issue by ivansarachman** [docker/for-win#12853]
I am using this docker-compose:

`version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443`

In Windows 11 WSL Docker Desktop I can access http://192.168.1.80/ or http://127.0.0.1/ or http://localhost/, but I can not access https://192.168.1.80/ or https://127.0.0.1/ or https://localhost/.

ERR_CONNECTION_CLOSED in Chrome or PR_END_OF_FILE_ERROR in Firefox.

In Windows 10 WSL Docker Desktop, with the same docker-compose, I can access http://192.168.1.80/ or http://127.0.0.1/ or http://localhost/ and I can access https://192.168.1.80/ or https://127.0.0.1/ and https://localhost/.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
