### ISSUE TITLE
Read $ in env

### ISSUE THREAD

**Issue by nal-duongpq** [docker/for-win#12863]
I using "$" in env. But docker make "$" and endline.
In MacOS, I working good.
Thank you.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
