### ISSUE TITLE
docker push error 404: 

### ISSUE THREAD

**Issue by xiaomaosusie** [docker/for-win#1291]
While pushing image I had following error:
:
```
error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n"
```
I'm using windows 10; trying to push image to corporate private registry. 

### Information

  - Diagnostic ID: 59336000-3628-4D06-8666-77DD45BCA64F/2017-11-06_18-36-12

### docker info
```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 22
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: RHZQ:CRI7:JM4B:GEVX:KJ3Q:22WS:YWU4:BYBI:QZYA:6BYS:AIW4:TO6F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 25
 System Time: 2017-11-06T23:41:08.5224314Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries: (I've input private registry...I just removed it here for security purpose) 
 127.0.0.0/8
Live Restore Enabled: false
```
Let me know if anything else I shall provide...

Thank you so much!!

**Comment by xiaomaosusie** [comment]
Hi Jason,

Thanks for picking up the ticket. I had a feeling that it could be related to V1 and V2 thing...I noticed that the latest docker I downloaded automatically generate  http://private host:5000/v2/repositories while my corporate one is http://private host:5000/v1/repositories....if I changed "v1" to "v2", I got the 404 error. 

Would this be the issue? 

Thanks,
Susie

**Comment by jasonbivins** [comment]
Hi Susie, thanks for the extra information! The "v1" and "v2" are definitely the issue here, the error you're seeing says that it's a mistyped URL.  Are you using DTR, or is your company using the standard Docker hub?  
![image](https://user-images.githubusercontent.com/28021664/32616921-9a91debe-c541-11e7-954c-6591109eed98.png)

**Comment by jasonbivins** [comment]
Hi Susie, do you have a Docker Login?  It looks like you're signed out.  You'll need to sign into your Docker Hub account to get to the right Repositories.
Try a  ``` docker login ``` command


Thanks

**Comment by xiaomaosusie** [comment]
I've created a login. my company is using our own insecure repository. So now I can see "Repositories"...do I need to set up anything here? 

Thanks,
Susie

**Comment by jasonbivins** [comment]
Hi Susie, 
If your Docker cloud account doesn't already attach you to the repositories you need, then you'll need to point to them manually using the Docker Daemon settings. Is there someone on your team who already has it setup, you should be able to copy theirs.
  Right click the Whale icon > Settings > Daemon
![image](https://user-images.githubusercontent.com/28021664/32622919-7ea1c820-c552-11e7-92e1-6c804d640525.png)

**Comment by xiaomaosusie** [comment]
Hi Jason,
Yes. I had set up "insecure-registries", same setup as my coworker. But then, the 404 error came along (the reason I submitted this ticket). Do you know how to solve the v1, v2 thingy? 

really appreciated,
Susie

**Comment by changming1988** [comment]
Hi Jason,
I had a same issue. I can login docker hub, run hello world successfully, and set the insecure registry, but I cannot pull image from our registry.

My colleague has the same configuration, and can pull image from our registry. But we cannot figure out what the problem is in my docker...

Thanks,
Arthur

**Comment by thaJeztah** [comment]
> while my corporate one is http://private host:5000/v1/repositories....if I changed "v1" to "v2", I got the 404 error.

@xiaomaosusie Yes, that most likely is the issue. The V1 protocol is deprecated, and interacting with V1 registries was deprecated in Docker 1.8.3. Since then, docker has printed a warning for each image that was pulled from a V1 registry; if you've seen that message when pulling images, then your internal registry is in deed a V1 registry;

    this image was pulled from a legacy registry.
    Important: This registry version will not be supported in future versions of docker

Since Docker 17.06, pulling from legacy registries was disabled by default (but could be enabled with the `--disable-legacy-registries=false`  / `{"disable-legacy-registries": false}` daemon configuration), and is now completely removed in Docker 17.12.

Docker 17.09 is the last version that still allows you to connect to v1 registries, but I would really urge you to upgrade your internal registry to a registry that supports the V2 standard. The V1 standard is known to have vulnerabilities, and if you're running the open-source V1 registry; that code hasn't been maintained for 3 years, and should not be used anymore.

You can run the open source V2 registry, but for a corporate environment I'd recommend running DTR (Docker Trusted Registry), as it also brings additional features targeted at corporate use (access control, security scanning of your images for CVE's/vulnerabilities, image signing)

**Comment by xiaomaosusie** [comment]
Hi @thaJeztah , where can I download Docker 17.09 for windows? 

Thank you so much!!
