### ISSUE TITLE
Error while run Docker Desktop on Win11

### ISSUE THREAD

**Issue by l00pss** [docker/for-win#12945]
Hi,
I get this error when I want to run the application. I turned off Hyper V and I'm getting the same error again. I've never had a similar problem before. At that time I was using a VM, it was fine after turning off Hyper-V, but now it is not.
Error : `Docker Desktop is shutting down.`

The second problem is that I cannot install the new version of Docker Desktop on my computer.
`Unpacking failed: Access to the path 'C:\Program Files\Docker\Docker\com.docker.service.config' is denied.
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()`
Thanks

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
