### ISSUE TITLE
Docker Desktop and Windows 11 Timeout

### ISSUE THREAD

**Issue by endo-aki22** [docker/for-win#12951]
- [ ] I have tried the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
![2022-09-06_18-40](https://user-images.githubusercontent.com/61251512/188615004-4724be80-d791-4133-b673-cbabc2e1985b.png)
### Information

  - Windows Version: 11
  - Docker Desktop Version: v4.12.0
  - WSL2 or Hyper-V backend? Yes 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
