### ISSUE TITLE
Docker Desktop doesn't want to start

### ISSUE THREAD

**Issue by mabram1** [docker/for-win#12950]
054CB91D-5E46-4868-986C-ED8314C977CB/20220906084855

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
