### ISSUE TITLE
System.InvalidOperationException: Failed to set version to docker-desktop: exit code: -1  stdout: Não há suporte para a operação tentada para o tipo de objeto a que é feita referência.

### ISSUE THREAD

**Issue by alessandrodesign** [docker/for-win#12962]
Não consigo instalar e executar o docker sempre exibe esse problema, estou instalando no windows 10, com wsl 2

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
