### ISSUE TITLE
Removing auto-adding of *.docker.internal is a significant breaking change

### ISSUE THREAD

**Issue by rfay** [docker/for-win#13463]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

In Docker Desktop 4.19.0 on both Windows and macOS, `*.docker.internal` is not resolved inside containers by default, as it has been for years.

That means `host.docker.internal` for example, is not properly resolved. 

It also seems that escalation has to happen on every restart, which means manual intervention at reboot time; this is also a breaking change. 

### Expected behavior

`host.docker.internal` should be resolved correctly inside containers as it has been for years

### Information

This seems to be deliberate on both Windows and macOS.

It can be enabled specifically but the user has to know to do it. 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/112444/236501056-1011771c-84b1-499a-8fb2-e3742e7ea74a.png">

**Comment by rfay** [comment]
Successfully changing this also seems to require system reboot on Windows.

**Comment by rfay** [comment]
Thanks @elapuyade - My first experience was that this change in 4.19.0 broke DDEV's use of host.docker.internal, and that adding enabling the hosts-file-addition fixed it. (And enabling the addition of the hosts file solved it)

I'll go back and study the actual problem and see if I can understand it. Perhaps something about it tricked DDEV into using a different host.docker.internal.

**Comment by rfay** [comment]
There are some really strange things going on here @elapuyade - 

1. On my system, without the additions to /etc/hosts, `host.docker.internal` resolves to 192.168.65.254 inside a container.
2. If I click the checkbox to have DD add to the hosts file, it adds the IP address `192.168.1.175` for host.docker.internal
3. However, after adding to the hosts file (and rebooting), the resolution inside the container is still to 192.168.65.254.

I don't think this is what is intended is it?

**Comment by galvakojis** [comment]
Same problem, fixed after enabled host fie

**Comment by elapuyade** [comment]
@rfay Everything you describe is normal and expected.

This is because the host and the container are not on the same network. The host has 2 network interfaces:
- one 'virtual' with IP `192.168.65.254` that is connected to the container
- one 'real'  with IP `192.168.1.175` that is connected to your LAN

1. When inside a container, your host can be reached at `192.168.65.254`
2. When you check the new setting to patch the host `etc/hosts`, it adds an entry with the local IP of your host, as viewed from the host real network. This entry is only used when you try to resolve from the host.
3. Rebooting doesn't change anything.

**Comment by rfay** [comment]
Closing this for now; although I've had reports of trouble I'm not able to recreate.
