### ISSUE TITLE
Docker cant open, keeps closing when i start. Reason : hypervisor unable thing. idk. i have Hyper-V turned on. idk why. im in windows 10

### ISSUE THREAD

**Issue by CommunistDex** [docker/for-win#13486]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  i have hyper - v turned on and 64 bit
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by CommunistDex** [comment]
please help me

**Comment by bhe-talendbj** [comment]
Yes, same problem for me.

always popup a window and say, then close....Actually my hyper visor is running and can check vms in windows hypervisor manager.

```
Check that hardware-assisted virtualization (either Intel VMX or AMD SVM) and Data Execution Prevention (sometimes labeled XD or Execute Disable or NX) are enabled in your BIOS.

Check your bootloader is configured to launch Hyper-V.

See https://docs.docker.com/desktop/windows/troubleshoot/#virtualization
```

**Comment by AndreSilva1993** [comment]
We’re closing this issue because it doesn’t contain enough information for us to investigate the problem. If you’d like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/desktop/troubleshoot/overview/?
