### ISSUE TITLE
docker desktop is not running

### ISSUE THREAD

**Issue by zaki-sudo** [docker/for-win#13542]
### Description

docker desktop is not running

### Reproduce

docker desktop is not running

### Expected behavior

docker desktop is not running

### docker version

```bash
docker desktop is not running
```

### docker info

```bash
docker desktop is not running
```

### Diagnostics ID

2D2197A0-80A4-49F9-9119-99D5678EA9B5/20230614014540

### Additional Info

docker desktop is not running

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
