### ISSUE TITLE
unable to detect a hypervisor i need help

### ISSUE THREAD

**Issue by Flowrack** [docker/for-win#13576]
### Description

please help

### Reproduce

123

### Expected behavior

it wont open

### docker version

```bash
idk
```

### docker info

```bash
'
```

### Diagnostics ID

6D517D76-F859-448F-A108-4ADB99DD7244/20230703093406

**Comment by lorenrh** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
