### ISSUE TITLE
Pulling a image build on windows 1709 fails on server 2016

### ISSUE THREAD

**Issue by thepill** [docker/for-win#1362]
### Expected behavior
A image wich was build on windows 10 1709 and pushed to a registry, should be working on Windows Server 2016.
### Actual behavior
Pulling the image fails with:

```
failed to register layer: re-exec error: exit status 1: output: time="2017-11-27T09:31:11+01:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\8f9191263fd2a5ae93c29ba554426c4adce8fcf333c1b9bf4f217556650d628e flavour=1 folder=C:\\Windows\\TEMP\\hcs456696507"
hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\?\C:\ProgramData\docker\windowsfilter\8f9191263fd2a5ae93c29ba554426c4adce8fcf333c1b9bf4f217556650d628e flavour=1 folder=C:\Windows\TEMP\hcs456696507
```

### Information

  diagnostic id (Windows 10 1709): `1F535868-F728-4D28-A97A-611BAA5D870F/2017-11-27_13-13-34`

The docker file is as simple as possible for my testing:

`FROM microsoft/aspnet`

docker version on my machine:

```
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

docker version on the server 2016 nodes:
```
Client:
 Version:      17.06.2-ee-5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:51:36 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ee-5
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   508bb92
 Built:        Thu Nov  2 00:54:07 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Comment by jasonbivins** [comment]
Hi @thepill   Can you run the Winver or the [environment]::OSVersion.Version
 command on the server 2016 nodes?  This issue is most likely linked to the build numbers, but I'd like to try and repro

**Comment by thepill** [comment]
@jasonbivins 

```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

**Comment by jasonbivins** [comment]
Hi @thepill 
This is actually a windows versioning issue.  We're  working through this now to find a way to make the issue a bit more transparent to the end user, but you can't actually run a Windows container image with a newer build than the one your host is running.  Since you built the image on 1709, you won't be able to run it on a machine running 14393. 
If you're able to, running Windows Updates on the server and bringing it up to 1709 should resolve the issue. 
Please see here for more information regarding version compatibility, there are a few workarounds using Hyper-V isolation that may help- including changing your default Daemon config -   https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility

**Comment by thepill** [comment]
@jasonbivins Thank you for your information. So i´m tightly coupled to my client which is building the image? Do you knwo if this will change in the feature, because i can not simple run windows updates to bring the server 2016 up to 1709 (requires a clean installation).

**Comment by thepill** [comment]
> It worked for me that you can use the 10.0.14393.xxx base images (not the 1709 base images) on Win10 1709 and build images that will also run on Server 2016. Win10 1709 uses hyperv isolation to run the older base images. I see you use `FROM microsoft/aspnet` then your Win10 1709 Docker engine chooses the best fitting image that is then the 1709. You have to use tags (it’s always better than implicit `latest`) like `microsoft/aspnet:4.7.1-windowsservercore-ltsc2016`.
> Hm, but the good practise would be using the version tag `4.7.1`, but this is also a manifest list that will pick the 1709 variant for you and then you will have the same effect that you produce an image that doesn’t work on Win Server 2016 LTSC.
> ping @friism maybe we need some build flag to select the desired OS version?

This is a information from slack and indeed it works if i specify `microsoft/aspnet:4.7.1-windowsservercore-ltsc2016`

**Comment by jasonbivins** [comment]
@thepill   We're working through this now, but this is based on the new MS build conventions, so there's a lot to talk through.
You can specify the Windows build  like this as well if it's easier to remember than ltsc2016:  windowsservercore:14393

In most of these situations, you can change Docker to use Hyper-V isolation instead of Process isolation but according to the docs i sent you earlier, it looks like you have the one scenario that this doesn't work for.

**Comment by thepill** [comment]
@jasonbivins thank you for your help and work!
