### ISSUE TITLE
Net Core Publish fails CS5001

### ISSUE THREAD

**Issue by OnamChilwan** [docker/for-win#1388]
Hi, I am getting some very odd behaviour when attempting to build a `dockerfile`. I am using VS2017 15.4.4 and creating a new `Empty` `.NET Core Web Application` entitled `WebApplication1`. I have a docker file which has the following contents:

```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy everything else and build
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 81
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
```

The file structure is:
- MySolution.sln
  - WebApplication
    - WebApplication.csproj
    - Dockerfile

Based on the default template I get the following `Program.cs` file:
```
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }
```

Please note, I have not made any changes to the code I am using the defaults. When I run `docker build .` it all completes fine up until the `RUN dotnet publish -c Release -o out`. I get the error:

```
error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/app/WebApplication1.csproj]
```

Not sure what I am doing wrong here, is this a known issue? I have followed docs but can't seem to find a solution to the problem.

Using:
- Docker 17.09.0-ce-win33 (13620)
- Windows 10 Enterprise N 2016 LTSB

I can provide further info if required.

*EDIT*
The only way I have managed to get this to work is to change the `COPY` to be `COPY . ./`. Isn't this ineffcient?

**Comment by danechambers** [comment]
Not an expert by any means, but I believe the `COPY . ./` is required because docker needs to copy all the stuff that dotnet restore creates in order to complete the build in its next container. I generally reference this project when looking at dockerfile build examples:
https://github.com/dotnet/dotnet-docker-samples/tree/master/aspnetapp
The fix you have is what they have in their example from that repo.

**Comment by OnamChilwan** [comment]
Ah right yes that resolves it. This also lead me to the multiple project reference example too and from that it suggests your docker file must live at solution level? Is this correct? Is it possible to have multiple docker files at solution level as you may have multiple deployables in a single solution..

**Comment by danechambers** [comment]
I think you still want one Dockerfile per csproj. For the solution, I would check out [docker compose](https://docs.docker.com/compose/overview/).
You can use docker compose to configure and spin up containers per project and network them together.

**Comment by alexvy86** [comment]
I know this is an old thread but I wanted to comment to make sure my understanding is correct (feel free to correct me if not), and not to mislead other people that read the thread... `COPY . ./` can't be doing anything with the output of `dotnet restore` because it only brings files from the build context (outside of the container) into the container, and `dotnet restore` in this case is happening inside. What it does do in this case, is bring all the **source code** that wasn't copied by the previous `COPY` (which only brought the `*.csproj` files).

And my theory as to why this is split in two `COPY` steps like that, is to leverage Docker's layer caching. The project file probably changes little compared to the source code, so by bringing just that one first and executing `dotnet restore` (this only needs the NuGet package references from the `.csproj`) we let Docker cache those layers and reuse them next time we build an image, instead of having to execute `dotnet restore` again even if all the referenced NuGet packages are the same.

**Comment by SibeeshVenu** [comment]
@danechambers Thanks, adding `COPY . ./` fixed the issue for me as well.

`RUN dotnet restore -p:RestoreUseSkipNonexistentTargets=false Service/M4Movie_Api/M4Movie_Api.csproj
COPY . ./
WORKDIR /src/Service/M4Movie_Api
RUN dotnet build -p:RestoreUseSkipNonexistentTargets=false M4Movie_Api.csproj -c Release -o /app`
