### ISSUE TITLE
Unable to install docker in Ubuntu 24.04 in WSL Windows 10

### ISSUE THREAD

**Issue by subhasisbanik** [docker/for-win#14081]
### Description

I am trying to install Docker in Ubuntu 24.04 WSL with the steps mentioned in https://docs.docker.com/engine/install/ubuntu/
However, after the whole installation is complete, I am not able to start docker with:
`docker ps`
![image](https://github.com/docker/for-win/assets/25420904/eee929d1-e79f-4adf-9f73-a6bee0cbe463)

I have tried to run the below with results:
![image](https://github.com/docker/for-win/assets/25420904/36ad386f-5af2-4ef4-b513-aedb63ac0709)

I have also run:
`sudo dockerd`
with results below:
![image](https://github.com/docker/for-win/assets/25420904/06c434b3-fde6-48d0-a018-363dec0bac3c)

I have followed this as well thinking this is a WSL issue:
https://gist.github.com/peteristhegreat/4bcbca81ed68605e36cf56bb0fff2960

But it did not help.

### Reproduce

1. https://docs.docker.com/engine/install/ubuntu/

### Expected behavior

Docker running successfully in Ubuntu WSL

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:35 2024
 OS/Arch:           linux/amd64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### Additional Info

Windows details:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎18-‎05-‎2024
OS build	19045.4412
Experience	Windows Feature Experience Pack 1000.19056.1000.0

Ubuntu version:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

**Comment by voonyee** [comment]
Thanks for reporting this, based on the error message you have shared.
`System has not been booted with systemd as init system (PID 1). 
Can't operate. Failed to connect to bus: Host is down
`
There is an ongoing discussion here related to this error: https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate

You can refer the above workaround. If you still facing issue with it, you can install Docker Desktop on Windows using WSL2 as the backend. 
Install Docker Desktop on Windows doc: https://docs.docker.com/desktop/install/windows-install/

**Comment by JosephKings7** [comment]
My case is the next: I just installed Docker Desktop for the first time in Windows 11; Of course, it is the current version of the software and when I tested it and followed the tutorial for beginners, while at the same time updating it, in a period of 2 days WSL and Ubuntu 22.04.3 were installed on the system without having executed these facilities still. The problem is that when I check the installed distros (with wsl --list --verbose) and that should appear in Configuration -> WSL Integration Resources, only Ubuntu appears and nothing else: This Ubuntu 22.04.3 distro does not appear; What can I do about it? Thanks for your help.

**Comment by JosephKings7** [comment]
Hi. My case is the next: I just installed Docker Desktop for the first time in Windows 11; Of course, it is the current version of the software and when I tested it and followed the tutorial for beginners, while at the same time updating it, in a period of 2 days WSL and Ubuntu 22.04.3 were installed on the system without having executed these facilities still. The problem is that when I check the installed distros (with wsl --list --verbose) and that should appear in Configuration -> WSL Integration Resources, only Ubuntu appears and nothing else: This Ubuntu 22.04.3 distro does not appear; What can I do about it? Thanks for your help.
