### ISSUE TITLE
LCOW: paths starting with / are not accepted anymore

### ISSUE THREAD

**Issue by colthreepv** [docker/for-win#1411]
### Expected behavior
Able to execute `docker run --rm -v $(pwd):/data alpine ls /data`

### Actual behavior
```
$ docker run --rm -v $(pwd):/data alpine ls /data
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: invalid volume specification: '/c/projects:/data'.
```

### Information
Windows 1709 Pro x64 (build 16299.64)
Docker 17.11.0-ce-win40 (14328)

### Steps to reproduce the behavior
Specified above, there is no support anymore for "bash for windows" style paths

**Comment by rn** [comment]
We currently don't support running `docker` in WSL as WSL is under active development and a moving target.

This is also not an issue specific to the Docker for Windows application but related to the upstream `moby/moby` project, which Docker for Windows consumes, so I'm closing this issue here. Feel free to open a new issue in the upstream repository: https://github.com/moby/moby/issues

**Comment by colthreepv** [comment]
ok, upstream issue https://github.com/moby/moby/issues/36932 , feel free to add informations
