### ISSUE TITLE
docker images

### ISSUE THREAD

**Issue by webdesignbestinclass** [docker/for-win#1413]
### Information
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/json:
em cannot find the file specified. In the default daemon configuration on Windows,
d to connect. This error may also indicate that the docker daemon is not running.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
