### ISSUE TITLE
Can I use gpu in windows-docker?

### ISSUE THREAD

**Issue by janelu9** [docker/for-win#1496]

**Comment by jasonbivins** [comment]
Hi @janelu9  The forum might be a better place for questions like this one - forums.docker.com

We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
