### ISSUE TITLE
17.12.0-ce-win46 (15048) - Unable to switch to Linux Containers.

### ISSUE THREAD

**Issue by MartinSGill** [docker/for-win#1522]
### Expected behavior

Switch to Linux Containers works

### Actual behavior

Error/Crash report.

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 3D7631C6-E780-4759-9B5E-3924576C0363)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID 3D7631C6-E780-4759-9B5E-3924576C0363)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information

  - Diagnostic ID: D592EFE6-9AC8-4F6D-A3BB-0D7320F74EF2/2018-01-10_15-34-17

### Steps to reproduce the behavior

  1. Start Docker for win
  2. Select "Switch to Linux Containers" from menu.

**Comment by jasonbivins** [comment]
Hi @MartinSGill   It looks like there's a problem with one of the virtual adapters - `[17:03:57.190][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled
`
Let's see what the current state of the DockerNat adapter is - please run this and share the results:
`Get-NetAdapter "vEthernet (DockerNAT)" | Get-NetIPInterface`

**Comment by robertwray** [comment]
This looks like the issue documented in [Microsoft KB Article 4052082](https://support.microsoft.com/en-gb/help/4052082/hyper-v-cannot-start-vm-after-you-upgrade-to-windows-10-version-1709) (Hyper-V virtual machines don't start after you upgrade to Windows 10 Version 1709).

The short answer is that one of the components of Hyper-V in Windows 10 1709 has been changed to prevent non-Microsoft DLLs being loaded into the process. This is usually caused by your Anti-Virus solution.

**Comment by MartinSGill** [comment]
@robertwray That was it!

It didn't entirely fix the issue, I had to uninstall and re-install docker before it started working again, but now it is working again!

Thanks.

**Comment by robertwray** [comment]
@MartinSGill, glad I could be of help - your issue came up when I was searching for the error message so thought I'd share what I'd found :)
