### ISSUE TITLE
docker run -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h edwin-Vostro-3900 progrium/consul. I am running the above command but I am receiving this error: docker: Error response from daemon: driver failed programming external connectivity on endpoint silly_panini (dfaa4478e653cc2f5684622696cf6c250a89bce79c1c168b79699d5d51cf2e95): Error starting userland proxy: listen udp 0.0.0.0:8600: bind: address already in use.

### ISSUE THREAD

**Issue by eddamalique01** [docker/for-win#1535]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
