### ISSUE TITLE
Strage behaviour during installation

### ISSUE THREAD

**Issue by aliaksandrmikhailik** [docker/for-win#1570]
### Expected behavior

Expected installation without any issues :)

### Actual behavior

![image](https://user-images.githubusercontent.com/20465238/35049978-bda6e5aa-fbb2-11e7-8d48-bca2c8bba69d.png)

I have windows 10 pro with 1709 build number

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
