### ISSUE TITLE
Error response from daemon: Get https://registry-1.docker.io/v2/

### ISSUE THREAD

**Issue by jzoran05** [docker/for-win#1572]
### Expected behavior
docker run -it hello-world to download DockerHub image
### Actual behavior
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection

### Information

  - Diagnostic ID: 26A2C5CC-4946-4C2E-93C1-60DE31DDF305/2018-01-17_20-46-07
  - Windows 10 build 15063 
  - Running on home PC with direct access to the internet without internet proxy

### Steps to reproduce the behavior

  1. docker run -it hello-world

**Comment by jasonbivins** [comment]
HI @jzoran05 
Do you get errors when you run the ```docker login``` command?

You can also try setting Docker to used a fixed DNS here:
![image](https://user-images.githubusercontent.com/28021664/35065338-0010e8cc-fb9b-11e7-8a1c-f5ba7c976baf.png)

**Comment by smartmeta** [comment]
I had the same issue and it turned out that I changed the DNS settings to 

![grafik](https://user-images.githubusercontent.com/10464459/38979447-829c08d2-43ba-11e8-955d-a8807c600150.png)

(because of some posts I found on the web)
Turning it back to **Automatic** solved my issue.

**Comment by digikin** [comment]
Ok, Now I have figured out the entire problem why Docker was not working on windows. <>
Here is the solution
After you create the "default" machine in HyperV, for some reason it defaults the virtual network switch to "NAT". NAT is what allows communication through the network adapter. Change this in the settings to the "Default Switch". The Default Switch is the what automatically gives virtual machines access to the computer's network using NAT.

<<<<<Once I did that the docker host came back online with a IPV4 address

C:\WINDOWS\system32>docker-machine ls
NAME ACTIVE DRIVER STATE URL SWARM DOCKER ERRORS
default * hyperv Running tcp://192.168.65.238:2376 Unknown Unable to query docker version: Get https://192.168.65.238:2376/v1.15/version: x509: certificate is valid for 127.0.0.1, not 192.168.65.238
dev - hyperv Unknown

<<<Then in the https://docs.docker.com/toolbox/faqs/troubleshoot/#example-errors it says to regenerate-certs because of invalid certificates.

C:\WINDOWS\system32>docker-machine regenerate-certs default
Regenerate TLS machine certs? Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

C:\WINDOWS\system32>docker-machine restart default
Restarting "default"...
(default) Waiting for host to stop...
(default) Waiting for host to start...
Waiting for SSH to be available...
Detecting the provisioner...
Restarted machines may have new IP addresses. You may need to re-run the docker-machine env command.

C:\WINDOWS\system32>docker-machine env
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.65.238:2376
SET DOCKER_CERT_PATH=C:\Users\eric.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM @for /f "tokens=*" %i IN ('docker-machine env') DO @%i

C:\WINDOWS\system32>@for /f "tokens=*" %i IN ('docker-machine env') DO @%i

C:\WINDOWS\system32>docker info
Containers: 0
Running: 0
Paused: 0
Stopped: 0
Images: 0
Server Version: 18.04.0-ce
Storage Driver: aufs
Root Dir: /mnt/sda1/var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 0
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
seccomp
Profile: default
Kernel Version: 4.9.93-boot2docker
Operating System: Boot2Docker 18.04.0-ce (TCL 8.2.1); HEAD : b8a34c0 - Wed Apr 11 17:00:55 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 986.3MiB
Name: default
ID: CD2Y:WAHG:BLZX:P5FF:O3AO:2FCW:4W34:YYLW:GCS4:EOV7:JTRE:FZV3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
provider=hyperv
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

C:\WINDOWS\system32>docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
2a72cbf407d6: Pull complete
04b2d3302d48: Pull complete
e7f619103861: Pull complete
Digest: sha256:18156dcd747677b03968621b2729d46021ce83a5bc15118e5bcced925fb4ebb9
Status: Downloaded newer image for nginx:latest

<<<Now everything is working as expected after a week of searching the internet.

**Comment by Amrkamel1** [comment]
im getting same issue, is there any actual fix on windows 
![image](https://user-images.githubusercontent.com/32042806/60282233-c37b4500-9906-11e9-8a74-097255654fb5.png)
