### ISSUE TITLE
Multiple issues, -cannot connect to MobyLinuxVM Hyper-V Windows 10, Docker cannot connect to pipeline 

### ISSUE THREAD

**Issue by binoynanavati** [docker/for-win#1592]
### Expected behavior
Hyper V - MobyLinuxVM connection to be established
Docker ps should work without Pipe line error
### Actual behavior
Cannot Connect MobyLinuxVM through Hyper V manager, Windows 10
Docker ps throws error "error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running."
### Information

Diagnostic ID: A39AF95F-B01F-4F68-9B4F-28528104E0F9/2018-01-21_21-16-23

Docker version 17.12.0-ce, build c97c6d6

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by brentarias** [comment]
My `docker ps` works fine, but I also am unable to make Hyper-v connect  to MobyLinuxVM.  The error message is "Could not connect to virtual machine."

I have Windows 10 Pro, Version 1709 build 16299.248.  The docker version I have installed  is 17.12.0-ce, build (15139) c97c6d6.  

I've noticed a similar [hyper-v  could not connect to MobyLinuxVM problem](https://superuser.com/questions/1253357/hyper-v-could-not-connect-to-mobylinuxvm-of-docker-docker-wont-run) on super-user  stackexchange.  That discussion [pointed to a re-install of Docker, with emphasis  on deleting  a peculiar  registry key](https://github.com/docker/for-win/issues/1043#issuecomment-348088910).  Unfortunately, that fix didn't  work for me because the  indicated registry key does not exist on my laptop.   

In fact, taking the hint from those commentaries - I used procmon to see if I could  find a new `UpgradeCodes` registry entry.  No luck.

In case it helps,  here  are select "interesting" parts of my docker log file:

	[13:21:19.385][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
	[13:21:20.571][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT

	[13:21:20.569][VpnKit         ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
	[13:21:20.571][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
	[13:21:20.572][VpnKit         ][Info   ] vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for client.openvpn.net
	[13:22:26.681][Linux          ][Error  ] Failed to start: Docker hv-sock proxy (vsudd) is not reachable. Let's retry
	[13:22:56.820][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
	[13:23:19.972][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
	[13:23:20.266][VpnKit         ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
	[13:23:20.266][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT

**Comment by brentarias** [comment]
I have now installed Docker for Windows on a brand-new Windows 10 Pro system.  The system has nothing else installed (not Visual Studio, not node.js...nothing else).  The first thing I did was check the ability for Hyper-V Manager to connect to MobyLinuxVM.  It cannot connect!

Is connecting to the VM via Hyper-V Manager simply not an option?  Am I trying to achieve something that was never an intended feature or capability?

**Comment by supports2004** [comment]
I have the same issue. The only thing I have understood - it's better not to deal with microsoft anymore

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.

**Comment by brentarias** [comment]
@rn  
This issue (#1592) is completely unrelated to the the issues you've listed above.  Please re-open this ticket.

To clarify:

* This is not about Docker for Windows inside a Windows 10 VM.
* This is not about the Linux VM booting or being unavailable (#1995).  On the contrary, MobyLinuxVM  is up.  It is running, and it is actively hosting Docker containers successfully.  
* This is not about a Linux crash (#1994).  Again, the MobyLinuxVM container is active and running Docker container.

Instead, this issue is about Hyper-V Manager being unable to connect to MobyLinuxVM, even though MobyLinuxVM is currently up, running, and successfully hosting Docker containers.  For example, I have a docker container that is hosting an official WordPress image.  I'm interacting with the WordPress site inside the Docker container.  Then I open Hyper-V Manager and attempt to connect to MobyLinuxVM...it gives the error message that it can't connect.  Then I return to my WordPress site and continue to interact successfully with the site.

This means that MobyLinuxVM is working perfectly.  The only problem is, the Hyper-V Manager won't connect to it.

**Comment by rn** [comment]
@brentarias as said, I've looked at all the diagnostics supplied and the last one before the diagnostics is submitted a slow VM boot. There were others errors (such as not enough memory available). But that also falls into the category of begin resource constraint.

You have not supplied diagnostics so I can't triage it. Please open a new issue with your issue and diagnostics
