### ISSUE TITLE
Change Docker temp directory

### ISSUE THREAD

**Issue by anbencic** [docker/for-win#1593]
### Expected behavior

Ability to configure Docker temp directory that is used during pull, build, etc. to another location.

### Actual behavior

Docker uses c:\windows\temp by default. AFAIK, currently I'll have to remap the system path to fix this.

### Information

N/A

### Steps to reproduce the behavior

N/A

**Comment by AbsolutelyFreeWeb** [comment]
@anbencic how were you able to change the temp path? for me it is trying to save to c:\programdata\docker\tmp but I do not have any system path that is directing it there. I was not able to get this opened, and since my issue is slightly different I created a new issue here:
https://github.com/docker/for-win/issues/1593

**Comment by anbencic** [comment]
You can use a config file to change the path:

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#configure-docker-with-a-configuration-file
