### ISSUE TITLE
archive for older releases

### ISSUE THREAD

**Issue by riezebosch** [docker/for-win#162]
### Expected behavior

I'm creating a chocolatey package to install docker for windows. It is common the tie the package to the specific release of the software and the package includes the hash to validate the download. Currently it is only possible to download the latest release. The effect of this is twofold:
1. The install of the package will with every new release due to a changing checksum
1. It will not be possible to install older specific releases.
### Actual behavior

Only latest version available.
### Information

Some other docker packages provide releases via github and seem to include a version number specific to that release. Please, do the same thing for the docker for windows installation.
### Steps to reproduce the behavior
1. ...
2. ...

**Comment by friism** [comment]
Thanks for opening this issue!

It's not really meaningful for the the installers to be versioned since they're just envolopes around the app, and even if you get an old envelope, the app will immediately start auto-updating once install completes.

Your effort is appreciated, but I'm not sure a Chocolatey package is required - Docker for Windows will install unattended with two commands:

    Invoke-WebRequest "https://download.docker.com/win/beta/InstallDocker.msi" -OutFile "$env:TEMP\docker.msi" -UseBasicParsing
    Start-Process $env:TEMP\docker.msi -ArgumentList '/quiet' -Wait

**Comment by friism** [comment]
We're not currently planning to publish installers for old packages since those will container known bugs and possibly security problems and we don't want to encourage users to install those. I'm closing this issue for now.

**Comment by kcd83** [comment]
What about instructing docker for windows to install an older version of the engine? 

Known bugs can be in new releases too. For example OpenShift has problems with parsing the new version scheme.

**Comment by friism** [comment]
@kcd83 thanks for adding that perspective. I'm really sorry that the version change caused problems for software that you want to run on Docker. Strictly speaking, however, it's not a bug in Docker that software running on Docker fails to parse a Docker version string.

As mentioned above, it's not attractive for us to make (for example) Docker 1.13.X or Docker 1.12.X available through Docker for Windows since they're no longer maintained and contain known security issues and bugs.

It looks like Openshift already has a fix: https://github.com/openshift/origin/pull/13204

**Comment by djensen47** [comment]
How about when you push out a release that horks existing installs to the point that Docker just can't be used?

**Comment by djensen47** [comment]
Or when somebody pushes Edge to Stable? Did you know that Edge and Stable are the same right now? Should they be ever?

**Comment by riezebosch** [comment]
I discovered direct download links in the mean time so installing with chocolatey is already a pinned version 😄

**Comment by djensen47** [comment]
Awesome, yeah I eventually discovered the same thing. Chocolately FTW!

**Comment by ehazlett** [comment]
@friism I get your comment about wanting to have people on the latest and greatest but I just ran into an issue that I've confirmed on 17.12 and 18.01 but works fine on 17.06.  This is a case where I would take an older more stable build over latest features and bug fixes.  Ultimately I just need a version of Docker that works.

**Comment by friism** [comment]
@ehazlett congrats, we started adding download links in the release notes last fall: https://github.com/docker/for-mac/issues/1120#issuecomment-338759689

https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17062-ce-win27-2017-09-06-stable

**Comment by ehazlett** [comment]
awesome thanks!

**Comment by pd93** [comment]
@friism Out of curiosity, the download links [seem to have stopped since 17.09.0](https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17091-ce-win42-2017-12-11-stable). I'd like to downgrade to `17.09.1` to resolve [this problem](https://github.com/docker/for-win/issues/1514), but currently only `17.09` is available. If possible, I'd prefer to have the patched version for reasons you stated above (security/bugs etc).

**Comment by riezebosch** [comment]
Extracted from [my package](https://chocolatey.org/packages/docker-for-windows/17.09.1.14687) the [url])(https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe) seems to work fine.

**Comment by pd93** [comment]
@riezebosch Thanks for the link. It seems to work well - though I'd still prefer for this to be officially supported rather than relying on Chocolatey support.
