### ISSUE TITLE
Kubernetes does not complete startup, "Kubernetes is starting"

### ISSUE THREAD

**Issue by sundhaug92** [docker/for-win#1649]
### Expected behavior
Kubernetes starts up

### Actual behavior
Kubernetes gets stuck on "Kubernetes is starting"

### Information
- Diagnostic ID: 7F113F70-E430-4720-82B3-94080A1EA18B/2018-02-02_09-28-26
- Windows 10 Pro 1709 (16299.192)
- Docker CE 18.02.0-ce-rc1

### Steps to reproduce the behavior

  1. Enable Kubernetes in the settings
  2. Wait

PS: I also enabled "Show system containers" but I'm not sure that's relevant

**Comment by pgayvallet** [comment]
I'm sorry to ask, but the diagnostic upload seems to have failed. Could you perform another diag and give us the new ID ?

**Comment by sundhaug92** [comment]
Diagnostic ID 7F113F70-E430-4720-82B3-94080A1EA18B/2018-02-02_14-46-04

**Comment by pgayvallet** [comment]
Thanks. The cluster initialisation apparently failed, but as the diag only contains log since last boot, and as the cluster initialisation was performed before that, I can't dig the root cause.

Could you go to options -> reset  and click on the "reset kubernetes cluster" button, then wait like 2 minutes and perform a diagnostic again ?

**Comment by sundhaug92** [comment]
7F113F70-E430-4720-82B3-94080A1EA18B/2018-02-02_16-45-54

**Comment by cristianokbc** [comment]
Same thing here.
Diagnostic ID: 8F6907E3-A3D5-4FCC-A21F-82E769B3627D/2018-02-02_15-20-29

**Comment by funky81** [comment]
same here. Diagnostic ID : B6B6D1F1-B2EA-4166-9375-41CA6D9E2308/2018-02-04_02-57-37

**Comment by Adamyounger** [comment]
Same here, reset the kubernetes cluster then uploaded the diagnostic
8B2338D2-D2E8-4FE0-88F2-F11341C8DDE9/2018-02-06_12-54-02

**Comment by jamct** [comment]
Same problem for me:
2A62F543-1B98-41ED-848F-B6ADD1F84121/2018-02-06_14-09-45

**Comment by pgayvallet** [comment]
@sundhaug92 Thanks. kubelet starts, but then it's waiting for the api-server that apparently never booted correctly.

I see in the logs that the vm disk appears to be full ( `[imageGCManager]: Disk usage on image filesystem is at 97% which is over the high threshold (85%). Trying to free 10230534963 bytes`)
which may explain why some pods never get ready.

Can you try increasing the disk size ? (docker's settings => advanced tab => disk size), and then re-resetting the cluster ? then if still failing, perform a diagnostic again.

**Comment by pgayvallet** [comment]
@funky81 or others : could you get me your logs of the kube-apiserver container ( enable "show system containers in the kubernetes tab, then `docker ps | grep kube-apiserver-amd64` & `docker logs` on the id"

**Comment by Adamyounger** [comment]
@pgayvallet, even with "show system containers" enabled I never see any running containers after a docker ps -a, So no logs available :). All the docker images have been downloaded correctly (5 of them, gcr.io/google_containers/kube-controller-manager-amd64 etc), I also made sure I have enough room on vm disk.  I have uploaded another diagnostic. 8B2338D2-D2E8-4FE0-88F2-F11341C8DDE9/2018-02-08_10-41-17

**Comment by sundhaug92** [comment]
@Adamyounger Strange. When I looked some of them would start but die and be removed

**Comment by funky81** [comment]
@pgayvallet here you go...for apiserver log

> PS C:\Users\funky81-NSP> docker logs 55aeb4db63d1
I0208 21:00:09.795477       1 server.go:121] Version: v1.9.2
I0208 21:00:10.524050       1 feature_gate.go:184] feature gates: map[Initializers:true]
I0208 21:00:10.524111       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup
I0208 21:00:10.538671       1 master.go:225] Using reconciler: master-count
W0208 21:00:10.636045       1 genericapiserver.go:342] Skipping API batch/v2alpha1 because it has no resources.
W0208 21:00:10.653318       1 genericapiserver.go:342] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W0208 21:00:10.655100       1 genericapiserver.go:342] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W0208 21:00:10.672791       1 genericapiserver.go:342] Skipping API admissionregistration.k8s.io/v1alpha1 because it has no resources.
[restful] 2018/02/08 21:00:10 log.go:33: [restful/swagger] listing is available at https://192.168.65.3:6443/swaggerapi
[restful] 2018/02/08 21:00:10 log.go:33: [restful/swagger] https://192.168.65.3:6443/swaggerui/ is mapped to folder /swagger-ui/
[restful] 2018/02/08 21:00:11 log.go:33: [restful/swagger] listing is available at https://192.168.65.3:6443/swaggerapi
[restful] 2018/02/08 21:00:11 log.go:33: [restful/swagger] https://192.168.65.3:6443/swaggerui/ is mapped to folder /swagger-ui/
I0208 21:00:16.559846       1 serve.go:89] Serving securely on [::]:6443
I0208 21:00:16.560128       1 controller.go:84] Starting OpenAPI AggregationController
I0208 21:00:16.560241       1 apiservice_controller.go:112] Starting APIServiceRegistrationController
I0208 21:00:16.560323       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I0208 21:00:16.560494       1 available_controller.go:262] Starting AvailableConditionController
I0208 21:00:16.560562       1 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I0208 21:00:16.562837       1 crdregistration_controller.go:110] Starting crd-autoregister controller
I0208 21:00:16.563041       1 controller_utils.go:1019] Waiting for caches to sync for crd-autoregister controller
I0208 21:00:16.579191       1 crd_finalizer.go:242] Starting CRDFinalizer
I0208 21:00:16.825195       1 customresource_discovery_controller.go:152] Starting DiscoveryController
I0208 21:00:16.825271       1 naming_controller.go:274] Starting NamingConditionController
I0208 21:00:50.826604       1 trace.go:76] Trace[635183933]: "Create /api/v1/nodes" (started: 2018-02-08 21:00:16.8247981 +0000 UTC m=+7.213532901) (total time: 34.001706s):
Trace[635183933]: [4.0012378s] [4.0009778s] About to store object in database
Trace[635183933]: [34.001706s] [30.0004682s] END
I0208 21:00:51.563766       1 trace.go:76] Trace[418361413]: "Create /api/v1/namespaces" (started: 2018-02-08 21:00:17.5617221 +0000 UTC m=+7.950502201) (total time: 34.0019625s):
Trace[418361413]: [4.0014159s] [4.0013422s] About to store object in database
Trace[418361413]: [34.0019625s] [30.0005466s] END
E0208 21:00:51.564559       1 client_ca_hook.go:78] Timeout: request did not complete within allowed duration
E0208 21:01:16.815815       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *rbac.ClusterRole: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterroles.rbac.authorization.k8s.io)
E0208 21:01:16.815956       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/client/informers/internalversion/factory.go:73: Failed to list *apiregistration.APIService: the server was unable to return a response in the time allotted, but may still be processing the request (get apiservices.apiregistration.k8s.io)
E0208 21:01:16.816018       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.LimitRange: the server was unable to return a response in the time allotted, but may still be processing the request (get limitranges)
E0208 21:01:16.816070       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Endpoints: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints)
E0208 21:01:16.830955       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *rbac.ClusterRoleBinding: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterrolebindings.rbac.authorization.k8s.io)
E0208 21:01:16.832199       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.ResourceQuota: the server was unable to return a response in the time allotted, but may still be processing the request (get resourcequotas)
E0208 21:01:16.832403       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *rbac.RoleBinding: the server was unable to return a response in the time allotted, but may still be processing the request (get rolebindings.rbac.authorization.k8s.io)
E0208 21:01:16.832591       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.PersistentVolume: the server was unable to return a response in the time allotted, but may still be processing the request (get persistentvolumes)
E0208 21:01:16.832656       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.ServiceAccount: the server was unable to return a response in the time allotted, but may still be processing the request (get serviceaccounts)
E0208 21:01:16.834271       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Service: the server was unable to return a response in the time allotted, but may still be processing the request (get services)
E0208 21:01:16.834372       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Pod: the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
E0208 21:01:16.834579       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/client/informers/internalversion/factory.go:73: Failed to list *apiextensions.CustomResourceDefinition: the server was unable to return a response in the time allotted, but may still be processing the request (get customresourcedefinitions.apiextensions.k8s.io)
E0208 21:01:16.834707       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *storage.StorageClass: the server was unable to return a response in the time allotted, but may still be processing the request (get storageclasses.storage.k8s.io)
E0208 21:01:16.834909       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.Namespace: the server was unable to return a response in the time allotted, but may still be processing the request (get namespaces)
E0208 21:01:16.835090       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
E0208 21:01:16.835599       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *rbac.Role: the server was unable to return a response in the time allotted, but may still be processing the request (get roles.rbac.authorization.k8s.io)
E0208 21:01:17.583906       1 storage_rbac.go:175] unable to initialize clusterroles: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterroles.rbac.authorization.k8s.io)
I0208 21:01:21.566171       1 trace.go:76] Trace[2133304229]: "Create /api/v1/namespaces" (started: 2018-02-08 21:00:51.5652856 +0000 UTC m=+41.954033501) (total time: 30.0008373s):
Trace[2133304229]: [30.0008373s] [30.0006547s] END
E0208 21:01:21.567361       1 client_ca_hook.go:78] Timeout: request did not complete within allowed duration
F0208 21:01:21.567413       1 hooks.go:188] PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition

**Comment by winglerw28** [comment]
For me, Windows firewall was blocking `vpnkit.exe`; resetting my Docker network settings had Windows prompt me to allow `vpnkit.exe`. Once allowed, performing "Settings > Reset > Reset Kubernetes Cluster" resolved this issue for me. 

I will attempt to pull up any logs I can find to see what may have resulted in this state in the first place and whether `vpnkit.exe` is a red herring.

**Comment by sundhaug92** [comment]
```
# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
69e38a7e72f7        gcr.io/google_containers/etcd-amd64        "etcd --listen-clien…"   29 seconds ago      Up 28 seconds                           k8s_etcd_etcd-docker-for-desktop_kube-system_7278f85057e8bf5cb81c9f96d3b25320_0
e442416fe5fd        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 29 seconds ago      Up 28 seconds                           k8s_POD_kube-controller-manager-docker-for-desktop_kube-system_d44da25f7ce80f700f8d8b3b7ebeef60_0
70125bb929f4        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 29 seconds ago      Up 28 seconds                           k8s_POD_kube-apiserver-docker-for-desktop_kube-system_c738ee9a2925624d2125f10019ebed8a_0
bc33d96f8238        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 29 seconds ago      Up 28 seconds                           k8s_POD_etcd-docker-for-desktop_kube-system_7278f85057e8bf5cb81c9f96d3b25320_0
f333f50499bc        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 29 seconds ago      Up 29 seconds                           k8s_POD_kube-scheduler-docker-for-desktop_kube-system_69c12074e336b0dbbd0a1666ce05226a_0
```


```
# etcd
2018-02-16 20:40:01.236797 I | etcdmain: etcd Version: 3.1.11
2018-02-16 20:40:01.236899 I | etcdmain: Git SHA: 960f4604b
2018-02-16 20:40:01.237138 I | etcdmain: Go Version: go1.8.5
2018-02-16 20:40:01.237154 I | etcdmain: Go OS/Arch: linux/amd64
2018-02-16 20:40:01.237159 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2018-02-16 20:40:01.242062 I | embed: listening for peers on http://localhost:2380
2018-02-16 20:40:01.242110 I | embed: listening for client requests on 127.0.0.1:2379
2018-02-16 20:40:01.248467 I | etcdserver: name = default
2018-02-16 20:40:01.248501 I | etcdserver: data dir = /var/lib/etcd
2018-02-16 20:40:01.248510 I | etcdserver: member dir = /var/lib/etcd/member
2018-02-16 20:40:01.248516 I | etcdserver: heartbeat = 100ms
2018-02-16 20:40:01.248522 I | etcdserver: election = 1000ms
2018-02-16 20:40:01.248527 I | etcdserver: snapshot count = 10000
2018-02-16 20:40:01.248538 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2018-02-16 20:40:01.248646 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2018-02-16 20:40:01.248661 I | etcdserver: initial cluster = default=http://localhost:2380
2018-02-16 20:40:01.255380 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2018-02-16 20:40:01.255417 I | raft: 8e9e05c52164694d became follower at term 0
2018-02-16 20:40:01.255430 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2018-02-16 20:40:01.255437 I | raft: 8e9e05c52164694d became follower at term 1
2018-02-16 20:40:01.377045 I | etcdserver: starting server... [version: 3.1.11, cluster version: to_be_decided]
2018-02-16 20:40:01.377709 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2018-02-16 20:40:02.155856 I | raft: 8e9e05c52164694d is starting a new election at term 1
2018-02-16 20:40:02.155933 I | raft: 8e9e05c52164694d became candidate at term 2
2018-02-16 20:40:02.155949 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
2018-02-16 20:40:02.155983 I | raft: 8e9e05c52164694d became leader at term 2
2018-02-16 20:40:02.155995 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
2018-02-16 20:40:02.156442 I | etcdserver: published {Name:default ClientURLs:[http://127.0.0.1:2379]} to cluster cdf818194e3a8c32
2018-02-16 20:40:02.156509 I | etcdserver: setting up the initial cluster version to 3.1
2018-02-16 20:40:02.156614 I | embed: ready to serve client requests
2018-02-16 20:40:02.156917 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
2018-02-16 20:40:02.158936 N | etcdserver/membership: set the initial cluster version to 3.1
2018-02-16 20:40:02.159031 I | etcdserver/api: enabled capabilities for version 3.1
```

**Comment by funky81** [comment]
Finally i fixed this by write this command into Powershell with Admin Priv 

[Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)

**Comment by sundhaug92** [comment]
Strange, that works @funky81. Curious if that's the same underlying issue @winglerw28 hda underlying. Also, why isn't KUBECONFIG being set?

**Comment by funky81** [comment]
I dont know..well, after I set the path for KUBECONFIG, i can finally start kubernetes pods.
And then got problem, and it's progress still starting right now

**Comment by sundhaug92** [comment]
@funky81 I got it running now. Could it be that you're experiencing some of the other issues, such as VM storage-space? Might want to create a few separate issues for that. 
![image](https://user-images.githubusercontent.com/519283/36375902-6a2f5960-1571-11e8-8a2e-1c864cb421ae.png)

**Comment by sundhaug92** [comment]
Noticing that kubernetes doesn't create KUBECONFIG if the folder is invalid. Btw, @funky81, should it not be \.kube\config?

**Comment by sundhaug92** [comment]
Changing the command in @funky81's comment to [Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine) (notice added \) solves the kubectl issue for me

**Comment by JerryGM** [comment]
Small fix for the command above: Add a "\" in front of ".kube". Run this command as administrator before you activate Kubernetes. Worked for me in 18.03.0-ce-rc1 on Win10. 

> [Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)

**Comment by josiahpeters** [comment]
I am having a similar issue. I enable the "[x] Enable Kubernetes" checkbox and the docker settings shows "Kubernetes is starting..." for what seems like forever.

I followed the suggestions above and set KUBECONFIG to point to my home directory/.kube/config
My diagnostic ID is: 7D3951AE-DB9E-4462-8222-A8395CBA5571/2018-03-24_06-30-56

I'm running Version 18.03.0-ce-rc4-win56 (16511) on Windows 10 Enterprise 1709 (from a fresh windows install 3 days ago)

![image](https://user-images.githubusercontent.com/446011/37863999-c38e1d5e-2f2d-11e8-81eb-640ff8b81719.png)

![image](https://user-images.githubusercontent.com/446011/37863978-60bdbc34-2f2d-11e8-9f9d-a653a3efd728.png)

**Comment by sundhaug92** [comment]
@josiahpeters Did you try the suggestion in https://github.com/docker/for-win/issues/1649#issuecomment-366670495 (or https://github.com/docker/for-win/issues/1649#issuecomment-371611239) or the firewall-solution https://github.com/docker/for-win/issues/1649#issuecomment-364628494?

**Comment by josiahpeters** [comment]
@sundhaug92 I'm hoping the last comment you linked to was the solution: [#1649 (comment)](https://github.com/docker/for-win/issues/1649#issuecomment-364628494). 👍 

I looked in my docker log files and found the following :

```
[06:38:51.083][VpnKit         ][Error  ] vpnkit.exe: Flow read_thread caught: An established connection was aborted by the software in your host machine.
[06:38:51.095][ApiProxy       ][Info   ] Failed to invoke init: Post http://unix/init: The network connection was aborted by the local system.
[06:38:51.095][ApiProxy       ][Info   ] time="2018-03-24T06:38:51-06:00" msg="Failed to initialise the cluster: Post http://unix/init: The network connection was aborted by the local system."
[06:38:51.095][ApiProxy       ][Info   ] time="2018-03-24T06:38:51-06:00" msg="Failed to update the host kube config: Post http://unix/init: The network connection was aborted by the local system."
[06:38:51.095][ApiProxy       ][Warning] time="2018-03-24T06:38:51-06:00" msg="Error while setting up kubernetes: Post http://unix/init: The network connection was aborted by the local system.. Retrying in 1s"
[06:38:51.145][VpnKit         ][Error  ] vpnkit.exe: Flow write_thread caught: An existing connection was forcibly closed by the remote host.
[06:38:51.549][VpnKit         ][Warning] vpnkit.exe: netif writev errored unknown: unknown: unknown: attempted to write to a closed flow
[06:38:51.550][VpnKit         ][Warning] vpnkit.exe: Error sending Ethernet frame: unknown: unknown: unknown: attempted to write to a closed flow
```


Its now obvious that vpnkit was having some kind of connection issue. 

### I fixed this by:

- Setting my environment variable KUBECONFIG as suggested ```[Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)```
- Reinstalling Docker 18.03.0-ce-rc4-win57
- Allowing VPNKit through the firewall when prompted after checking the Install Kubernetes checkbox

I wish I would have been more impatient before reinstalling Docker. Someone else with this issue may be able to check if vpnkit is allowed through the firewall by running the following command ```Get-NetFirewallRule -DisplayName vpnkit``` and verifying that they have a rule that has ```Action: Allow``` set for their private/domain network/

**Comment by sundhaug92** [comment]
@josiahpeters Yeah it seems there might be a bug or two in the installer, guessing it doesn't create a firewall-rule for this and lacks the . when setting the env or something. Strange, since Hanselman got it working.

**Comment by kuops** [comment]
A diagnostic was uploaded with id: A1937A95-1E08-4E39-9CBB-0858A87F5FFD/2018-04-09_08-57-19

"Kubernetes is starting..."

**Comment by MisterNatureQ** [comment]
failed to load plugin io.containerd.snapshotter.v1.btrfs
[ApiProxy       ][Info   ] time="2018-05-08T10:42:29+08:00" msg="Node status error: Get https://localhost:6445/api/v1/nodes: EOF"

**Comment by Deniulor** [comment]
/remove-lifecycle stale
I get this issue again，with log in <User>\AppData\Local\Docker
![image](https://user-images.githubusercontent.com/5369212/43990906-e4ffb47c-9d94-11e8-9a8e-e7b85dc35c88.png)

the last words means,  some software in my host stop a connection. 
but in fact the service on https://localhost:6445 dosen't start. it can not be accessible.
ps: I already shutdown my fire walls.

with:
windows 10
![image](https://user-images.githubusercontent.com/5369212/43990968-c19e1004-9d95-11e8-810a-bc4d4b671206.png)

**Comment by dfme** [comment]
I have the same issue as also reported here https://github.com/docker/for-win/issues/2065

**Comment by Montrazul** [comment]
Same here: DE9F3AF8-6CFA-430F-815E-EE9F59EE4CF9/20181129105514

**Comment by tuanicom** [comment]
Same behavior here. Fun fact: I managed to make it run the first time and use it. I stopped it for a test using the command "Stop local cluster" on Docker for Desktop menu. Since then, I never had it run again. I tried all the solutions I saw here but nothing changed.

**Comment by vmaruhpe** [comment]
Same issue since couple of months. I tried resetting, reinstalling etc. I finally switched to Ubuntu VM on W10.

**Comment by mshekharc** [comment]
> There is nothing "proper" in using Chocolatey for installing docker. There is an official Docker installer that should work. Kubectl is bundled with docker installer, so you should not need to resort to using some random third-party software to make it work. I do agree that if someone is desperate to get it working, trying _anything_ does not sound crazy, but calling it "proper" is a huge misnomer ;)

Hi Andrew, As Docker bundle is not able to fulfill the prerequisites for Kubernetes, so Chocolatey is used to meet those requirements.

**Comment by mshekharc** [comment]
> There is nothing "proper" in using Chocolatey for installing docker. There is an official Docker installer that should work. Kubectl is bundled with docker installer, so you should not need to resort to using some random third-party software to make it work. I do agree that if someone is desperate to get it working, trying _anything_ does not sound crazy, but calling it "proper" is a huge misnomer ;)

Hi Andrew, Its not about Docker, Its about Kubernetes. BTW Chocolatey is not a random third-party software, its Kubernetes recommended application in the [documentation of Kubernetes ](https://kubernetes.io/docs/tasks/tools/install-kubectl/), which I have already mentioned earlier.

**Comment by shawnmgoulet** [comment]
Wow, I tried everything suggested here to no avail, then finally found [Kubernetes development environment using docker on Windows](https://medium.com/@jonjam/kubernetes-development-environment-using-docker-on-windows-9cd731c776b5). Downloaded the Edge channel, followed the commands listed there and **_finally_** 😆 was able to get kubernetes running. @pgayvallet - does that agree with Docker's suggestion for win?

**Comment by mtrtm** [comment]
I am having this problem to.  I have uninstalled and reinstalled docker, tried the environment variable fix, and I have even turned my firewall completely off.  Nothing works.  I finally got it to work after looking at logs and seeing dns errors and folder permission errors.  Here is what I did (not sure which one fixed it):

uninstall/reinstall docker for windows
allow c/d drive access
set environment var: [Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)
change to hardcoded dns

**Comment by jonaseck2** [comment]
@pgayvallet I think the problem stems from windows having two HOME equivalents %UserProfile% and %HomeDrive%%HomePath%. The problem shows up when these aren't aligned:

Credentials for docker-for desktop are placed in %UserProfile%\.kube\config when kubernetes is enabled.
Credentials are by default read from %HomeDrive%%HomePath%\.kube\config, causing the context to not show up in the menu and kubectl commands to fail. 

The proposed solution is of course that docker-for-windows should  resolve an unset HOME or KUBECONFIG the same when both creating and reading credentials.

powershell sets a HOME to %UserProfile%, but git bash sets it to %HomeDrive%%HomePath%, so an unset KUBECONFIG or HOME will result in shell specific, or application specific behaviour, depending on the order environment vars are read. So the solution may not be that simple.

I think the reason why people are reporting setting KUBECONFIG doesn't work is because the first solution in this post is missing a slash, setting the var to an invalid path, and even when it's correct, it'll use HOME resolved by powershell which (hopefully consistently) matches where the docker-desktop credentials are created. ie.
```
set environment var: [Environment]::SetEnvironmentVariable("KUBECONFIG", $HOME + "\.kube\config", [EnvironmentVariableTarget]::Machine)
```

as a workaround (and separate issue), setting both alternatives works for kubectl, but seems to break the docker-for-win kubernetes context menu:
```
setx KUBECONFIG '%HomeDrive%%HomePath%.kube\config:%UserProfile%\.kube\config'
```

kubectl config get-context
works

context menu is empty

**Comment by jonaseck2** [comment]
I don't hink there's an issue, both kubectl and the context menu fails if any of the upplied KUBECONFIG paths are invalid, and unless you've run something like gcloud get credentials, you won't have credentials in both places.

**Comment by sheng-jie** [comment]
If your version is v2.0.0.2/v2.0.0.3, please follow this guide [Enable Kubernetes on Docker for Mac/Windows in China](https://github.com/AliyunContainerService/k8s-for-docker-desktop/blob/master/README_en.md).
I have tried that, it works for me.

Attention:
**If you want to use v2.0.0.2/v2.0.0.3 (with Docker CE 18.09.1 and Kubernetes 1.10.11), please use the 18.09 branch git checkout v2.0.0.2**

**Comment by fouadroumieh** [comment]
Uploade my diagnostics: 138D29F3-FCC1-46C0-A14B-3109055FA760/20190316044839

**Comment by csuzhangxc** [comment]
Uploaded my diagnostics: 4EA3DA23-A61D-44BF-89B6-176E32D9C271/20190328145652

**Comment by ManiacDC** [comment]
I tried all the steps here, they didn't help. My issue turned out to be that somebody has registered localhost.<domain>.com on our domain network. Fixing that fixed the issue.

**Comment by jorrit** [comment]
For me there already was a service running on port 6445 (Teamviewer_Service.exe).

Run the following in an admin CMD / PS to find if this occurs for you:

`netstat -anb`

Mine showed this:

`[TeamViewer_Service.exe]
  TCP    127.0.0.1:6445         0.0.0.0:0              LISTENING`

For now I just stopped the teamviewer service.

**Comment by pellea** [comment]
I have the same issue.

Diagnostic ID: E3BECDB0-EE3E-4617-B404-A8B0600E5B96/20190429210638

Docker edge 2.0.3.0 (31778) - Kubernetes 1.13.0

**Comment by zhan520g** [comment]
this is crazy!

**Comment by jorrit** [comment]
You could also try to remove Docker, reboot, disable Hyper-V, reboot, enable Hyper-V, reboot, install Docker, reboot. Maybe you can do without some of the reboots, but it doesn't hurt.

**Comment by Triple-Z** [comment]
I have tried:

* Reset Kubernetes Cluster;
* Reset to factory defaults;
* Set DNS Server to `fixed 8.8.8.8` in Docker settings;
* Close the Windows Firewall;
* Set KUBECONFIG environment variable;

But **none of them** work.

My diagnose id is: `675838AA-D2D0-4C4C-AAA6-581C21B07659/20190522182248` and i always get these messages in log:

```
[20:49:53.629][ApiProxy       ][Info   ] time="2019-05-22T20:49:53+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:54.629][ApiProxy       ][Info   ] time="2019-05-22T20:49:54+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:55.630][ApiProxy       ][Info   ] time="2019-05-22T20:49:55+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:56.630][ApiProxy       ][Info   ] time="2019-05-22T20:49:56+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:57.630][ApiProxy       ][Info   ] time="2019-05-22T20:49:57+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:58.630][ApiProxy       ][Info   ] time="2019-05-22T20:49:58+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:49:59.630][ApiProxy       ][Info   ] time="2019-05-22T20:49:59+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:50:00.629][ApiProxy       ][Info   ] time="2019-05-22T20:50:00+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:50:01.629][ApiProxy       ][Info   ] time="2019-05-22T20:50:01+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
[20:50:02.629][ApiProxy       ][Info   ] time="2019-05-22T20:50:02+08:00" msg="Cannot list nodes: Get https://localhost:6445/api/v1/nodes: EOF"
```

Docker Desktop info:
![image](https://user-images.githubusercontent.com/16285716/58175773-7c7cad00-7cd3-11e9-922c-9c5e84cf5229.png)

**Comment by jorrit** [comment]
@Triple-Z: have you tried reinstalling Hyper-V?

**Comment by Triple-Z** [comment]
@jorrit How to reinstall the Hyper-V?

**Comment by jorrit** [comment]
You could look at posts like https://ugetfix.com/ask/how-to-disable-hyper-v-in-windows-10/. I only had to unmark Hyper-V in features, reboot, and then mark it, reboot. Then install Docker and enable Kubernetes.

**Comment by EugeneMsv** [comment]
Tried everything. 
As a result add vpnkit to outbound rules in the firewall (also check inboud ).

And the main thing which helped me is to  correct file 
`c:\Users\<YourUser>\AppData\Roaming\Docker\dhcp.json`

the file content should be like this

```
{
  "searchDomains": [
 
  ],
  "domainName": "localdomain"
}
```

**Comment by netors** [comment]
this is on Mac but may do the trick on Windows too:

I was having this same issue today and noticed that for some reason my localhost.localdomain did not resolved to 127.0.0.1, it was pointing to my router's IP so I just added:
`127.0.0.1 localhost.localdomain`
to my /etc/hosts file, I reset Kubernetes on Docker for mac and it started working

**Comment by inech** [comment]
For me the only thing which helped was to to remove `C:\ProgramData\DockerDesktop\pki` folder and restart Docker. As described here https://github.com/docker/for-win/issues/3769#issuecomment-486046718

**Comment by DUWENINK** [comment]
FK GFW，i spent much time on the meanless thing because of the gfw

**Comment by kunwei2005** [comment]
I tried these steps and it works.
* Quite Docker Desktop
* Delete folder ~/.kube
* Delete folder C:\ProgramData\DockerDesktop\pki
* Start Docker Desktop

**Comment by AndrewSav** [comment]
Note, that by deleteing `.kube` you wipe out all your kubernetes client configurations. So all that clusters that you used to manage and their credentials? Gone. Not sure what useful private keys and certificates are deleted along with pki.

Use your jusdgement folks before following random advices on internet and do not shoot yourself in the foot.

**Comment by manlsc** [comment]
uploadey my 8748522F-869C-4EB6-9479-6CF37F78D801/20200527105854
