### ISSUE TITLE
Cannot switch docker to linux container

### ISSUE THREAD

**Issue by wyx2000** [docker/for-win#1678]
### Expected behavior
Switch to Linux container
### Actual behavior
Failed to switch, return Error response from daemon: Bad response from Docker engine
### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
0148D5E7-7BF7-4D7B-AB9E-F709F15FD7E0/2018-02-08_13-55-35

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by pluczak99** [comment]
> Issues go stale after 90d of inactivity.
> Mark the issue as fresh with `/remove-lifecycle stale` comment.
> Stale issues will be closed after an additional 30d of inactivity.
> 
> Prevent issues from auto-closing with an `/lifecycle frozen` comment.
> 
> If this issue is safe to close now please do so.
> 
> Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
> /lifecycle stale

"Issues go stale after 90d of inactivity".

Just to clarify: is it inactivity of the user reporting the issue, or inactivity of the Docker team that is supposed to fix the issue as stale after 90 days since the original report?

Usually, if an issue like this (that I am experiencing too and is driving me nuts) is reported, it is required that the dev team does some coding to fix it and then asks the user who reported it if it was fixed in the latest build. That is called communication with users. You guys at Docker are not fans of it? Do you prefer to ignore the issue, then pretend it never happened since within 90 days the original poster did not report it again? (and why should he/she, if the Docker team provided no info about fixing it in the recent build?)

Sorry, this is lousy SDLC and lousy issue resolution process. Just saying. You can close this report, but Docker still doesn't work for me - frankly, when I select an option from right click menu of the Docker client ("Switch to Linux containers") and then "docker info" in PowerShell window returns errors about pipe name, this is not production quality code for external users and it doesn't quite infuse me with confidence that I or my clients should pay Docker any money for the Enterprise edition of the product.
