### ISSUE TITLE
Docker not starting on Windows 10

### ISSUE THREAD

**Issue by luigikitten** [docker/for-win#1720]
### Expected behavior
Docker should start

### Actual behavior
It doesn't
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
1C3F08F2-D5D2-4483-859B-D263B71CA4E9/2018-02-17_16-27-42

  - host distribution and version (Windows version, build number, etc)
WIn10. PC is a corporate one, so with all the (bad) things like proxy, vpn, features controlled by remote admin, etc...

### Steps to reproduce the behavior
on this machine it simply refuses to start... I have tried to:
- disable hyper-v, reboot, install a clean docker, and let it re-enable it --> no way
- upgrade to the edge channel: no way
- manually start an hyperv vm in windows: seems fine
- manually start all the "hyper-v *" services on windows: no way

latest error is:
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Thanks!

**Comment by ncarandini** [comment]
Hi @luigikitten 
I'm running the stable 17.12.0-ce on a Windows 10 Insider preview and I have a similar problem.

I've partially solved it, so maybe this can be helpful:

Switching to Windows container seemed to solve the starting error on my machine. Too bad that even if the docker settings windows reported the docker status as "running", trying to get `docker info` resulted on the error "...the docker daemon is not running".
I've solved enabling the "General | Expose daemon on tpc://localhost:<port> without TLS" setting.
Once restarted, the docker finally accepted the `docker info` command and the classic `docker run hello-world`.

The funny thing is that once done, the docker continue to successfully run even after disabling the "General | Expose daemon on tpc://localhost:<port> without TLS" setting.

I can only desume that enabling that setting triggers some action needed but missed by the installer, something that is not reversed when disabling back the setting.

**Comment by luigikitten** [comment]
Many thanks for the hint, but this workaround does not work for me :(
Waiting for some news from docker team.....

**Comment by Ageraluon** [comment]
I've been experiencing the same issue on a Server 2016 with DfW latest stable/edge. 
While windows containers would work fine, upon switching to linux containers, the docker client would try to install and start the MobyLinuxVM, but stop it again after about 1min. After two tries, the error mentioned above would show.

Based upon my research, this issue seems to be showing quite often in a number of different conditions. 

What finally worked for me was to set the number of Processors in the VM to 1, which can be done as follows:

- Goto your docker installation directory (e.g. C:\Program Files\Docker\Docker)
- Under 'resources', find and open 'MobyLinux.ps1' for editing
- Change the following line (currently Line 57):
`    [Parameter(ParameterSetName='Create',Mandatory=$false)][int] $CPUs = 2,`
To
`    [Parameter(ParameterSetName='Create',Mandatory=$false)][int] $CPUs = 1,`

Save, close and restart Docker.
I'm planning to run quite a number of different containers, so I see this as a temporary workaround and would be quite interested in multiple CPUs.

Besides, what I tried (and didn't work for me)

- Reinstalling Docker
- Switching to Edge
- Disabling and Reactivating Hyper-V
- Starting Docker as Admin
- Various other suggestions on different forums

**Comment by maddoglv** [comment]
Had problem with docker run hello-world it dropped error ->

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

tried to restart service restart pc doing all kind of actions nothing seemed to help but tnx to @ncarandini  tried to switch to widows containers and then only from Run as Administrator power shell this command **run hello-world** finally for the first time started to run ... tnx @ncarandini 

My system info->

 docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 17.12.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.437GiB
Name: **
ID: 644L:JBD4:BJ7F:XNA3:PKH6:PVWR:B6RH:H32P:JOK4:****:****:****
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2018-03-02T20:50:44.6983549+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by Ageraluon** [comment]
Actually, no I am back to the error mentioned above, docker only started twice without displaying that error, then stopped running again. 
I completely formatted the pc, then set up the AD, the DHCP and DNS server again, then installed docker, and - same error...
I am seriously wondering whether this is due to some timing issue, some timout being too short, since my machine is indeed not the fastest. I have been experiencing this problem persistenly since about december last year.

**Comment by ncarandini** [comment]
Works on my machine with Windows Insider Preview 17112 (RS4)

**Comment by Ageraluon** [comment]
Another report:
F00DD952-FB18-43DE-9026-B546C7B82BE3/2018-03-11_22-42-33

**Comment by Ageraluon** [comment]
https://github.com/docker/for-win/issues/1811

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
