### ISSUE TITLE
fresh install - could not read CA certificate. The system cannot find the path specified.

### ISSUE THREAD

**Issue by JimBlob1979** [docker/for-win#1746]
- Fresh install on Windows 10.  
- Virtual machine "Moby" created successfully in Hyper-V and is able to start successfully.  
- Tray application states "Docker is up and running!".

### Expected behavior
- Issue a "docker images" at command prompt
- docker should return an (empty) list of images.

### Actual behavior
- Issue a "docker images" at command prompt
- an error message is presented stating 
`"could not read CA certificate "C:\\Users\\...\\.docker\\machine\\machines\\default\\ca.pem": open C:\Users\...\.docker\machine\machines\default\ca.pem: The system cannot find the path specified."`
(*note the "..." in the path is my username for my home directory)

I'd expect that the default docker-machine would automatically generate certificates in the correct location.  Instead  ...\\.docker\machine\machines is empty.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: 922D6223-5E7B-4382-9261-2357D39E22AC/2018-02-23_09-04-38

  - host distribution and version (Windows version, build number, etc)
**Windows version:** Windows 10 Enterprise 
**OS Build:** 14393.2035
**Version:** 1607

**Docker Version:** Version 17.12.0-ce-win47 (15139)

### Steps to reproduce the behavior

  1. Download and run (elevated) "Docker for Windows Installer.exe" (MD5: 8427cee2e9ee0c2c342e0ce8747c4217 )
  2. After installation,  execute "Docker for Windows" shortcut on desktop (elevated).
 3.  Wait until dialog pops up saying "Docker is running!".
 4. Open PowerShell and type 'docker images' 
 5. Sit and stare the the error message for a moment, and then go on a hunt for missing certificates...

**Comment by JimBlob1979** [comment]
I've discovered that if I run `docker-machine create --driver hyperv  vm`,  new certs are successfully generated at 'C:\Users\...\.docker\machine\certs'.    But this is a different path than what is stated in the initial error message.

Additionally, at the end of the 'vm' creation,  was presented with another error message:
`Warning: got an invalid line error parsing /etc/os-release: Expected The system cannot find the path specified. to split by '=' char into two strings, instead got 1 strings
Error creating machine: Error detecting OS: OS type not recognized`

**Comment by georaldc** [comment]
Do you have any DOCKER environment variables that would have been interfering with the application? I had the same problem after moving from Docker Toolbox to the native app and had to just delete those environment variables to get things working.

**Comment by JimBlob1979** [comment]
Thanks @georaldc .   That does appear to be the case here.  Great suggestion!

**Comment by Ebeid** [comment]
what environment variables you removed @georaldc ?

**Comment by rwdietrich** [comment]
Just went through this myself and things seem to be working. I deleted

- DOCKER_TLS_VERIFY
- DOCKER_CERT_PATH
- DOCKER_HOST

**Comment by leehaskings** [comment]
Hit the same issue. I suspect it's come from first having Docker Toolbox installed and then later on installing Docker for Windows.

One additional thing I did to fix this issue was also uninstall Virtualbox to remove any clashes there.

The solution from @rwdietrich above fixed it for me, but took me a while to work out how to remove these variables. Here's how:

(from: https://apilevel.wordpress.com/2017/11/23/docker-for-windows-certificate-error-solution/)

1. Go to Control Panel\All Control Panel Items\System Then click Advanced system settings, In System Properties, Go to Advanced Tab and Click Environment Variables. Delete all DOCKER_* from System/User variables.

2. Remove DOCKER_* from command prompt or PowerShell, i used PowerShell. using following steps

[Environment]::SetEnvironmentVariable("DOCKER_CERT_PATH", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_HOST", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_MACHINE_NAME", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_TLS_VERIFY", $null, "User")
[Environment]::SetEnvironmentVariable("DOCKER_TOOLBOX_INSTALL_PATH", $null, "User")

**Comment by umairsarwar** [comment]
I removed the environment variables through UI but it didn't work. Then I had to manually set all the docker related variables to empty through command line i.e `SET DOCKER_HOST=` etc.

**Comment by upsyl** [comment]
Following up on @leehaskings  for the UI solutions and @umairsarwar for the command lines, 
the problem was fixed for me. 

Below are the plain text command lines.

SET DOCKER_CERT_PATH= $null, "User"
SET DOCKER_HOST= $null, "User"
SET DOCKER_MACHINE_NAME= $null, "User"
SET DOCKER_TLS_VERIFY= $null, "User"
SET DOCKER_TOOLBOX_INSTALL_PATH= $null, "User"

I ran into the problem after an upgrade from windows 7 pro and the use of Docker Toolbox + oracle virtual box to windows 10 pro and native docker.

**Comment by gkimpson** [comment]
I had the same issues - I had to remove the following from the System Environment variables :-
DOCKER_TLS_VERIFY
DOCKER_CERT_PATH
DOCKER_HOST
DOCKER_TOOLBOX_INSTALL_PATH

Once I removed Docker then re-installed Docker this seems to work fine 👍

**Comment by jangobel** [comment]
For me it was also an environment variables problem.
Instead of deleting them manually, just close your terminal and open it again.
The variables should be gone.

**Comment by Shaker1978** [comment]
Great solution! Worked for mee to, after switching from Docker Toolbox (Win7) to Docker for Windows (Win10) on the same machine. About 4 environment variables were left and causing this problem.

Thank you!

**Comment by thebadhatter** [comment]
This seems to occur whenever Docker Toolbox is installed prior to Installing Docker for Windows. Just delete the following environment variables:
SET DOCKER_CERT_PATH
SET DOCKER_HOST
SET DOCKER_MACHINE_NAME
SET DOCKER_TLS_VERIFY
SET DOCKER_TOOLBOX_INSTALL_PATH

I've noticed not all installs have all of those and might be missing one or two (Not sure if this was caused by the user or just due to the installation though I never looked into it.)
But just delete them and run docker in the cmd line and everything will be 👌.

**Comment by ChrisDillinger** [comment]
Running into this same issue now. You all seemed to have a work around where we can just clear out these values, but doesn't this just disable the usage of TLS? What is the secure way of dealing with this issue?

This SO answer here references documentation that specifically says it is not recommended to disable TLS: https://stackoverflow.com/questions/31176262/what-does-the-docker-tls-verify-and-docker-cert-path-variable-do

**Comment by nabhanabdulla** [comment]
Copying contents of  "C:\Users\nabhu\.docker\machine\certs\." to 
"C:\\Users\\...\\.docker\\machine\\machines\\default\\" worked for me

**Comment by jbelford** [comment]
In addition to the about I had to also regenerate certs `docker-machine regenerate-certs default`

**Comment by chandra-devs** [comment]
Simple solution for unsetting 
`eval "$(docker-machine env -u)"`

check after unset
`env | grep DOCKER`

**Comment by sz332** [comment]
Had the same issue, removed the DOCKER_... environment variables and everything works perfectly. I think the troubleshooter solution check for this and suggest a removal of the variables.

**Comment by aditya-bhuyan** [comment]
Hi,
I also had the same problem. I have changed my DOCKER_CERT_PATH value to C:\Users\adity.docker\machine\certs. It worked fine.

**Comment by EnnioWolsink** [comment]
Note when modifying/deleting environment you may need to restart your terminal for changes to take effect. That's at least what I needed to do.

**Comment by 99suresh81** [comment]
> Just went through this myself and things seem to be working. I deleted
> 
> * DOCKER_TLS_VERIFY
> * DOCKER_CERT_PATH
> * DOCKER_HOST
> * DOCKER_TOOLBOX_INSTALL_PATH
> 
> If you have any other variables set, you probably want to delete those as well. You can experiment by opening a command window, doing one or more `SET DOCKER_HOST=` (or whatever variable), and then trying a docker command.

Thanks a lot it fixed my issue.

**Comment by 99suresh81** [comment]
Thanks a lot it fixed my issue.

**Comment by 99suresh81** [comment]
> having

Thanks a lot fixed my issue.

**Comment by 99suresh81** [comment]
> Hit the same issue. I suspect it's come from first having Docker Toolbox installed and then later on installing Docker for Windows.
> 
> One additional thing I did to fix this issue was also uninstall Virtualbox to remove any clashes there.
> 
> The solution from @rwdietrich above fixed it for me, but took me a while to work out how to remove these variables. Here's how:
> 
> (from: https://apilevel.wordpress.com/2017/11/23/docker-for-windows-certificate-error-solution/)
> 
> 1. Go to Control Panel\All Control Panel Items\System Then click Advanced system settings, In System Properties, Go to Advanced Tab and Click Environment Variables. Delete all DOCKER_* from System/User variables.
> 2. Remove DOCKER_* from command prompt or PowerShell, i used PowerShell. using following steps
> 
> [Environment]::SetEnvironmentVariable("DOCKER_CERT_PATH", $null, "User")
> [Environment]::SetEnvironmentVariable("DOCKER_HOST", $null, "User")
> [Environment]::SetEnvironmentVariable("DOCKER_MACHINE_NAME", $null, "User")
> [Environment]::SetEnvironmentVariable("DOCKER_TLS_VERIFY", $null, "User")
> [Environment]::SetEnvironmentVariable("DOCKER_TOOLBOX_INSTALL_PATH", $null, "User")

Thanks a lot for your help, fixed my issue, I frustrated

**Comment by IYABAO** [comment]
> Just went through this myself and things seem to be working. I deleted
> 
> * DOCKER_TLS_VERIFY
> * DOCKER_CERT_PATH
> * DOCKER_HOST
> * DOCKER_TOOLBOX_INSTALL_PATH
> 
> If you have any other variables set, you probably want to delete those as well. You can experiment by opening a command window, doing one or more `SET DOCKER_HOST=` (or whatever variable), and then trying a docker command.

Thanks a lot for your help~！！！！！
