### ISSUE TITLE
Changing windows Password Broke windows volume mounts

### ISSUE THREAD

**Issue by bjholmes23** [docker/for-win#1761]
### Expected behavior

Changing windows password, which strips Docker access to the C: drive, should cause a docker error message to display if it no longer has access to the Windows host filesystem to tell me to re-enter my Windows password in the Docker preferences interface.

### Actual behavior

Changing windows password, which appears to strip Docker access to the C: drive, throws no errors and suddenly my containers stop working because they don't have any files. Hours later I realize what has happened. 

### Information

Docker version 17.12.0-ce, build c97c6d6
docker-compose version 1.18.0, build 8dd22a96
Windows 10 pro version 1709 

### Steps to reproduce the behavior

  1. Run docker-compose with Windows host volume mounts  
  2. Change Windows Password 
  3. Mayhem ensues

**Comment by Kelvin-Meyer** [comment]
I think that this is the same issue as I am experiencing:
## Description of the issue
After changing my windows password docker runs into problems.

## Context information (for bug reports)
It would be nice if docker could give a warning that there is something wrong with the password instead of a driver programming issue.

https://github.com/docker/compose/issues/3277

```
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017```

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false```

```
version: '2'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
    - C:\dev\gitlab\X/build/www:/usr/share/nginx/html
    - C:\dev\gitlab\X/site.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "19192:19192"

```


## Steps to reproduce the issue
1. Start nginx (in my case)
2. Confirm the workings
3. Change windows password
4. Reboot
4. Start nginx again

### Observed result
![image](https://user-images.githubusercontent.com/11310940/42328696-f65c7b9e-803c-11e8-8f2f-ddae712c4ee7.png)

### Expected result
![image](https://user-images.githubusercontent.com/11310940/42329027-ce30d4ac-803d-11e8-8e79-2a2ad1cb6c8e.png)



## Additional information
Interesting behavior BTW I've changed my password back to the password it was before and docker automatically worked again. Does it store it in plain text?


OS version / distribution, `docker-compose` install method, etc.
Windows 10

**Comment by mac-dev** [comment]
Same here. We have to change our PW every 30 days. After changing it I wondered why the mounts don't apear in the containers anymore and my db-container was broken. In Docker settings the shares still looked okay, but there was a popup asking for "Apply Changes" and I didn't change anything - anyway I clicked "Apply"
Afterwards while I still not could figure out what was going on I started everything from scratch. Deleted the DBs files in the mountpoint. Deleted the Images, too and some Containers. 
After starting again, Docker suddenly asked for my User and PW again to mount the shared drive.

**Comment by jpazsedano** [comment]
Same problem here. After a password change, the containers started to crash because they failed to access the volumes.

As a workaround, going to Docker settings and unsharing the disk will make the share prompt to appear again, ask for the password again and fix the problem. However Docker should be able to detect this situation and ask for the new password by itself.

**Comment by waltronix** [comment]
I'm currently using 18.06.1-ce-win73 (19507) and had the same problem.
After a password change, my volume mounts had problem.
I would really prefer to get a proper error if credentials do not match any more!

**Comment by h3xstream** [comment]
Workaround : https://stackoverflow.com/a/50219928/89769

**Comment by bjholmes23** [comment]
Darnit, reset my password and wasted yet another hour trying to figure out why my volume mounts weren't working before I realized again I was hitting this issue.

**Comment by h3xstream** [comment]
I'm pretty sure no change was made to address the issue.

**Comment by yybot1** [comment]
I encountered the same problem, and it took me hours if not days to notice what the problem is. Eventually, I reset Docker Desktop, so have to enter the password again, I notice this is the problem. 

There definitely need a message displayed when the account password changed. Can't you just throw a warning or error message when you detect the password changed?

**Comment by cjw296** [comment]
Seeing similar problem on Version 2.0.0.3 (31259): Changed my Active Directory password, kept on getting locked out by the process above repeatedly presenting the wrong password.
