### ISSUE TITLE
Can't add Shared Drive - Firewall is blocking Sharing

### ISSUE THREAD

**Issue by wkrd** [docker/for-win#1762]
### Expected behavior
Ability to add C:\ or E:\ as a Shared Drive through docker settings

### Actual behavior
After clicking the Drive and entering domain credentials in docker settings, always get the 'A firewall is blocking Sharing between Windows and the containers'.

### Information

  - Diagnostic ID 618C99D5-F41E-4230-AF90-6C49D7BEEBB8/2018-02-28_12-09-13
  - Windows 10 Pro Version	10.0.16299 Build 16299

### What I've tried

Everything I could find on several different tickets:

Reinstalling Docker/Rebooting/etc.
Disabling/Enabling "File and Printer Sharing for Microsoft Networks", as well as Uninstall / Install
Setting DockerNAT network to private
Adding Firewall Incoming port rules for 445 
Disabling all end-point protection (Webroot SecureAnywhere) and turning off windows defender firewall entirely
regedit -> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
Set SMB2 Key to 1 (enabled)

**Comment by wkrd** [comment]
Does this network setup seem correct?

In Network and Sharing Center:

Under 'Unidentified Network' (Private network) there are two connections: 
vEthernet (Default Switch)
vEthernet (DockerNAT)

**Comment by robnardo** [comment]
I am also having the same issue.  Running "[System.Environment]::OSVersion.Version" in PS gives me..
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15063  0
```
I have tried everything that @wkrd has tried.  One thing I will try (when i get some time) is to uninstall Docker, reboot, then re-install.  And will let you all know if that worked.

**Comment by robnardo** [comment]
i have some time today to continue.. so i tried the "Reset to factory defaults" option and it returned an error: "Docker hv-sock proxy (vsudd) is not reachable".  This is the crash report: **4F7AE5C5-FEA5-4D2F-8F87-9C58348EF5BA/2018-03-08_10-21-21** I opened the Hyper-V manager and noticed the MobyLinux virtual machine is no longer listed.  

Trying the "Reset to factory default" again (but this time from the error modal) returns a different error: "Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled" crash report uploaded: **4F7AE5C5-FEA5-4D2F-8F87-9C58348EF5BA/2018-03-08_10-32-22** 
 While the second try was happening, i had Hyper-V Manager and Network Connections windows open and noticed MobyLinuxVM was listed for a bit, then removed.  And DockerNAT also listed then removed.

Next i will try actually uninstalling Docker, removing the Hyper-V

**Comment by robnardo** [comment]
Update.. trying to uninstall seems to work (kind of) but the Docker for windows / Uninstalled successfully window hangs.  And when i attempt to close, it asks "Are you sure you want to cancel the installation?".  I will click Yes, then reboot, download a fresh install file and try again.

**Comment by robnardo** [comment]
Same thing.. a fresh install yields the same result.. Firewall detected :(

**Comment by robnardo** [comment]
SOLVED by having administrator adjust the Group Policy on Private Profile!  If you work for a company with Windows Group Policy rules in place, then you should check if your Private Profile has "All inbound connections are blocked." - If this is set, then NOTHING will work until this setting is set to the default, which is "Inbound connections that do not match a rule are blocked."  I took a screen grab of what it should look like.
![wf](https://user-images.githubusercontent.com/12520995/37990041-1e0defb4-31d3-11e8-8016-d0821a348493.png)

you can check this by opening a command prompt and running `wf.msc` which should open the Windows Firewall control panel.

**Comment by stephen-turner** [comment]
This seems to solve the issue so closing this ticket.

**Comment by david-airfire** [comment]
I am having this problem. 

Windows Firewall is set to "Block all connections to apps that are not on the list of allowed apps" for incoming connections. I have the "DockerSMBMount" firewall rule from my install, which should allow the traffic in. 

I also tried dropping and re-creating the "File and Printer Sharing for Microsoft Networking" on the DockerNAT network, per the help link in the error message. 

What else can I do?

**Comment by rvanlaak** [comment]
Hope this will help others too, having Tunnelbear installed turned out to be the reason that changes to Windows Firewall rules were reverted.

After uninstalling Tunnelbear and unchecking `vEthernet (DockerNAT)` as protected network connection the shared did work again 👍
