### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable - win 10 pro crash on start

### ISSUE THREAD

**Issue by MarcoSpittka** [docker/for-win#1776]
### Expected behavior
Docker is starting

### Actual behavior
Docker doesn't start
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
EDF09FF3-B4F9-400B-B35F-6B8691221576/2018-03-02_11-32-07
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Install Docker
  2. Start Docker

**Comment by ctmcisco** [comment]
I have the same behavior on stable or Edge. This occurs when switching to linux containers. I have to kill the docker process and start it again and hope it starts in  Windows container mode. Windows container mode does work. Seems the Moby VM has a network issue. I also have tried to edit the settings.json to set the CPU to 1 vs 2 or 4 cpus.

23:00:40.672][CrashReport    ][Info   ] Diagnostics successfully uploaded (01CD3DA8-66FC-4DEA-9C5A-5F8B469D1CC4/2018-03-02_23-00-10)
[23:00:40.675][GUI            ][Info   ] Sending Bugsnag report 7365e8be-cc5d-46d2-a4a0-c6168eb96ccf...

**Comment by ctmcisco** [comment]
01CD3DA8-66FC-4DEA-9C5A-5F8B469D1CC4/2018-03-02_23-00-10

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
