### ISSUE TITLE
Docker for windows should detect Kitematic installed by Docker Toolbox

### ISSUE THREAD

**Issue by juherr** [docker/for-win#18]
### Expected behavior

Launch installed Kitematic.
By default, Docker Toolbox installs it in `C:\Program Files\Docker Toolbox\kitematic`
### Actual behavior

Ask to install Kitematic
### Information
- Diagnostic ID: 63FC49AC-136A-4694-8FC1-E651A239AEE3/2016-08-02_13-35-11
- Windows 10 Pro
### Steps to reproduce the behavior
1. Install Docker for Windows & Docker Toolbox
2. Run Kitematic from Docker for Windows (right click in systray icon + "Open Kitematic..."

**Comment by dgageot** [comment]
Thanks @juherr for the report. That's right, we could do that. @FrenchBen wdyt?

**Comment by FrenchBen** [comment]
@dgageot I like that idea - Although I would prefer it lived under the same folder as Docker for Windows:
`C:\Program Files\Docker\kitematic`

**Comment by dgageot** [comment]
@FrenchBen What can we do to improve current behaviour?

**Comment by FrenchBen** [comment]
@dgageot Could we package it as part of the Docker for Windows installer?

**Comment by otravers** [comment]
As a Windows user currently diving into Docker, it does feel like Docker for Windows and Kitematic are somewhat disconnected. It would make sense to install the latter with the former. It would also make sense for Kitematic to be aware of Docker for Windows Shared Drives (https://github.com/docker/kitematic/issues/376) under Volumes, and integrate with that functionality (instead of overlapping it).

**Comment by jasonbivins** [comment]
When you hit the Kitematic option now, it looks for C:\Program Files\Docker\Kitematic
If it is there - it launches Kitematic.  if not, it launches a dialog box telling you what do do
