### ISSUE TITLE
Docker for Win is likely the most unstable program ever

### ISSUE THREAD

**Issue by hoegge** [docker/for-win#1805]
Firstly: I love docker, ... but

### Expected behavior
Start after reboot without error messages.
I have used docker for windows for about a year - both stable and edge version. They all have shown random and frequently occuring startup errors - that can come and go. The error messages do not really give any information on what is wrong. Is it something you want to improve?

### Actual behavior
Version after version you get random "docker cannot start" messages

### Information
- Diagnostic ID for the error of the day: E9CBF190-66D5-420A-A5A8-9FA5D6D52443/2018-03-08_08-34-28

### Steps to reproduce the behavior

  1. Install docker for windows - any version
  2. Experience start-up errors

**Comment by MPJHorner** [comment]
👍 Feel like throwing my Win desktop out the windows, my macbook on the otherhand works perfectly.

**Comment by MPJHorner** [comment]
Tried installing fresh version today on fresh windows 0.

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 7A6767CF-EADE-44F4-9135-83142F2BF749)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

**Comment by mlmeyers** [comment]
I have to second this as buggy, but would be far from the worst I have worked with :)

Started down the Docker for Windows path a few months back. My excitement around Docker on Windows was enormous, One of the biggest value propositions for Docker was being able to both build test, and deploy local our software stack and promote the same through the pipeline. This beginning to seem more a pipedream. The more I use the software on the workstation the more frustrated I become with encountering defects and bugs. On the server side "knock on wood" things appear much simpler and more stable so far, the struggle is more around limitations. 

Some current issues | grievances :

1. The Docker for Windows service likes to consume huge amounts of CPU. This was bloat in my opinion to cater to the less technical and enable clicky click to switch modes, make config changes, etc. On the server this bloat does not exist, a simple service pointing to the daemon and a json config file. This also has made installation hard to automate across the org unlike the few commands required on the server. It adds lots of additional layers making it more complex and challenging to troubleshoot and work with. You can't just modify the docker service as it is recreated and managed by the docker for windows service.

2. The windowsfilter directories consume huge amounts of disk space and can become a pain to manage. Try cleaning them up manually you will probably just succumb to using the docker-ci-zap tool.

3. Localhost binding, was released and shortly after broken and remains broken with latest windows patches, it is actively being worked on.

4. Start-up issues, similar to @hoegge has called out. 

5. Slow, only hyper-v containers supported. Why? I deploy to server with process isolation but all local testing has to be done with hyper-v isolation, further killing the value prop.   

6. How to manage docker versions from windows workstation to server when the same binaries are not available on both?

I really want @Microsoft and @Docker to be successful on the promise of running both Linux and Windows containers on Windows, no doubt it will propel both companies and open the doors for a much improved more streamlined approach to building and delivering software. I have always been on the fence on adoption of containers mainly because developers in my shop mostly run Windows. I certainty appreciate all the efforts that are going into making this happen, at the same time I don't want to put "lipstick on a pig".

**Comment by E88** [comment]
Cannot start Docker for Linux container
```
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
OS: Windows 10 Enterprise

[09:04:19.381][Linux          ][Error  ] Failed to start: Unable to stop: Die Methode kann nicht aufgerufen werden. Der Methodenaufruf wird in diesem Sprachmodus nur für Kerntypen unterstützt.
bei <ScriptBlock>, <Keine Datei>: Zeile 87. Let's retry
...
[09:04:29.063][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: Die Methode kann nicht aufgerufen werden. Der Methodenaufruf wird in diesem Sprachmodus nur für Kerntypen unterstützt.
bei <ScriptBlock>, <Keine Datei>: Zeile 87    bei Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:Zeile 181.
   bei Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 306.
   bei Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 129.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 47.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 145.
[09:04:29.079][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: Die Methode kann nicht aufgerufen werden. Der Methodenaufruf wird in diesem Sprachmodus nur für Kerntypen unterstützt.
bei <ScriptBlock>, <Keine Datei>: Zeile 87
[09:04:29.079][Notifications  ][Error  ] Unable to stop: Die Methode kann nicht aufgerufen werden. Der Methodenaufruf wird in diesem Sprachmodus nur für Kerntypen unterstützt.
bei <ScriptBlock>, <Keine Datei>: Zeile 87

```

**Comment by TomDobbelaere** [comment]
Was just about to create this issue when I came across this one. It's absolutely ridiculous.

Every day I have to use Docker for work, and every day my containers will not start, unless I turn experimental features off then on again, then click "Restart docker..". What's the point of starting with Windows if I need to restart every time anyway?

Honestly it is insanely unstable, and you should feel blessed if you get error messages because my containers just refuse to start without crashing unless I restart Docker. (and yes, they weren't already running or something like that)

**Comment by pulse14** [comment]
I don't understand why it's so unstable. 
1. Everything works
2. Restart docker deamon
3. Everything is corrupted and crash

**Comment by snintendog** [comment]
Issue is still persisting till this day gave up on docker entirely. This Thread being auto closed without even a look from a dev shows windows will never be considered seriously. just went back to a Vbox linux distro and packages 99% less headaches.
