### ISSUE TITLE
cannot start a docker - error message stated that there was not enough memory although there is enough memory

### ISSUE THREAD

**Issue by lastthing2** [docker/for-win#181]
### Expected behavior
start a docker
### Actual behavior
 cannot start a docker - error message stated that there was not enough memory although there is enough memory
### Information

  - Diagnostic ID from "Diagnose & Feedback":  0779B458-E3F2-4B9D-9D35-F98FAD510275/2016-10-29_05-37-42

[log error.txt](https://github.com/docker/for-win/files/559923/log.error.txt)

**Comment by rneugeba** [comment]
@lastthing2 your system seems to have less than 4G of total memory. The Linux VM we start, by default, is configured to use 2GB of memory. Running a 2GB VM on a 4GB system is quite tight and may result in the VM not starting with the message you report. This is expected behaviour so I'm closing this issue.

You can try reducing the memory used by the VM to 1.5GB or maybe even 1GB via the advanced tab in the settings menu, though we would recommend running with 2GB.
