### ISSUE TITLE
Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable [Windows 10 Enterprise]

### ISSUE THREAD

**Issue by Aimpist** [docker/for-win#1816]
### Information

  - F24C703E-79C2-4B64-ABED-6EE472E51CD8/2018-03-11_21-02-50
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - Windows 10, Enterprise edition
### Steps to reproduce the behavior

  1. ...Install Docker version 17.12.0-ce, build c97c6d6
  2. ... Start Docker

**Comment by Ageraluon** [comment]
https://github.com/docker/for-win/issues/1811

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
