### ISSUE TITLE
"ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

### ISSUE THREAD

**Issue by dkirrane** [docker/for-win#1821]
### Expected behavior

Docker starts

### Actual behavior
Fails to start with Error:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass16_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 124
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
406964F7-3B67-4868-A8A9-74ACF1BC712C/2018-03-12_10-45-47
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Installed Docker Edge 18.03.0.ce-rc1-win54
  2. Started Docker
3. Error occurs

**Comment by ste93cry** [comment]
I also have the same error on Windows 10 Pro. I also have installed BitDefender Antivirus Plus with Threat Defense Off and Comodo Firewall with both firewall, HIPS and sandbox on.

- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: 89EBE0B8-8358-44F5-8DA4-D613C2D57BB5/20180726091659

### Expected behavior
After starting up the computer no error should be thrown.

### Actual behavior
After starting up the computer Docker crashes with the given error. The strange thing is that I had unchecked the "Start Docker when you log in" option. If I restart Docker manually then it works.

### Information
  - Windows Version: Windows 10 Pro 10.0.17134.165
  - Docker for Windows Version: 18.06.0-ce-win70 (19075)

**Comment by joshcsmith13** [comment]
Same here.  Windows 10 Pro.  Linux containers.   On system reboot, I get the exact error provided by OP.
I have found that I am unable to "Restart Docker" from the system-tray icon.  It gets stuck "restarting".
There is no VM running in Hyper-V.
Uploaded Crash Report:  49A49C80-59C4-4E94-8D75-B5C0A06A0762/20180927084019
