### ISSUE TITLE
Hyper-V isolation uses only 2 cores.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [docker/for-win#1877]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise 1709 - 16299.309
  - Docker for Windows Version: 18.03.0-ce-rc4

### Expected behavior
Container uses all the available cores.

### Actual behavior
Container uses only 2 cores.

### Information
The following command reports that only 2 cores are available. The cpu usage is also limited to only 2 cores.
`docker run microsoft/windowsservercore WMIC CPU Get DeviceID,NumberOfCores,NumberOfLogicalProcessors`

The issue can also be seen on Windows Server 2016 with hyperv isolation:
`docker run --isolation=hyperv microsoft/windowsservercore WMIC CPU Get DeviceID,NumberOfCores,NumberOfLogicalProcessors`

However running first command on Windows Server 2016 gives the expected output and the containers use all available cores.

**Comment by yusuf-gunaydin** [comment]
Adding `--cpu-count N` to the command works. But, why do I have to specify the number of cpu's every time? Isn't it a more meaningful default to use all the cpu's available in host like the process isolation does? If needed one can limit the cpu usage anyways.

**Comment by rn** [comment]
This is more a artefact of how containers are implemented with Hyper-V isolation. They are started in a VM an when configuring the VM the number of CPUs needs to be specified. With process isolation (only available on Windows Server) the container runs as a process which can use all cores (when it starts more threads).

Since this is not an issue specific to the Docker for Windows application, I'm closing this issue. Feel free to open an issue on https://github.com/moby/moby where some of the windows container development happens, but I suspect you may get a similar answer there.
