### ISSUE TITLE
Dockerfile “RUN” statement always returns 0

### ISSUE THREAD

**Issue by gtaspider** [docker/for-win#1878]
**Any RUN statement** in a Dockerfile **returns** a non-zero code **4294967295 (-1)** on Windows Server with *Linux containers on Windows* turned on (` LCOW_SUPPORTED = 1 `)

Dockerfile:

    FROM debian:jessie
    RUN exit 0

PowerShell output (same on cmd)

    PS C:\docker\images\test> docker build -t test .
    Sending build context to Docker daemon  2.048kB
    Step 1/2 : FROM debian:jessie
     ---> 5dd74d62fab8
    Step 2/2 : RUN exit 0
     ---> Running in b8a7d0d722c8
    The command '/bin/sh -c exit 0' returned a non-zero code: 4294967295

Same with Ubuntu Image and any other command I put after RUN.

Running *Docker17.10.0-ee-preview-3* and *Windows Server 2019 17623 prerelease.*

**Comment by rn** [comment]
looks like a dup of https://github.com/moby/moby/issues/36682

Also, this is an issue with the upstream  https://github.com/moby/moby code, not with the Docker for Windows application so closing this here. If your issue is different to the one I cited, please open another issue there.

Thanks for reporting
