### ISSUE TITLE
Running 2 containers consumed 24 Gig

### ISSUE THREAD

**Issue by eliassal** [docker/for-win#192]
I tried to run Multi-Container Applicationns at
https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md
After several tries, the containers were up and running but surprisingly, they consumed 24Gig of disk. I opened a thread at 
https://github.com/docker/labs/issues/96
It was recommended to open an issue here in order to find a solution with you guys and see what is wrong and how to clean my laptop.
By the way, how can I change the location where containers, layers, images are downloaded to avoid filling the C drive, currently my C drive has 400Meg free out of 30 GIG
Here is a snapshot of the system
![dockerimages_003](https://cloud.githubusercontent.com/assets/8447864/19926937/0f32cf94-a0bd-11e6-8b62-e7d5254d1ee8.jpg)

**Comment by eliassal** [comment]
snapshot of the running 2 containers
![dockerimages](https://cloud.githubusercontent.com/assets/8447864/19926979/4f445f76-a0bd-11e6-9e60-0539c81c2734.jpg)

**Comment by rneugeba** [comment]
@eliassal thanks for the report. Some of the windows container images can be quite "chunky", though I didn't think there were this big. But it turns out the MusicStore sample app indeed consumes 20+GB.

You can reclaim the space by removing the images:
- check with `docker ps -a` if any stopped containers are there and remove them with `docker rm <container id>`
- then check with `docker images` and remove unwanted/needed images with `docker rmi <image id>`

**Comment by eliassal** [comment]
Thanks, OK the question now is how I can change the location for the pull and downloaded images? I can create a   Gig virtual hard drive and attach it to the VM in order not to fill the C drive and work comfortably Any idea? I googled since  days and was not able to find the right information

**Comment by cons0l3** [comment]
have a look at #191 (with tips that worked for me) and #185.

**Comment by dgageot** [comment]
@eliassal I'm sorry we can't fix the size every container is taking out there. So I'm going to close this issue. Feel free to weight on #185 since it's a very valid issue.
