### ISSUE TITLE
Handler for POST /v1.37/containers/29897919e5c5bc30727cfe7b64c7716de45e4935aae57cfa507e4a8426961509/start returned error: failed to create endpoint iisdemo12 on network nat: HNS failed with error : The process cannot access the file because it is being used by another process. 

### ISSUE THREAD

**Issue by amitceh** [docker/for-win#1951]
Handler for POST /v1.37/containers/29897919e5c5bc30727cfe7b64c7716de45e4935aae57cfa507e4a8426961509/start returned error: failed to create endpoint iisdemo12 on network nat: HNS failed with error : The process cannot access the file because it is being used by another process.

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
