### ISSUE TITLE
Future of Docker: AF_Unix support?

### ISSUE THREAD

**Issue by DarthSpock** [docker/for-win#1954]
With Spring Creator's Update releasing this month for Windows 10 comes the numerous possibilities associated with using AF_Unix on Windows. Socket streams will be able to be created from one Windows app/service to another or from Windows to Linux via WSL. This being said, could Docker for Windows be tweaked to have a version that utilizes socket streams or will more of AF_Unix need to be implemented first? Relevant blog from Microsoft here: https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/

In case this is useful for implementing this: https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/

**Comment by DarthSpock** [comment]
bump

**Comment by rn** [comment]
What's your use case and where would you like unix domain sockets to be used? 

On Windows, docker currently uses named pipes for CLI to daemon communication. This comes from the upstream https://github.com/moby/moby implementation and you may want to open an issue there.

I'm closing this issue here for now as it does not seem to be directly related to the Docker for Windows application (for which this tracker is), but feel free to comment here if your request is more specific to the application itself.
