### ISSUE TITLE
Docker starts when I log in, but I have that unchecked.

### ISSUE THREAD

**Issue by SkipSailors** [docker/for-win#1991]
See: E57B7065-56DE-4549-BD8D-2F6336C904F4/2018-05-01_19-28-53
Windows 10 Pro 64-bit
DfW Version 18.03.1-ce-win65 (17513)

In the newest Docker for Windows, The daemon starts when I boot.  I don't want it to do so.  The General settings form shows that box is unchecked.

Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

### Expected behavior
Docker not started

### Actual behavior
Docker started

### Steps to reproduce the behavior

  1. Uncheck the Start Docker When You Log In
  2. Restart

**Comment by rn** [comment]
I can  not reproduce this with 18.05.0-ce-rc1-win63 (17439)

**Comment by stephen-turner** [comment]
That's odd. If you open the Task Manager and look at the Startup tab, is Docker present?

**Comment by SkipSailors** [comment]
No, Docker is not present in the Startup tab

**Comment by SkipSailors** [comment]
I have Windows 10 Pro Version 1803 OS build 17134.1, if it makes a difference.  That's the recent Creator's Update.

**Comment by SkipSailors** [comment]
Uninstall, reinstall, reboot a couple times, update an unrelated VPN driver, start the service again.  It begins to work.

**Comment by SkipSailors** [comment]
See E57B7065-56DE-4549-BD8D-2F6336C904F4/20181220073517.  Recent update, this happens again and rebooting, and messing with unrelated configurations is not an effective resolution.

**Comment by SkipSailors** [comment]
Docker is on my laptop.  It is configured to use an external drive.  I don't always have that drive plugged in when I start the machine.  Docker crashes when it doesn't find the drive.  It shouldn't try to start itself until I have a drive plugged in.  Docker needs to wait till I tell it to start.

**Comment by debug-desperado** [comment]
I'm having this issue as well with the 2.0 update. It is possible that I missed some of the prior updates over the last few months.

The problem is that there is a "leftover" entry in the Startup tab with the "Start Docker Desktop when you log in" option disabled. When you enable the option, another startup entry appears and is enabled. 

I have gotten around the issue for now by setting the orphaned startup entry to be disabled. The Docker team should have the update installer remove any previous registry entries regarding this startup option.
