### ISSUE TITLE
Docker for Windows is a joke

### ISSUE THREAD

**Issue by Mico-Fucho** [docker/for-win#2012]
If I try 'docker pull microsoft/powershell:nanoserver' on Windows 10 I get the following error:
failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer C:\ProgramData\Docker\windowsfilter\2bdb023bafe4f53e887d3624d84448d47c9f6b066edcd7f30f341a58b030f3a0: Acceso denegado.

If I try 'docker pull microsoft/powershell:nanoserver' on Windows 2016 Server I get the following error:
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage \\?\C:\ProgramData\docker\windowsfilter\197432dd7339f6af54a4cd293f66fc0d1eecae96d5b3db05cbdb1f62c0ffa7c6\UtilityVM: El sistema no puede encontrar la ruta especificada.

On windows 10 I've created exclusions on Norton, disabled Norton with no results.
On w2k16 I created exclusions for Windows Defender, if I generate the folder UtilityVM while extracting I get error telling me that the folder exists, if I don't generate the folder, it says the system can't find the path. The OS is completly fresh, only Microsoft Updates and Docker Installation.
I've around with Microsoft products over 25 years, and nothing changes. Pain, blame, shame, time waste, wrecked weekends, full of flaws products, untested and useless.

**Comment by rn** [comment]
Your issue seems to be with the upstream implementation of Windows containers and not with the Docker for Windows application itself (for Windows container support, Docker for Windows just packages the upstream code from the moby project). We do run tests with Windows containers in our CI (like pulling an image, running windows containers), but there obviously is something different in your setup.

Since this is an issue with an upstream component, I'm closing this here. Could you please open an issue on https://github.com/moby/moby/issues instead.
