### ISSUE TITLE
Service DNS does not working at 1803 cotnainers in swarm mode

### ISSUE THREAD

**Issue by vitaliy-leschenko** [docker/for-win#2036]
- [x] I have tried with the latest version of my channel (master-dockerproject-2018-05-14)
  - Windows Version: Windows Server 1803 (10.0.17134.48)
  - Docker for Windows Version: master-dockerproject-2018-05-14

### Expected behavior
Any services in some network must be able to resolve IP of other services.

### Actual behavior
Services can't resovle IP of other services.

### Information
Windows Server 1709 have no this issue.

### Steps to reproduce the behavior

 1. init swarm
 2. create overlay network N
 3. create service A into network N
 4. create service B into network N
 5. try to ping B from A by IP - OK.
 6. try to ping A from B by IP - OK.
 7. try to ping B from A by name - fail (can't resolve IP).
 8. try to ping A from B by name - fail (can't resolve IP).

**Comment by rn** [comment]
Thank you for the report. This isssue tracker is for Docker for Windows, which is a application for Windows 10. So I'm closing this here.

For issues with master builds, please open an issue on https://github.com/moby/moby which is where the windows container development happens. Since you are using Windows Server, if this issue also exist with Docker EE basic (which comes for free with Windows Server) you can also look at http://success.docker.com/article/where-to-get-help-with-windows for where to report.
