### ISSUE TITLE
"docker for win10" how to open ssh?

### ISSUE THREAD

**Issue by dongasai** [docker/for-win#2044]
I want to perform some personalized operations on virtual machines in ssh?

Version 18.03.0-ce-win59 (16762)
Channel: stable

In order to prevent misunderstanding

See figure

https://raw.githubusercontent.com/dongasai/note/master/QQ图片20180516085857.png

**Comment by rn** [comment]
we don't enable SSH in the virtual machine. You can try a `nsenter` image to get access, but any changes will likely disappear after a restart. The VM also has a read-only root filesystem so it will be hard to customise.

you can enter the VM with something like:
```
docker run -it --privileged --pid=host justincormack/nsenter1
```

Since we do not support customising the VM (or logging into it to change settings etc) I'm closing this issue.

If you have specific things you'd like to change, please let use know.
