### ISSUE TITLE
Unable to start: The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by qwidget** [docker/for-win#205]
### Expected behavior
Docker should start

### Actual behavior
Docker fails to start. First error in log file is 

```
[10:10:17.547][DataKit        ][Info   ] +1208732us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[10:10:17.566][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[10:10:18.030][HyperV         ][Info   ] Wait for the VM to get an IP address

(60x more)

[10:11:22.506][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The VM couldn't get an IP address after 60 tries
```

### Information

  - Diagnostic ID: 8BD9A3D5-160B-4C55-A63E-60E21BBBB353/2016-11-05_10-12-04
  - Windows 10 (stable) version

I've tried disabling the firewall, using different DNS settings, and a couple of other suggestion I found online but nothing worked so far.

### Steps to reproduce the behavior

  1. Install Docker
  2. Attempt to start

**Comment by rneugeba** [comment]
@qwidget thanks for your report. Could you try the latest Beta release from https://download.docker.com/win/beta/InstallDocker.msi and post the diagnostics ID. The Beta channel has improved diagnostics for this kind of issue?
Thanks

**Comment by qwidget** [comment]
@rneugeba - I've installed the latest beta and it failed the same way. Diagnostic ID is 
8BD9A3D5-160B-4C55-A63E-60E21BBBB353/2016-11-05_14-05-18

Thanks for the help!

**Comment by rneugeba** [comment]
@qwidget thanks for the quick reply. Unfortunately your system is suffering from the same problem as tracked in #54. I've posted a temporary workaround here https://github.com/docker/for-win/issues/54#issuecomment-257157813 and some additional comments here: https://github.com/docker/for-win/issues/54#issuecomment-258507126. We are working on a more permanent solution we are battling several Linux kernel bugs in the process.

I will close this issue as a duplicate and will tag you in a post on #54 so that you get further updates.

**Comment by qwidget** [comment]
The workaround described in #54 did resolve the problem - docker is running on my system now. Thanks!

**Comment by rneugeba** [comment]
Thanks for reporting back. We are getting closer to a permanent solution and hopefully will ship one in one of the next Beta.
