### ISSUE TITLE
Docker can not start to run.

### ISSUE THREAD

**Issue by macknight** [docker/for-win#2085]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 1FAF625C-185E-4C13-BC71-A828B31FF0E5/2018-06-05_15-19-48

### Expected behavior
Docker should start to run.
### Actual behavior
Docker stopped.

### Information

  - Windows Version:
Windows 10 Enterprise - Version:1703
  - Docker for Windows Version:
18.05.0-ce-win66 (17760)

### Steps to reproduce the behavior

  1. install docker edge for win, and run it, then it stopped.
[log.txt](https://github.com/docker/for-win/files/2071221/log.txt)

**Comment by OSHI7** [comment]
Hello,
I also am having this issue.  Grateful for any assistance.
[log.txt](https://github.com/docker/for-win/files/2073272/log.txt)

**Comment by ahilmathew** [comment]
Can you check if Hyper-V Management Tools is installed/turned on.  [Reference](https://forums.docker.com/t/erroractionpreference/10047)

**Comment by OSHI7** [comment]
Hi. In my case, for sure it is enabled. "Containers" too..

**Comment by macknight** [comment]
And I am using ThinkPad T570 laptop. I see other people who has the same OS version, but different laptop succeed. What's your machine ? @OSHI7

**Comment by OSHI7** [comment]
@macknight: I am using a Dell Precision 7520.  Breakthru today. I disabled TrendMicro Office Scan, and Docker fired up right away. I also uninstalled VMware viewer, and so am unsure of any interaction there, but it is in my mind. Good Luck.

**Comment by rn** [comment]
@macknight from the logs, it looks like you were succesfull in running Windows Containers but when you switch to Linux Containers, you get an error, right?

Something odd seems to be happening. The Hyper-V VM used for Linux Container seems to be created well, but the starting it fails. This is also confirmed by the Event Log, which also contains:
```
6/5/2018 2:12:58 PM           3062 Error            Virtual Machine Worker
                                                    Process initialization has
                                                    timed out, and will
                                                    terminate.
```

In HyperV manager, can you create a new empty VM (just click through all the defaults) and try to start it?

Since you can seem to start Windows containers there doesn't seem to be an issue with Hyper-V itself (On Windows 10 windows containers also use Hyper-V but in a very different way to normal Hyper-V VMs). Maybe some AV software is blocking creating VMs?

@OSHI7 yeah, other users had issues with some  TrendMicro Office Scan versions as well

**Comment by nicowernli** [comment]
Same here with Windows 10 Pro 17134.112 and Docker 18.03.1-ce

The error message is the following (its in spanish)


```
Unable to create: Se detuvo el comando en ejecución porque la variable de preferencia "ErrorActionPreference" o un parámetro común se han establecido en Stop: El objeto ya existe.


   en Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:línea 36
   en Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:línea 67
   en Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() en C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:línea 51
   en Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() en C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:línea 59
```
