### ISSUE TITLE
Docker won't launch in Windows 

### ISSUE THREAD

**Issue by btmoffat** [docker/for-win#2098]
[log.txt](https://github.com/docker/for-win/files/2085989/log.txt)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
