### ISSUE TITLE
Recommended number of cores and amount of memory to allocate

### ISSUE THREAD

**Issue by LarryEitel** [docker/for-win#21]
I am running `Win10Pro` with `16G` with `i7-3770K CPU 3.50GHz`.

Just curious... Normally Docker fires up with `2 CPUs` and `2048 MB`.

Other than trial and error, are there any thoughts as to determining how to set these values?

Thank You

**Comment by dgageot** [comment]
Hi @LarryEitel thank you for taking the time to ask your question!

I guess the answer really depends on the workload you plan to run with Docker. 2CPUs should be plenty enough for most development task. However, since you have 16Gb on the host, you might want to give more memory to the containers. Something between 4Gb and 8Gb will leave plenty of memory on the host.

**Comment by LarryEitel** [comment]
Thank you @dgageot.

I will drop back to 2CPUs. At the moment, I have set 4Gs and my memory usage shows `System and compressed memory` at about 2Gs. I am assuming that although I have it set at 4Gs, it will only USE it as needed.

**Comment by LarryEitel** [comment]
FYI, just tried to bump to 8Gs and Docker Windows complained that there was not enough memory to start Docker. So, for now I will keep it at 4Gs.

**Comment by dgageot** [comment]
@LarryEitel Good to know! Feel free to close the ticket if you think your question was answered. And have fun!
