### ISSUE TITLE
Docker fails after startup

### ISSUE THREAD

**Issue by pulse14** [docker/for-win#2101]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Network and volumes work
### Actual behavior
Network and volumes don't work
### Information
  - Windows Version: Windows 10, version 1803
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

### Errors
- OCI runtime create failed: container_linux.go:348
- driver failed programming external connectivity on endpoint, Error starting userland proxy: mkdir /port/tcp:0.0.0.0:22:tcp:172.19.0.2:22: input/output error

To fix them I need to remove networks, containers and restart deamon, reset credentials at every startup.

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by pulse14** [comment]
@jasonbivins What is the content of the diagnostic file ? is it only the log file ?
