### ISSUE TITLE
msi installer not working for docker windows container

### ISSUE THREAD

**Issue by Shivani-Bansal** [docker/for-win#2137]
I am using a msi installer to install one of my application in windows container.
But it is getting hanged at 
InstallShield 11:23:40: Initializing Engine
InstallShield 11:23:43: Done Initializing...
InstallShield 11:23:43: Registering Msi Server...

nothing is happening after this.
Can someone please help me with this.

I am using microsoft/aspnet as my base image
and using below command in powershell script that i am running in a docker container.
Start-Process "msiexec.exe" -ArgumentList $argList -PassThru -Wait

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
