### ISSUE TITLE
Support Windows 10 IoT Core for ARM

### ISSUE THREAD

**Issue by siebigteroth** [docker/for-win#2152]
Since docker is running on Windows 10 IoT Core for x64, the ARM platform should also be targeted.
E.g. to run docker on a Raspberry Pi 3b+ (ARMv8, 64bit).

### Expected behavior
Docker should run on Windows 10 IoT Core for ARM processors, like the ARMv8 (64bit).

### Actual behavior
Not available.

**Comment by rn** [comment]
Hi Thanks for the suggestion.

This tracker is for the Docker for Windows application, it just uses the underlying infrastructure provided by both Windows and `docker`, so I'm closing this issue here.

In order to run containers on a Windows for arm64, first Microsoft would need to add container support in the arm64 version of Windows. Then support would need to be added to `moby/moby` (the upstream project for the Docker engine). You may want to open an issue on https://github.com/moby/moby/issues but as said, first container support would need to be enabled in Windows for am64.
