### ISSUE TITLE
failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builde*/../*.csproj: no such file or directory.

### ISSUE THREAD

**Issue by walidabouzaid** [docker/for-win#2154]
Can anyone help regarding the below issue, which happen while trying to visual studio solution 
----------------------
Creating network "dockercompose8189206996091753172_default" with the default driver
Building search.api
Service 'search.api' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder017835305/src/services/Flights/Search/Search.API/Search.API/Search.API.csproj: no such file or directory.

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by AlbertAY** [comment]
when i user linux model for windows docker ,building  image have this error
COPY failed: stat /var/lib/docker/tmp/docker-builder638888056/Web01/Web01.csproj: no such file or directory
