### ISSUE TITLE
win10 - 'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file

### ISSUE THREAD

**Issue by inuwan** [docker/for-win#2160]
Same as closed issue https://github.com/docker/for-win/issues/1127, but still experiencing.

1. Uninstalled, downloaded the most recent version of the stable Docker CE Windows, and installed.  I get the error.

1. Uninstalled, downloaded the edge version and installed.  I get the error

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by Sviatik** [comment]
Faced with the same issue after update windows and found how to fix it. 

You need to find your windows iso image which is running on your machine and follow this manual.
https://troubleshooter.xyz/wiki/fix-dism-error-0x800f081f-in-windows-10/

After it you need to restart machine.

Also before it tried to reinstall docker and hyper-v, both didn't help.
