### ISSUE TITLE
Using Windows Subsystem for Linux Fail to Connect to Docker on Windows

### ISSUE THREAD

**Issue by smrtRock** [docker/for-win#2161]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by smrtRock** [comment]
Expected behavior:  Run Draft up in Ubuntu (WIndows Subsystem for Linux) and container is created and uploaded to registry 
Actual behavior:  Failure to connect
Information
Windows Version: 10 (version 1803) OS Build 17134.112
Docker for Windows Version: 18.05.0-ce

Also installed Docker on WSL see if that fixed and sadly no that version is 1.13.1, build 092cba3
Steps to reproduce the behavior
… Create a dotnet core mvc app - dotnet new mvc --name myfirstmvc
… draft init -- This should package and prepare for container

… draft up -- This should run docker up and take instructions emitted from draft to a docker file

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
