### ISSUE TITLE
Upload Issue using docker - Windows 10 

### ISSUE THREAD

**Issue by atulb-webonise** [docker/for-win#2170]
Hi 
My Name is Atul Bhalerao  I have windows 10 machine and I have Installed docker in which I have a project setup. which is running fine but there is a functionality of upload file. So when we upload it says file could not upload. Till now what I have found out is that when we upload a file from application from docker container the windows 10 don't allow to get it placed or paste.

Waiting for Positive Reply.

**Comment by ebriney** [comment]
Hi @atulb-webonise, soory but I don't understand your error, what cannot be uploaded? An image?

**Comment by atulb-webonise** [comment]
@ebriney there is a permission issue inside the container image. But I am unable to set permission inside the container (the container is running with Linux OS). However, the host machine is windows 10 and the permission system for windows and Linux is different. it seems that windows not allowing to override the permissions of volume from the container. 

I am trying to give 777 permission to a directory by logging in to the container. The directory is shared in a volume between host windows and docker container. But the permission is still intact and not changed.

**Comment by ebriney** [comment]
-v is using smb to mount you local disk in a container, and so you can't change the rights on those files.
But you should be able to move files and copy them, why do you need to change permission?

**Comment by hrishikesh** [comment]
@ebriney : We are uploading a file from Drupal web interface and the upload location is in the mounted volume. It is not allowing Ngnix user to write a file on that location

**Comment by ebriney** [comment]
Can you try [that build](https://download-stage.docker.com/win/pr/1885/Docker%20for%20Windows%20Installer.exe) ?
I changed file_mode and dir_mode flags we use to setup smb.

**Comment by atulb-webonise** [comment]
@ebriney, not File Found - 404 Not Found page

**Comment by ebriney** [comment]
Sorry, copy/paste error, [here](https://download-stage.docker.com/win/pr/18855/Docker%20for%20Windows%20Installer.exe)

**Comment by atulb-webonise** [comment]
@ebriney Thank you for the build it worked perfectly. ❤️ 
Just a request can you please send the same the upcoming build for new users. 😃

**Comment by ebriney** [comment]
This fix will be in the next release (in 1 or 2 weeks)

**Comment by atulb-webonise** [comment]
Thankyou @ebriney that really sounds good.

**Comment by Ageraluon** [comment]
@ebriney could you give a quick overview over what has changed regarding the permissions in the latest release? I understand standard file/dir permissions is now 777 with uid/gid 0/0, is that correct?

Thank you and best regards

**Comment by nateleavitt** [comment]
Also curious about what changed. Could be tied to some other issues I'be been tracking in the past.

**Comment by dragon512** [comment]
I am curious as well. Does this mean I can mount my .ssh directory on windows have give it the correct read permission so ssh command in the container will work and not complain about the files being to open?

**Comment by ebriney** [comment]
By default smb share set rights to 755 and cannot be changed with chmod.
It's works on most of the cases because containers run with the root user usually.
But in your case, ngnix creates new linux users and so they cannot write in folder created by root user.
We have changed the smb default rights to 777, which gives full rights for all the users.

**Comment by ebriney** [comment]
For ssh, it complains because it's readable to all users, you will get the same issue with those changes @dragon512.

**Comment by ebriney** [comment]
Fixed in 18.06

**Comment by atulb-webonise** [comment]
@ebriney is this fix present in this version **18.06.0-ce-win69 (19257)** ?

**Comment by ebriney** [comment]
@OctavianParalescu : ok, it is noticed, I think what we can do is to have a tick to make a drive world writable (777) or root only writable (755)

**Comment by ebriney** [comment]
NB: it should be the same mounting ssh keys

**Comment by Ageraluon** [comment]
@ebriney Thanks for the clarification. Actually, this is an enormous issue for all linux containers executed on windows hosts. It would help a lot if the permissions and owner would be freely definable instead of just ticking between two permission sets. 

I've talked about this here: https://github.com/docker/for-win/issues/2042

Background is that many standard containers, like apache, nextcloud, mariadb, etc. require a very specific permission set or else they refuse to run. I am currently working around that with a rather complicated workaround, but that involves manually sharing files and defining SMB mounts individually with the mount options. A standard solution for that would make things much easier here. Also, a tick for changing the SMB share to allow the 'dynperms' option for linux containers that try to change file permissions during run time would be great!

**Comment by ebriney** [comment]
Sounds like an annoying issue, we will not change the gui in the next stable patch. Perhaps as temporary solution we can set 777 on directory only and restore file rights to 755.
Do you think it is a good tradeoff for now @Ageraluon?
I don't know what imply `dynperm` flag but perhaps we can test it in next edge.
I did a build with 755 file rights [here](https://download-stage.docker.com/win/pr/19454/Docker%20for%20Windows%20Installer.exe) @OctavianParalescu @atulb-webonise @hrishikesh, can you test it?

**Comment by Ageraluon** [comment]
Thanks @ebriney for looking into this. For me, this does not matter, since the individual containers would need different permission sets on the shares anyway. For instance, nextcloud would need www-data to own the folder with 750/640 permissions on some folders, and I remember that apache would require 700 rights before starting.

The dynperm flag allows a process to change the (emulated) permissions on a samba shared folder - just like this is possible on 'normal' folders. When starting, apache and nextcloud (as examples) try to set the correct permissions on the shares they are using, and are only refusing to start if they are not able to. With the dynperm flag enabled, the processes succeed in changing the permissions.
 However, these permissions are not stored on the server and might change during runtime, so this is a little tricky. For me it worked very well so far.
More about this here:
https://linux.die.net/man/8/mount.cifs

**Comment by dragon512** [comment]
I think the side thread here is that it is a major issue for Windows users that cannot map in .ssh keys or other certs with more restricted permission when running a Linux container. I personally would love to be able to start up an Apache traffic server container that had certs on my local drive in a restricted permission on the Linux container. or be able to call git or ssh without it complaining about my shared .ssh directory on my windows drive. At this moment I have to run a Linux VM with docker in it to get this work in any fashion. As far as I understand there is no way to set these values when starting docker on windows
