### ISSUE TITLE
Nightly channel not working

### ISSUE THREAD

**Issue by edrevo** [docker/for-win#2175]
1. Open Docker settings in Docker 18.03.1-ce-win65 (17513)
2. Click "switch to another version"
3. Select nightly channel
4. Click "Install"

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
I should receive 18.06, which is the latest version as of 2018-07-04

### Actual behavior
I receive 17.03:

![image](https://user-images.githubusercontent.com/1845771/42264445-e61dcb9c-7f70-11e8-8ecf-74b8206ff334.png)

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? I don't know
  - Did the problem appear with an update? I don't know
  - Windows Version: Windows 10 1803
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)

**Comment by ebriney** [comment]
Hi @edrevo thanks for report.
Nightly channel is not anymore valid for now, this option should have been removed.

**Comment by CollinChaffin** [comment]
@ebriney You need to actually do something to fix this as it is destroying people's setups and after a quarter year, nothing has changed.  If you read my comments over in issue #2176 you will see EXACTLY WHY this is occurring - which is simply because whenever this decision (which is frankly idiotic for Docker to throw away free testing from willing users) Docker did NOT take down the cooresponding actual software ftp/http distribution point that the GUI above is checking which is at https://download.docker.com/win/static/edge/x86_64/

On top of the fact that Docker is the only company I've ever seen that buries it's only official downloads within their "docs.docker" sub-domain (and buried in actual docs) which then do not even contain ANY version numbering within those binary filenames, that by the way do NOT then match the binaries found at Docker's Github repos so if you want to compare there is no way to have any idea (short of actually executing the setup) which is even newer.....it's frankly a mess.
