### ISSUE TITLE
Failed to OpenRelative failed in Win32

### ISSUE THREAD

**Issue by jeffsaremi** [docker/for-win#2203]
I am running docker Docker version 18.03.1-ce, build 9ee9f40 on Windows 10.
Trying to pull an image from an internal registry. It keeps giving me this error:

failed to register layer: re-exec error: exit status 1: output: Failed to openRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\41d22880d272d8d45220700216f00c4ca23d2b926e59912399f5dc0d54c915ee\usr\lib\perl\5.18.2\sys: Cannot create a file when that file already exists. (0x1f) usr\lib\perl\5.18.2\sys\

**Comment by ejukams** [comment]
Not a docker pro, but I had the same problem pulling krol/oracledb11g:

failed to register layer: re-exec error: exit status 1: output: Failed to openRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\364372ef5da77969cf1fdc1d57af2b47e04f39eb8a69370867e0058d974070ea\usr\lib\perl\5.18.2\sys: Cannot create a file when that file already exists. (0x1f) usr\lib\perl\5.18.2\sys\

 I just switched from Windows containers to Linux containers and the problem is gone

**Comment by jeffsaremi** [comment]
same here. thanks

**Comment by artcard** [comment]
Hi, I have the same problem, with the image microsoft/mssql-server-linux:2017-latest,  is there a way to run it in windows containers?, wiithout switching to Unix containers?

**Comment by vcsekhar** [comment]
Yes, I ran into this same issue on Windows 10 Command Prompt after switching from Linux to Powershell
