### ISSUE TITLE
Unable to build or run microsoft/iis image due to error: The driver was not loaded because it failed its initialization call. 

### ISSUE THREAD

**Issue by eoliverio** [docker/for-win#2239]
Issue: Unable to `build` or `run` microsoft/iis docker images
Environment: Microsoft Windows 10 Version 1803 (OS Build 17134.165)

**Error**:
```
container <sha1> encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287)
```

**Procedure**:
1. Pulled microsoft/iis image. (also attempted on microsoft/iis:windowsservercore-1803 image)
2. Attempted to build the pulled microsoft/iis image

**Dockerfile:**
```
FROM microsoft/iis

RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

WORKDIR /inetpub/wwwroot

COPY ./Executables/ .
COPY ./HostWebServer/ .
```

**Output:**

```
PS C:\Users\xxxxx\Documents\WORKDIR\xxxxx> docker build -t testimg .
Sending build context to Docker daemon  3.714MB
Step 1/6 : FROM microsoft/iis
 ---> 248afbbe0fd1
Step 2/6 : SHELL ["powershell"]
 ---> Running in fea62fa54616
Removing intermediate container fea62fa54616
 ---> 8c0aa999c671
Step 3/6 : RUN Remove-Item -Recurse C:\inetpub\wwwroot\*
 ---> Running in 9090104f6805
container 9090104f6805d52797163bb335174a5ca45e674282e0b12a395af6c6220bc5eb encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287)
```

**Docker info**
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 4
Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.89GiB
Name: MyComputer
ID: H6NA:JZQF:OU6J:Q4RB:KF2N:APGW:2Z7Z:V6RP:MS5C:H73U:KWNN:DLF3
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 27
 System Time: 2018-07-23T17:48:15.7928097+09:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Making a container directly from the microsoft/iis image gives the same error:
```
PS C:\Users\xxxxx\Documents\WORKDIR\xxxxx> docker run -it microsoft/iis powershell
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 306db7788b403d8e468c82d45de8a23bf27f95787676733cc9ec5e19a09b95e9 encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287).
```

If there are any other information needed, I will gladly provide.
This is driving me nuts. Haha

**Comment by PhilBarila** [comment]
This is not stale.
`
User@Host: ~
$ docker run -d -p 1433:1433 -e sa_password=Pa$$word1 -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer
a2341718f3286f9341a7879bc42bc27ba5178222807c18608693954a09759f4d
docker: Error response from daemon: container a2341718f3286f9341a7879bc42bc27ba5178222807c18608693954a09759f4d encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287).
FAIL: 125

User@Host: ~
$
`
/remove-lifecycle stale

**Comment by PhilBarila** [comment]
`
PS C:\> docker info
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 4
Server Version: 18.09.0-ce-beta1
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 18267 (18267.1001.amd64fre.rs_prerelease.181020-1908)
Operating System: Windows 10 Enterprise Version 1809 (OS Build 18267.1001)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 31.86GiB
Name: USLTD0225PBARI
ID: GVKA:YXGT:VEFP:LEQT:T2S3:HEIT:2G23:BZKI:DPST:PA6X:4EEO:WH7E
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2018-10-30T09:12:33.2812224-06:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

PS C:\>
`

**Comment by PhilBarila** [comment]
Same thing happens with the current Stable version:
```
PS C:\> docker info
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 4
Server Version: 18.06.1-ce
Storage Driver: windowsfilter (windows) lcow (linux)
 Windows:
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 18267 (18267.1001.amd64fre.rs_prerelease.181020-1908)
Operating System: Windows 10 Enterprise Version 1809 (OS Build 18267.1001)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 31.86GiB
Name: HOSTNAME
ID: GVKA:YXGT:VEFP:LEQT:T2S3:HEIT:2G23:BZKI:DPST:PA6X:4EEO:WH7E
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 26
 System Time: 2018-10-30T09:21:05.7701334-06:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

PS C:\> docker run -d -p 1433:1433 -e sa_password=Pa$$word1 -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer
28ac76a33ed418b316cfd65f73032c357884f1aa0bda63c1412046a9aad9392d
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 28ac76a33ed418b316cfd65f73032c357884f1aa0bda63c1412046a9aad9392d encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287).
PS C:\>
```

**Comment by kumarrus** [comment]
I see this issue when I run with Windows Containers. I am able to run hello-world with Linux Containers.
-- Docker version 18.06.1-ce, build e68fc7a
-- Environment: Microsoft Windows 10 Version 1809

**λ  docker run hello-world --isolation hyperv**
`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container _XXX_ encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287).`

**From the docker daemon logs:**
`debug: starting container [module=libcontainerd namespace=moby container=_XXX_]`
`debug: HCSShim::Container::Start id=_XXX_
failed to start container [module=libcontainerd namespace=moby error=container _XXX_ encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287)]`
`debug: HCSShim::Container::Terminate id=_XXX_`
`debug: cleaned up after failed Start by calling Terminate [namespace=moby module=libcontainerd]`

**Comment by apwestgarth** [comment]
I am also experiencing this issue however it appears to be localised to Windows Server 2016 Core LTSC or Nano sac2016 base images

**Comment by Tadimsky** [comment]
I'm having a similar issue.

I'm trying to run a command as part of docker build:

```
Sending build context to Docker daemon  152.2MB
Step 1/26 : FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-1803
 ---> 85e02ec502ae
Step 2/26 : WORKDIR /rps
 ---> Using cache
 ---> fbbcfb38731b
Step 3/26 : COPY ./packages/RPS.Official.*/msi/vc_redist.x64.exe ./
 ---> Using cache
 ---> 64d30dea2851
Step 4/26 : COPY ./packages/RPS.Official.*/msi/rps64.msi ./
 ---> Using cache
 ---> 7807f2630755
Step 5/26 : RUN ["cmd /s /c", "vc_redist.x64.exe", "/install", "/quiet", "/log vc.log"]
 ---> Running in 2d47b3f95367
container 2d47b3f9536753553c78b440c7a54072c73625bab8bb9becdbe24d6807252f20 encountered an error during Start: failure in a Windows system call: The driver was not loaded because it failed its initialization call. (0x287)
```

Anyone had any luck getting around this issue?

**Comment by guillaumerose** [comment]
Related error: https://github.com/docker/for-win/issues/3282

/reopen 
/lifecycle frozen

**Comment by guillaumerose** [comment]
This issue, if I'm correct, is the same as reported here: https://social.msdn.microsoft.com/Forums/en-US/d5d55f11-3980-4dcf-abfd-576031de7d67/tp4-container-error-failed-to-initialize-the-driver-was-not-loaded-because-it-failed-its?forum=windowscontainers

@stgraves, from Microsoft, announced in December 2015, that they were working on a solution. I guess it's fixed by now.

**Comment by guillaumerose** [comment]
I ran a loop starting `microsoft/iis` 100 times. It works fine with latest Windows and latest Docker Desktop. Let's consider this issue fixed.
