### ISSUE TITLE
Windows 10 problem runing

### ISSUE THREAD

**Issue by mencerz** [docker/for-win#2266]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
![image](https://user-images.githubusercontent.com/38666998/43223578-37a7935c-905c-11e8-8a36-24725aa34c13.png)

  - Docker for Windows Version: last version

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
