### ISSUE TITLE
During upgrade: Killed VM MobyLinuxVM did not stop

### ISSUE THREAD

**Issue by FrenchBen** [docker/for-win#229]
### Expected behavior
Upgrade to work as expected

### Actual behavior
Upgrade failed with the following error:
```
Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 353
at Stop-VM, <No file>: line 341
at Stop-MobyLinuxVM, <No file>: line 284
at <ScriptBlock>, <No file>: line 360
   at Docker.Backend.ContainerEngine.Linux.Stop()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
```
F1FE4C2D-8536-4974-B87C-A50EE54B1B27/2016-11-14_15-21-06
```
  - a reproducible case if this is a bug, Dockerfiles FTW
```
Running Docker 1.12.3 (8488) - Stable
```
 
Windows update was launched at the same time Docker for Windows update was launched. Laptop went into 'sleep' mode during the update.

**Comment by rneugeba** [comment]
Did you have any containers running at the time of update? Any interactive sessions?

**Comment by FrenchBen** [comment]
No containers nor interactive sessions that I was aware of.

**Comment by rneugeba** [comment]
@FrenchBen Thanks for the info. Looking at the debug info, I noticed that you are running Windows in a VMware VM. Since we have little to no control over the configuration of the VMware VM nor on what's running on the physical host, we don't really support this configuration. So I'm closing this issue.

However, we keep an eye out in case this issue also is reported on real hardware. Thanks for reporting.
