### ISSUE TITLE
Docker not booting correctly in Win10

### ISSUE THREAD

**Issue by jan-koch** [docker/for-win#2303]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2C1001CF-5647-4039-A6E8-AC15E38FA1C6/20180727113229

### Expected behavior
Docker-compose working after Windows 10 has booted.

### Actual behavior
Docker-compose returns with this error:
```
ERROR: for mysql_db_1  Cannot start service db: driver failed programming external connectivity on endpoint mysql_db_1 (5dcb0a2a2c87e1e90b443af1d7428a177f5f7f6db9d6476f763e2ceae9cfad45): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8836:tcp:172.19.0.2:3306: input/output error

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint mysql_db_1 (5dcb0a2a2c87e1e90b443af1d7428a177f5f7f6db9d6476f763e2ceae9cfad45): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:8836:tcp:172.19.0.2:3306: input/output error
```

Trying to restart Docker ended in a crash with the message "Directory is not empty". Crash-log has been uploaded.

### Information

  - Windows Version: 10
  - Docker for Windows Version: latest

### Steps to reproduce the behavior

Every time I boot Windows, I have to restart Docker for it to work. See docker-compose.yml attached (zipped as Github doesn't allow me to upload .yml directly).
[docker-compose.zip](https://github.com/docker/for-win/files/2235294/docker-compose.zip)

**Comment by znmeb** [comment]
I've been seeing this issue for a few years now. If you search for the error `driver failed programming external connectivity on endpoint` you will find many hits with both Mac and Windows hosts and with all sorts of services in containers. My recollection is that resetting Docker for Windows makes this go away, but somebody needs to track down the root cause and fix it.

**Comment by znmeb** [comment]
There are 24 issues with this symptom - 11 open and 13 closed: https://github.com/docker/for-win/issues?utf8=%E2%9C%93&q=is%3Aissuedriver+failed+programming+external+connectivity+on+endpoint :-1:

**Comment by jan-koch** [comment]
Yes, I'm also seeing it on Mac and Windows. Restarting helps for me, I don't have to reset Docker... Don't have the skills to track it down unfortunately :-/

**Comment by znmeb** [comment]
I think other people have traced it to a root cause and supposedly it was fixed at one time. My plan is to give up on Docker Compose for desktop deployment and just use raw Docker commands called within a scripting language. For cloud deployment I'm going with Kubernetes, since Docker for Windows now ships it.

**Comment by jan-koch** [comment]
I'll close this ticket, don't have time to further investigate. I'm living with the manual Docker restart for now until I'm eventually moving development to some sort of cloud provider and moving away from docker-compose on Win.
