### ISSUE TITLE
Error Occured while installing Docker

### ISSUE THREAD

**Issue by akashgangrade** [docker/for-win#2319]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by gtardif** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by nanduinjeti** [comment]
Hi Gtardiff,

Please find the below diagnostic id for getting an issue while reinstalling docker. Kindly look into this and resolve asap

506AE7B5-3382-4ADF-977E-5F3A2B9ED984/20190708080759
