### ISSUE TITLE
Windows 10 VM - Switch to Linux Containers - Error

### ISSUE THREAD

**Issue by liquifiedart** [docker/for-win#2375]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4AF52081-0922-4D55-A73C-0955CEF5017A/20180806103023

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by liquifiedart** [comment]
Nested virtualization in a VMware Windows 10 vm. Switching to Linux containers.

That's. all.
