### ISSUE TITLE
troubleshooting on docker

### ISSUE THREAD

**Issue by wissjava216** [docker/for-win#2376]
09FD15CB-BDB3-41C6-9ABA-FFE459ADBB55/20180806163733

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
