### ISSUE TITLE
Hostnet_udp udp log message

### ISSUE THREAD

**Issue by whitecolor** [docker/for-win#240]
I have many events in the log like:

[21:13:05.265][VpnKit         ][Debug  ] com.docker.slirp.exe: Hostnet_udp udp:192.168.65.2:55011-8.8.8.8:53: creating UDP NAT rule
[21:13:06.262][VpnKit         ][Debug  ] com.docker.slirp.exe: Hostnet_udp udp:192.168.65.2:41966-8.8.8.8:53: creating UDP NAT rule

https://gist.github.com/whitecolor/c9203a4742a465cebf63c01167a680cd

Is it normal?

Windows 10. Beta 30.1

**Comment by rneugeba** [comment]
@whitecolor yes, for now this is normal, though we are turning down the logging level over time.

it's interesting though that the container is contacting google directly for DNS instead of going through the system default, but that shouldn't matter.

Hopefully this helps and I'm closing this issue, but please ask further questions here if you have them

**Comment by whitecolor** [comment]
> it's interesting though that the container is contacting google directly for DNS instead of going through the system default, but that shouldn't matter.

I use https://github.com/aacebedo/dnsdock and host system uses this container's DNS service. So other containers go though systems default, that goes though dnsdock container.
