### ISSUE TITLE
I can't install MDM Express

### ISSUE THREAD

**Issue by RALMOGUERA** [docker/for-win#2408]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by jasonbivins** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by RALMOGUERA** [comment]
Wow incredible, I can't believe that your answer is that you are just
closing the case because there isn't enough information....

2018-08-09 14:47 GMT-05:00 Jason Bivins <notifications@github.com>:
