### ISSUE TITLE
can not start dockers，when  I restart my computer。

### ISSUE THREAD

**Issue by zhanjx1314** [docker/for-win#2433]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
can not start dockers，when  I restart my computer。
docker's command all does not work.
### Information

  - Windows Version:   Microsoft Windows 10  10.0.17134.165
  - Docker for Windows Version: CE Version 18.06.0-ce-win72 (19098)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
