### ISSUE TITLE
Docker Daemon does not start

### ISSUE THREAD

**Issue by parimdev** [docker/for-win#2445]
Docker daemon does not start though "Docker for Windows" service is restarted and running.

  - [x ] I have tried with the latest version of my channel - Stable 
  - [x ] I have uploaded Diagnostics
  - **Diagnostics ID: 91345E20-860B-4BDE-BFC3-4EE8C87E800C/2018-08-17_11-01-46**

Expected behavior- 
Daemon should start as expected.

Actual behavior
Error message:
**error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, 
the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.**

Information
  - Windows Version: 10
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513)
      Channel: stable
       93354b3

### Steps to reproduce the behavior

  1. After Install, Issue command 'docker ps -a' to list containers.
  2. Error message is seen.

**Comment by bklassen** [comment]
I have this same problem.  Seems like a fair number of people are experiencing the same thing.  Docker was working fine until the latest windows updates were installed (on Aug 14 for me).  Since then I have been unable to get it to work.  The docker windows service seems to start and stop fine.  The MobyLinuxVM in hyper-v gets created and is running.  But the docker client cannot connect or finish starting.

My diagnostics ID:  0A90E265-6417-4774-BD3E-A0984BCB386B/20180817091328

I've tried reinstalling docker (stable & edge) multiple times.  I've tried turning off hyper-v and reinstalling it.  I've tried running services & client as a local admin account (at work we have separate local admin accounts).  Nothing I've tried has worked.  The errors seems to manifest in slightly different ways, but here's the latest error I see (just after doing a clean install, starting the docker client):

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
