### ISSUE TITLE
Unable to stop: Killed VM MobyLinuxVM did not stop

### ISSUE THREAD

**Issue by ll2jwork** [docker/for-win#2467]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?

**Comment by pbbhopp** [comment]
SOLVED
The same situation here( Win10( Version 10.0.17134) with Docker 2.0.0.3), after switch to Windows containers it was unable to return to Linux containers - an error occurred with the VM.
So, I stopped the Hyper-V process vmcompute.exe in the Task Manager. Then run it again as Admin, then switch Docker to Linux containers, it switched and runs well. Try this and return feedback.
