### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

### ISSUE THREAD

**Issue by hikal** [docker/for-win#248]
### Information

  Id: A87B93B9-688A-49DD-9A22-EEE229B7DA52/2016-11-23_09-53-12

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Steps to reproduce the behavior

  1. Set up docker for win
  2. Run docker cause a error

**Comment by abhinav-h-saxena** [comment]
What is the resolution for this issue?

**Comment by kristopher-d** [comment]
Closing this issue was inappropriate, particularly without comment. It's a real issue. 

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by friism** [comment]
@abhinav-h-saxena @kristopher-d can you check whether you're hitting this issue: https://github.com/docker/for-win/issues/402

If so, please run diagnostics and post the diagnostic ids there - if not, please open separate issue.

**Comment by yossi-neeman** [comment]
Have the same issue
ID - 52540761-A3D5-4CB1-A7EE-12326EB7A457/2017-01-29_15-05-40
Any resolution on this?

**Comment by MihaMarkic** [comment]
Check out Event Viewer. I had a situation where I was running low on c: disk space and no hyper-v virtual guest would start - docker reported the message in the title.
Also try starting MobyLinuxVM manually in hyper-v to see if it starts at all.

**Comment by JLospinoso** [comment]
I had a similar issue. If the VM is unavailable (e.g. due to removable drive not present, drive not mounted) you may get this. Might make a good feature request: check for presence of drive hosting VM and present friendlier message.

**Comment by MihaMarkic** [comment]
Or just simply put in a message "Checkout out your virtual guest in Hyper-V"

**Comment by bjimdar** [comment]
I ran into this same issue and it turned out to be orphaned virtual adapters. I went to device manager and deleted the Docker-created Hyper-V virtual adapters and reran setup and it worked fine.

As described here:
https://stackoverflow.com/questions/42500353/docker-on-windows-10-cant-startup-after-deleting-mobylinuxvm-in-hyper-v-manuall 

My take is that the "object already exists" error is referring to the virtual network adapter.
