### ISSUE TITLE
在win10环境, 如果禁用desktop的写权限, 会一直卡在安装的界面 

### ISSUE THREAD

**Issue by zaijiachipaomian** [docker/for-win#2496]
if the desktop is forbidden writable permission , install failed  , 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
