### ISSUE TITLE
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID DF06A6A6-30D8-477C-A6B6-D99EC447F2D3) at Start-MobyLinuxVM

### ISSUE THREAD

**Issue by Kumararch87** [docker/for-win#2515]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
