### ISSUE TITLE
Backend service is not installed

### ISSUE THREAD

**Issue by aspiringwei** [docker/for-win#2542]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...
Backend service is not installed
   在 Docker.WPF.BackendClient.CheckService() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:行号 344
   在 Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:行号 157
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 77
   在 Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 137
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
