### ISSUE TITLE
docker容器一直在restarting怎么解决

### ISSUE THREAD

**Issue by RaiyenXiao** [docker/for-win#2587]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

创建容器之后 启动容器docker-compose up -d 
查看容器状态 一直在Restarting (126) 2 seconds
You cannot remove a restarting container 9fd113232786e566556a7d4e9015964964ca81b893378451fc3f90da948bafad. Stop the container before attempting removal or force remove

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
