### ISSUE TITLE
error during connect Get https://192.168.99.100:2376/v1.38/containers/json

### ISSUE THREAD

**Issue by Foadsf** [docker/for-win#2596]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics 
[log.txt](https://github.com/docker/for-win/files/2374476/log.txt)

  - Diagnostics ID: 4751922A-3186-4B60-BD14-950E40145369/20180912112345

### Expected behavior

When running `docker container ls` to get a list of containers.

### Actual behavior
getting the error message:
> error during connect: Get https://192.168.99.100:2376/v1.38/containers/json: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Information

  - Windows Version: Windows 10 Enterprise 
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507), Channel: stable, b0f14f1

### Steps to reproduce the behavior

  1. open terminal
  2. run `docker container ls`

**P.S.** Guys, I do appreciate your efforts. But I have never been able to touch docker without spending hours to fix errors and issues. I think the whole docker structure is getting too cluttered. You need to spend more time fixing the common errors and be active on website like StackOverflow answering the questions and issues.

**Comment by Foadsf** [comment]
upon restart the error happened again. the way I solved it this time:

1. opened virtualbox and find the container where `docker-machine` or `boot2docker` (whatever it is!!!) is named `default`
2. from [here](https://tutel.me/c/programming/questions/32547427/docker+unreachable+after+computer+sleep) run `docker-machine stop default` and `docker-machine start default`
3. at this step you might get the error:
> Error response from daemon: client version ... is too new. Maximum supported API version is ...
4. from [here](https://github.com/docker/machine/issues/2147#issuecomment-233294338) you may run `docker-machine upgrade`

these steps solved my problem for the moment.

**Comment by Foadsf** [comment]
for those of you who end up here, do not install docker for windows. Install [Docker ToolBox](https://docs.docker.com/toolbox/toolbox_install_windows/) instead.

**Comment by yamlCase** [comment]
> for those of you who end up here, do not install docker for windows. Install [Docker ToolBox](https://docs.docker.com/toolbox/toolbox_install_windows/) instead.

Hi Foadsf, can you sum up why not to use Docker for Windows and instead ToolBox?

**Comment by yamlCase** [comment]
> for those of you who end up here, do not install docker for windows. Install [Docker ToolBox](https://docs.docker.com/toolbox/toolbox_install_windows/) instead.

> for those of you who end up here, do not install docker for windows. Install [Docker ToolBox](https://docs.docker.com/toolbox/toolbox_install_windows/) instead.

Hi @Foadsf, can you sum up why not to use Docker for Windows and instead ToolBox?  I'm apparently uninformed.  Thanks!

**Comment by atifmir** [comment]
@yamlCase Docker for windows is the best way to do it toolbox was for the legacy desktop.
Here is the solution that works, and there is no need to uninstall Oracle Virtual box hope this helps

**Comment by eugene-matvejev** [comment]
got same error :(

**Comment by claudivanmoreira** [comment]
got same error using Docker For Windows:

> error during connect: Get https://192.168.99.100:2376/v1.39/containers/json: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by shruti-rao** [comment]
Same error. /remove-lifecycle stale

**Comment by scarabetta** [comment]
Same error here:

$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get https://192.168.99.100:2376/v1.39/version: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by marquish** [comment]
would you check ?
`eval $(docker-machine env default)`

please post  > docker-machine env default  result if not solved.

**Comment by edward-objsec** [comment]
I am getting the same error, but only when shelling out from python to execute docker commands. The ip in the error msg is as above: 192.168.99.100:2376. If I execute docker from a terminal command prompt they work as expected.

I have docker toolkit installed on a windows 10 machine. In the docker quickstart terminal the environment variable DOCKER_HOST=192.168.99.**101**:2376. I can ping 101, but pinging 100 errors with "TTL expired in transit."

Thanks in advance for your help.

**Comment by halmai** [comment]
I had the same error message after an unexpected power failure of the host computer.

After rebooting, I started VirtualBox and later on the Docker Toolbox. Then I get the same error message for the command `docker images`. 

I deleted the virtual machine that the DockerTools installed for me and uninstalled the DockerTools too, then re-installed the same version. The problem was still the same. 

Finally, I sent an ACPI shutdown to the VBox (Right click -> Close -> ACPI Shutdown) and exited from the Docker Toolbox too. Then, I did start only the Docker Toolbox and did _not_ start the VBox. After a while, the Toolbox has started it automatically and it started to work fine. 

I have no idea what exactly solved the problem but maybe it helps someone in the future.

**Comment by ChrisCWerner** [comment]
Got it working just by doing `docker-machine restart` on the Docker Toolbox.

**Comment by pinakispecial** [comment]
Got same error 

> docker: error during connect: Post https://192.168.99.100:2376/v1

 and was banging my head as no help found over google.  **Then applied own intelligence and found the solution.**

Looks like due to some issue your docker machine URL not got updated properly in environment file. So you need to fix that. 

-------------------------------------------------------------------------------------------
First Run : `docker-machine ls`
output will be like this [URL may be something else]:
```
NAME      ACTIVE   DRIVER   STATE     URL                        SWARM   DOCKER     ERRORS
default   -        hyperv   Running   tcp://192.168.1.194:2376           v18.09.9
```
If you are not able to see any VM then you have to create a VM using this [link](https://docs.docker.com/machine/drivers/hyper-v/")

I'm hoping you are able to see VM. now hit : `set`

Along a lot environment variable you will able to see DOCKER_HOST which will be ponting to wrong URL. For me it was like 
`DOCKER_HOST=tcp://192.168.1.194:2376`

So simple change that `set DOCKER_HOST=tcp://192.168.1.194:2376`

Bingo!!!!

Just run `docker run  hello-world` you should be able to see desire output ...

**Comment by abmjunaed** [comment]
Solved:
I updated from Docker toolbox to Docker for windows and this problem happened.
Then I deleted all the environment variables for windows starting with Docker.
It solved the problem

**Comment by Rupinder1161** [comment]
just regenerate the machine and follow official docker documentation. worked for me 
https://docs.docker.com/toolbox/faqs/troubleshoot/

**Comment by tommyb82** [comment]
Likewise @abmjunaed - environment variables hanging around from previously (long) removed Docker Toolbox installation caused this problem with Docker Desktop (which was started ok after HyperV disable / reenable).  Removed them all, restart terminal, all working great now 🚀

**Comment by SteversIO** [comment]
Just adding what worked for me:
I was upgrading from Window 10 _Home_ && Docker Toolbox

to Windows 10 **Pro** && **Docker for Windows**.

These Environment Variables were used by Toolbox.  They need deleted:
```
DOCKER_TLS_VERIFY
DOCKER_CERT_PATH
DOCKER_HOST
DOCKER_TOOLBOX_INSTALL_PATH
```

**Comment by Foadsf** [comment]
One reason one should avoid [Doker on Windows](https://docs.docker.com/docker-for-windows/) and use [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/) instead is the fact, that the former uses Hyper-V which only exists on Windows Pro and Enterprise:



<pre>
  <img src="https://user-images.githubusercontent.com/12762442/76874058-e374df00-686e-11ea-8101-be76e52b24bd.png" width="500">               
</pre>

although your hardware might support Hyper-V if you check the `systeminfo` command, it is impossible to activate on Windows Home editions. Hyper-V in my humble opinion is evil as it also locks any other virtualizations at boot time (more info [here](https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/915#issuecomment-482908102)) and @#%# your Virtualbox. So do yourself a favor and avoid Docker on Windows and use Docker Toolbox instead.

**Comment by vakkisan** [comment]
> Got it working just by doing `docker-machine restart` on the Docker Toolbox.

got this error in windows.. 
 >docker image ls
error during connect: Get https://192.168.99.100:2376/v1.40/images/json: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

then restarted using `docker-machine restart` .. worked like a charm
