### ISSUE TITLE
No contexts listed for kubernetes

### ISSUE THREAD

**Issue by paschini** [docker/for-win#2737]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 14D48BBC-3E71-4D3C-AFA9-5E2596D5A0F5/20181012092251

### Expected behavior
I expected to have a docker-for-desktop listed for kubernetes

### Actual behavior
no contexts listed

### Information
I have just installed docker desktop for windows and activated kubernetes. Then I ran kubectl to check that the installation was working:
 kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
error: open Y:\/.kube/config: The system cannot find the path specified.

I noticed the path was wrong for kubeconfig and tried to fix it by setting the ENV variables by hand:
PS C:\Users\Camila\.kube> set HOMEDRIVE=C:
PS C:\Users\Camila\.kube> set HOMEPATH=\Users\Camila
PS C:\Users\Camila\.kube> kubectl cluster-info
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

I noticed there are no contexts listes for kubernetes and it seems to be runnin on the wrong port.

after that I tried to reset the cluster, still no contexts.

  - Windows Version:
Windows 10 Pro

  - Docker for Windows Version:
C:\Users\Camila\.kube> docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

### Steps to reproduce the behavior
This computer lives inside a network, with role policies applied. I log in to domain rather then the machine itself. I thought the problem with getting no contexts might be linked to the environment variable being set wrong by the default installation.

**Comment by jonstelly** [comment]
I bet you're on a windows domain and you have a HOME environment variable set to "Y:\" for a mapped home folder (that happens automatically if a home folder is specified)?  Look in your `$env:USERPROFILE\.kube` directory and I bet you'll find the config there, you just need to copy/merge it to `Y:\.kube`

I actually see this quite a bit with GO/multi-platform tools like this.  It's because I'm on a windows domain and have a Home folder set.  When you have a home folder in windows, an environment variable of `HOME` is set to that mapped drive, and that's the variable used in unix platforms to find a user's home directory.

It seems that some cross-platform utilities are written like:

```
if($HOME) {
  //USE $HOME
} else {
  //WINDOWS BEHAVIOR - $USERPROFILE
}
```

And others seem to be written like:

```
if($PLATFORM == "Windows") {
  //WINDOWS BEHAVIOR - $USERPROFILE
} else {
  //USE $HOME
}
```

I'm pretty sure that in this case, whatever took Docker for Windows uses to spin up the kubernetes cluster has one behavior, but it's not the same as the kubectl behavior, so they're reading/writing completely different kubernetes config files.  But the bug only shows up for windows users with mapped home profile drives.

**Comment by srsabu** [comment]
I had the same problem and copying the .kube directory from c:\users\blah\ over to the Y: drive fixed it for me.

**Comment by gimlichael** [comment]
I think this should be re-opened .. Docker Desktop should adapt the behavior of kubectl for consistency and clarity. Right now, as @jonstelly pointed out, it is a bug present for AD users with a mapped "home" drive.

**Comment by ed-graham** [comment]
> I think this should be re-opened .. Docker Desktop should adapt the behavior of kubectl for consistency and clarity. Right now, as @jonstelly pointed out, it is a bug present for AD users with a mapped "home" drive.

+1
