### ISSUE TITLE
docker not running in windows 10. Though Virtualization enabled. 

### ISSUE THREAD

**Issue by Femina** [docker/for-win#2812]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded diagnose details.

Diagnostics ID:     7EF1E78F-A8B5-4D6D-9308-6E8C911D213D/20181026205300 (uploaded)

### Expected behavior

Docker should run

### Actual behavior

Error 

### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: Docker version 18.06.1-ce, build e68fc7a

### Steps to reproduce the behavior

  1. Error Occurred: Hardware-assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
  2. BIOS set up and other details mentioned in the above link is done still same issues.

**Comment by yodaheis** [comment]
I struggled quite a bit with this. What worked for me is the following.. 
1. Turn **off** Hyper-v by **unchecking** the box in 'Turn Windows features On and Off' settings. Then reboot
2. Turn **on** Hyper-v by **checking** (make sure you see tick and not a box in the options, selecting/ unselecting sub-features will eventually get you there :) the box in 'Turn Windows features On and Off' settings. Then reboot
Let me know if it works for you. Looks like a problem with Windows 10 pro rather than docker-for-windows here. Good luck!

**Comment by Femina** [comment]
It works. Thank you
