### ISSUE TITLE
Failed to launch docker after changing memory setting

### ISSUE THREAD

**Issue by 84monta** [docker/for-win#2815]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
  Automatic  launch failed when windows started
### Information

  - Windows Version:  Windows 10 Pro
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

  1. ... Changed memory configuration from fixed to dynamic
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
