### ISSUE TITLE
proxyconnect tcp: dial tcp: lookup http on 192.168.65.1:53: server misbehaving

### ISSUE THREAD

**Issue by sylvaingirardbe** [docker/for-win#2860]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A4EF00C3-4B25-40C0-B03C-8D130031AA65/20181107211343

### Expected behavior
The hello-world image to be pulled and started.
### Actual behavior
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup http on 192.168.65.1:53: server misbehaving.
### Information

  - Windows Version: Windows 10 1803 17134.376
  - Docker for Windows Version: 18.06.1-ce, build e68fc7a

### Steps to reproduce the behavior

1. docker run hello-world 

The host is sitting behind a proxy which requires authentication. The exact config is in the diagnostics package.

I was trying to attempt to get Docker for Windows configured for this setup and serve as a private repo since the main Docker host is running on Ubuntu 18.04 Server and gives me about the same issues except the error is: proxyconnect tcp: dial tcp: lookup http on 127.0.0.53:53: server misbehaving.

If I'm interpreting the error correctly, it looks as if docker is trying to connect to the dns server through the proxy, which, of course, isn't what needs to happen...

**Comment by sylvaingirardbe** [comment]
I got my issue fixed and it had to do with proxy configuration. I took a hint from [this issue](https://github.com/docker/for-win/issues/894) and went ahead to install cntlm to abstract that proxy config away from docker. Now cntlm proxies everything for docker and docker is simply configured to use 127.0.0.1:3128 as a proxy.

**Comment by LeonardAB** [comment]
Is there any other way to solve this issue without using [cntlm](https://stackoverflow.com/a/47282257/5122657)? 

I also have the same problem but using cntlm seems to be way beyond my current level of knowledge.





  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 07998B46-5C08-4C6E-87D3-9D8EF3669349/20181127092626

### Expected behavior
being able to pull repository from docker

### Actual behavior
`Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup <companyProxy> on 192.168.65.1:53: server misbehaving.`

### Information

  - Windows Version: Win 10 Pro
  - Docker for Windows Version: Docker ver: 18.09.0, build 4d60db4

I'm trying to run docker on windows (OS: Microsoft Windows 10 Pro 64bit, Docker ver: 18.09.0, build 4d60db4), by following the hello-world instruction [here](https://docs.docker.com/v17.09/docker-for-windows/). Then I got a "server misbehaving" error mentioned above.
I tried to change the DNS (in Docker setting - Network - DNS Server) from Automatic to Fixed (8.8.8.8 or 8.8.4.4) as suggested [here](https://github.com/docker/for-mac/issues/1317), but still did not solve the problem, and resulted in another type of error ("timeout exceeded").

`Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).`

I am behind company's proxy, and have set the proxy (and the credentials) both on environment variable and also docker setting. I also tried to reinstall both docker and hyperV but still got the same problem.

Here is the log at the point where I execute `docker pull hello-world:latest` on cmd

```
[09:39:30.083][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy >> GET /_ping\n"
[09:39:30.086][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy << GET /_ping (3.9976ms)\n"
[09:39:30.088][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy >> GET /v1.39/info\n"
[09:39:30.100][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy << GET /v1.39/info (12.0066ms)\n"
[09:39:30.185][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy >> POST /v1.39/images/create?fromImage=hello-world&tag=latest\n"
[09:39:30.196][VpnKit         ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6

[09:39:30.196][VpnKit         ][Info   ] vpnkit.exe: UDP interface connected on 192.168.65.1

[09:39:30.268][ApiProxy       ][Info   ] time="2018-11-27T09:39:30+09:00" msg="proxy << POST /v1.39/images/create?fromImage=hello-world&tag=latest (81.9955ms)\n"
[09:39:33.326][LocalhostForwarder][Info   ] Reconciliation succeeded
[09:39:33.329][WindowsDaemon  ][Info   ] debug: Calling GET /v1.39/containers/json?limit=0
```

### Steps to reproduce the behavior


  1. run Docker on windows, behind company firewall. set DNS to auto (or fixed to your company's DNS). Set proxy on docker setting as well as on your PC environment variable.
  2. use cmd or power shell `docker run hello-world` or `docker pull hello-world:latest`

this question was also posted [here](https://stackoverflow.com/questions/53475168/docker-for-windows-server-misbehaving-when-trying-to-pull)

**Comment by ericjoy1991** [comment]
I am facing similar issue in my Ubuntu 16.04 ...can anyone please help me out with this one?

**Comment by ericjoy1991** [comment]
ISSUES:
/Desktop# sudo docker run hello-world
Unable to find image 'hello-world:latest' locally docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup usrname on 10.200.50.100:53: server misbehaving. See 'docker run --help'.
/Desktop# docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: 123456
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup er370121 on 10.200.50.100:53: server misbehaving

HISTORY:
124 sudo apt update
125 apt-get update && apt-get upgrade -y
126 sudo apt-get install \n apt-transport-https \n ca-certificates \n curl \n gnupg-agent \n software-properties-common
127 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
128 sudo apt-key fingerprint 0EBFCD88
129 lsb_release -cs
130 sudo add-apt-repository \n "deb [arch=amd64] https://download.docker.com/linux/ubuntu \n $(lsb_release -cs) \n stable test nightly"
131 docker --version
132 sudo apt-get update
133 sudo apt-get install docker-ce docker-ce-cli containerd.io
134 apt-cache madison docker-ce

137 sudo apt-get install docker-ce=5:19.03.1~3-0~ubuntu-xenial docker-ce-cli=5:19.03.1~3-0~ubuntu-xenial containerd.io

PROXY with AUTHENTICATION (corporate proxy config details)
/Desktop# cat /etc/apt/apt.conf
Acquire::http::proxy "http://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::https::proxy "https://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::ftp::proxy "ftp://usrname:paswrod@proxy.example.com:8080/"; 
Acquire::socks::proxy "socks://usrname:paswrod@proxy.example.com:8080/";

/Desktop# cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service] Environment="HTTP_PROXY=http://usrname:paswrod@proxy.example.com:8080/" Environment="HTTPS_PROXY=https://usrname:paswrod@proxy.example.com:8080/ Environment="NO_PROXY="localhost,127.0.0.1,::1"

~/.docker# cat config.json
{ "proxies": { "default":
{
 "httpProxy": "http://usrname:paswrod@proxy.example.com:8080",

 "httpsProxy": "https://usrname:paswrod@proxy.example.com:8080",

 "noProxy": "localhost,127.0.0.0/8,*.local,host.docker.internal"
} } }
once PROXY is configured tries out below steps

sudo systemctl daemon-reload
sudo systemctl restart docker.service

Other Details
/.docker# lsb_release -a
No LSB modules are available. Distributor ID: Ubuntu Description: Ubuntu 16.04.6 LTS Release: 16.04 Codename: xenial
:/.docker# docker --version
Docker version 19.03.1, build 74b1e89e8a
:/.docker# uname -a
Linux bc-VirtualBox 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
