### ISSUE TITLE
有人解决window10 的挂载问题吗?

### ISSUE THREAD

**Issue by zhou-xiaobing** [docker/for-win#2864]
_Originally posted by @adminjiang in https://github.com/docker/for-win/issues/125#issuecomment-375852898_

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
