### ISSUE TITLE
Docker Desktop on Windows ignores de-selecting "Start when you log in"

### ISSUE THREAD

**Issue by megadix** [docker/for-win#2950]
- [x] I have tried with the latest version of my channel (Stable or Edge)
- [ ] I have uploaded Diagnostics
- Diagnostics ID:

### Expected behavior

- de-select "Start Docker Desktop when you log in"
- Docker Desktop should not start when I log in

### Actual behavior

- Docker Desktop starts when I log in

### Information

- Windows Version: Win 10 Professional 1803
- Docker for Windows Version:
  - Version 2.0.0.0-win78 (28905)
  - Channel: stable
  - Build: c404a62

### Steps to reproduce the behavior

1. install Docker Desktop for Windows
2. de-select "Start Docker Desktop when you log in"
3. restart Windows

This also happens between updates: in past installations I was able to permanently de-select "Start Docker Desktop when you log in", but each new update reactivates it. This time it seems impossible to deactivate it permanently.

**Comment by giordyb** [comment]
Same problem after updating from 1.x. Is there a registry hack that we can apply in the meantime?

**Comment by DHclly** [comment]
Same here...

**Comment by hho** [comment]
Same here.

Diagnostics ID: EADF1A9D-1F4C-4764-A42F-21197B72C658/20181129110319

**Comment by SkipSailors** [comment]
I have this issue Diagnostics ID: E57B7065-56DE-4549-BD8D-2F6336C904F4/20181203120648

**Comment by edmorley** [comment]
Same using the latest release:

Version 2.0.0.0-win82 (29268)
Channel: edge
Build: e69fe76

**Comment by rlogiacco** [comment]
Same issue here, right now there's a [workaround reported in the community forum](https://forums.docker.com/t/docker-desktop-always-starts-although-disabled/63494)

**Comment by bighe2016** [comment]
Same here...，I use **Task Manager** to disable it.


![image](https://user-images.githubusercontent.com/25766806/50957132-688c9780-14f8-11e9-946d-932accc8dffe.png)

**Comment by jb-asi** [comment]
Checkbox is still non-functional as of:

Version 2.0.1.0 (30090)
Channel: edge
Build: c8b6ca6

**Comment by KingMario** [comment]
Same here. Mac version edge channel

Version 2.0.1.0 (30090)
Channel: edge
Build: c8b6ca6

**Comment by mjordan79** [comment]
I have the same problem, Docker Desktop CE version 2.0.0.2 (30215), Windows 10 version 1809 (build SO 17763.292) - x64 
Channel: stable
Build: 0b030e1

**Comment by rcarmo** [comment]
Same for me (Windows 10, stable build, etc.)

**Comment by reureu** [comment]
It seems that the culprit is the installation package for Windows.
Please see [this forum entry](https://forums.docker.com/t/docker-desktop-always-starts-although-disabled/63494/30).
The installation packages creates an obsolete "Docker for Windows" value in HKCU:\Software\Microsoft\Windows\CurrentVersion\Run\.
This "Docker for Windows" value is no longer controlled by the "Start Docker Desktop when you log in" preference in the Settings panel.
This preference now controls the presence of the "Docker Desktop" registry value under the same key 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run\'

Can the Docker team please remove this erroneous "Docker for Windows" value ?

**Comment by faustool** [comment]
Still not working at Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

**Comment by GeorgeWL** [comment]
how is this still an issue when it was reported all the way back in  2.0.0.0-win78 (28905) version?

**Comment by f-w** [comment]
I second @reureu's conclusion - "Docker for Windows" reg key is the culprit 
![image](https://user-images.githubusercontent.com/12823994/55895319-c7ea5a00-5b70-11e9-8e3f-fedc7cd3ea48.png)

**Comment by spacecat** [comment]
/me don't like having bad value entries in Windows registry!

**Comment by abarberenaCPDS** [comment]
> I second @reureu's conclusion - "Docker for Windows" reg key is the culprit
> Problem still persists in Version 2.0.0.3 (31259) I installed yesterday.

Thx! this seems to be the solution!

**Comment by paulo-bastos-nau-21** [comment]
> Same here...，I use **Task Manager** to disable it.
> 
> ![image](https://user-images.githubusercontent.com/25766806/50957132-688c9780-14f8-11e9-946d-932accc8dffe.png)

In a clean installation (new machine)  Version 2.0.0.3 (31259) was installed an entry in startup (via taskmanger) remains after deselecting the start desktop on log in. If I select it again (after various shutdowns/restarts) a new entry in the startup tab of taskmanager appears.

![Capture](https://user-images.githubusercontent.com/37453357/58013538-b17bda80-7aee-11e9-9e53-9ca166fb9c41.PNG)

**Comment by jaltmanQ** [comment]
Still happening on the version I just upgraded to.

**Comment by mat007** [comment]
@jaltmanQ have you tried toggling the checkbox on and off again?

**Comment by jaltmanQ** [comment]
> 
> 
> @jaltmanQ have you tried toggling the checkbox on and off again?

I did try that without any luck.  Disabling it through the TaskManager however did seem to finally stop it.

**Comment by arkhitekton** [comment]
I have version 2.1.0.3 (38240) / stable.  It was upgraded earlier today from a version that also exhibited this behavior.

I opened the registry editor and I do NOT have a "Docker for Windows" entry in HKCU/Software/Microsoft/Windows/CurrentVersion/Run, however I DO have "Docker Desktop," which runs the command "C:\Program Files\Docker\Docker\Docker Desktop.exe" (there are NO quotes around the value in the registry editor).

When I toggle the setting, and hit Refresh in the Registry editor, there are no changes - no new items appear, no items disappear, and no items' contents change.

While I understand there is a workaround, I think there is value in fixing the root cause instead of just patching it.  So I'm going to leave it broken until you guys figure it out. If you need testing, I'm happy to oblige.

**Comment by braykov** [comment]
It's still here in 2.1.0.5 :-(

**Comment by mat007** [comment]
I believe this has been fixed in Edge 2.1.2.0 released back in September.
If you’re on the Stable channel you will have to wait until the next Stable release which at the moment is planned for mid-December and will include this fix.
I’m very sorry about that.
