### ISSUE TITLE
Can't connect to Windows host from Windows container

### ISSUE THREAD

**Issue by itsuart** [docker/for-win#3033]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B0892ACC-A120-4DCF-8291-D28AF9C868A9/20181205124316

### Expected behavior
Being able to connect to the host from a container.

### Actual behavior
Can't connect to the host from a container. Neither DNS name nor IP address work.

### Information
  - Is it reproducible? Yes.
  - Is the problem new? Don't know, never tried to connect to host from container before.
  - Did the problem appear with an update? Ditto.

  - Docker for Windows Version:
```
Version 2.0.0.0-win81 (29211)
Channel: stable
Build: 4271b9e
```
  - Windows Version:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB4230204
                           [02]: KB4343669
                           [03]: KB4456655
                           [04]: KB4465663
                           [05]: KB4467694
                           [06]: KB4477029
                           [07]: KB4467702
Network Card(s):           4 NIC(s) Installed.
                           [01]: Realtek PCIe GBE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.100
                                 [02]: fe80::d4dd:b895:ed26:86cf
                                 [03]: fd07:8b59:1db5:0:58e7:c733:37fb:63c9
                                 [04]: fd07:8b59:1db5:0:d4dd:b895:ed26:86cf
                                 [05]: fd07:8b59:1db5::100
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    Yes
                                 DHCP Server:     255.255.255.255
                                 IP address(es)
                                 [01]: 172.18.141.145
                                 [02]: fe80::7ddb:967d:1880:9754
                           [03]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (nat)
                                 DHCP Enabled:    Yes
                                 DHCP Server:     255.255.255.255
                                 IP address(es)
                                 [01]: 172.30.128.1
                                 [02]: fe80::b4cb:eb3e:2b42:e4d3
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (DockerNAT)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.0.75.1
                                 [02]: fe80::84d3:5282:a6c6:d305
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```
### Steps to reproduce the behavior

1. Run ```docker run -it microsoft/windowsservercore```
2. Inside container try
```
C:\>nslookup host.docker.internal
Server:  UnKnown
Address:  172.30.128.1

*** UnKnown can't find host.docker.internal: Server failed

C:\>ping host.docker.internal
Ping request could not find host host.docker.internal. Please check the name and try again.

C:\>nslookup 192.168.1.100
Server:  UnKnown
Address:  172.30.128.1

*** UnKnown can't find 192.168.1.100: Server failed
```
where 192.168.1.100 is IP address of the host.

Following excerpt from the log might explain failure of the name resolution:
```
[12:41:37.377][WindowsDaemon  ][Error  ] Error running exec 4ac627026497c36457f776a1755468f5df598a9e23e81fb74c852e5e5b8d2985 in container: container 97e05a1b5b9239dd22a24290fe7ecfb4b7e68d20fb0b035f0fc036e3db6085b4 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"cmd.exe /C \"ECHO 192.168.1.100    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 192.168.1.100    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts\"","User":"Administrator","WorkingDirectory":"/","CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
[12:41:37.377][WindowsDaemon  ][Info   ] debug: attach: stderr: end
```

Thank you for reading! :)

**Comment by itsuart** [comment]
After switching to Linux Containers and back to Windows' ones I can connect to 192.168.1.100.
host.docker.internal still does not resolve though.

**Comment by rodpl** [comment]
It works for nano server but not for windows core

**Comment by MagicShoebox** [comment]
While playing around with something completely different, I found something possibly related.

The host names are injected into the container by this automatically executed docker command (taken from the Windows Event Log with docker daemon debug set to true):
(192.168.XXX.XXX is the host IP)

`debug: exec commandLine: cmd.exe /C "ECHO 192.168.XXX.XXX    host.docker.internal >> %systemroot%\system32\drivers\etc\hosts & ECHO 192.168.XXX.XXX    gateway.docker.internal >> %systemroot%\system32\drivers\etc\hosts" [...]`

The POST call that triggered this command was this:

`debug: form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":["cmd.exe","/C","ECHO 192.168.XXX.XXX    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 192.168.XXX.XXX    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts"],"Detach":false,"DetachKeys":"","Env":null,"Privileged":false,"Tty":false,"User":"Administrator","WorkingDir":""}`

The key part is `"User":"Administrator"`.
**On nanoserver:1803, the built-in Administrator account is enabled with no password and it works fine.
On servercore:1803, the built-in Administrator account is disabled (with a password) and it rejects the command.**

`CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(174)\vmcomputeagent.exe!00007FF7B648C00A: (caller: 00007FF7B645ECEA) Exception(2) tid(36c) 8007052E The user name or password is incorrect.
    CallContext:[\Bridge_ProcessMessage\ComputeSystemManager_ExecuteProcess\VmHostedContainer_ExecuteProcess] 
 Provider: 00000000-0000-0000-0000-000000000000]`

**Steps to reproduce**
docker run --rm -it mcr.microsoft.com/windows/nanoserver:1803
(in container)
type %systemroot%\system32\drivers\etc\hosts
(Notice the hosts are listed correctly)

docker run --rm -it mcr.microsoft.com/windows/servercore:1803
(in container)
type %systemroot%\system32\drivers\etc\hosts
(Notice the hosts are **missing**)

**Strangely, when I tried putting the "type ...hosts" directly after docker run, the hosts were missing from BOTH**
docker run --rm -it mcr.microsoft.com/windows/[flavor]:1803 cmd /C type %systemroot%\system32\drivers\etc\hosts
(Notice the hosts are missing)

Unfortunately, this doesn't seem to actually fix the ping, merely the lookup.

Still, **Docker should probably use "User":"ContainerAdministrator" instead of "User":"Administrator" when adding the hosts**, at least on 1803. Unfortunately I can't test either flavor of 1809 to see if they behave the same way.

As a side note, if anyone wants to get the hosts working on servercore:
```
# escape=`

FROM mcr.microsoft.com/windows/servercore:1803

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Enable-LocalUser Administrator; `
    SecEdit.exe /export /cfg secpol.cfg; `
    (Get-Content secpol.cfg).Replace('PasswordComplexity = 1', 'PasswordComplexity = 0') | `
    Out-File secpol.cfg; `
    SecEdit.exe /configure /db C:\Windows\Security\Local.sdb /cfg secpol.cfg /areas SECURITYPOLICY; `
    Remove-Item secpol.cfg; `
    Set-LocalUser Administrator -Password (New-Object SecureString)
```
