### ISSUE TITLE
error during connect: Post https://192.168.99.100:2376/v1.39/containers/create:

### ISSUE THREAD

**Issue by aniono** [docker/for-win#3041]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 14ED1AE6-ABBA-40D5-956D-6A14593B64B5/20181206083212

### Information

  - Windows Version: Windows 10 Pro 1803(17134.407)
  - Docker for Windows Version: Docker version 18.09.0, build 4d60db4

### Steps to reproduce the behavior

  1. docker run hello-world
  2. C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post https://192.168.99.100:2376/v1.39/containers/create: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by rexnfx** [comment]
I'm having the same problem. I recently updated docker versions. I'm also running bridged network adapter.

**Comment by mat007** [comment]
Do you have a `DOCKER_HOST` environment variable?
If so, remove it and try again.

**Comment by vpnicholls** [comment]
I checked and, yes, I did. It was referencing that IP address. I've removed the environment variable now and rebooted my laptop. I've tried `docker run hello-world` and now get a similar message with a localhost IP address:

`C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post https://127.0.0.1:2376/v1.40/containers/create: dial tcp 127.0.0.1:2376: connectex: No connection could be made because the target machine actively refused it.`

If I run `docker version` I get:

Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get https://127.0.0.1:2376/v1.40/version: dial tcp 127.0.0.1:2376: connectex: No connection could be made because the target machine actively refused it.

So I figure I've got to get the correct IP address and then add it *somewhere*?

**Comment by vpnicholls** [comment]
So, it seems my issue was related to this issue: https://github.com/docker/for-win/issues/741

Removing DOCKER_TLS_VERIFY from my environment variables and then setting "Expose daemon on tcp://localhost:2375" in Docker. Reboot, and the running docker version, I get:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by oter-git** [comment]
Open the port (2375) on the firewall. Worked for me.

**Comment by jdavis-leasehawk** [comment]
`docker-machine regenerate-certs`
worked for me
