### ISSUE TITLE
kubectl installed on path with high priority and old version

### ISSUE THREAD

**Issue by jtnord** [docker/for-win#3049]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

if I have a local kubectl installed I should be able to use that

### Actual behavior

docker4win ships with `kubectl` in `C:\Program Files\Docker\Docker\resources\bin`
the version it ships is old

the installation puts `C:\Program Files\Docker\Docker\resources\bin` second in the system path.  (YES SECOND before c:\windows\system32)...

because it adds it to the system path as a user I am unable to override this using the normal system controls as system path comes before user path.

this means to work with recent clusters (e.g. gke) I need to constantly change my PATH variable in a command prompt, or specify the full path to kubectl.   any other tools that run kubectl will also pick up old versions.

### Information
  - Is it reproducible?

Yes

  - Is the problem new?

probably since k8s support came into docker4win, but at that point the client was probably mostly up to date.

  - Did the problem appear with an update?

N/A
  - A reproducible case if this is a bug, Dockerfiles FTW.

N/A

### Steps to reproduce the behavior

1. as a normal user create `c:\tools` and add it you the USER path. (not SYSTEM path)
2. download kubectl 1.13 and place the binary in `c:\tools`
3. verify the version with `kubectl version`
4. as an admin user install docker4win
5. restart
6. login as normal user
7. verify the version with `kubectl version` and its location with `where kubectl`

**Comment by Banchio** [comment]
Totally agree, PATH environment variable should be treated like when you enter somewhere and find a line. You don't go directly to the beginning of the line but you should put yourselves at the end :)

**Comment by atrauzzi** [comment]
Just encountered this today as well.

There needs to be a better way to allow us to manage our own installation of these tools.

**Comment by timgilbert** [comment]
Another problem with this is that is makes [installation of `kubectl` from scoop](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-windows) impossible, since scoop installs files in the user path and the system path always overrides the user path on Windows.

My preference would be for Docker to not install this executable, or maybe rename its version if the user has disabled the "kubernetes" setting. As a workaround for this I've gone into the `C:\Program Files\Docker\Docker\resources\bin` directory and renamed the binary to `kubectl-docker.exe`, which has seemed to work so far.
