### ISSUE TITLE
Linux container in LCOW has unstable file systems

### ISSUE THREAD

**Issue by craigemery** [docker/for-win#3051]
After enabling experimental features and "switching to Windows containers" I can run Linux containers, but directories in shared volumes that have more than about 520 files cannot be read properly.

  - [x] I have tried with the latest version of my channel (both Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DCE1442C-3E06-41C2-B0EC-45810F011F06/20181207130355

### Expected behavior
Can ls a directory with lots of files
### Actual behavior
ls -laF bid_dir
ls: reading directory 'big_dir/': Input/output error

In any volume that was "imported" to the Linux container, if a directory has more than 520 files then it is not stable or usable.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? not sure, has always been there with LCOW
  - Did the problem appear with an update? No
  - A reproducible case if this is a bug, Dockerfiles FTW.
  - Windows Version: Windows 10 Enterprise 1709 (OS 16299.785)
  - Docker for Windows Version: 2.0.0.0-win82 (29268)

### Steps to reproduce the behavior
A reproducible case, Dockerfiles FTW.

  1. ... Make a directory with 600 files (say C:\big_dir)
  2. ... docker run -it --platform linux -v C:\big_dir:/big_dir ubuntu:latest /bin/bash
  3. \# ls -l /big_dir
ls: reading directory 'big_dir/': Input/output error
total 0

**Comment by djs55** [comment]
I installed the same build (`29268`) and created 600 empty files with a short python program and unfortunately it works for me:
```
PS C:\Users\djs\big_dir> docker run -it --platform linux -v C:\Users\djs\big_dir:/big_dir ubuntu:latest /bin/bash
root@52f72ca0e1bb:/# ls -l /big_dir | wc -l
601
```
I notice you're using Windows 10 1709. A lot of the Windows-Containers-On-Windows and Linux-Containers-On-Windows code is inside the "Host Compute Service" and the "Host Networking Service" which are both part of Windows 10. I suspect the reason it worked for me is because I'm running Windows 1809 (build 17763.134).

I recommend upgrading to Windows 1809 or perhaps installing it onto a temporary machine to check whether it helps or not. If you get a chance to do that, please let me know the results.

Thanks for your report! :)
