### ISSUE TITLE
Hybrid swarm routing mesh not working

### ISSUE THREAD

**Issue by stevenmiller** [docker/for-win#3052]
Howdy!

I have a two node hybrid swarm, with one Ubuntu Linux 18.04 node acting as manager and one Windows 2019 node participating as a worker. We have a sample environment we are testing which are entirely Windows containers. We are able to reach the published port for these services from the Windows node (ex. 10.20.1.121:8888) but we are unable to from the Linux node (ex. 10.20.1.122:8888). Our understanding of the ingress mesh networking is that this should work fairly seamlessly as it will route traffic within the swarm to the correct node.

This issue is also occurring with the swarmpit UI stack we have deployed to the swarm. The UI (10.20.1.122:888) is not able to be reached from the Windows node IP (10.20.1.121:888).

  - [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Services running on one node should be accessible from published port on another node 

### Actual behavior

Published Windows container services are not accessible from linux node and vice versa

### Information

  - Windows Version: Server 2019
  - Docker for Windows Version: 18.09.0
  - Linux Version: Ubuntu 18.04.1 LTS
  - Linux Node Docker Version: 18.09.0

Published services and ports:

![image](https://user-images.githubusercontent.com/9146886/49654381-a7b15f80-fa05-11e8-9d1b-22f3dbeda0e3.png)

Both the environment we have pulled from a private repo and the swarmpit stack exhibit this behavior. I am unable to reach the swarmpit UI from port 888 on the Windows node IP.

### Steps to reproduce the behavior

Here is the stack with our private repo removed:

[teststack.zip](https://github.com/docker/for-win/files/2657687/teststack.zip)

Let me know if I can provide any other info.

**Comment by olljanat** [comment]
@stevenmiller first of I can see that this is your first issue on GitHub so let me say welcome :)

Then some side comments (which you don't need to comment but maybe it is good idea to check them out):
* Some best practices with Windows containers: https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/818
* You can set [default logging driver](https://docs.docker.com/config/containers/logging/configure/) to all Docker hosts so you don't need specify it separately for all containers.
* Environment variable *ASPNETCORE_ENVIRONMENT* gives me hint that your applications are ASP.NET Core based so unless your application really needs something Windows specific features I highly recommend to use Linux version of these images. It sounds bit weird idea but based on my two years experience with Linux and Windows containers I still highly recommend it.
* Kestrel web server which is used by .NET Core have been supported to [publish directly to internet starting from version 2.1](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#when-to-use-kestrel-with-a-reverse-proxy) but I would still recommend to consider configuration where you run example NGINX as reverse proxy front of it and make it running on Linux nodes even if your applications are running on Windows nodes.
* Consider to use Portainer instead of Swarmpit. It example have support for native Windows containers which is missing from Swarmpit and especially their [agent deployment](https://portainer.readthedocs.io/en/stable/agent.html) is very interesting as you can manage Linux and Windows containers from one UI and even connect multiple Swarms to it if needed.
* If you need Windows containers then consider to get Microsoft Premier Support contract (if you don't have it yet).
* Microsoft recommends to [use host mode in production](https://blogs.technet.microsoft.com/virtualization/2017/09/26/dockers-ingress-routing-mesh-available-with-windows-server-version-1709/) 
* You can find me with same nick from Docker and Portainer Slacks if you want hear some real world examples how this stuff works on production.

Then what comes to this issue, IMO your stack file looks to be just like documentation says that how it should work but in real life it looks that Windows implementation of overlay network / components used behind it (example: [hcsshim](https://github.com/Microsoft/hcsshim)) have some undocumented weaknesses.

**Comment by stevenmiller** [comment]
Thanks for the tips! We are revising the apps to run what we can on linux containers. At least one service requires Windows so we are stuck with it for the time being. Is there any further troubleshooting you can advise with this current setup or is likely just an issue we will have to wait out?

**Comment by stevenmiller** [comment]
Just as a note: with my org's Microsoft SA agreement we get support, so I have a technical support case open regarding this issue.  I will update with the resolution (if one is found).

**Comment by olljanat** [comment]
> At least one service requires Windows so we are stuck with it for the time being. Is there any further troubleshooting you can advise with this current setup or is likely just an issue we will have to wait out?

Depending on your application architecture (which apps need to be able to talk which apps) you can example place Windows and Linux containers to same overlay network so they can talk with each others inside of it.



> Just as a note: with my org's Microsoft SA agreement we get support, so I have a technical support case open regarding this issue. I will update with the resolution (if one is found).

OK. It is really interesting to hear if they are solve this issue as my earlier experiences of level of Microsoft support have not been too positive.

**Comment by stevenmiller** [comment]
@olljanat Just FYI I have been going back and forth with a MS support engineer and we've about established that the issue lies with the port translation when it occurs between hosts.

If I deploy a stack with the following config (keeping the default port as the one I expose):
![image](https://user-images.githubusercontent.com/9146886/50246734-22825f00-03a4-11e9-9903-db3e3b303bcc.png)

I am able to reach the default IIS site from both the Windows and Linux node. Obviously it is not ideal but we are making some progress with their support.

**Comment by olljanat** [comment]
Btw is this related to #38484 ?
