### ISSUE TITLE
Custom docker network disappeared after server 2019 reboot

### ISSUE THREAD

**Issue by JoergBrugman** [docker/for-win#3076]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
An created custom docker network will continue to exist after the server is restarted.

### Actual behavior
After rebooting the server, both the custom network and the standard docker network (nat) disappeared. 
Due to this behavior, containers that use the custom network (transparent network) can no longer be started!

### Information

  - Windows Version: Windows Server 2019 Standard (Desktop)
  - Docker for Windows Version: 18.09.0

### Steps to reproduce the behavior

  1. Create a new network (docker network create -d transparent --subnet=192.168.60.0/24 --gateway=192.168.60.1 tlan
  2. Check networks (docker network ls)
  3. Reboot Windows Server 2019
  4. Check networks (docker network ls) --> Networks "nat" and "tlan" disappeared!

**Comment by veepee78** [comment]
I noticed similar behavior. Server installed updates and booted. Docker was unable to restore containers because user created nat network disappeared. I noticed this couple of times but have not done any testing  to replicate it.

**Comment by niklaslundberg** [comment]
I am experiencing the same behavior using Docker EE 18.09.1 on Windows Server 2019.

**Comment by akunaatrium** [comment]
Yes, same for me. What's going on? Docker version 18.09.2.

**Comment by LuomingXu** [comment]
I have the same problem. Docker version 18.09.2, community version, Docker desktop version 2.0.0.3(31259), Windows education 1809(17763.316).

**Comment by akunaatrium** [comment]
Same problem with Docker 18.09.2 on Windows 10 Enterprise (1809, 17763.316).

**Comment by LuomingXu** [comment]
Still, no one has found a way to solve this problem?

**Comment by sandersaares** [comment]
I fixed this by installing Ubuntu and migrating to Linux containers. Might not work for everyone, though.

**Comment by niklaslundberg** [comment]
I have also tried with Docker EE 18.09.3 on Windows Server 2019, same results.

**Comment by akunaatrium** [comment]
This issue renders almost the whole concept of "Docker for Windows" useless. I wonder why nobody from Docker or Microsoft is commenting.

**Comment by daschott** [comment]
Can you try using Docker EE 18.09.3? Does it work?

**Comment by gmenounos** [comment]
I've just verified that this is still an issue in Docker EE 18.09.5 running on Windows Server 2019 Build 17763.379.

**Comment by daschott** [comment]
Thank you @gmenounos! Can you please also share which network type is affected? For transparent network persistence you need https://support.microsoft.com/en-us/help/4482887 or above. For the issue where NAT network's aren't being recreated you need Docker EE 18.09.3.

**Comment by gmenounos** [comment]
It was a NAT network. So, you are saying that I should downgrade from 18.09.5 to 18.09.3 for my NAT network to persist across reboots?

As for transparent network persistence and KB4482887, why is that issue not listed in the "Improvements and Fixes" documentation for the KB?

**Comment by daschott** [comment]
@gmenounos Sometimes KB's don't exhaustively enumerate every single issue that was fixed in the "Fixes" section. This is one such case unfortunately. The KB will not help with the NAT network's not being persisted, only transparent networks specifically.

No, you shouldn't downgrade to Docker EE 18.09.3; you only need Docker EE 18.09.3 or above, so you are good.

NAT networks are not being persisted on Windows Server 2019 by design. Docker creates a default NAT network for you, and recreates it on start of Docker (assuming you have Docker EE 18.09.3 or above). But if you are building your own orchestrator based on the NAT network driver, and creating custom networks you need to recreate the network after restart for containers as well.

**Comment by gmenounos** [comment]
@daschott I'm not building an orchestrator. I just had created a custom NAT network, attached a handful of containers to it and noticed that after a reboot I could not restart the stopped containers because their network no longer existed. I cannot just recreate the network and start the containers because the id of the network changes when it's created after a reboot. I guess I will have to try manually attaching the containers to the new network after creating it and then see if I can start them.

The reason I'm using a custom NAT network is so that I can manually assign IP addresses to the containers. The reason I'm manually assigning IP addresses is that I have IIS running on the container host as a reverse proxy and I could not route requests to the containers by container name as the container host cannot resolve the IP addresses of the containers. It was able to do this in Server 2016 but that seems to have changed in Server 2019. I know I could publish port 80 of each container to a unique port on the container host and have the IIS reverse proxy route incoming requests to those ports on localhost but that I would prefer not to expose the containers directly on the container host's external network.

**Comment by akunaatrium** [comment]
Where is it documented that NAT networks are not persisted by design on Windows Server 2019? This came as a surprise to me right now, especially given the fact that on Ubuntu the custom NAT networks **are** persisted. All deviations in behavior across platforms should be noted somewhere in capital letters along with good justifications (if there already isn't such document).

**Comment by kkbruce** [comment]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/network-drivers-topologies

document write: **"NAT networks created on Windows Server 2019 (or above) are no longer persisted after reboot."**

But he did not explain why.

**Comment by sandersaares** [comment]
Doesn't this make using custom Docker networks completely pointless? I don't get how this could possibly have made it into a released version of Windows.

**Comment by liberdis** [comment]
I am seeing the same behavior on Docker Desktop (Win10 1803 & 1809, haven't checked higher yet)

Also, what on earth rationalizes blowing away a custom network that a user has specified to run their containers with? Really would like to understand the justification for this because simply saying "by design" when the design appears as an inherent disadvantage only fosters confusion and erodes trust in the solution.

**Comment by daschott** [comment]
Container networks of type “NAT” are not persisted on Windows Server 2019 after reboot. That being said, the Docker service is responsible for creating its own default NAT network. This means that after reboot, the default NAT network will be present again after the Docker service has launched again. Containers that were attached to the old NAT network and persist after reboot (e.g. using --restart always flag) should re-attach to the fresh default NAT network and behave/connect exactly the same way as before reboot after Docker service start. If it doesn’t then there is a bug.

Please make sure you're using the latest Docker version as any version below Docker engine 18.09.3 on Windows Server 2019 may have problems since it will use the old logic of container attachment.

The reason why this was done is so that users can expect a fresh and clean environment without any leaking network resources after reboot, which NAT is prone to.

If you want to specify a custom subnet for the default NAT network (e.g. 10.0.0.0/24), you should also be able to set {"fixed-cidr" : "10.0.0.0/24"} in the Docker daemon.json file located under C:\ProgramData\docker\config\daemon.json

If you need another network that needs to be persisted there is also l2bridge network driver which is more performant and widely used in SDN, Kubernetes, etc. and has additional security features like micro-segmentation using network ACLs.

@liberdis @sandersaares @gmenounos  Can you share your use-case for needing multiple custom NAT networks? It would be really helpful as I can pass on the feedback to people that made the persistence decision.

**Comment by sandersaares** [comment]
It is not clear to me what the relationship between "Docker" networks and "Windows" networks is here. From my perspective, I use Docker networks and ignore whatever Windows internal network architecture is used to service the Docker networks - that's strictly between Docker and Windows.

My need is not for *multiple* Docker NAT networks, I only need a single one. The reason I create a custom one instead of using the default is because there were some differences in what the default Docker NAT network supported versus what a custom Docker NAT network supported.

I forget the details of what was different but this is the functionality I use and the difference was somewhere in here:

* I assign specific IP address range to the network.
* I assign specific IP address to the host (as gateway) in this network.
* I assign specific IP address to each service in this network.

Nothing too exotic, I think. I have by now migrated my software to Linux so I do not have up to date information on what exactly prevented me from doing this with the default network. I see some open bugs for fixed-cidr https://github.com/docker/for-win/issues/625 maybe that was it?

**Comment by federicobarera** [comment]
@daschott I am struggling finding up-to-date documentation on networking in Docker for Windows.
Do you have some links with in-depth, up-to-date, information?

eg: why hns nat networks are not listed in Get-NetNAT?

**Comment by SalFicara** [comment]
> Container networks of type “NAT” are not persisted on Windows Server 2019 after reboot. That being said, the Docker service is responsible for creating its own default NAT network. This means that after reboot, the default NAT network will be present again after the Docker service has launched again. Containers that were attached to the old NAT network and persist after reboot (e.g. using --restart always flag) should re-attach to the fresh default NAT network and behave/connect exactly the same way as before reboot after Docker service start. If it doesn’t then there is a bug.
> 
> Please make sure you're using the latest Docker version as any version below Docker engine 18.09.3 on Windows Server 2019 may have problems since it will use the old logic of container attachment.
> 
> The reason why this was done is so that users can expect a fresh and clean environment without any leaking network resources after reboot, which NAT is prone to.
> 
> If you want to specify a custom subnet for the default NAT network (e.g. 10.0.0.0/24), you should also be able to set {"fixed-cidr" : "10.0.0.0/24"} in the Docker daemon.json file located under C:\ProgramData\docker\config\daemon.json
> 
> If you need another network that needs to be persisted there is also l2bridge network driver which is more performant and widely used in SDN, Kubernetes, etc. and has additional security features like micro-segmentation using network ACLs.
> 
I do understand the reasoning however, none of the describe solutions work. l2Bridge is broken, completely not recognize in: 
Docker Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
same goes for transparent. NAT works but is useless since after first reboot it's removed entirely leaving your containers dead in the water. I have bookmarked at least 3 related, open issues I think they even go back an entire year or more. I just don't understand how there isn't a solution yet. To me this seems like a super high priority thing. Stop me dead in my tracks and all my work is potentially wasted without a solution to this. Any news yet on a fix?

**Comment by dlitty** [comment]
I'm having the same issue on Server 2019 with Docker EE 19.03.5, build 2ee0c57608; The reason I had created a custom network was specifically to set the IP range to a specific subnet, because my company uses the default range for other purposes which these containers need access to.  

I attempted using fixed-cidr to set this range on the default network, but it did not work - the subnet was still something else.  According to the documentation, the fixed-cidr also requires you to set "bip"; however, setting that results in an error: "fatal: unable to configure the Docker daemon with file C:\ProgramData\docker\config\daemon.json: the following directives don't match any configuration option: bip"

How can I get around this?  Any workaround ideas would be appreciated.

**Comment by daschott** [comment]
@dlitty after setting fixed-cidr, did you try to restart your machine?

**Comment by dlitty** [comment]
Sorry, yes, after I wrote that I realized it required a restart - it is working now - thank you.

**Comment by tiger5226** [comment]
I referenced this issue in https://github.com/docker/compose/issues/8116 , so that we can have a better default network with docker-compose that retains the capability to function across restarts without having override the default network everytime or defining a custom network every time. Please up vote if you also find it useful.

**Comment by MassimoTambu** [comment]
Taken me half a day, understanding what's going on wrong and then I found this issue.
I am with @tiger5226, this should not be the default behavior.

To solve this problem I have to specify the networks field in the docker-compose.yaml file like this:
`networks:
  default:
    external: true
    name: nat
`

In this way I use the default nat network which remains even after the machine host reboot.


Also I noticied that if you try to create (`docker compose up -d`) two Windows Containers without specify the networks field it will works. **When you try to create the third one**, always with `docker compose up -d` command, **it will enter into some kinda like infinite loop and it will never been create.**
Is this happens only on me?
Tried on Windows 10 Pro, hyper-V on.
