### ISSUE TITLE
Reset to factory defaults in Windows containers mode result in `Error creating default network: HNS failed with error : The parameter is incorrect.`

### ISSUE THREAD

**Issue by jornh** [docker/for-win#309]
### Expected behavior

Reset to factory default should result in a functioning Windows mode

### Actual behavior

`PS C:\Users\jornh> Get-ContainerNetwork` does not return anything

_and_ same error as reported in #304:
```
Docker daemon failed with message:
time="2016-12-09T22:21:46.156110800+01:00" level=info msg="Windows default isolation mode: hyperv" 
time="2016-12-09T22:21:46.158614300+01:00" level=info msg="[graphdriver] using prior storage driver: windowsfilter" 
time="2016-12-09T22:21:46.176623600+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-12-09T22:21:46.176623600+01:00" level=info msg="Loading containers: start." 
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The parameter is incorrect. 


   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: 3FA2B1C7-21C2-429F-A4E5-DFDE352275E1/2016-12-09_22-21-46
  - host distribution and version: Windows 10 Enterprise, D4W build number: `beta32.1 ` build (9324)

### Steps to reproduce the behavior

  1. Install/upgrade to Beta32.1 *with functioning NAT*
  1. My state was that i had no Windows images (don't know if that matters)
  1. In Windows container mode, in the GUI select Reset
  1. => boom

**Comment by S3curityPlu5** [comment]
Reset to factory defaults does not work for me either, I am having a hell of a time getting Docker for windows running again on Windows 10 14393 and also Docker in Windows Server 2016 as well. Always getting: "An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified". . In the windows 10 case, using docker for windows with Hyper-V - used to work, however now service won't start, and have tried resetting to defaults twice now.  Still have only one internal network adapter which is called DockerNat, Very frustrating, spending so much time just trying to get docker working again.  Have no containers,

**Comment by jornh** [comment]
@S3curityPlu5 regarding the pipe connection problem does the Microsoft script or even better the improved version in the PR mentioned in https://github.com/docker/for-win/issues/178#issuecomment-266272334 bring you forward (if you haven't already tried it)?

Ideally, I think "reset to factory" could make the same checks and fixes as the script - or the UI at least give hints to try that script (maybe even offer to run it) - if that's more flexible as long as we are talking beta ...

**Comment by S3curityPlu5** [comment]
OK I am not using the beta, should I uninstall the stable version and switch to the beta?? 
It seems like part of what is happening is that my mobylinux Hyper-V VM is not controllable from docker, as it even fails to shut down when I use Hyper-V manager to shut it down. Running the Debug-ContainerHost.ps1 script yields an empty log file and a message in the console of  unable to configure the Docker daemon with file C:\ProgramData\docker\config\daemon.json.

**Comment by jornh** [comment]
Not beta, so I guess the only thing we have established is that factory reset does not work for your particular case with the stable release branch then. *Maybe* also that the disappearing DockerNat on factory reset is not an issue in stable, just a regression in beta?

@S3curityPlu5 the uncontrollable MobyLinuxVM, and not networking, sounds like your real issue then. For fun I just tried stopping mine in the Hyper-V manager, renamed it, then did a Docker factory reset. It restored a fresh MobyLinuxVM image. After that I was able to `docker run -rm alpine ls`. Maybe worth trying as a last resort for a quick fix?

Off topic related to the original issue #309 reported here:
@S3curityPlu5 your original problem must be related to upgrading to https://docs.docker.com/docker-for-windows/release-notes/#docker-for-windows-1123-2016-11-09-stable then? Maybe better to file a separate issue on that if you are able to somehow describe reproducible steps with e.g. from what version you upgraded etc. That could potentially save problems for others.

Guess its always worth trying the beta (or a clean stable install) if you have no containers and nothing working. It is certainly working fine with Linux containers for me, it's only `docker pull` of Windows containers on Win 10 I'm currently struggling with, but that is already reported in a separate issue.

**Comment by S3curityPlu5** [comment]
Ok it will be moved


Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone
-------- Original message --------From: jornh <notifications@github.com> Date: 12/11/16  12:18 PM  (GMT-05:00) To: docker/for-win <for-win@noreply.github.com> Cc: jgnetworksecurity <james@jgnetworksecurity.com>, Mention <mention@noreply.github.com> Subject: Re: [docker/for-win] Reset to factory defaults in Windows containers mode result in `Error creating default network: HNS failed with error : The parameter is incorrect.` (#309) 
Not beta, so I guess the only thing we have established is that factory reset does not work for your particular case with the stable release branch then. Maybe also that the disappearing DockerNat on factory reset is not an issue in stable, just a regression in beta?
@S3curityPlu5 the uncontrollable MobyLinuxVM, and not networking, sounds like your real issue then. For fun I just tried stopping mine in the Hyper-V manager, renamed it, then did a Docker factory reset. It restored a fresh MobyLinuxVM image. After that I was able to docker run -rm alpine ls. Maybe worth trying as a last resort for a quick fix?
Off topic related to the original issue #309 reported here:

@S3curityPlu5 your original problem must be related to upgrading to https://docs.docker.com/docker-for-windows/release-notes/#docker-for-windows-1123-2016-11-09-stable then? Maybe better to file a separate issue on that if you are able to somehow describe reproducible steps with e.g. from what version you upgraded etc. That could potentially save problems for others.
Guess its always worth trying the beta (or a clean stable install) if you have no containers and nothing working. It is certainly working fine with Linux containers for me, it's only docker pull of Windows containers on Win 10 I'm currently struggling with, but that is already reported in a separate issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-win","title":"docker/for-win","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/docker/for-win"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jornh in #309: Not beta, so I guess the only thing we have established is that factory reset does not work for your particular case with the stable release branch then. *Maybe* also that the disappearing DockerNat on factory reset is not an issue in stable, just a regression in beta?\r\n\r\n@S3curityPlu5 the uncontrollable MobyLinuxVM, and not networking, sounds like your real issue then. For fun I just tried stopping mine in the Hyper-V manager, renamed it, then did a Docker factory reset. It restored a fresh MobyLinuxVM image. After that I was able to `docker run -rm alpine ls`. Maybe worth trying as a last resort for a quick fix?\r\n\r\nOff topic related to the original issue #309 reported here:\r\n@S3curityPlu5 your original problem must be related to upgrading to https://docs.docker.com/docker-for-windows/release-notes/#docker-for-windows-1123-2016-11-09-stable then? Maybe better to file a separate issue on that if you are able to somehow describe reproducible steps with e.g. from what version you upgraded etc. That could potentially save problems for others.\r\n\r\nGuess its always worth trying the beta (or a clean stable install) if you have no containers and nothing working. It is certainly working fine with Linux containers for me, it's only `docker pull` of Windows containers on Win 10 I'm currently struggling with, but that is already reported in a separate issue.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/docker/for-win/issues/309#issuecomment-266294213"}}}

**Comment by simonferquel** [comment]
The 2 issues where different.
I am working on the Windows Containers one.
@jornh Can you give me the results of the following powershell commands (in an elevated powershell command prompt):
`Get-ContainerNetwork` and `Get-NetNat`

**Comment by jornh** [comment]
Sure @simonferquel, and thanks for so quickly looking into this. 

Here is my current state (due to I manually did `New-ContainerNetwork -Name nat -Mode NAT –subnetprefix 10.0.76.0/24` as mentioned in https://github.com/docker/for-win/issues/304#issuecomment-266122685):

```
PS C:\WINDOWS\system32> Get-ContainerNetwork

Name Id                                   Subnets        Mode SourceMac DNSServers DNSSuffix
---- --                                   -------        ---- --------- ---------- ---------
nat  15c9ae2f-17ac-46d6-bc72-2dcda278f5c3 {10.0.76.0/24} NAT


PS C:\WINDOWS\system32> Get-NetNat


Name                             : DockerNAT
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 10.0.0.0/17
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True
```
After performing a Docker factory reset I get:
```
PS C:\WINDOWS\system32> Get-ContainerNetwork
PS C:\WINDOWS\system32> Get-NetNat


Name                             : DockerNAT
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 10.0.0.0/17
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True
```

Not sure if it matters at all - probably not - but seeing 10.x.x.x addresses and ranges above (for the docker related networking) I just wanted to mention that I'm jumping back and forth between a 10.x.x.x. work network and a home network with a 192.168.1.1 default gateway. I think the last Docker install I did was at work and I'm now at home.

**Comment by jornh** [comment]
Followup:

After the factory reset above (done in Linux Containers mode) I did `docker run --rm alpine ls` to confirm Linux containers was working. Switching to Windows Containers resulting in the same error dialog as originally reported (as expected due to the missing ContainerNetwork) - and this new diagnostic id: `3FA2B1C7-21C2-429F-A4E5-DFDE352275E1/2016-12-12_21-03-21`

**Comment by jornh** [comment]
Just tried a factory reset now after update to D4W version `1.13.0-rc4-beta34 `. Looks like the issue is fixed and the `nat` network is now correctly restored.

Steps:
1. Perform factory reset
1. Check via `Get-ContainerNetwork` return a result as below

```
PS C:\WINDOWS\system32> Get-ContainerNetwork

Name Id                                   Subnets           Mode SourceMac DNSServers DNSSuffix
---- --                                   -------           ---- --------- ---------- ---------
nat  4e2882ca-2387-40e5-8aa8-e28188f4ebbe {172.30.112.0/20} NAT
```

Closing the issue. Thanks & merry 🎄 🎅

**Comment by andyliddle** [comment]
I am having this issue on latest stable release
