### ISSUE TITLE
Can't share drive on Windows 10

### ISSUE THREAD

**Issue by isahaulin** [docker/for-win#3198]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: BC7E2274-5FE9-40E0-A864-C607DB6A382B/20190107214612

### Expected behavior
trying to run share C drive in docker Settings

### Actual behavior
Error message: A firewall is blocking file Sharing between Windows and the containers. See documentation for more info.

### Information

  - Windows Version: 10
  - Docker for Windows Version: 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior

  1. ... Already checked the firewall and re-installed Printer as described here:
https://blog.olandese.nl/2017/05/03/solve-docker-for-windows-error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers/
  2. ...

**Comment by jamisonkirk** [comment]
I'm having the same, exact problem. With that said, I don't have access to uninstall/install File and Print Sharing but I have unchecked, Saved, checked the box for it for DockerNat. From what I've read that does essentially the same thing since it unbinds and binds the service. I'm dead in the water and my IT support want me to reinstall Docker. No simple task as I'm thinking that a more meaningful "reinstall" would be to recreate the VM in Hyper-V. As you can guess I'm not inclined to go through with that as I don't think it will solve the problem. MacBook here I come...

**Comment by rmNyro** [comment]
Seems like the issue is still present, just no one get a clue about it I guess. : /
Even in Windows 10 pro last update 1903 (build v18362.356).
