### ISSUE TITLE
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full

### ISSUE THREAD

**Issue by ahoka** [docker/for-win#320]
### Expected behavior
Normal operation or meaningful error message.
### Actual behavior
Lost network access to some of the containers (but not all), docker ps fails with error message:
Error response from daemon: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
### Information

Diagnostic ID:
9DE458B7-12ED-4FC1-9313-0E2A381143FF/2016-12-14_12-25-04

Host version:
Microsoft Windows [Version 10.0.14393]

### Steps to reproduce the behavior

Running a fair amount of containers, around 20-25, with light internal load.

**Comment by ahoka** [comment]
Restarting docker seems to be a good workaround.

**Comment by dgageot** [comment]
Hi @ahoka Can we close the issue then or are you facing this issue often?

**Comment by ahoka** [comment]
What additional info do you need?

**Comment by rneugeba** [comment]
@ahoka I had a look at your logs and there is nothing conclusive. 

The error comes from from here:
```
[11:23:40.438][ApiProxy       ][Info   ] Dial Hyper-V socket 2b8eaf44-cd35-4bf0-b677-6891ae244767:23a432c2-537a-4291-bcb5-d62504644739
[11:23:40.442][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 2b8eaf44-cd35-4bf0-b677-6891ae244767:23a432c2-537a-4291-bcb5-d62504644739
[11:38:13.449][SegmentApi     ][Info   ] Usage statistic: heartbeat
[12:22:08.646][ApiProxy       ][Info   ] proxy >> GET /v1.24/containers/json
[12:22:08.669][ApiProxy       ][Info   ] Dial Hyper-V socket 2b8eaf44-cd35-4bf0-b677-6891ae244767:23a432c2-537a-4291-bcb5-d62504644739
[12:22:08.703][ApiProxy       ][Info   ] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
```

The error code is this [WSAENOBUFS 10055](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx) and likely comes from the Hyper-V socket implementation.

I notice you are on Windows build `14393.0`. There are have been several important updates and bug fixes to that build. Not sure this is relevant, but worth updating if you can.

I would also normally suggest to try the Beta channel as this has an updated Linux kernel with some significant changes and updated to the Hyper-V socket implementation on the Linux side, however, there are some known issues with Hyper-V in Windows build you are on and the 4.8 Linux kernel used in the Beta channel (https://github.com/docker/for-win/issues/274), but it's worth try.

**Comment by ahoka** [comment]
Thanks for the RCA. I haven't encountered this problem again, so you can close the issue.

**Comment by micdah** [comment]
I seem to be experiencing this (or a similar) issue.

Diagnostic ID: 30667474-C49F-4185-B957-3A7AE1F38393/2017-01-23_11-19-16

I am running fairly few containers (only running 4 containers), but I am putting a high load on one particular (mssql-server-linux) running about 10 services on the host machine as well as a handfull of websites and API's all pulling from the mssql container.

**Comment by parha** [comment]
I seem to be experiencing this (or a similar) issue.
Diagnostic ID: DD0B897E-F560-41B6-B1E8-D4D0675B2E39/2017-02-10_10-12-16

**Comment by BringerOD** [comment]
+1 

I am experiencing this issue as well.  I am on the latest OS and Docker for windows.

**Comment by dvlsg** [comment]
Having the same issue with the latest update. The issue occurred after a full computer reboot.

Diagnostic ID: 1AB0DE4F-CCDE-4719-A361-1A2678C3C27A/2017-04-26_09-22-18
* Windows 10 x64
* Docker Version 17.03.1-ce-win5 (10743)

Restarting docker seems to fix the issue for me as well.

**Comment by tobias-kuendig** [comment]
I can confirm this issue. Having it after docker is running for a few days. Some containers are still responding, others are completely offline.

Diagnostic ID: 3A9706C4-8F98-4B7C-A5D0-7B6A53327748/2017-06-15_07-01-16

```
Version: 17.06.0-rc2-ce-win14 (12510)
Channel: edge
Sha1: e4067577a34951ceb09b9e7d029cbdff2ca0ffb4
Started on: 2017/06/09 10:23:48.460
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
```

**Comment by whitecolor** [comment]
An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

Diagnostic ID: 7D3B6C3A-9617-4CD7-8513-C98A06C313AE/2017-06-17_02-26-15

@dgageot reopen and investigate please

**Comment by whitecolor** [comment]
BTW I followed advice [in this article](https://support.microsoft.com/en-us/help/196271/when-you-try-to-connect-from-tcp-ports-greater-than-5000-you-receive-the-error-wsaenobufs-10055) (linked from [this](https://blogs.msdn.microsoft.com/sql_protocols/2009/03/09/understanding-the-error-an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-sufficient-buffer-space-or-because-a-queue-was-full/)

The default maximum number of ephemeral TCP ports is 5000 in the products that are included in the "Applies to" section. A new parameter has been added in these products. To increase the maximum number of ephemeral ports, follow these steps:

- Start Registry Editor.
- Locate the following subkey in the registry, and then click Parameters:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
- On the Edit menu, click New, and then add the following registry entry:
Value Name: MaxUserPort
Value Type: DWORD
Value data: 65534
Valid Range: 5000-65534 (decimal)
Default: 0x1388 (5000 decimal) 

At least after this docker started even without machine restart.

**Comment by IoTFier** [comment]
Having the same issue with the latest update.

A diagnostic was uploaded (before restarting docker) with id: CA5C10D3-2322-4065-B4E3-30B231C9718A/2017-12-29_09-31-15

Windows 10 Pro x64
Docker Version 17.09.1-ce-win42 (14687) | Channel: stable | 3176a6a

Restarting docker did help, but not a motivating experience to build a confidence in the application delivery using Docker for Windows.

Thanks

**Comment by AndreLouisCaron** [comment]
I just ran into this issue.  I tried rebooting the "Docker for Windows Service" from the Windows service control manager.

I see a crash in the Windows Event Viewer that matches the time at which I shut down the service:

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2018-03-13T19:27:29.805008700Z" /> 
  <EventRecordID>7587</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="996" ThreadID="23632" /> 
  <Channel>System</Channel> 
  <Computer>MTL-BH224.ubisoft.org</Computer> 
  <Security /> 
</System>
<EventData>
  <Data Name="param1">Docker for Windows Service</Data> 
  <Data Name="param2">1</Data> 
  <Binary>63006F006D002E0064006F0063006B00650072002E0073006500720076006900630065000000</Binary> 
</EventData>
</Event>
```

Ther service rebooted successfully, but `docker ps` now spits this error message:
```
$ docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Comment by ahmadalli** [comment]
why is this issue closed @dgageot

**Comment by aftabnaveed** [comment]
I am also getting the same error:

```
Error response from daemon: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144
```
The only way to make it work again was to reset it to the Factor Defaults.

**Comment by lanzkron** [comment]
Ditto C0E0B938-B361-43E8-90AA-5F34568953A8/2018-06-25_10-27-22

**Comment by TheSimpleZ** [comment]
I also just experienced the same issue. 34619F3D-3A33-4AC4-BC23-19BAFAF640BA/2018-07-04_13-53-54

**Comment by aftabnaveed** [comment]
No one from the Docker For Win team seems to be bothered about this issue :(

**Comment by hcaicedo** [comment]
I also just experienced the same issue 0F9EF870-22C7-4B40-A718-4CD9933072B8/20180806081344

**Comment by MariusBidireac** [comment]
I have the same problem: 78F48B3E-5CB7-4611-9D97-38ECF142ADA2/20180912164107

**Comment by dc995** [comment]
I have to restart docker service to do anything again.  
Before restart:
C:\Users\davidcra>docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
Error response from daemon: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.

After:
C:\Users\davidcra>docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by jvasekpn** [comment]
I experience this error every day (sometimes multiple times per day).  When the problem happens vpnkit.exe begins constantly using an entire CPU core (kernal-mode operations as denoted by process explorer).  I have to restart docker in order to get it working again which means that all my containers are killed and sometimes data is lost during this process or it completely destroys databases that were running and they need to be wiped and initialized again (a huge PITA when that happens).

I am running a minimum of 18 containers at once and sometimes up to 30.

**Comment by zolthan** [comment]
I also have this issue. Today after running docker desktop for about 1 hour! Why is this issue closed? The solution can't be to restart docker desktop... thats a rather "Windows"y solution...

**Comment by comeUpWithItLater** [comment]
Microsoft's explanation   https://answers.microsoft.com/en-us/windows/forum/windows_7-networking/an-operation-on-a-socket-could-not-be-performed/5e8e321e-53bc-44bf-9aec-1f945da00c07

**Comment by gordonwatts** [comment]
Going to add a me-too here. Sometimes this happens to me after running only one container for, perhaps, 10 minutes. And the container is quiet (a web server which is doing very little).

BTW, the container itself is still responding to web request. Just the ability to contact the docker deamon has died.

**Comment by STaRDoGG** [comment]
Tack me onto the list.

I notice this happens when I download a torrent with qBittorrent.

Win 10x64, and the latest Docker Desktop.
