### ISSUE TITLE
Docker fails to mount volumes after a Windows password change

### ISSUE THREAD

**Issue by aarongoldenthal** [docker/for-win#3290]
### Expected behavior

Docker should prompt for new password to access shared drives after a system password change.

### Actual behavior
Docker starts after system restart and service runs, but trying to mount a volume results in: "Error response from daemon: error while creating mount source path '<path>'".  Right clicking on Docker icon in system tray causes the client to crash and can't change/see any settings.  Docker containers with no volume mounts do still run.

### Information

This is a duplicate of #1712, which is stuck in "lifecycle/frozen".  I didn't try the workaround described there (didn't know about the issue until afterwards), but even changing the password back and rebooting did not fix the issue.  Uninstalling/reinstalling Docker did resolve the issue.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3943FED3-E8B8-4377-BF17-B5C25621D49D/20190126141342

  - Windows Version: Windows 10 Pro Version 1809 (OS Build 17763.253)
  - Docker for Windows Version: 
```
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

### Steps to reproduce the behavior

  1. Change Windows password
  2. Run a container with a volume mount or right click on Docker icon in system tray

**Comment by marcosjmfilho** [comment]
One solution might be this:
https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051#43904051

**Comment by aarongoldenthal** [comment]
I did look at that, but the workaround in #1712 does work (turn of drive sharing, change password, re-enable sharing) without any firewall or Hyper-V changes.

**Comment by bacon1986** [comment]
I just had this same issue but it manifested differently.

I have a docker compose volume `- ./configs/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro`
After a password change this didn't display any docker errors it just created "/docker-entrypoint-initdb.d/mongo-init.js" as a directory rather than a file causing an error from mongo `[main] directory [/docker-entrypoint-initdb.d/mongo-init.js] doesn't have any *.js files`

[Docker Mongo Log Issue.txt](https://github.com/docker/for-win/files/2888722/Docker.Mongo.Log.Issue.txt)

The fix for this for me was to right click the docker icon, choose settings, shared drives, un-tick "C" and apply. Re-running docker compose then re-prompted for permission to set up the share and re-prompted for the username and password.

**Comment by FluffierThanThou** [comment]
Just ran into the same issue after a password change. 

Docker should raise an error after losing drive permissions, instead of silently failing.

**Comment by belucha** [comment]
I had simulair issues mounting the local drive like
```batch
docker run -it -v %cd%:/documents/ asciidoctor/docker-asciidoctor
```
mounts an empty directory without any error message. This happend after I changed my windows password.

The problem was easy to resolve in the settings dialog, by pressing "Reset creditentials" in Drive sharing tab.

What I was missing is any kind of error message, that the folder could not be mounted due to access problems.

So a message like:
"Unable to access shared drive, invalid creditentials!"
would be extremly helpful.

**Comment by GliderGeek** [comment]
I completely agree: its easily fixable, but annoying to debug. Today was the second (or third?) time that i took at least an hour to research why the volumes were not mounted on a client pc. when asked what changed since the last time it worked correctly, they always say 'nothing' as they would never guess that changing their password might have any influence.

it would be great if there would be a clear error message / popup for crendentials.

in the meantime: anyone know of a way to detect this as a possible error?

**Comment by markus-ksg** [comment]
Now that #1712 is open with lifecycle/frozen again, there's no reason for this bug to exist any more. Please close as duplicate of #1712.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
