### ISSUE TITLE
 Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9092:tcp:172.17.0.2:9092: input/output error.

### ISSUE THREAD

**Issue by Tsakirogf** [docker/for-win#3338]
I am trying to install sonarqube in a docker container
I used  :
`docker pull sonarqube`
and ran : `docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube`
### Expected behavior 
It is supposed a new sonarcube server will be added.
### Actual behavior
I got error:

> Error response from daemon: driver failed programming external connectivity on endpoint sonarqube (58c77758f0e9b4f1013b5a2e3ceed5b99eef0e1003ee75a734fbb07d0e89f28a): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9092:tcp:172.17.0.2:9092: input/output error.

### Information

  - Windows Version:Windows 10
  - Docker for Windows Version: 2.0.0.2

### Steps to reproduce the behavior

  1. ...docker pull sonarqube
  2. ...docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube

***

> $ ./PortQry.exe -n 127.0.0.1 -p tcp -e 9092
> Querying target system called:
> Attempting to resolve IP address to a name...
> IP address resolved to 18423-ftsakirog.mwe.local
> querying...
> TCP port 9092 (unknown service): NOT LISTENING

**Comment by wtask** [comment]
Same here. Restarting docker helps. Also when I remove port publishing option from command, container starting without errors...

**Comment by stormmuller** [comment]
I just got a similar issue. Rebuilding and running the images didn't help. As @wtask mentioned restarting docker helped. Still it's not great...

**Comment by mrliptontea** [comment]
I got the same issue, now on version 2.0.0.3 (31259), channel: stable, build: 8858db3, but had it on many versions before.

I found a number of duplicate issues here on GitHub but most do not describe the problem well and many of them are closed due to being stale/inactive.

The issue seems to be with the networking, i.e. containers that do not expose any ports work as expected, but those that do fail to launch.

Restarting Docker manually helps. Also, it doesn't matter if Docker autostarts after system startup or is manually launched at a later time. I also noticed that Docker boots much quicker (just a couple seconds) when the issue occurs, compared to the correct boot up (couple dozen of seconds).

Another thing is that I have this issue now on two different PCs but didn't have on one. All run Windows 10 Pro except the one where I didn't have the issues was upgraded from Windows 7 whereas the others had 10 freshly installed.

**Comment by Yahuu261** [comment]
I also ran into the same issues.
It seems the reason is a new feature brought with a new Windows Update. Turning of the Fast Startup option in Windows solved this issue for me. 

See this stackoverflow thread for more information: https://stackoverflow.com/a/49564445

**Comment by pfuntner** [comment]
I was experiencing this with Docker Desktop 2.0.0.3.  Restarting Desktop and removing the old containers seemed to resolve the problem.

**Comment by l0gicgate** [comment]
I'm experiencing this same issue. Running version 2.0.5.0 (35318).

I haven't tried @Yahuu261's solution yet. But that seems like a regression and shouldn't be an accepted solution.

**Comment by mrliptontea** [comment]
@pfuntner @l0gicgate I turned off Fast Startup option and never looked back. It didn't really affect the startup time but I haven't had any issues with Docker since.

**Comment by niclarcipretti** [comment]
I'm trying the fast startup solution here too. I'll reply this post in a week or two with the results.

**Comment by cmcarey** [comment]
/should/ be fixed https://github.com/docker/for-win/issues/2722#issuecomment-514530476
