### ISSUE TITLE
Docker for Desktop crashes when the password is changed

### ISSUE THREAD

**Issue by oldium** [docker/for-win#3365]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:C2168876-14FE-47A0-ABCE-0C1EF4EF6C80/20190208174535

### Expected behavior
Docker for Desktop does not crash when changing password on cloud.docker.com.

### Actual behavior
Docker for Desktop crashes.

### Information
I have just changed my password on the hub.docker.org site, tried to open Docker from tray, but it crashed.

  - Windows Version: 10, build 18329
  - Docker for Windows Version: 2.0.0.2 (30215)

### Steps to reproduce the behavior
  1. Change password on cloud.docker.com
  2. Open Docker from tray

**Comment by pebbie** [comment]
I got frustrated because not just crashed, Docker desktop won't start at all. The only workaround I did was manually go to Docker installation directory and call 

`resources\bin\docker-credential-wincred list`

which will show a JSON string with the ServerURL as a key and use this key (in my case it was `https://index.docker.io/v1/`) into the next command to erase the credential information

`resources\bin\docker-credential-wincred erase`

and type the `ServerURL` value manually (Ctrl-Z to finish)

Afterward you can start docker desktop again and re-login from the command-line (`docker login`)

**Comment by oldium** [comment]
If I remember correctly, I resolved it by restarting a computer - I was asked to enter the password.

**Comment by mikeparker** [comment]
I can't reproduce this. I've successfully changed my password on hub whilst logged in and docker desktop correctly logs me out. 

We had another report around docker desktop not having the account privileges required, so I'm going to look into that. Meanwhile, could you try running Docker Desktop as Admin, and see if this fixes the issue?

**Comment by mikeparker** [comment]
This is fixed on latest stable.
