### ISSUE TITLE
Impossible to change memory size

### ISSUE THREAD

**Issue by lakeba-solutions** [docker/for-win#342]
### Expected behavior
Change memory size
### Actual behavior
Grey out Advanced page
### Information
Docker for Windows Beta on Windows 10

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Start docker
  2. Settings
  3. Advanced

All is grey out, no way to change the memory size and CPU number.

**Comment by friism** [comment]
That suggests Docker is not up and running yet. Can you run containers? Please upload a diagnostic dump, if possible.

**Comment by lakeba-solutions** [comment]
All solved with the nightly update.

**Comment by friism** [comment]
@lakeba-solutions awesome, thanks for following up.

**Comment by shadercode** [comment]
Hello, I am running containers, but I am limited to 2 CPUs and 2 GB Ram as well.  I am using docker for windows beta, installed using the msi package from [this](url) page.  I would like to use the build in which this problem was fixed.  What are my options for obtaining this?  I am guessing you don't rebuild a msi package nightly, so will I have to build it locally and install it some other way?  Thank you.
