### ISSUE TITLE
some files cannot be accessed/removed in shared volumes (host+container): access denied

### ISSUE THREAD

**Issue by ckiddo74** [docker/for-win#343]
I have been using docker for windows 10 for a while, and it is working fine except for a tiny problem. There are occasions when some files cannot be accessed or removed in shared volumes. When this happens, I cannot remove the file neither from the container nor from the host. On the host side, it gives me the error that I do not have security access to said file (I do). There are no processes locking these rogue files from either side.  The only way I can remove these files is by shutting off docker. 

My feeling is that this is a CIFS problem: it somehow locks these files, and prevents containers and the host from accessing them. Unfortunately, stopping the containers is enough - I need to shutdown off docker, to have access to those files again.  I am currently on the latest version of docker (stable version). It is very difficult to reproduce this problem. However, it would be great if there was a way to avoid this problem, or a faster workaround than restarting docker and the containers.

I am using Phusion's 14.04-based container. The problem got worse with Docker version 1.12.5 (latest version) which I updated yesterday. Will revert back to the previous version.

**Comment by rneugeba** [comment]
@ckiddo74 would it be possible to provide steps to reproduce the issue?  When it happens, do you still have containers running? What does `docker ps -a` say, what does `docker inspect` of the containers say?

**Comment by rneugeba** [comment]
Closing this issue due to lack of response. Please re-open if you have some steps to reproduce this issue or other additional information

**Comment by juhap** [comment]
I've been running into the similar issue on Windows 10, but it seems to be random and I can't reproduce it. Even after stopping the containers and restarting Docker, some files that have been used in the container (via volumes) remain locked and cannot be removed. 

This is quite likely related to the Windows sharing, since I was able to resolve my last incidents via Computer Management/Shared Folders/Sessions, selecting the only session my user had open and closing it manually (got the idea from here: https://stackoverflow.com/a/23148756/350615)
