### ISSUE TITLE
Mounted volumes are empty

### ISSUE THREAD

**Issue by dimitar-nikovski** [docker/for-win#3499]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D3BC213F-5014-44C7-8D2B-79F890E365A5/20190304091006

### Expected behavior

Mounting volumes from a local hard drive should result in the files in the volumes being present and mounted in the respective directories mapped inside the container.

### Actual behavior

Mounted volume paths inside the container are empty. In the past, when I restart Docker desktop, most of the time, the problem is fixed and when I start the container again, the volumes are mounted correctly. But as of reporting, neither restarting docker or rebooting helps. 
The container is an apline image of redis and it's started with the --rm option. So I start it manually when I need to for local development.

### Information

  - Windows Version: 17763.316
  - Docker for Windows Version: 2.0.0.3 (31259) stable
  - Build 8858db3

### Steps to reproduce the behavior
Unknown, the process for me is just to boot the OS, Docker is running when I do that and the issue is always there.

**Comment by diomac** [comment]
Same behavior after update Windows for version 17763.316. My all works is stopped :(

**Comment by dimitar-nikovski** [comment]
After un-sharing and re-sharing the drive and a reboot the volumes are now mounted correctly. I will leave this issue open, because it should just work on a first boot & not require a Docker restart and throw some errors if the volumes are empty.

**Comment by Y2zz** [comment]
Can solve `docker-compose restart`

**Comment by shinomathew** [comment]
I had the same problem ever since upgrading to **_Docker Desktop version 2.0.0.2 (31259)_**. I am unsure which version I was upgraded from, but I can confirm that I didn't have issue with **_Docker Community Edition 18.06.0-ce-win72 2018-07-26_**.
Basically, the volumes I mount from host to the container appears to to be empty in the container, but the host volumes are NOT. This isn't just a problem with my container, but other containers as well (I tried mounting with ubuntu image, the mounted volumes appeared empty within the container)
After some googling, I reset my windows local administrator's password to NOT have any special characters (my password had special characters).

**Comment by witi83** [comment]
To fix this issue you have to go to the docker settings dialog -> Shared Drives -> Reset credentials. You may also need to uncheck your shared drives before resetting
