### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by KoichiSenada** [docker/for-win#3501]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 36B6D584-1AB7-4D02-ADA7-7120F88B6952/20190304194445

### Expected behavior

It is expected that once Docker Desktop is installed on Windows, the hello-world sample should run with the default settings. It is also expected that known problems with that should be published on https://docs.docker.com/docker-for-windows/troubleshoot/

### Actual behavior

1. Download Docker Desktop from https://hub.docker.com/editions/community/docker-ce-desktop-windows
2. Install Docker Desktop
3. Reboot the computer
4. Run the Powershell as adminstrator and execute the "docker run hello-world" command.

> PS C:\WINDOWS\system32> docker run hello-world
> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://localhost:2375/v1.39/containers/create: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.
> See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

5. Check the https://docs.docker.com/docker-for-windows/troubleshoot/
It says nothing related.

6. Open Docker Settings -> General, then enable the "Expose daemon on tcp://localhost:2375 without TLS"
7. Run the same "docker run hello-world" command again.

> Hello from Docker!
> This message shows that your installation appears to be working correctly.

### Information

  - Windows Version: Windows 10 x64 (Microsoft Windows NT 10.0.17763.0)
  - Docker for Windows Version: Docker version 18.09.2, build 6247962

The problem is that the default configuration for Docker Desktop is not compatible with the hello-world example, and there is no related explanation on the troubleshooting page.

### Steps to reproduce the behavior

  1. Download and install Docker Desktop
  2. Run the "docker run hello-world" command with the default settings (daemon exposing for legacy clients is disabled)

**Comment by ebriney** [comment]
Hi @KoichiSenada, docker cli should use named pipe endpoint and not localhost. So perhaps you have `DOCKER_HOST` set, just unset all `DOCKER_*` envs.

**Comment by KoichiSenada** [comment]
> Hi @KoichiSenada, docker cli should use named pipe endpoint and not localhost. So perhaps you have `DOCKER_HOST` set, just unset all `DOCKER_*` envs.

@ebriney , indeed, the `DOCKER_HOST` environment variable was set to http://localhost:2375
I have removed that variable and the `docker run hello-world` works fine since then, even without exposing the daemon on tcp://localhost:2375 without TLS.

But how is all that related?
Why does that variable break it?

**Comment by nbv2222** [comment]
Check "Expose daemon on....." in general settings in docker desktop

**Comment by amit-verma911** [comment]
Hi Guys,

I have been facing a similar issue where in when I try to start my Docker Quickstart terminal, and put in the first command (for eg docker run hello-world) i get the below error : 


$ docker run hello-world
C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post https://localhost:2375/v1.40/containers/create: dial tcp [::1]:2375: connectex: No connection could be made because the target machine actively refused it.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

So, I did some digging and found this and Ibelieve this occurs when your VM is inactive.
Here's how I remedied the situation

docker-machine rm default
after it's cleaned up you can create a new default machine (assuming you haven't heavily modified it, then you'll probably want to script/automate that with packer/terraform etc)

docker-machine create default --driver virtualbox
eval $(docker-machine env default)
