### ISSUE TITLE
Network fails after connection to VPN.

### ISSUE THREAD

**Issue by kimhmadsen** [docker/for-win#3561]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 7D3894A4-3A56-4F80-B565-39FDD9E7F4BC/20190313112215

### Expected behavior

I expected to be able to reach the network outside the container.  
This is possible before connecting to VPN. 
The network is working fine outside the container/docker. 

### Actual behavior

```
C:\Users\khm>docker run --rm -it ubuntu:18.04
root@ad8426d33eb3:/# apt update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Information

  - The problem is reproducible when connected to VPN. 
  - I have also tried to restart docker for Windows after I connected to VPN, but the problem is still present.
  - Windows Version: Windows 10 version 1803 (build 17134.648)
  - Docker for Windows Version: 2.0.0.3 (31259) 

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Connect to company VPN
  3. Try to reach the network outside the container.

**Comment by jeethridge** [comment]
I suspect I am experiencing a similar problem. I move around with my notebook a lot. I generally keep docker running as there are several containerized tools I use which need to connect to remote hosts. I'm finding that I frequently need to run the [WindowsContainerNetworking-LoggingAndCleanupAide.ps1 script ](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking) because external network connectivity stops working from containers. So far my best guess is that changing networks or hopping on/off VPN is related to the cause.
