### ISSUE TITLE
Use nightly build and retain ability to use Linux containers on Windows

### ISSUE THREAD

**Issue by shadercode** [docker/for-win#357]
Is it possible to install from a nightly build, but still retain the functionality that allows one to use linux containers on Windows?

A known [issue ](https://github.com/docker/for-win/issues/342) prevents changing settings for Linux containers, but this has been resolved and is available as a nightly update.  However, the only way to run linux containers on Windows seems to be to install using the msi package for the [beta release](https://docs.docker.com/docker-for-windows/).  The nightly updates don't appear to come with the same functionality.  I installed docker-1.14 and the only executables are docker.exe and dockerd.exe.  There is no dockerCLI, nor any GUI for changing settings.  That installation doesn't appear to work with linux containers.  (It fails due to file naming problems, since linux is case-sensitive.)

### Information
 - This is in reference to closed issue [# 342 Impossible to change memory size](https://github.com/docker/for-win/issues/342)
  - Host distribution and version: Windows 10 Professional version 1607, build 14393.576
  - Diagnostic ID: BE81BB37-ADB8-4C24-BE87-A6863092A5C1/2016-12-26_13-48-04

Thank you very much.

**Comment by rneugeba** [comment]
@shadercode I'm not sure I understand your request.

- Docker for Windows/Mac currently does not have nightly builds but we ship updated Beta's almost every week. For the Betas we typically use the latest RC from engine. For the stable channel we only ship released version of docker engine (and provide updates if engine is updated)
- There are nightly builds from docker engine, but the issue you refer to was an issue with the UI and would have not been fixed by the nightly docker engine build.

Related to #342 we did have an issue that sometimes the advanced settings in the UI were greyed out. This was fixed in Beta35, which we shipped yesterday.

I'm closing this issue, but if I misunderstood the request, please comment.

Thanks

**Comment by shahriarhossain** [comment]
@rn : I am using 18.06.1-ce version and looks like I am still facing the same issue. I need to change the memory size as without that I am unable to start linux container, its keep complaining about memory issue.
