### ISSUE TITLE
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.  Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by BrianDeJesus** [docker/for-win#3577]
### Expected behavior
Launch Docker
### Actual behavior
Unable to start
### Information

  - Windows Version: 10.0.14393
  - Docker for Windows Version: 2.0.0.3
### Steps to reproduce the behavior

  1. Download Docker on Windows Server 2016 (Virtual Machine)
  2. Launch Docker Desktop
  2b. If I run Docker with Admin powershell, I get : 
   Program 'docker.exe' failed to run: Access is deniedAt line:1 char:1

**Comment by jagraj** [comment]
@BrianDeJesus 
I did hit similar problem and opened this issue and I  got mine working with this workaround posted here. Please give it a try and see if this resolves your problem as well.

https://github.com/docker/for-win/issues/3597#issuecomment-474949164

**Comment by techvimal** [comment]
This might help,

1, Open "Window Security"
2, Open "App & Browser control"
3, Click "Exploit protection settings" at the bottom
4, Switch to "Program settings" tab
5, Locate "C:\WINDOWS\System32\vmcompute.exe" in the list and expand it
6, Click "Edit"
7, Scroll down to "Code flow guard (CFG)" and uncheck "Override system settings"
8, Start vmcompute from powershell "net start vmcompute"

**Comment by edjostenes** [comment]
Hi guys!

I solved my problem openning the Hyper-V and applying the right directory for my HD and Conf folders. To check if it's your problem as well, please follow the steps:

1 - Open Hyper-V
2 - Right-click on the virtual machine (if you have it already created)
3 - Click on Hyper-V settings
4 - Check the "Virtual Hard Disk" and "Virtual Machine" directories.

I started to have this issue after trying to change my files to another directory.

**Comment by mikeparker** [comment]
Hi, this error looks like its caused by running nested virtualisation, i.e. running Docker Desktop on windows running inside a virtual machine.

For anyone that has got this working (e.g. using the Code Flow Guard fix), could you let me know which virtual machine type / provider this worked for? E.g. AWS, VirtualBox..

I would also be interested in hearing if anyone saw this error NOT using a virtual machine windows.

**Comment by joelabrahamsson** [comment]
I'm also having this issue. Running Windows 10 on Parallels on OS X. Sadly the The Code Flow Guard fix did **not** work.

Stack trace below:

`
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()`

**Comment by joelabrahamsson** [comment]
In case anyone running Parallels stumbles upon this thread: enabling nested virtualization in Parallels fixed this issue for me.

**Comment by ldario** [comment]
> Hi guys!
> I solved my problem opening the Hyper-V and applying the right directory for my HD and Conf folders. To check if it's your problem as well, please follow the steps:
> 1 - Open Hyper-V
> 2 - Right-click on the virtual machine (if you have it already created)
> 3 - Click on Hyper-V settings
> 4 - Check the "Virtual Hard Disk" and "Virtual Machine" directories.
> I started to have this issue after trying to change my files to another directory.

Thanks for this fix!  Somehow after a Windows and docker update, I started getting this error.  I created new directories for the "Virtual Hard Disk" and "Virtual Machine" and deleted the old ones. After that, Docker started up properly.

**Comment by auberginekenobi** [comment]
> I would also be interested in hearing if anyone saw this error NOT using a virtual machine windows.

@mikeparker I am running docker for windows not using a VM. Some possibly relevant details:
- Started getting the error after I ran a script in a container that was killed after it ran out of memory. Played with the Docker memory slider and started getting this.
- Fresh reinstall doesn't work
- Am connecting to Docker for Windows through WSL.

**Comment by SandeepTechM** [comment]
I am trying to get docker working in a Windows 10 Enterprise VM running on Linux machine.  I would appreciate any potential fix. Thanks

Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 14535F37-442E-4FDB-8B21-20443497D8D4)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 14535F37-442E-4FDB-8B21-20443497D8D4).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by genemcsween** [comment]
A suggestion from @mojiwa in this thread https://github.com/docker/for-win/issues/4470 worked for me.  The answer was to "expose hardware assisted virtualization to the guest OS" under CPU settings. Running Windows Server 2019 on VMware 6.7.

**Comment by trumpet4hire** [comment]
[Docker Error After Install check-windows10.docx](https://github.com/docker/for-win/files/4431811/Docker.Error.After.Install.check-windows10.docx)
