### ISSUE TITLE
I installed Docker on Windows 10 and 1000 error messages appear.

### ISSUE THREAD

**Issue by githubgia** [docker/for-win#3582]
[diagnostics.log](https://github.com/docker/for-win/files/2975367/diagnostics.log)

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior
[20190317163623.zip](https://github.com/docker/for-win/files/2975369/20190317163623.zip)
[20190317163750.zip](https://github.com/docker/for-win/files/2975370/20190317163750.zip)

I installed Docker on Windows 10 and 1000 error messages appear.
Windows 10 was installed on March 17, 2019 and was updated to the latest version using windows update.
During the installation of docker I deactivated the firewall.
There are no programs or utilities on the system that may conflict with Docker.
The computer is new, I have an i3-8100.
Thank you

**Comment by PavelSosin** [comment]
I just tried to install the promised v2.0.4.0 and got

2019-03-17 18:39:59,435 14896 [ERROR] -  - v2.0.4.0 - v2.0.4.0 not installed. The package was not found with the source(s) listed. 

I found that my previous attempts to install edge version failed due to choco issue: it doesn't know to clean cache without help from choco-cleaner. Even uninstall doesn't clean cache properly.  From o ther hand it looks at cache first  at finds versions which installation has been failed repeatedly.

**Comment by githubgia** [comment]
**So what do you advise me to do?**
I am not a professional, I would like to use docker because I am not able to put up a server and I would like to use docker to test the java programs I create in a java course I am doing.
A huge thanks if you want to help me.
