### ISSUE TITLE
Desktop crash on startup following Win 10 Update.

### ISSUE THREAD

**Issue by GadgetSteve** [docker/for-win#3725]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Deamon starts on windows startup.

### Actual behavior
Crash is reported. ID 5169F872-057D-4232-9455-581206399F7B/20190410053738

### Information

  - Windows Version: 10 (Update had occurred)
  - Docker for Windows Version: 

### Steps to reproduce the behavior

  1. Seems to happen almost every time Win 10 does an update.

**Comment by mikeparker** [comment]
Hi, from your logs this is caused by a timeout waiting for the Linux VM to respond halfway through the boot process, normally the VM only goes seconds between responses but on your machine this is taking up to 7 minutes. We have a 2 minute timeout on this.

The root cause is either your machine running too slowly or Docker Desktop not having enough available resources.

Some ideas:

- Are you running nested virtualization? 
- Is there anything that would be hogging your CPU and preventing Docker from having enough resources? Check CPU usage of other programs and tools. 
- Is the new windows update indexing your disk drives? 
- Virus scanning?
- Background tasks such as installing / downloading windows update pieces?

**Comment by GadgetSteve** [comment]
@mikeparker It is Windows 10 so it could be any or all of the above (at least I am using AVG rather than MacCatty!). Not sure that I will be able to do anything about this but nice to know what the problem is.
