### ISSUE TITLE
Docker should not include kubectl without ever enabling Kubernetes feature

### ISSUE THREAD

**Issue by ddebrecenijr** [docker/for-win#3813]
- [x] I have tried with the latest version of my channel (Stable)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installing Docker should not include extra binaries not being used.

### Actual behavior
Docker adds additional binaries.

### Information
On install, Docker will add kubectl.exe without the feature being enabled.  This causes an issue on already having an appropriate kubectl version for development.  Typically would not be an issue, but due to it currently being 4 Minor Versions behind, there are version mismatches with the cluster and errors with: `error: SchemaError(io.k8s.api.batch.v1beta1.CronJob): invalid object doesn't have additional properties`

  - Windows Version: 18.09
  - Docker for Windows Version: 2.0.0.3 / 18.09.2

### Steps to reproduce the behavior
  1. Install Docker Desktop
  2. See kubectl.exe in C:\Program Files\Docker\Docker\resources\bin

**Comment by larryms** [comment]
adding clarify, Docker Desktop for windows installs kubectl.exe and adds it to the beginning of the system path, even if docker desktop's kubernetes service is not being used. 
This is developer unfriendly behavior as it makes it difficult to use a different (newer) version.

**Comment by JohannesEH** [comment]
Anybody found a way to fix this reliably? It sucks that the installer hijacks my kubectl and often causes problems. Problem is that docker for desktop is controlled by my IT department. So they sometimes update it without me knowing. Then after a while I discover scripts failing because they use some option on kubectl that isn't available in earlier versions. Please stop hijacking kubectl.
