### ISSUE TITLE
Docker for Windows 10 Experiencing Random Freezes

### ISSUE THREAD

**Issue by noonii** [docker/for-win#3815]
After installing Docker on my Windows 10 machine, I experience these random freezes. The frequency is 1-3 times per day at any given hour. My desktop will just freeze and require forced shutdown from the power button.

### Information
- Is it reproducible? **Install Docker & Enable Hyper-V and wait for a random freeze to occur.**
- Is the problem new? **Ongoing for months**
- Did the problem appear with an update? **No**
- Windows Version: **1803**
- Docker for Windows Version: **18.09.2**

### Steps to reproduce the behavior
1. Install Docker for Windows
2. Enable Hyper-V manually or through installation wizard
3. While Docker is running day-to-day, I randomly experience freezes that require me to manually restart my PC via power button.

When I've uninstalled Docker and disabled hyper-v this problem disappeared. So I know it's to do with docker/hyper-v.

**Comment by mello2100** [comment]
Hello. Same problem here.  Whenever I start docker desktop, windows freezes randomly.

**Comment by saumilagg** [comment]
Any updates on this? Experiencing similar issues

**Comment by endormi** [comment]
Apparently not.

**Comment by Hamaze** [comment]
We're experiencing similar issues specifically with Windows / Hyper-V/ Docker

**Comment by ekiscrim** [comment]
Me too.

**Comment by kambbado** [comment]
I'm also getting these hangups, it can take up to 5 minutes. My CPU is running normal 6%. All of the docker processes are normal.  This happens if I try to restart/stop or remove a container. 

The only thing I see in the  event viewer

> debug: container kill failed because of 'container not found' or 'no such process' [error=no such container container=5705adbd5596f866fa7fc5a82f8684357bcd539e0979c0876aa99ec456d29147 action=kill]

**Comment by mello2100** [comment]
> I'm also getting these hangups, it can take up to 5 minutes. My CPU is running normal 6%. All of the docker processes are normal. This happens if I try to restart/stop or remove a container.

In my case, freezes occur mainly when I am navigating the web with Google Chrome. But it happens in other situations either.

But it never happened to crash when restarting/stopping containers.

**Comment by colbyy** [comment]
experiencing this as well -- I did a fresh windows 10 reformat and as soon as I installed docker I get the random freezes 

usually I get BSOD with the DPC_WATCHDOG_VIOLATION error

**Comment by AzyCrw4282** [comment]
Same issue here. I also get the DPC_WATCHDOG_VIOLATION error. It always seem to happen when I am using my app on Google chrome.

**Comment by AzyCrw4282** [comment]
> experiencing this as well -- I did a fresh windows 10 reformat and as soon as I installed docker, I get the random freezes
> 
> usually I get BSOD with the DPC_WATCHDOG_VIOLATION error

Did you manage to solve it?

**Comment by colbyy** [comment]
> > experiencing this as well -- I did a fresh windows 10 reformat and as soon as I installed docker, I get the random freezes
> > usually I get BSOD with the DPC_WATCHDOG_VIOLATION error
> 
> Did you manage to solve it?

ended up creating a ubuntu vm in virtualbox and installing docker inside of it instead ..

**Comment by harrisdt15f** [comment]
same problem on a day with 2 to 3 times freeze after updated to 2.1.0.1( 37199) seem more severe, need help.

**Comment by DefiCzech** [comment]
Same problem here, win 10, after restarting docker, port problem occure.

**Comment by vroyibg** [comment]
Same problem here Windows 10 Pro 1903, engine version 19.03.1

**Comment by mgsmus** [comment]
Same here...

**Comment by lancescape** [comment]
SOLVED!   For me at least this is on and old MSI 990FXA-GD65 with a phenom II X6 1090t. AMD. With SVM enabled and MMIO enabled and Radeon RX 580

1) my network card in my computer was not working properly. I switched to a USB wireless adapter and that did NOT work either.  I had to disable my network adapter and buy a PCI based one even though I don't use it.  I appears docker needs one and it must be working 

2) i had some issues with using HDMI and or displayport cables I had to switch to display port but I think this was more to do with the AOC monitor and bios settings 

Anyways works like a charm finally

**Comment by bjorn-ali-goransson** [comment]
This occurs to me as well. Up to 10 times per day. Now with Docker disabled (but still HyperV enabled) I am back to normal operation. I'm using an XPS 15 9570. I am not even using Docker and I get freezes. I only occasionally need to debug some image, but most often the freeze occurs when not using Docker at all - only running in the background.

**Comment by Nomelas** [comment]
Same issue here, but i get BSOD, with error:
SYNTHETIC WATCHDOG TIMEOUT


Machine:
win10 build 1903
Linux Containers
AMD FX4100
M5A97 Motherboard

Disabling Docker for Windows restabilizes my PC

I'm going to try switching to Windows Insider Preview - Fast Ring for build >=18917
Then use linux docker within WSL 2 (https://docs.microsoft.com/en-us/windows/wsl/wsl2-install)

**Comment by Cycloone** [comment]
Same issue, machine:
windows 10 build 1903

**Comment by tomik23** [comment]
Same issue here.
After updating the new Docker, I have BSDO or freezes. Always in the morning when I start the computer for the first time after a night. The computer starts and runs for a while in the background it starts in the docker because it is added to the autostart. At this time I can run everything but after a while BSDO / freezes appears.

I have disabled the docker from autostart for several days and the problem has stopped appearing.

Machine:
Windows Version: windows 10 build 1903
Docker for Windows Version: 2.1.03 (38240)

**Comment by Kryptonien** [comment]
Same here.

Tested on two different computer. As soon as I install Docker Desktop for Windows, after a while without even touching the computer I get a BSOD with SYNTHETIC WATCHDOG TIMEOUT

**Comment by def-studio** [comment]
Same happened to me, any news?

**Comment by Nomelas** [comment]
The short answer is docker for windows is terrible for Linux containers so don't use it. Switch to Linux OS if you want Linux docker.

**Comment by DefiCzech** [comment]
I added more memory resources to docker service (in settings -> advanced) and it solved my problem.

**Comment by mikicho** [comment]
I get DPC_WATCHDOG_VIOLATION  too, I have this error for almost a year now and it's really frustrating.
I also tried to install docker in WSL 2 (not docker for windows) and it still crashes.

**Comment by Mike-EEE** [comment]
For those experiencing watchdog violations in 1903+, there are a few issues opened on Windows Feedback Hub:

https://aka.ms/AA6xnfe (Non-Widows Insider)
https://aka.ms/AA6ekem (Windows Insider)

I myself have been tracking this since installing 1903 and noticing the host would crash pretty much every night while left unattended.

Reverting back to 1809 has been the only remedy.  Although someone on [this thread](https://social.technet.microsoft.com/Forums/windows/en-US/fbbd3963-885d-4f22-baf2-c7fc29a8a53d/bsod-on-hyperv-host-after-upgrading-to-1903) has said they have had limited luck putting the machine's power plan on High Performance, the author has not yet checked in with results past a week as of yet.  I myself have had my machine run for an entire week on 1909 without a BSOD, thinking it was fixed until the 7th morning when I was met with a reset machine and lost state on all of my guest instances.  Alas, currently back on 1809. 😞

We also have a Twitter thread running here (it's how I found out about this issue 😁):
https://twitter.com/MikeTripleE/status/1187777192815665157

Any additional noise you can generate on any of these resources would be greatly appreciated. 👍

**Comment by layanto** [comment]
> I added more memory resources to docker service (in settings -> advanced) and it solved my problem.

@DefiCzech Is the problem still solved? What did you set the memory resource to? What was it set to before? What containers do you have running?

**Comment by eddgeywing** [comment]
Same here. As soon as Docker is started I get random freezes. No issues with Docker for Windows shut down.

**Comment by Mike-E-wins** [comment]
FWIW all, a potential fix has been deployed for 1909: installing KB4541335 brings up to build 18363.752.  A few of us (including me) are [trying this out on Reddit right now](https://www.reddit.com/r/HyperV/comments/djqnhk/encountering_bsods_on_windows_10_hyperv_host/).  

I am personally entering day 3 currently without issue.  This isn't saying much, of course, as it can take up to 8 days to BSOD, but I thought I would let you all know in case you want to jump in as well.  👍

(BTW I am not _entirely_ sure this is the same issue as what others are describing here, but in case it is, I feel it's worth a mention!)

**Comment by mikicho** [comment]
@Mike-E-wins Hey
Do you know if slow-ring (insiders) have this patch?

**Comment by Mike-E-wins** [comment]
good question, @mikicho.  What I was told from the Hyper-V team on Friday was that it was in "1131+".  I didn't find out later that `1131` is a 1809 build (wasn't familiar with Windows builds at all until I had to start hunting all of this down), and was released on March 17th.  

So, my best-educated guess at the moment is that any build made after this date *should* have the fix in it (e.g. `752` was released March 24th).

**Comment by mikicho** [comment]
Seems like it's working. it doesn't freeze anymore 
Thanks for whoever did that 💯

**Comment by Mike-E-wins** [comment]
Yes I have not had a single problem since installing that `.753` version @mikicho ... talk about an ordeal!  Very happy with Windows ATM... wishing they would stop updating it and keeping it as-is forever. :P

**Comment by ngtaky** [comment]
I have a same issue.
I have the BSOD when I shutdown Windows and then power on.
When I reboot Windows. BSOD doen't happen.

Windows version: 2004 19645.1
Windows 10 home

**Comment by mac-dev** [comment]
Same here! 
Docker Desktop freezes on composer install or drush cex not always but regularrly when many files (100-200) are changed and synced.
During that sync phpstorm will start to index those new files to and I guess McAfee EPS will start scanning those files.
After a Docker Desktop restart Containers run fine again but the might freeze by running e.g. drush cex again.

Docker Desktop 2.3.0.3
Windows 10 Enterprise 1809 17763.1294
Windows Developer Mode ist disabled

**Comment by mikicho** [comment]
@mac-dev try to upgrade your windows

**Comment by bcastagna** [comment]
Constantly freezes, everything is stuck, docker-compose cant stop containers, docker stats shows no sign of activity, has to restart or now even has to QUIT the app an re launch it for it to work again...
Thats a massive loss of time...

**Comment by mikicho** [comment]
@bcastagna this is not what this ticket about.

**Comment by bcastagna** [comment]
@mikicho Yes it is

**Comment by gregdegruy** [comment]
This fixed it for me [Docker run always Frozen or WSL Ubuntu distro stopped while waiting for Lifecycle server](https://stackoverflow.com/questions/63320408/docker-run-always-frozen-or-wsl-ubuntu-distro-stopped-while-waiting-for-lifecycl). 

> When I've uninstalled Docker and disabled hyper-v this problem disappeared. So I know it's to do with docker/hyper-v.

As @noonii  said I experienced the same.

**Comment by nshevcun** [comment]
I am getting the same problem with Docker Desktop on my Windows 10 Home. I was unable to install the Stable version of Docker Desktop, and had to install the Edge. I noticed that, save for one occasion, all of my random freezes occur while I am typing (be it Word, a messenger, Notepad, e-mail, etc.), even if Docker isn't running in the background. Is anyone else noticing a similar pattern in their freezes?

**Comment by rotaercz** [comment]
I did a fresh Windows 10 reformat and installed Docker. I'm getting random freezes with a DPC_WATCHDOG_VIOLATION error. I'm using Hyper-V because WSL 2 was VERY slow for shared files (it would literally take a minute).

**Comment by bcastagna** [comment]
You should install an ubuntu VM and use Docker from there.... DockerForWin is a massive loss of time.

**Comment by grivanov** [comment]
I managed to solve the freezing issues with enabling the 'Containers' feature from Control Panel. As addition, decided to disable the auto-start option inside the docker app itself and made a Task Scheduler task for starting docker 2 minutes after computer power up. Since all that haven't had any issues with docker for Windows.

**Comment by rotaercz** [comment]
> I managed to solve the freezing issues with enabling the 'Containers' feature from Control Panel.

Where is this? I can't seem to find it.

**Comment by rotaercz** [comment]
> I managed to solve the freezing issues with enabling the 'Containers' feature from Control Panel. 

Where is this? I can't seem to find it.

**Comment by grivanov** [comment]
Here:
![image](https://user-images.githubusercontent.com/66895365/98855786-7db81180-2454-11eb-8741-d2ff96033365.png)
![image](https://user-images.githubusercontent.com/66895365/98855857-9fb19400-2454-11eb-964b-39a409dc376f.png)

:)

**Comment by azarc3** [comment]
Late to the party but experienced similar issues. [Originally reported here](https://github.com/docker/for-win/issues/1549) but was suggested to find other issues where people might benefit... so...

**ORIGINAL POST 2020.11.24:**
I'm in a similar boat with everyone else though; I installed Docker Desktop in a brand new custom build (Intel i-9 10290X) on 2020.11.10. After that, every so often the machine would completely freeze. Only resolution is to turn the computer off using the physical button/switch. I couldn't figure out what the problem was -- no logs ANYWHERE detail what was happening -- but looking back on it, the behavior started AFTER I'd enabled the Docker Desktop "Start with Windows" option.

Continuing forward the machine would freeze at least once every other day. A few days ago I realized I didn't need Docker to start with the OS so I turned off the option. Guess what? The freezing stopped. Further cementing my theory (which corroborates what all of you are reporting), I launched Docker Desktop on this morning (2020.11.24) to take a quick look at an image and within 3 minutes the machine froze.

I guess I've found the culprit.

Based on @youngaj 's post I checked my BIOS and saw that the Hyper Threading was set to Auto instead of Enabled. I'm thinking that maybe it has something to do with my mobo/CPU not "spinning back up" properly when the demand hits. I'm going to try this for a few days to see what happens. Hopefully it's just a funky driver implementation that was intended to save power (or something like that).

**UPDATE 2020.12.01:**
Looks like it worked for me. Updating my BIOS to Enabled instead of Auto has worked wonders -- no more crashing! Of course, your solution will vary based on your manufacturer and motherboard, so -- if you plan to try this -- please refer to their respective support pages to figure out what/how to do this for your situation.

- Happy Hunting!

**Comment by Jassi10000** [comment]
Seriously , being an undergrad student , it's very difficult to use Docker Desktop on Windows , with that whenever I have installed it , it simply says install some WSL, Linux Kernel  etc .
I don't why it's all necessary

**Comment by damncorwell** [comment]
Same issue. Getting DPC_WATCHDOG_VIOLATION after enabling "Security Virtual Machine Mode" in BIOS. Without that Docker won't work.

**Comment by daxaxelrod** [comment]
Same issue, DPC_WATCHDOG_VIOLATION. I tried disabling the windows container service as well as uninstalling docker for windows but the problem still persists.

Only reinstalling a fresh copy of windows makes it stop, obviously very painful.

**Comment by EgoPingvina** [comment]
more than 2 years have passed, why is this problem still not solved?!
/remove-lifecycle stale

**Comment by Jassi10000** [comment]
> more than 2 years have passed, why is this problem still not solved?!
> /remove-lifecycle stale

Maybe the solution the community is trying to deliver is out of understanding for ones who have raised the issue

**Comment by injectedfusion** [comment]
I came across this issue and resolved it by enabling containers. I too thought my PC was overheating based upon how it would just lockup. The one thing I realized it was docker-desktop specific was in the evenings when I was playing computer games, my PC would not have any issues, but during the day during development it would lock up randomly. The difference was docker-desktop was not running in the evenings. After enabling the container setting, no crashes so far...

**Comment by Edwin0570** [comment]
So uploaded Docker in my Asus x555q windows 11 and I get the "BSD"  or to be specific  the "Grey screen of death "  I decided to system to full system reset. Uploaded all my necessary apps until  I got to Docker. This app is required to be uploaded for my coding class, and unfortunately crashes my OS again.  Can someone help me troubleshoot this issue? Thanks.

**Comment by jmal327** [comment]
I have been rebooting and freezing all week.  This morning I disabled docker immediately on start up.  I am sure I don't have Docker configured properly, but it shouldn't be taking the machine down, imho.  

![image](https://user-images.githubusercontent.com/22328860/143769800-059bb3f0-5d4f-451a-aa76-a426dfd3a6bb.png)

**Comment by terellison** [comment]
I am experiencing this exact issue on Windows 10, 21H@, OS Build 19044.1466. I have been receiving Blue Screen of Death crashes with the stop code DPC_WATCHDOG_VIOLATION for the last two weeks since installing Docker. Any assistance would be greatly appreciated
