### ISSUE TITLE
[BUG] Docker freezes when upgrading

### ISSUE THREAD

**Issue by matjazmav** [docker/for-win#392]
I tried to upgrade docker, but process freezed. I have also tried to remove it but that also freezes?

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engin
e: The system cannot find the file specified.
```

**Comment by matjazmav** [comment]
To fix failed upgrade, I had to go to "Uninstall or change a program" find Docker and repair it. At least it works now, but I still can't upgrade it.

**Comment by simonferquel** [comment]
Can you try to update after having closed Docker for Windows and stopping the Docker for Windows Service ?

**Comment by matjazmav** [comment]
I had stopped both service and program, but when I start program, it sais that service is not running, then I click start service. Docker is now running and then I get popup that update is available, naturally I click update without killing service and closing docker for windows. Can you change workflow, check for update should preform before starting docker?

**Comment by simonferquel** [comment]
You can just download the latest msi on https://docs.docker.com/docker-for-windows/. It will update your installation as would do the automatic update (but you'll be able to do it while everything is closed)

**Comment by simonferquel** [comment]
Did the issue get resolved ?

**Comment by matjazmav** [comment]
Nop, I still got stuck.
![image](https://cloud.githubusercontent.com/assets/9011654/22115139/423f04ec-de6c-11e6-86bc-cc6439878e54.png)

**Comment by simonferquel** [comment]
This step can take a few minutes to go. Can you give it some more time ?

**Comment by matjazmav** [comment]
I left it for about 1 hour and it is still on the same place.

**Comment by breed85** [comment]
I have also been having this same problem for several weeks. Automatic upgrades get stuck and installing from the new MSI gets stuck as well.

**Comment by unclev** [comment]
I confirm this issue for the `Docker version 1.12.6, build 78d1802` when upgrading to `Docker version 1.13.0, build 49bf474`, - managed to upgrade with the @breed85's workaround. Windows version:
```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.14986 N/A Build 14986
OS Configuration:          Member Workstation
```

**Comment by simonferquel** [comment]
Hi, InstallerCli.exe -k -u kills Docker for Windows processes (the Docker for Windows UI, as well as the Windows service, as well as any other executable we need to bring connectivity to the Linux VM). Then it stops / delete the linux VM and its vhd, remove our settings file and on Windows containers enabled builds, restart temporarly the Windows daemon to remove all containers, networks, volumes and images.

On update, the windows containers things is skipped, and the removal of settings file and VHD (which stores Linux images, containers configuration, etc.) as well.

So if you find yourself in this configuration, what you can try is to exit Docker for Windows, manually stop Docker for Windows service, and manually remove the MobylinuxVM (an optionaly its vhd, if you don't mind loosing your existing containers / images). That might help InstallerCli to do its job.

**Comment by rneugeba** [comment]
@unclev @matjazmav have you had a change to try what @simonferquel suggested?
thanks

**Comment by matjazmav** [comment]
@simonferquel @rneugeba 

When I try manually stop Docker for Windows service I get this error, but service is stopped.

![image](https://cloud.githubusercontent.com/assets/9011654/23102206/5b944ae6-f6a5-11e6-88a7-e8d13b7eb835.png)

I tried uninstalling it with `InstallerCli.exe -k -u` but noting happend, then I killed InstallerCli process and tried to uninstall it via Control Panel\Programs\Programs and Features but got stuck.

![image](https://cloud.githubusercontent.com/assets/9011654/23102255/5978b444-f6a6-11e6-977c-119b427e1efe.png)

**Comment by unclev** [comment]
Updating to Docker 17.03.0-ce. The issue still exits. I exited docker from the system tray menu. At first I didn't notice the Docker Service in the Task Manager Services tab (as it is named com.docker.service, and it got stuck on configuring Docker as before.
When I forcibly killed InstallerCli.exe (this required admin privileges), and then I started docker Desktop App it complained the Docker service is not started. Unfortunately the updater does not check for updated if the service is not started.
Trying to stop the Docker Service leaving it in "Stopping" state.
My the only docker VM was in the "Saved" state all the time. When the docker service started it likely started MobyLinuxVM. Even though I turned off MobyLinuxVM the Docker Service hadn't stopped.
com.docker.service has child processes: com.docker.db.exe, com.docker.slirp.exe, and com.docker.proxy.exe, each of them started conhost.exe.
I noticed the update window open, but closing the update window did not get the service stopped.
I noticed docker icon in the tray and exited it, - the icon disappears but the service didn't stop.
I started the Docker Desktop App again, but it didn't start this time with error:
```
Unable to start Docker for Windows service: 2
   at Docker.Program.Run(IReadOnlyCollection`1 args)
```
obviously because the service is still in "stopping" state. At this point the only thing possible is killing com.docker.service tree (needed admin privileges).
After started the docker service again, tried stopping it brings the the error @matjazmav showed above.
KIling the com.docker.service tree brings docker crash report window, but leaves the "Update" notification window open. Launching update from that window brings the following info message box (I expected it not appear as the docker service had not been started), - 
![dockerwinupdate](https://cloud.githubusercontent.com/assets/5719098/23597112/6f60bb16-025a-11e7-8fce-4507ecfe2996.png)
and it appears again on clicking OK, then it gets stuck again at the very beginning of new "Windows configures Docker" window. Killing ```InstallerCli.exe``` allowed the update to complete. At this point I noticed MobyLinuxVM was disappeared and re-appeared.

**Comment by unclev** [comment]
It seems the issue has gone by now (for at least couples of upgrades). It just successfully updated to 17.09.0-ce-win33 (13620). The only quirk I noticed - it did re-start the daemon after upgrade, - had to start it manually.

**Comment by rn** [comment]
closing. looks fixed (and it's an old issue anyway)

**Comment by sakopov** [comment]
Same exact issue with 2.0.0.3. Can't install. Can't uninstall.

**Comment by DimoHG** [comment]
I have the same issue...
