### ISSUE TITLE
Can't get kubernetes to start with docker for windows

### ISSUE THREAD

**Issue by deepsNG** [docker/for-win#3966]
I have uploaded Diagnostics
  - Diagnostics ID: 02DF1189-8B85-4393-AE79-74D53075EC6A/20190523140930

### Expected behavior
Can't get Kubernetes running 
### Actual behavior

I enabled kubernetes but it won't start. Docker is running but kubernetes is hung up on stating mode.

**Comment by mikeparker** [comment]
May be a duplicate of https://github.com/docker/for-win/issues/3799
This is caused by an installer bug when you install a new version with changed certs on top of an old version.

If your certs are out of date you can either:
a) Uninstall and reinstall, that should update your certs
b) Delete your certs folder https://github.com/docker/for-win/issues/3799#issuecomment-486457446

Let me know if this works.
