### ISSUE TITLE
Cannot upgrade or downgrade on Docker Desktop 2.0.5.0 Edge

### ISSUE THREAD

**Issue by nphmuller** [docker/for-win#4331]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics (Not possible)
  - Diagnostics ID: (Not possible)

### Information
  - Windows Version: Win 10 1903
  - Docker Desktop Version: 2.0.5.0 Edge

### Steps to reproduce the behavior
  1. Docker Desktop will prompt that an update is available.
  2. When clicking `Update`, Docker Desktop will start downloading the update and close
  3. Windows UAC prompts for admin privileges.
  4. After clicking `Yes` in the UAC prompt the installer never starts.

**Comment by nphmuller** [comment]
Switching to the stable (2.0.3.0) didn't work either. Same problem: The installer didn't open.
After uninstalling and installing the new version (2.1.0.0) manually everything worked again.

**Comment by glours** [comment]
Yes, in some  specific cases, the auto-updater of the 2.0.5.0 version briks the upgrade process and the only option you'll have is to install manually the [new edge version of Docker Desktop](https://download.docker.com/win/edge/36873/Docker%20Desktop%20Installer.exe)
This issue has been fixed in the 2.1.0.0 version, the next update should be easier to do 😉
