### ISSUE TITLE
Timed out while waiting for Docker daemon to be ready

### ISSUE THREAD

**Issue by Kiranhsr** [docker/for-win#4440]
I am a newbie and trying to start the docker for desktop(for windows) but unable to start because of the following error.
![image](https://user-images.githubusercontent.com/29139920/62528816-0d453c80-b870-11e9-98bc-9a71af715369.png)

  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:3CEAB5E8-49B9-4FE2-8845-AE818FF57A02/20190806092116

### Expected behavior
Would expect to start the docker
### Actual behavior
Not able to start and encountered crash.
### Information

  - Windows Version:10.0.17134 N/A Build 17134
  - Docker Desktop Version: 2.1.0.0(36874)

### Steps to reproduce the behavior

  1. ... Launch Docker for desktop. 
  2. ...

**Comment by mat007** [comment]
Here is the relevant error from the logs you provided
```
[17:17:14.489][WindowsDaemon     ][Error  ] fatal: failed to start daemon: Error initializing network controller: Error creating default network: HNS failed with error : Element not found. 
```
This error seems to be a Hyper-V bug fixed in Windows 10 build 1903, see https://borncity.com/win/2019/06/18/windows-10-v1903-ip-resolution-bug-in-hyper-v-switch/
Your Windows build number is 17134 (i.e. Version 1803 from the April 2018 Update) which is starting to be a bit old, you should probably upgrade.

**Comment by Kiranhsr** [comment]
The above reported issue is reported from the version 1903 and 1809. And the workaround provided was to install windows sandbox which is available only from 1903.
