### ISSUE TITLE
Ports blocked by Docker, even when restarting

### ISSUE THREAD

**Issue by lutin2706** [docker/for-win#4561]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: Ooops, euh, forgot to note it. Will do it next time

### Expected behavior
When restarting Docker after failure, I expect the ports used to be free.

### Actual behavior
Ports are still in use (visible when making a netstat)

### Information
Problem is reproducible (happens each time I restart Docker)
It is new since last version (never had the problem before)

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.1.0.1

### Steps to reproduce the behavior
Use this docker-compose.yml file :
[docker-compose.zip](https://github.com/docker/for-win/files/3520524/docker-compose.zip)

Restart Docker

Ports are in use : 
![pb docker](https://user-images.githubusercontent.com/33020491/63346574-9327b400-c355-11e9-964f-122f1d2627b7.png)

**Comment by wprogLK** [comment]
I've a similar problem. Does not always happens when restarting docker. Only when it hung up/crashed. 
Apparently process com.docker.backend is still using the ports (in my case 3302). My solution is the kill the proccess manually and restart docker afterwards.

![image](https://user-images.githubusercontent.com/666748/63431579-6f30a500-c41f-11e9-920a-b9a140bf7cf6.png)

I'm using:
- Windows 10
- Docker 2.1.0.1
