### ISSUE TITLE
Run only with wsl2 Engine

### ISSUE THREAD

**Issue by Ognev1990** [docker/for-win#4700]
Is it possible to run only  wsl2 engine without default engine on windows startup?  I have tried to remove default context by ` docker context rm default`  but this action is not permitted. Currently, default docker-engine just reserve 1GB RAM and don't do anything useful. Same question #4357 was closed without a solution. 

PS: docker with wsl 2 is awesome , thanks to the developer team for that :-)

**Comment by stephen-turner** [comment]
Yes, that is our intent once WSL 2 is GA in Windows and available in our Stable version. As it's only in tech preview at the moment, we wanted people to be able to switch back to the LinuxKit VM, but that's not the long-term plan.

**Comment by aelij** [comment]
Workaround (in latest Edge, 2.1.7.0):
* During installation, uncheck "install missing features"
* When Docker loads, it will warn Hyper-V is missing. Dismiss this message and Docker will shut down
* Open `%appdata%\Docker\settings.json` and set `wslEngineEnabled` to `true`
* Start Docker

@stephen-turner How can you remove Hyper-V support as soon as WSL 2 is GA'd? Your docs say Docker follows Microsoft's support lifecycle, which means about 30 more months if I understand correctly. That's why I think it would be best to make the Hyper-V prompt less intrusive. For example, let Docker load and use a toast message to warn about Hyper-V missing. It would allow the user to go to the settings page and switch to WSL.

**Comment by stephen-turner** [comment]
We will of course still have Hyper-V for people with older Windows versions
