### ISSUE TITLE
Run Kubernetes cluster on WSL 2

### ISSUE THREAD

**Issue by leonvzGit** [docker/for-win#4823]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 Build 18990.vb_release.190921-1704
  - Docker Desktop Version:2.1.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
    no.
### Steps to reproduce the behavior

Just a question, How do I run the Kubernetes Cluster for docker desktop on the WSL2 docker-engine rather than the default?

**Comment by sc0ttwad3** [comment]
You can't. The docs for the [Docker for Desktop WSL 2 Tech Preview](https://docs.docker.com/docker-for-windows/wsl-tech-preview/) say:

> Note that it is currently not possible to run Kubernetes while running Docker Desktop on WSL 2. However, you can continue to use Kubernetes in the non-WSL 2 Docker Desktop using the Daemon Settings option.

**Comment by leonvzGit** [comment]
H

> You can't. The docs for the [Docker for Desktop WSL 2 Tech Preview](https://docs.docker.com/docker-for-windows/wsl-tech-preview/) say:
> 
> > Note that it is currently not possible to run Kubernetes while running Docker Desktop on WSL 2. However, you can continue to use Kubernetes in the non-WSL 2 Docker Desktop using the Daemon Settings option.

I Want to use the docker engine on WSL2 for kubernetes not the default on windows host.

**Comment by sc0ttwad3** [comment]
@leonvzGit Seems we're after the same thing then, running kubernetes on wsl 2 docker (docker_wsl) and not the docker-desktop (docker_engine) default context. Which is what we are stuck with, for now...

![Kube-issue-01](https://user-images.githubusercontent.com/1682691/66426459-e0ccae80-e9df-11e9-97c0-bd0c75043f41.png)

There's going to be a new edge release this week I'm told—since 2.1.3.0 has issues that broke the WSL2 tech preview from even starting. Hopefully, they will be addressing this problem running kubernetes on the WSL2 context in this coming edge release. 

#4734 WSL 2 Tech Preview Not Working with 2.1.3.0 (38275)

**Comment by sc0ttwad3** [comment]
Looks like today's awaited new edge Docker 2.1.4.0 hasn't made any progress on running Kubernetes on WSL 2. 😥

**Comment by sc0ttwad3** [comment]
## Docker 2.1.5.0 with WSL 2 Kubernetes Support! 

Putting it through its paces...

2.1.5.0 (40323)
This is the Edge channel, which gives you early access to our newest features. Be aware that some of them may be experimental, and some of them may not ever reach the Stable release.

This release includes Kubernetes upgrade. Your local Kubernetes cluster will be reset after install.

Upgrades

Kubernetes 1.15.5 
Docker Compose 1.25.0-rc4 
Linux kernel 4.19.76 
New

Replace WSL 2 Tech Preview with WSL 2 Backend. 
Kubernetes support 
All wsl distribution compatibility 
The Docker Desktop WSL 2 Backend is experimental

New filesharing implementation 
Uses gRPC, FUSE and Hypervisor sockets instead of Samba, CIFS and Hyper-V networking 
Improve I/O performances in many scenarios 
No need to open Samba port: no clash with IT firewall or drive sharing policy 
No need to provide user credentials to Docker Desktop; file access rights will be enforced naturally when accessing mounted folders from containers 
New Dashboard UI 
Easy access to local containers 
Stop, start and delete containers from the UI 
Easy access to logs, container details and resource usage 


![Docker 2 1 5 0](https://user-images.githubusercontent.com/1682691/68172049-1cf22100-ff44-11e9-9735-3b8a2fe556c9.jpg)

**Comment by mituso89** [comment]
Any update?

**Comment by mituso89** [comment]
![image](https://user-images.githubusercontent.com/29556841/69476406-0e44ae80-0e0c-11ea-8b45-39520e9a21b4.png)

I still not run kubernetes in wsl2

**Comment by sc0ttwad3** [comment]
@mituso89 Looks like you're context didn't get set correctly. Try ```docker context use default``` and you should see it listed as the ```default *``` instead of the ```wsl *```

![Docker-Context-Default](https://user-images.githubusercontent.com/1682691/69766465-1707ee00-1146-11ea-8ee1-f8464f9e6fa7.jpg)

**Comment by leonvzGit** [comment]
blah

**Comment by antoineco** [comment]
I believe this works now.

**Comment by leonvzGit** [comment]
ok
