### ISSUE TITLE
Error: EPERM: operation not permitted, symlink 

### ISSUE THREAD

**Issue by GANG-CHEN-1** [docker/for-win#4885]
### Expected behavior
Use windows nodejs image to build source code, run "call npm run install-peers" the build failure 
### Actual behavior
lerna info Installing external dependencies
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished installing in root
lerna info Symlinking packages and binaries
lerna ERR! execute callback with error
lerna ERR!
{ [Error: EPERM: operation not permitted, symlink 'c:\data\uid-web\packages\core' -> 'c:\data\uid-web\packages\angula
ode_modules\@wuitk6\core']
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',

### Information

  - Windows Version: windows 10 1809
  - Docker Desktop Version: 19.03.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
 No, on a physical laptop
### Steps to reproduce the behavior

  1. checkout code 
  2. npm install

Error info
=======================

**Comment by kpentaris** [comment]
I get the same error.
I have mounted a directory from my host to a docker windows image and I'm trying to run pnpm install from within docker in order to download the packages into the node_modules of the directory. Apparently the Docker container does not allow the creation of Symlinks from within it? I even tried accessing the directory using a Samba share and still have the same problem so it is not an issue with docker mount.

**Comment by GANG-CHEN-1** [comment]
@kpentaris this is regarding permission issue, it seem the containeradministrator account still not permit to run this command, are there a way to give the administrator permission? meanwhile when I checkout source code directly to the container (not into any mount point, the build successfully.

**Comment by kpentaris** [comment]
If it works properly inside the container then it means that the container user (e.g. ContainerAdmin) is not allowed to create symlinks with container-external resources (mounted, shared or otherwise). Let me note that I did not identify this problem with Linux based containers running on a Windows host.

**Comment by GANG-CHEN-1** [comment]
@kpentaris , I did the build successfully inside docker volume(created a docker volume on windows docker host and mount it to container) based on Linux container, then I am trying to make it works in windows container. actually I saw some user's blog mentioned this problem even not in container,  the solution is change the command prompt by administrator, so I assume if there is a way to grant administrator permission as "--user "NT AUTHORITY\SYSTEM" , which means start container with --user "NT AUTHORITY\Administrators", it may work, but unfortunately, it prompted other issue " 8007052E The user name or password is incorrect" , have you been met this issue ? or you have a way let the "real NT admin work in container".

**Comment by kpentaris** [comment]
I did not follow up with Windows Containers unfortunately. The technology seems **extremely unstable** at least at the moment and I've had issues at multiple points from docker build to running etc (especially random crashes). We will be using Linux containers for now on Window host with **wine** and **winetricks** from https://www.winehq.org for our Windows only stuff.
