### ISSUE TITLE
FIXME in log when running a module from VisualStudio

### ISSUE THREAD

**Issue by pkoronawa** [docker/for-win#5008]
Diagnostic Id 665C4E6B-FA4E-461C-B4F1-7190981EA132/20191025220121

Intermittently, running an IoT Edge module as the startup project in Visual Studio will fail with the message
![image](https://user-images.githubusercontent.com/47200230/67607437-543d2280-f739-11e9-81cc-9afe267f4293.png)

This seems to persist until host machine is rebooted. I note in the docker log instances of debug FIXME messages.

**Comment by thaJeztah** [comment]
The FIXME is printed for errors that were not explicitly given a type (e.g.; if it's a problem with the API request that is made, the API should give a http status code in the 400 range). Unknown errors are returned as a 500 error (something the docker daemon wasn't able to handle)

In this case, it looks like a 500 error is valid (but could be explicitly set as an internal server error to suppress the FIXME)

That said; this error seems to be an issue in Windows itself; something prevents docker from removing a file.


Note that Docker is not supported on Azure IoT, and does not provide packages for that platform. The "docker" version running on Azure IoT is built by Microsoft, and based on the upstream Moby Engine; I suggest contacting Azure support for this issue

**Comment by pkoronawa** [comment]
Docker is used to test locally on a dev machine...moby is used only on deployed devices. That said, is there any way to track what API was called, what file is locked, or what process is locking it?

**Comment by thaJeztah** [comment]
The error looks to come directly from the Windows HNS (Host Network Service); https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

Which is the Windows Kernel API for networking. Docker / Moby Engine connect to that API though the hcsshim package; https://github.com/microsoft/hcsshim/blob/6f55763adb33e840f8c66aecd523d07466cca355/hnsendpoint.go#L28, which is where the error comes from.

Might be difficult to get the information what is locking the file, because the returned error message doesn't include what file is in use (otherwise, something like https://gallery.technet.microsoft.com/How-to-find-out-which-c0d4e60e could be tried)

**Comment by pkoronawa** [comment]
Thanks a lot. In this test case the modules are running as dotnet apps but communicating through some MS supplied test tools. Sounds like they may be in error rather than docker itself.
