### ISSUE TITLE
mounting windows drive using api is not working

### ISSUE THREAD

**Issue by kamkie** [docker/for-win#5066]
### Expected behavior
crating container using http api should work this same as in hyper-v version

### Actual behavior
docker deamon returns response that path is not formatted correctly 

### Information
mounting windows volume using windows docker client is working
using linux docker client it is not working also

docker wsl2 2.1.5

**Comment by kamkie** [comment]
on windows 10 build 19018 i found path to mount windows catalogs using api 
paths needs to be prefixed with `/run/desktop/mnt/host/{drive letter}/`

**Comment by rmja** [comment]
I had the same problem when mounting host drives in Kubernetes.

Before, when setting up a host path:

```
hostPath:
    path: /C/Some/Path
    type: DirectoryOrCreate
```

Now:

```
hostPath:
    path: /run/desktop/mnt/host/c/Some/Path
    type: DirectoryOrCreate
```

Is this considered the new way to mount host paths, or is it a bug?

**Comment by kamkie** [comment]
in doker desktop 2.2.0.3 path is now more logical `/mnt/{drive letter}/` still different and requires changes in thing like https://github.com/bonigarcia/selenium-jupiter

**Comment by kamkie** [comment]
I found another issue 
```
docker run --rm -v /mnt/d/Projects/demo/demo-spring-jsf/build/screenshot:/host ubuntu ls -l /host
```
this executerd in cmd (and api) and ubuntu wsl2 (and other wsl2 connected docker clients) return different output 

docker from wsl2 repo is returning content of windows disk D
cmd and api mounted drive (or docker client from wsl 1 distribution) is mounting catalog wrom docker-desktop wsl2 distribution (fails can be seen using wsl -d docker-desktop)

**Comment by simonferquel** [comment]
So to understand why this behave differently, you need a bit more info about how Docker Desktop works.
When you run docker CLI (from windows, or your wsl distro), you don't reach the actual daemon socket directly, but you connect to an API proxy that does some magic:
On win32: 
- rewrites bind mounts to translate windows paths to the place where they are mounted from the docker-desktop distro perspective.
- setup port exposition so that exposed ports of the containers are reachable from windows and the main wsl2 network namespace

On WSL user distro:
- bind mount mount sources into a tmpfs shared volume (accessible both from your distro, and docker-desktop) and rewrites bind mount expressions to use this as the source of the container bind mount
- setup port exposition so that exposed ports of the containers are reachable from windows and the main wsl2 network namespace

So the bind mount handling is different.

To mount c:\Users into a container, you'll then use either
- `docker run -v c:\users:/data <...>` from a win32 cli
- `docker run -v /mnt/c/users:/data <...>` from a WSL distro

And the proxy will do the magic to make things work.

**Comment by kamkie** [comment]
@simonferquel acording to my tests you are correct and conversion is done in docker.exe (cli client) and it is same as docker desktop on hyper-v

the difference is that when you use alternate client as `docker-java`
on hyper-v backend using path like `/d/somefolder` would work (simple translation of windws to unix paths was applied in java) but now to work translation needs to be prefixed `/run/desktop/mnt/host/` and that is a braking change

**Comment by simonferquel** [comment]
Yes, actually it works on hyper-v, because it leverage an implementation detail:
In the very beginning of docker desktop, we used to mount each windows drive at `/<drive letter>` in the Hyper-v backend. We changed that to another path when we moved to Linuxkit, but for backward compatibility (not breaking existing containers when upgrading to the new version) we kept `/[c-zC-Z]` as symlinks to the new place. We never documented this, and always considered this an implementation detail.
Please note that the conversion is not done in the CLI but in an API proxy. So alternative clients such as docker-java can leverage the same bind mount conversion (from win32, bind mounting `d:\somefolder` to a any path should work, even when using third party tools such as docker-java).
Actually  the CLI and docker-compose versions we ship with docker-desktop are unmodified and know nothing about docker-desktop.

**Comment by kamkie** [comment]
this seams to not be working for me 
```
2020-05-18 11:10:29.535  WARN 32628 [rid= sid= user=] --- [    Test worker] i.g.bonigarcia.seljup.WebDriverCreator   : WebDriverException creating WebDriver object (start video container: create video container: Error response from daemon: invalid volume specification: 'D:\Projects\demo\demo-spring-jsf\build\screenshot:/data:rw,z' (WARNING: The server did not provide any stacktrace information)
```

**Comment by simonferquel** [comment]
Is there a way to get rid of the :rw,z options ?

**Comment by kamkie** [comment]
I don't know what is adding mount options, 
my tests are done on decompiled code from https://github.com/bonigarcia/selenium-jupiter 

and that is my main point, I have no control over libraries using docker api and this implementation detail become public api in my opinion 


this works 
```
2020-05-18 11:26:44.618  WARN 2612 [rid= sid= user=] --- [    Test worker] i.g.b.s.handler.DockerDriverHandler      : The path of file build\screenshot in Docker format is /run/desktop/mnt/host/d/Projects/demo/demo-spring-jsf/build/screenshot
```
