### ISSUE TITLE
Config files should be stored in %appdata% instead of %userprofile%

### ISSUE THREAD

**Issue by neko4001** [docker/for-win#5104]
When I start Docker, it always make a .docker directory in %userprofile%. It'a bad behavior in Windows standards and should be customizable like XDG in Linux.

**Comment by MicahZoltu** [comment]
Can we get this re-opened?  I saw this issue previously and thus didn't file my own issue (hoping that this would get fixed eventually).  I just checked back since it has been a while and notice it was closed by the stale bot.  I'm now subscribed and will keep the bot off of this issue until it is fixed, but it appears the bot won't re-open the issue.

Should I just open a new issue?

**Comment by mat007** [comment]
Docker Desktop stores its configuration files in `%APPDATA%\Docker`.

You should probably open a new issue in https://github.com/docker/cli/ as it’s what is storing its `config.json` file in the `.docker` folder.
But given how common this has become on Windows (I have about 20 folders starting with dots in my home folder, including `.aws`, `.kube`, `.ssh`, etc…) I fear it has little chance of being changed…

**Comment by MicahZoltu** [comment]
@mat007 Thanks, I'll file an issue over there.  I'm not personally a fan of the "everyone else pees in the pool, so we might as well join them", though I agree it is a common response to this type of request.
