### ISSUE TITLE
Unable to Access Resource Limit Settings on Docker Desktop Edge

### ISSUE THREAD

**Issue by ericmclachlan** [docker/for-win#5119]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **59272144-F483-401E-B2F6-43D26BF5CA3F/20191112084509**

### Expected behavior
Expected to be able to navigate to the following settings:
![dockerlinuxcontainersettings](https://user-images.githubusercontent.com/36581184/68656112-df8c2580-0539-11ea-8b42-a193c58f560c.png)

### Actual behavior
These settings do not seem to be exposed; not via the UI at least. As a result, I cannot change the system-wide default RAM allocation and my container OOMs at runtime.

(I am able to work-around this issue by starting the container using `docker run --memory=4g` but since I have been using docker-compose, this requires a whole new workflow.)

### Information
  - Is it reproducible? **Yes**
  - Windows **Version: 10 Pro**
  - Docker Desktop Version: **2.1.5.0 (40323) Edge**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

### Steps to reproduce the behavior
Unable to locate the settings for system-wide resource allocation (see screenshot).

**Comment by rvanlaak** [comment]
Did you enable using the experimental WSL 2 based engine?

In that case resources will get allocated by WSL dynamically.

**Comment by ericmclachlan** [comment]
Hi @rvanlaak. Thanks for your response.

I am currently experiencing problems with the experimental WSL 2 engine. Specifically, whether I enable or disable this option, I get
```Command 'docker' not found, but can be installed with:
sudo apt install docker.io
```
So this problem could be a side-effect of a more general problem with that feature. (I assume this has been reported elsewhere.)

It's difficult for me to know from your answer whether you're suggesting I enable the WSL feature as a workaround to the issue I've described or whether you're trying to find out whether the WSL feature is responsible for the bug.

Based on the fact that specifying the memory limit with the --memory argument resolves the problem, I think we can safely conclude that resources are not being allocated dynamically.

Is the intention to remove the settings page indicated in the image above?

**Comment by stephen-turner** [comment]
The setting also doesn't appear if you are using Windows containers rather than Linux containers. The memory limit is actually the size of the VM that is running the containers, and there is no VM in the case of Windows containers.

**Comment by rvanlaak** [comment]
@ericmclachlan when you disable the WSL feature the resource settings will be back, as Docker Desktop will then use the VM (instead of WSL) again.

**Comment by ericmclachlan** [comment]
@rvanlaak : From what I'm seeing, that doesn't appear to be true:

The following screenshots were taken without modifying any settings. You can see that the WSL feature is disabled and the resource settings are not available.

![image](https://user-images.githubusercontent.com/36581184/68699115-10e11180-058b-11ea-83f4-459fce65c4ae.png)

![image](https://user-images.githubusercontent.com/36581184/68699292-67e6e680-058b-11ea-8a81-9adfd5489ce8.png)

@stephen-turner: Is the expected behavior that, if you're running with the WSL feature, you are expected to also host the containers on Linux? Also, if hosting on Windows, are the containers limitted to 1 Gb of memory (this was my observation of the behavior but it seems like a counterintuitive default)?

**Comment by stephen-turner** [comment]
Let me explain in a bit more detail.

Linux containers vs Windows containers is about what OS the code running inside the container is on. For Linux containers, Docker Desktop sets up a Linux VM to run the containers in (and passes commands and network/disk transparently across the boundary). In this case, the memory limit in the settings is the size of the VM, so it's the maximum size of all your containers added together. It is this mode which is replaced by WSL 2, using Microsoft's Linux isolation instead of a VM.

Windows containers are a completely different code path. It's code contributed by Microsoft in the Docker Engine that we bundle, not in Docker Desktop itself. I didn't know the answer to the memory limit in this case, but this StackOverflow page -- https://stackoverflow.com/questions/43460770/docker-windows-container-memory-limit -- suggests that it depends on which of the two possible isolation modes you have for your containers, "process isolation" or "Hyper-V isolation". In this case, the memory is per container, not for all the containers, so it's not comparable to the number above.

Hopefully that helps to explain it.
