### ISSUE TITLE
Unable to share drive w/o admin permissions

### ISSUE THREAD

**Issue by shawmanz32na** [docker/for-win#5139]
On my personal development machine, Docker is my favorite development tool (well, VS Code is up there, too). I use it constantly for spinning up/down services and development environments, most of which involve mapping volumes to containers (for code, configuration, and logs that support my development).

At work, we have a very active IA department who are keen on security. For me, this means that users must log in using PKI tokens (smart cards), never via username/password, and that the account used for day-to-day work cannot have administrator privileges.

Docker for Windows' current drive sharing solution, when combined with my company's security policies, has effectively rendered Docker unusable while at work. To mount a shared volume, we need to provide username/password credentials for an admin user. This means calling IT, having them assign a temporary password to my admin's AD account, then using my user to attempt to share the drive and have my admin enter their temporary credentials in the box that shows up. Whenever my machine reboots (at least weekly for Windows Updates), Docker attempts to re-mount the volume, and the temporary username/password credentials have undoubtedly expired, at which point the process starts again. Even if my admin and I jump through these hoops every few days, it's still technically breaking security policy since my admin's credentials are being used to mount the volume, potentially giving me (and any other Docker users) access to files/directories I have no business having access to (like other users' user directories).

_I'd really, really like a solution where I can share only my user's directory with Docker, and therefore only need my user's non-admin permissions to do so._

I can imagine other solutions that could improve the situation, like support for PKI authentication when sharing drives or persisting the shared drive across reboots, but they really don't address the baseline problem, which is that Docker for Windows' sharing mechanism require admin privileges and access to the entire drive. Additionally, I'd love to know if there are workarounds for my use case, i.e. manually creating a shared volume to my user's directory and mounting that to the Docker VM, and clear instructions for how to do so.

**Comment by djs55** [comment]
Thanks for creating this issue.

There's a new filesharing system for Windows about to ship on edge in 2.1.6.0 (in a couple of days). The new system:
1. doesn't require credentials (admin or otherwise)
2. doesn't use drive sharing
3. runs the file server process as your Windows user (it's part of the Desktop app itself) and therefore can only read your files (like a regular app)
4. doesn't use Hyper-V networking so doesn't interact with IT firewall or VPN policies.

With luck it will be compatible with your environment and your security policies (and if not, we'd like to know how we could make it compatible!)

The downside is the system is completely new and considered "experimental" as it may well be buggy and imperfect in various ways. We'd love feedback on it, if you have time to experiment. I'll let you know when a build is available just in case you have the time to check it out.

**Comment by djs55** [comment]
The new edge version has been released! The new version
- doesn't require credentials (admin or otherwise)
- doesn't use drive sharing
- runs the file server process as your Windows user (it's part of the Desktop app itself) and therefore can only read your files (like a regular app)
- doesn't use Hyper-V networking so doesn't interact with IT firewall or VPN policies.
- supports inotify event injection, useful for developer workflows which rely on events for automatic code reloading / page reloading.

Let me know if you have time to try it and if so, whether it works (or not...)

Install it by:
1. download and run edge 2.1.6.1 directly from here: https://download.docker.com/win/edge/40920/Docker%20Desktop%20Installer.exe
2. click "Yes" on the "Are you sure" dialog:

<img width="407" alt="Screenshot 2019-11-29 at 07 58 18" src="https://user-images.githubusercontent.com/198586/69853164-fcd12b80-127d-11ea-9274-b93380893b05.png">

3. start Docker Desktop
4. right click on the whale menu and click on "Settings"

<img width="354" alt="Screenshot 2019-11-29 at 08 01 01" src="https://user-images.githubusercontent.com/198586/69853271-56395a80-127e-11ea-8cac-c425d6f5f5ad.png">

5. click on "Docker Engine" and then change the line from `"experimental": false` to `"experimental": true`:
<img width="1045" alt="Screenshot 2019-11-29 at 08 01 38" src="https://user-images.githubusercontent.com/198586/69853331-7ec15480-127e-11ea-9ce1-e83f48e7953f.png">

6. click on "Apply & Restart"
7. to check whether it has worked, wait for the app to restart, open a powershell window and type

```
docker run -it -v C:\:/c --privileged --pid=host justincormack/nsenter1 /usr/bin/ctr -n services.linuxkit t exec -exec-id foo -t docker /bin/sh -c 'mount | grep host_mnt'
```

8. confirm that you would like to share the drive:
<img width="363" alt="Screenshot 2019-11-29 at 08 04 26" src="https://user-images.githubusercontent.com/198586/69853486-f2636180-127e-11ea-873f-bce1a53f5906.png">
9. observe the filesystem type `grpcfuse` mentioned in the command output, for example

```
grpcfuse on /host_mnt/c type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
```
(If it hasn't switched mode, the output will mention "cifs")

Hopefully this new filesharing mode will work better for you. It's still considered experimental, so please do provide feedback and bug reports if you can!

Thanks for your patience!

**Comment by spyd3rw3b** [comment]
changing the value to dataFolder in the system.json corrected mine update as well, only difference from the above, is I had a value and not null. It excepted the empty string and started without issue. No other changes were made on the system. build 2.1.05(40693)

**Comment by sameronline** [comment]
I had issues with the sync of file system between the docker containers and host machine. Whenever i deleted files or folders from the host machine.. they would not be picked up the container.

In my case changed  to `"experimental": false`  and problem was solved

Docker Edge: v19.03.5
Windows 10 Pro v1909 Build 18363.476

**Comment by sameronline** [comment]
This behaviour continues to happen at the latest Docker Edge: v2.1.7.0

if you delete a folder from host the folder would not be synced with the container  
![image](https://user-images.githubusercontent.com/660827/70829697-036faf00-1df7-11ea-87c5-9c0262829824.png)

then such errors start to happen

**Comment by STotev** [comment]
With version 2.2 when you set the experimental setting to true, the restart only doesn't help. After the prompt to share my driver, the container couldn't start. I stopped the app fully and started it again and then I was able to share my drive with no credential prompts.

**Comment by stephen-turner** [comment]
This is fixed with the new filesharing implementation in 2.2.0.3, so closing this ticket.
