### ISSUE TITLE
The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\DockerDesktop.vhdx': The file exists. (0x80070050).

### ISSUE THREAD

**Issue by andywolk** [docker/for-win#5164]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5843E04D-2E61-4250-B3A1-5EB9D155734B/20191118124903

### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: 2.1.0.4 (39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Windows restarted due to Windows Update.
  2. This issue happened. Docker does not start anymore.

**Comment by andywolk** [comment]
Renaming `DockerDesktop.vhdx` fixes the issue, but all containers and images are gone.

**Comment by tmtron** [comment]
I had the same issue: the vhdx file was corrupted for some reason and could not be repaired.
The day before I sent Windows 10 Pro to sleep (instead of shutdown) - maybe this was related. Also possible that there was no space left in th vhdx (the file was 27GB) and this caused an error..

I just renamed the old vhdx file and when docker started it created a new one.
