### ISSUE TITLE
Feature request: support Hyper-V Dynamic Memory

### ISSUE THREAD

**Issue by janwerner** [docker/for-win#521]
Currently, it can be difficult to run Docker for Windows on systems that have less than 16 GB of RAM. Dynamic memory might help with that.

The issue has already been discussed on the [forums](https://forums.docker.com/t/hyper-v-usage-of-dynamic-memory/11703/5).

**Comment by rneugeba** [comment]
@janwerner we deliberately do not enable dynamic memory as this can cause intermittent failures, ie you start a container which requires memory currently not available and it fails. Sometime later you start the same container and this time it works, kinda thing. Because of this I'm closing this issue as won't fix

You could try reducing the memory of the Linux VM via the settings menu if it is causing issues on your system

**Comment by principat** [comment]
>  you start a container which requires memory currently not available and it fails. Sometime later you start the same container and this time it works, kinda thing.

wouldn't it also happen if i start multiple container with changing memory consumption over runtime?

so it won't be an argument for me

**Comment by ahmadalli** [comment]
I use docker for development and I don't want it to preserve my memory unless it needs it (I already have chrome doing this for me).
Isn't it possible to add this option with "Dangerous" label and enough notes beside of it?

**Comment by vthuongt** [comment]
What is the status on this? Is this feature request closed permanently?

**Comment by z2z** [comment]
@rn case you trying to put forward can be handle using min / max options.
https://docs.docker.com/config/containers/resource_constraints/#limit-a-containers-access-to-memory

**Comment by Hades32** [comment]
Can this be enabled with a warning maybe? It easily prefer some intermittent failures to changing the memory settings every time I need a large container... ^^

**Comment by jonshipman** [comment]
Will this also be an issue with WSL2?
