### ISSUE TITLE
Docker container ping is too high

### ISSUE THREAD

**Issue by alexismaret1test** [docker/for-win#5232]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I tried disabling IPV6
  - [X] I  tried disabling netadapterRSC (this increased the internet speed but not the ping)
  - [X] I tried disabling Windows Defender
  - [X] I tried running 'Docker for Windows.exe' with a user which is in the docker-user group

### Expected behavior
I expect the ping to be the same on the host OS than in the docker

### Actual behavior
Ping Test done on https://speedtest.net/

ping on the host OS : 4ms
ping in the docker : 30ms

### Information
  - Windows Version: 10 build 1903
  - Docker Desktop Version: 2.1.0.5 (40693)

I have a docker with fedora 29 inside.

I observed that the ping in the docker is very high compare to the ping from the host OS.
Even when i ping a site like google, the ping is higher in docker.

I also try the speedtest with the fedora remix distribution in WSL 2 and the ping is the same than the host OS (4ms).

So i think that the problem came from docker.

docker network : "bridge".
network card : vEthernet (Docker NAT)

Do you have some idea ? 

Thanks for reading :)

### Steps to reproduce the behavior

  1. Create a container with fedora 29
  2. Test your speed connection on https://www.speedtest.net/
  3. Compare to the speed connection on your host OS

**Comment by alexismaret1test** [comment]
Nobody has feedback on it ?

I try to observe the network flow with wireshark.
On the ethernet adapter i see that the" requets ping" are the same on both Windows and Docker and the response time is the same.
But impossible to observe the packet transfert from "ethernet adapter" to "vEthernet DockerNAT" with wireshark.

Any idea ?

**Comment by djs55** [comment]
@alexismaret1test thanks for your report. Unfortunately the `ping` latency is higher for regular Linux containers in Docker Desktop on Windows because we tunnel all traffic through a user-space network stack (from the Moby [vpnkit](https://github.com/moby/vpnkit) project) instead of using normal Hyper-V networking to avoid clashes with enterprise VPN clients and endpoint security software.

Since Docker Desktop is a developer tool we aren't trying to achieve ultra-low latency or line-rate networking. For running containers in production with great network performance I recommend using `docker` directly on Linux.

**Comment by alexismaret1test** [comment]
@djs55 Thanks you for your explanation.
I hope one day we will have the same performance on Windows than on Linux.
