### ISSUE TITLE
Unable to open docker on windows.Please help

### ISSUE THREAD

**Issue by Nandini-nandu** [docker/for-win#5306]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: windows 10 enterprise
  - Docker Desktop Version:19.03.1, build 74b1e89
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: on VDI

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
