### ISSUE TITLE
Docker dont work

### ISSUE THREAD

**Issue by kereymen-87** [docker/for-win#5347]
Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Synthetic SCSI Controller: Failed to Power on with Error 'The process cannot access the file because it is being used by another process.'.

Attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.'.

'DockerDesktopVM' failed to start. (Virtual machine ID 460D9652-B9DA-4AFE-8922-467ABD40A8B8)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID A50FF37F-77B7-43CE-B0BC-273DACDB75D6): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 460D9652-B9DA-4AFE-8922-467ABD40A8B8)

'DockerDesktopVM': Attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 460D9652-B9DA-4AFE-8922-467ABD40A8B8)

   в Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   в Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   в Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   в Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by Jayeshecs** [comment]
any update on this issue. I am facing the same issue!

Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID FD94CD31-0DCE-41D0-B6C7-9AF1CAD688E2): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.'.

Attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.'.

'DockerDesktopVM' failed to start. (Virtual machine ID 85324E90-E616-43A7-B15B-A368E54B51A0)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID FD94CD31-0DCE-41D0-B6C7-9AF1CAD688E2): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 85324E90-E616-43A7-B15B-A368E54B51A0)

'DockerDesktopVM': Attachment 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID 85324E90-E616-43A7-B15B-A368E54B51A0)

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
