### ISSUE TITLE
DockerDesktopVM does not start on log in

### ISSUE THREAD

**Issue by Essler** [docker/for-win#5421]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A519590C-6A2C-4D83-A69F-6FA64DB090D0/20200105211338

### Expected behavior
Logging in to a Windows 10 account with Docker Desktop installed and the 'Start Docker Desktop when you log in' setting enabled should successfully start Docker Desktop and the DockerDesktopVM in Hyper-V.

### Actual behavior
Logging in to a Windows 10 account with Docker Desktop installed and the 'Start Docker Desktop when you log in' setting enabled results in Docker Desktop taking longer than usual to start and ultimately results in the following error being reported:

> Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version: **Microsoft Windows 10 Enterprise Version 10.0.17134 Build 17134**
  - Docker Desktop Version: **2.1.0.5 (40693) stable**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No**

  - Is it reproducible? **Yes, about a third of the time when logging in to a Windows 10 account.**
  - Is the problem new? **No, it has occurred as long as the machine has had Docker Desktop installed.**
  - Did the problem appear with an update? **No**

### Steps to reproduce the behavior

 
  1. Log in to a Windows 10 machine with a user account where Docker Desktop is set to start when logging in
  2. Note Docker Desktop startup takes much longer than usual
  3. Eventually receive an error from Docker Desktop saying that the DockerDesktopVM could not be started with Hyper-V

### Work-around
  1. Open **Hyper-V Manager** under **Windows Administrative Tools**
  2. Note **DockerDesktopVM** is not running under **Virtual Machines**
  3. Under the **Actions** pane, click **Stop Service**, then click **Start Service**
  4. Restart **Docker Desktop**

**Comment by gstevens-kyriba** [comment]
Same thing here...  Brand New Windows 10 Enterprise VM in Azure..  Fresh Install of Docker Desktop fails.  
Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 00545F88-CCEE-4C63-9679-EB0B613CC1F4)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 00545F88-CCEE-4C63-9679-EB0B613CC1F4).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
