### ISSUE TITLE
Failed to initialize storage: A document with id `license-server` was not found.

### ISSUE THREAD

**Issue by davidpaulstevens** [docker/for-win#5499]
When I type "http://localhost:8081/" in my browser, I get the following error message:

{"Error":"Seq is unavailable. Failed to initialize storage: A document with id `license-server` was not found."}

I am a single developer. Any idea what I need to do?

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
