### ISSUE TITLE
Is there anywhere to go to get actual Docker support?

### ISSUE THREAD

**Issue by STaRDoGG** [docker/for-win#5509]
Not trying to be insulting, but most questions here go unanswered; is there some actual forum or email, etc. to go to get actual responses? And in a timely manor?

I'm stuck with a problem that needs resolving soon, and waiting in hopes of a response here seems futile.

TIA

**Comment by magneticflux-** [comment]
The Docker Desktop for Windows forum is linked in [this article](https://docs.docker.com/docker-for-windows/troubleshoot/?utm_source=docker4win_2.1.7.0&utm_medium=docs&utm_campaign=referral#in-app-diagnostics).

**Comment by djs55** [comment]
@STaRDoGG thanks for your comment and sorry we've not managed to resolve your issue yet. Our goal is to make Docker Desktop work well, for the most number of people, as quickly as possible. This tends to be a somewhat statistical process involving sampling from multiple populations of bug reports (one of which is here) which can result in some individual tickets not getting addressed in a timely fashion.

Could you point me at the issue you have? The best way to maximise the chance of success is to make as actionable a bug report as possible. I recommend
- downloading the latest stable (released today) to see if it still reproduces there; assuming it does:
- upload a diagnostics report from the whale menu -> troubleshoot and acquire an ID
- make sure the diagnostics ID is on the ticket
- if possible, produce a self-contained `Dockerfile` or `docker-compose.yml` (or combination) which demos the issue easily. If the issue is easy to reproduce it's usually easy to fix.

Ping me on the ticket and I'll take a look.

**Comment by marwatk** [comment]
@djs55 Is there a way you can take a look at #5376? Now that I've tried to fix it by removing Docker I'm unable to enable local TLS access and can't get to it from WSL.

**Comment by STaRDoGG** [comment]
> The Docker Desktop for Windows forum is linked in [this article](https://docs.docker.com/docker-for-windows/troubleshoot/?utm_source=docker4win_2.1.7.0&utm_medium=docs&utm_campaign=referral#in-app-diagnostics).

Thanks, unfortunately the support there is next to non-existent as well, lol.

i.e. 

https://forums.docker.com/t/how-to-connect-to-remote-docker-daemon-running-on-a-pi/87768

https://forums.docker.com/t/disable-kubernetes-option-via-command-line/87860
