### ISSUE TITLE
Docker for Windows does not start

### ISSUE THREAD

**Issue by Ash-Ketchum1192** [docker/for-win#5631]
- [Y] I have tried with the latest version of my channel (Stable or Edge)
  - [Y] I have uploaded Diagnostics
  - Diagnostics ID: 90D79062-41EE-4088-A297-D126412377EA/20200129135251

### Expected behavior
Docker Desktop starts normally
### Actual behavior
Docker Desktop stuck in 'starting' and fails to start
### Information

  - Windows Version: Windows 10 1709 16299.1625
  - Docker Desktop Version: 2.2.0.0 (42247) stable
  - Are you running inside a virtualized Windows: No, a standard Windows 10 build

**Comment by developertotalview** [comment]
* [X] I have tried with the latest version of my channel (Stable or Edge)
* [X] I have uploaded Diagnostics
Diagnostics ID: E37D09A7-F695-4F6A-9380-A544CF140879/20200129161817

Expected behavior
Docker Desktop starts normally

Actual behavior
Docker Desktop stuck in 'starting' and fails to start
![image](https://user-images.githubusercontent.com/59614399/73377236-b5bae300-428c-11ea-90e3-73344e49d3e4.png)


Information
Windows Version: Windows 10 Pro 1909 OS build 18363.592
Docker Desktop Version: 2.2.0.0 (42247) stable
Are you running inside a virtualized Windows: No, a standard Windows 10 Pro build

**Comment by Ash-Ketchum1192** [comment]
That is the exact error I am receiving!
