### ISSUE TITLE
Starting Docker on Windows 10 Pro with Hyper-V

### ISSUE THREAD

**Issue by feraswilson** [docker/for-win#566]
### Expected behavior
Docker starts
### Actual behavior
Docker does not start and reports that it could not stop VM MobyLinuxVM

### Information
Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Steps to reproduce the behavior

  1. Restart Windows 10 pro
  2. Start docker on Windows

**Comment by feraswilson** [comment]
Restarting again solved the issue. I suppose this is not a Docker specific issue but rather Docker communicating with Hyper-V. Maybe permission? Or Hyper-V failure?

**Comment by rneugeba** [comment]
thanks for the report. Yeah, this is likely a Hyper-V issue. We try to stop the VM gracefully and if that doesn't work, try a bit more forcefully, and if that doesn't work we try to kill the process. For some reason this also failed.

The Hyper-V logging is typically not very useful in these situation. It will just say "failed to stop" or "failed to start", so it's quite hard to diagnose these type of errors.

Since this is working for you now, I'll close the issue, but please re-open when it happens again. The it would also be useful if you could include a diagnostics ID for us to take a look.

thanks
