### ISSUE TITLE
wsl2 failed on start up 

### ISSUE THREAD

**Issue by tim-pluralgroup** [docker/for-win#5752]
- [ x] I have tried with the latest version of my channel (Stable or Edge)yes
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
startup with wsl2
### Actual behavior
crash
### Information

  - Windows Version:Version: 2.2.0.0 (42247)
Channel: stable
Sha1: 2e3b4c91994e99da6458fe2291f2efbb3d5d80fe
Started on: 2020/02/10 09:50:02.302
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19559
BuildLabName: 19559.1000.amd64fre.rs_prerelease.200131-1437
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:NO

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
