### ISSUE TITLE
KB4532693 breaks SysWOW64 support in process isolation

### ISSUE THREAD

**Issue by jrad88** [docker/for-win#5773]
Hi, 

It seems Windows Update is at it again.  The 2020-02 Cumulative update breaks docker on every machine and VM I've tested it on.  This one is for Windows 10 1903. Running any 32 bit application will result in the same error code.  For simplicity, here is a quick and easy way to reproduce.  This is running latest Docker Desktop.

> docker run --isolation=process --rm -it mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-1903 powershell
> 
> PS C:\> .\Windows\SysWOW64\cmd.exe
> PS C:\> echo $lastexitcode
> -1073741502
> PS C:\> 

The important bit is process isolation.  hyperv will work fine in my testing.  That exit code is something to do with dll failing to load, my guess in the dark is because it's trying to load a 64bit version in to a 32bit application.  Viewing in procmon you can see it run for a bit, load some system dlls and fail somewhere.  

-1073741502 (STATUS_DLL_INIT_FAILED)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?

**Comment by stephen-turner** [comment]
Thanks for the report. It sounds like this is in the engine code, not in Docker Desktop. (The engine is only an upstream for us). So could you kindly file it in moby/moby instead of here? (Sorry, I would move it myself if I could, but issues can't be moved across organisations). Microsoft engineers wrote the Windows container code in moby/moby so they should see the issue.

**Comment by stephen-turner** [comment]
Snap!
