### ISSUE TITLE
Docker no longer starts in Windows 10

### ISSUE THREAD

**Issue by naris** [docker/for-win#5818]
All of a sudden Docker has started crashing on my Windows 10 machine. I uninstalled and reinstalled it and it still crashes :(

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ... Install Docker on Windows 10
  2. ... Attempt to start it.
  3. ... It crashes

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?

**Comment by naris** [comment]
I did document the steps. You install docker in windows 10 and it does't start. period. There is no opportunity to install anything. Clearly Docker is useless software that in not supported and should never be used!

**Comment by naris** [comment]
I did follow the step and document it. Clearly Docker is not supported at
all. Why would anyone use this software that get broken so it no longer
functions for an entire operating system and then the response is "closing
tickets" with a refusal to even investigate it at all?
