### ISSUE TITLE
Docker installation failed

### ISSUE THREAD

**Issue by Susanthab** [docker/for-win#5847]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Version 1909 (OS Build 18363.657)
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  1. ... Just download the Docker for Windows 
  2. ...Install it as Administrator

Failed to start service: The service did not respond to the start or control request in a timely fashion
   at CommunityInstaller.ServiceAction.<AddService>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ServiceAction.<DoAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()

**Comment by Susanthab** [comment]
With the latest Windows CU, I was able to installed Docker successfully. As usual its a Windows issue. :)

**Comment by johnsonzhangjo5** [comment]
Hi Susanthab,
May I know what CU stands for? As I'm meeting same issue when re-install docker in win10 now.
Thanks very much.

**Comment by Susanthab** [comment]
Hi,
CU = Cumulative Update.
When I checked the Windows update there was a CU (optional) and I installed that. 
https://support.microsoft.com/en-us/help/4535996/windows-10-update-kb4535996
Hope this helps. Thanks.

**Comment by johnsonzhangjo5** [comment]
Thanks very much. I will retry after company adopting the upgrade.

**Comment by gargankurg** [comment]
Looks like it is Docker and some Anti Virus issue, my docker was working fine and then it suddenly stopped working. 
When I am trying to reinstall it started giving me the same issue and here is the log from event viewer. 
-----------------------------

Faulting application name: com.docker.service, version: 2.2.0.43884, time stamp: 0xb5cd9c2c
Faulting module name: sysfer.dll, version: 14.2.5536.2100, time stamp: 0x5df8ae6d
Exception code: 0xc0000005
Fault offset: 0x000000000001c79a
Faulting process id: 0x4f98
Faulting application start time: 0x01d6276b05e8a0a3
Faulting application path: C:\Program Files\Docker\Docker\com.docker.service
Faulting module path: C:\WINDOWS\System32\sysfer.dll
Report Id: 328cb1ec-9e17-4825-b1ef-69328f90531d
Faulting package full name: 
Faulting package-relative application ID: 

-----
A timeout was reached (30000 milliseconds) while waiting for the Docker Desktop Service service to connect.

------
The Docker Desktop Service service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
-----
