### ISSUE TITLE
Docker crashes when trying to access any setting in graphical window - Faulting module name: d3d9.dll

### ISSUE THREAD

**Issue by diman82** [docker/for-win#585]
### Expected behavior
Launch the 'settings' window
### Actual behavior
Docker process crashes
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.: can't get, due to program crash
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc): Docker version 17.03.0-ce, build 60ccb22

Faulting application name: Docker for Windows.exe, version: 17.3.0.10300, time stamp: 0x58b5a757
**Faulting module name: d3d9.dll, version: 10.0.15048.0**, time stamp: 0x5aad085d
**Exception code: 0xc0000005**
Fault offset: 0x000000000001b641
Faulting process id: 0x4320
Faulting application start time: 0x01d29d041cb4fe3a
Faulting application path: C:\Program Files\Docker\Docker\Docker for Windows.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 78467440-ee05-458d-a9dc-783c3595b594
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to reproduce the behavior

  1. ... Launch Docker
  2. ... Try to access 'Settings..' in the menu.

**Comment by LimNicolas** [comment]
I have the same issue.

Having d3d9 mentioned in the crash report was suspicious, so I dug up a little.
It turns out it's caused by RivaTuner Statistics Server. (which comes with either MSI Afterburner or EVGA Precision)

Quitting Afterburner/Precision works, but that's not a great solution.

The best way is to:
1. Open RivaTuner
2. Click the big + button
3. Search for C:\Program Files\Docker\Docker\Docker for Windows.exe and add it
4. Select "Docker for Windows.exe" in the list
5. Set "Application detection level" to None

Voilà

**Comment by merinkumar** [comment]
@Nicnl , thank you verymuch, me too drilled down till the dll file issue, then searched and found this solution !!!

**Comment by dbykadorov** [comment]
@Nicnl it working! Thank you!

**Comment by wildw1ng** [comment]
thanks!
