### ISSUE TITLE
Can't run Linux containers on Windows 10

### ISSUE THREAD

**Issue by RhyattMCX** [docker/for-win#5880]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Switches to Linux containers

### Actual behavior
Errors and dies. Requires restart and switching to Windows containers using CLI
### Information

  - Windows Version: 10 pro
  - Docker Desktop Version: 2.2.0.3 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows Hyper V

### Steps to reproduce the behavior

  1. ... 
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
