### ISSUE TITLE
Timed out waiting for the lifecycle-server to start.

### ISSUE THREAD

**Issue by hckhanh** [docker/for-win#5885]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 620A1189-5152-4784-B237-26B31B84EF37/20200226134201

### Information

  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO

### Steps to reproduce the behavior

  1. Shutdown PC why Docker has running containers
  2. Start PC again then I receive this

**Comment by csmcallister** [comment]
I have also experienced this issue, although I did not have any running containers since I only used Docker once to [test the installation using the hello-world example](https://docs.docker.com/docker-for-windows/#test-your-installation). Like OP, this occurred after I restarted my computer. 

I uploaded my crash report (Diagnostic id: 4CD48BD8-14B4-4D74-8D3E-3F50F06B7EBF/20200310133106).

**Comment by hckhanh** [comment]
Yes, I did the same.
