### ISSUE TITLE
Cannot use \\wsl$ share to bind to WSL2 filesystem when using docker.exe from the Windows side

### ISSUE THREAD

**Issue by Chuxel** [docker/for-win#5888]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7B398F25-642B-42A0-BCCE-30D2652979D3/20200226191250

### Expected behavior

First - I am loving the new WSL2 mode for Windows.  This is amazing - really cool to see this coming together!

However, when using the WSL2 (and the WSL2 docker engine) and tools that work with Docker but run on the Windows side like the [VS Code Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension, I think you should be able to use Windows `\\wsl$` share to bind mount to files inside WSL2. The WSL2 Docker engine appears to be doing automatic path translation between WSL2 and Windows when doing bind mounts to the Windows filesystem, so ideally the reverse would also be true. 

### Actual behavior

There is currently no way to interact with files or source code sitting inside WSL2 from the Windows side. Unfortunately, referencing the `\\wsl$` in a bind mount fails.  

### Information
  - Windows Version: Windows 10 "slow ring" version 19041.89
  - Docker Desktop Version: 2.2.1.0 (42746) edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Happens both in a Parallels VM and directly on Windows hardware.

### Steps to reproduce the behavior
  1. Setup WSL2 with Ubuntu 18.04
  2. Install Docker Desktop and choose the WSL2 engine
  3. Run `docker run -it --rm -v \\wsl$\Ubuntu-18.04:/workspace debian` on the Windows side

Expected: The WSL root folder is bound to /workspace in the container
Actual: Errors complaining about the path: 

```
C:\Program Files\Docker\Docker\resources\bin\docker.exe: Error response from daemon: \\wsl$\Ubuntu-18.04%!(EXTRA string=is not a valid Windows path).
```

Note that there was a point during the Technical Preview that this worked and correctly bound to the filesystem in WSL2 rather than something strange like going out to windows and back.

**Comment by stephen-turner** [comment]
@simonferquel Do you have a comment on this? Thanks.

**Comment by simonferquel** [comment]
This is unfortunately complicated to enable, as we need to connect to the integration agent of the distro hosting bind mount sources to make sure they are available for binding. The workaround is to run the docker cli from within the Ubuntu-18.04 distro.

**Comment by simonferquel** [comment]
Note, from powershell, you can always type `wsl -d Ubuntu-18.04 docker run <...>`

**Comment by lachlankrautz** [comment]
Unfortunately many windows apps integrate with docker using the socket connection. These apps will not be able to create volume mounts to wsl2 paths.

For example phpstorm allows you to run tests using php in a docker container. 

- In wsl1 volumes mounted correctly
- In wsl2 the volume is unable to mount

**Comment by simonferquel** [comment]
I see, I'll add a ticket in our backlog.

**Comment by davclark** [comment]
@simonferquel I'd love a link to that ticket! I feel that I'm often here asking about bind-mounts because at @gigantum we're running a docker application that further manages other dockerized applications for you.

So when we run the management application (the Gigantum Client) from the WSL2 command line, we successfully get a bind-mount to something like `/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/WLinux/eed79b8bd074333a6cb5eac62777c4a04023f9a840e252734a938765073e15b6`. A reasonably easy way to get this printed out would be `docker inspect 23b |jq '.[0].Mounts[] | .Source + " -> " + .Destination'` (you'd have to install `jq` on your WSL2 distro of choice).

I am able to use this as a prefix and then add subdirectories for other containers. In Gigantum, we embed this prefix into the management container as an environment variable. If folks are interested, I'm happy to point you at our Python code.

I still need to wire this all together to make the application work, but we've taken a similar approach for running the application from the windows side and it seems to be working (it's just slow).

More importantly, I want to understand if this approach will keep working in the future. It is painful when an update to Docker for Windows makes it so you can't do this anymore!
