### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by strever** [docker/for-win#592]
### Expected behavior

docker can be start

### Actual behavior

docker can't be start

### Information

Server Version: 17.03.0-ce
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393
Operating System: Windows 10 Pro

report:
E2335A3B-7A2B-4DE8-81C1-8785425D7A28/2017-03-16_11-05-44

**Comment by runner7532** [comment]
I am seeing this same issue. I just installed Docker on my computer and it will not start. This is the error that I am seeing in the logs:

[NamedPipeServer][Error  ] Unable to execute Restart: Docker hv-sock proxy (vsudd) is not reachable   
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

A diagnostic was uploaded with id: 31F4F8DC-54D6-470E-8182-9AD6A9C4A749/2017-03-24_21-28-12

**Comment by schatzidogssss** [comment]
Same issue with newest build Version 17.03.1-ce-rc1-win3 (10625)\

**Comment by ankursaini2006** [comment]
I had the same issue on my windows 10 laptop. I have been trying to resolve it for 4 days and finally I am able to resolve it.

Since my laptop is enterprise one so Docker on windows was not running on startup with Admin rights. Then I tried to open Docker for Windows.exe with "Run as Admin" and then it worked correctly.

I hope this would help others also who are facing the similar issue.

**Comment by timshoaf** [comment]
I just ran into this myself.

Steps for success, for me at least, were as follows:
* Apply all windows updates
* Restart Host
* Run Docker for Windows as Administrator
* Go to Docker Settings and **disable experimental features**
* Apply (Docker should restart)
* Open Hyper-V Manager in Windows - Verify Moby VM is running

Incidentally, I also had Stanfords FAH running whole hog on my CPU and GPUs, I paused the CPU tasks during the docker restart to ensure there was enough cycles for the VM to boot up in a timely manner. Not sure if that makes any difference, but it was an additional thing I did.

**Comment by achinthas** [comment]
I had the same issue. After that I have reinstalled the edge version and change the VHD location. It worked.

**Comment by staff0rd** [comment]
In my case, I attempted to browse to the path noted in `Settings > Advanced > Images and volumes VHD location`.  This resulted in a windows dialog saying something along the lines of "You don't have access to this, click Continue (UAC) to permanently access this location", after which I restarted docker and the problem was resolved.

**Comment by rn** [comment]
@sstodd7532 Unfortunately, there is very little in your Logs. Could you try the most recent version?

@strever There is a Linux kernel crash in your logs, actually there are several different ones, they all look related to the context switch code.

It looks like you have a skylake processor, which Linux detects and then tries to use the appropriate context switch code for that processor. Unfortunately, the version of Hyper-V does not correctly handle this processor. We had several issues like this in the past.

I'm afraid the only solution is a Windows update. I don't know if this was fixed with a regular patch to build 14393 or if this requires an update to a newer Windows version.

I'm closing this issue as Won't fix as this is not something we (Docker) can fix, but please report back if an update did fix it.

These were the only diagnostics ID I could find.
