### ISSUE TITLE
Configure default virtual switch instead of DockerNAT (external)

### ISSUE THREAD

**Issue by vvsh** [docker/for-win#594]
### Expected behavior

I am able to change default network adapter of MobyLinuxVM

### Actual behavior

When I change MobyLinuxVM network adapter to newly created switch, then after the restart, docker switches to DockerNat

### Steps to reproduce the behavior

  1. Create new external virtual switch
  2. Change network adapter of MobyLinuxVM to newly created switch
  3. Restart Docker for Windows

Result: MobyLinuxVM has DockerNAT adapter.

Is it possible to change it to external by default?
Thanks.

**Comment by friism** [comment]
Thanks for posting this!

Can I ask for more details on your use case for this feature?

**Comment by vvsh** [comment]
Sure. I need to expose my containers to the local network. I would like to connect to them from my Android application in the same network.

**Comment by imarotte** [comment]
This is a similar issue to #367  and the fact we don't have a good way to interact with the local network in a secure way

**Comment by emarques** [comment]
I'm trying to do exactly the same as @vvsh. Is there any other alternative to sort this issue?

**Comment by viktorvillalobos** [comment]
The same here.

**Comment by zayscue** [comment]
Same here.

**Comment by jcmarchi** [comment]
How stupid this problem is. I hate applications that force the hand on users. I know it is for security purposes, but not all Docker usage is for production environments and this "limitation" prevents developers from set their network environments accordingly with their needs. Also, why MACVLAN doesn't work in Windows? In Linux it all work, flawlessly, but in Windows nothing does. I am not sure if Docker team is not competent enough to develop proper code in Windows or if they simply do not want to make it available for Windows users. Either way, it is a shame (and this is a voice of frustration speaking out loud). 
Note: I am frustrated mostly because I can make it work very easily by adjusting the Default Switch and the DockerNAT, then making the Network "external", but after each reboot, Docker simply UNDO my changes, which is extremely annoying, aggravating and unacceptable!!!!!

**Comment by myusrn** [comment]
In the windows 10 October 2018 / rs5 [ and April 2018 / rs4 ] release the Hyper-V "default switch" setup is the recommended special case nat configuration as it automatically provides an optimized nat based external network connectivity story w/o a developer having to change external network adapter binding when switching from undocked wifi adapter to docked wired adapter.  For that reason alone the dockers for windows install should simply install and use that always present and suggested "default switch" option for the "MobyLinuxVM" network adapter setting unless/until a developer reconfigures it to a switch setup that is defined to use internal or private network setting.   Sounds like currently if you make a change to "MobyLinuxVM" network adapter setting it always changes it back to the installer created "DockerNAT" setup which is configured just as an internal network nat configuration only.

**Comment by jcmarchi** [comment]
Hi @myusrn, thanks for the kind reply.

In fact, you are entirely mistaken in how Docker force the hand over user's preferences if you try to customize your workspace.

Try to do the following: create a network and give it an IP range (I.e. 172.168.0.1/24). Then build a LAMP Stack container and attach it to your network and give it an IP in the rage you defined, for instance, 172.168.0.10. You should be able to open a browser in the host and access the IP of the container and see the HTML page of the LAMP Stack, but you can't. The reason is that Docker runs isolated from the host via a network layer that only allows it to access the internet. Well, the solution should be simply: NAT. By setting the NA (or the Default Switch) to the Private network should allow the host to communicate with it, right? Well, yes and no. For certain configurations it may still fail because the IP may not be in the scope of the local network, which should be easily remediated by adding the IPs in your physical NIC or implementing a second NAT to interface both networks.  :-)

Oh, yeah. Now it works and should work for everyone... Uhuuu!!!!  :-D

But, hold your horses... :-/

Your happiness will end when you reboot the computer, reload Docker or upgrade it.  :-O

Some of the changes will be reverted and your settings will be broken, regardless of whatever you do, it will always get broken by Docker after a reboot.  :'-(

Basically, doesn't matter what you "adjust" in your network, either on Default Switch, NAT or even if you create your own, Docker will revert, block or adjust itself to NOT function as the user desires for long. >:-@

And, please, do not say we can (or should) use ports to point to the container and all would work fine because that is the most stupid thing ever! It does work, indeed, but it should not be the only way for it to work. I can list hundreds of reasons it would prevent a team of developers from using Docker, or situation where some products wouldn't find it appropriate or fail in this scenario. 

If Docker claims to be a virtualization solution, it should at least behave as if it was one.

I studied Docker from the inside out for quite a while, and it baffles me the reasons why there is an "internal switch" that no one can access that only exist to "adjust" its properties to the network, designed specifically to force or limit the network interconnectivity to whatever Docker Dev Team believe it should be. 

First of all, why an assigned IP to a Docker container cannot be accessed by the host machine and is forcefully blocked in Windows? In Linux, after a few tricks and tweaks, It can be done with no issues... 

All explanations I ever heard for the aforementioned gravitate around other "Docker needs", but I don't care about swarns, container level of communication or whatever security or isolation Docker try to implement. All that, for me, is irrelevant and I should be able to disable or bypass it. In my case, for my needs, I simply want to create a network, assign a static IP to a container and be able to access it from the host (and access the host from it) as if it was another machine in the network. There is not a simpler requirement than that (and Docker fails to deliver it)!!!!

Truth is, and I say it after actually studying it: Docker in Windows is stupidly implemented. The network layer should be completely redone to a proper implementation. Also, network drivers should exist across platforms, like anything else in the network environment. In special, network drivers are inexplicably weirdly implemented. Not only they differ from host to host, but some are either missing or not implemented at all (like the "macvlan" or the "transparent" one in Windows,). Why are they even there if they don't work or are not implemented? Why it is not done in a standardized manner across Host OSs?

Even beyond Windows Docker fails in terms of Virtual Machine's accuracy. If you run a Linux distro in a Docker container (regardless of the host), the iptables implementation gets bypassed by a subsystem on the container boot that ignores or revert some rules. Some other very important resources like the FSTAB are completely ignored when the container runs. That's why I said that Docker resembles a virtualization, but it doesn't exactly do what a virtualization system should do!

You may ask: are there ways or workarounds for those "problems"? Yes! But they should not even exist in the first place!

Please, do not take this rant as if I hate Docker. I like it. I actually use it and I am able to bypass all those "limitations" I listed, and for me and my teams, it does work as intended... But, what pisses me off is that I was forced to jump through hoops and wast hours and hours of debugging and tests to get those simple things done right. 

Things like having the guest os mounting a shared folder from the host via network, or access the WebServer that is running on a container from the browser in the host machine. Those should be straightforward and out-of-the-box functionalities and not challenges to be overcome. 

Docker is so weird that, in Windows, even the simplistic -v (volume) flag for a long time it has been driving everyone nuts by failing and complained about a "firewall" blockage (which was untrue). Just recently (and finally) an update resolved this bug (alleluia for that)! 

Can you imagine if you implement CIFS in a Linux OS that runs in the container and when you try to mount a shared folder from the host via SAMBA you realize it cannot be done because there are two "flags" that were purposefully created and enforced when you run the container exactly to prevent the container from accessing the host via CIFS? Yeah... It is unbelievable but it is true. Just try it and when you are done trying come back and ask for the resolution...

Docker should respect whatever settings that are defined by the administrator of the host and its network. If it is being used for a complex swarn, so be it. All good! If it is done as a basic implementation, so be it. All good! But, if it is a custom specific setting for an elementary purpose such as a development environment that needs no security or limitations, so be it too!!! Please, stop preventing it from being done!

Historically, any product that enforces difficulties for no good reason eventually gets redesigned or abandoned by the industry. In the case of Docker, when the roadblocks are purposefully created as part of the software and not a causality of misconfigurations, it raises serious red flags against the product.

Docker has all the great ingredients to become an industry leader, but it fails in the most basic concept when it to not deliver what it is expected of it. Eventually, something that does deliver that will surface and the market share will get segmented, giving a chance for other products to take the lead.

It has happened before, it will happen again.

**Comment by abarke** [comment]
The work around for me was to edit the `MobyLinux.ps1` file that sets the defaults for **Hyper-V**:

`C:\Program Files\Docker\Docker\resources\MobyLinux.ps1`

Replace the last section of the file with the following:

```
function Set-Switch-Private {
    Import-Module NetConnection
    Invoke-Expression -Command 'Set-NetConnectionProfile -interfacealias "vEthernet ($($SwitchName))" -NetworkCategory Private'
    Write-Output "Set interface 'vEthernet ($SwitchName)' profile to Private"
}

# Main entry point
Try {
    Switch ($PSBoundParameters.GetEnumerator().Where({$_.Value -eq $true}).Key) {
        'Stop'     { Stop-MobyLinuxVM }
        'Destroy'  { Stop-MobyLinuxVM; Remove-Switch; Remove-MobyLinuxVM }
        'Create'   { New-Switch; Set-Switch-Private; New-MobyLinuxVM }
        'Start'    { Set-Switch-Private; Start-MobyLinuxVM }
    }
} Catch {
    throw
    Exit 1
}
```

Reference: https://github.com/docker/for-win/issues/367#issuecomment-321422831
