### ISSUE TITLE
ETA on version containing 19.03.7

### ISSUE THREAD

**Issue by ebalders** [docker/for-win#5980]
Is there an ETA on a version of Docker Desktop for Windows that contains Docker Engine 19.03.7?

**Comment by mat007** [comment]
We’re hoping to do a Stable 2.2.0.4 release including an upgrade of the Docker Engine in a few days.

**Comment by stephen-turner** [comment]
However, I'm interested in why you ask, @ebalders. Was there something specific you wanted from 19.03.7? Or is there some reason why you always need to be on the latest?

I ask because it is not our assumption that we need to make a Desktop patch as soon as there is an Engine patch. Instead our policy is that we will consider including the latest stable Engine whenever we happen to be making a Desktop patch for other reasons. I'm interested in whether this is a problem to you.

cc @nebuk89.

**Comment by ebalders** [comment]
@stephen-turner I've been tracking this issue in docker engine that I bumped into on Windows in December: https://github.com/moby/moby/issues/36831#issuecomment-593398341

**Comment by stephen-turner** [comment]
Ah, OK, so it's something specific in this release. Thanks.

**Comment by isanych** [comment]
I'm also waiting for 2 issues which suppose to be resolved in 19.03.7, one of them is mentioned above, another is hard to reproduce without our environment, so I have not created an issue for that, I've tested that second issue was resolved in master (as there binaries for master available) before 19.03.6 release - but because there are no release binaries I do not even know if fix made into 19.03.6 or 19.03.7

**Comment by stephen-turner** [comment]
OK, thanks. As @mat007 says, we plan to have a new Desktop release within days (probably tomorrow or Monday, we try not to release on a Friday).

**Comment by stephen-turner** [comment]
2.2.0.4 is now released. Even on a Friday.

**Comment by isanych** [comment]
What about docker ee, who is packaging it now? Both DockerMsftProvider and DockerProvider (https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json and https://download.docker.com/components/engine/windows-server/index.json) have 19.03.5 as latest.

**Comment by stephen-turner** [comment]
Docker EE is now owned by mirantis.com not docker.com.

**Comment by isanych** [comment]
Is there any non gui installers or packages of docker ce for windows? So it could be installed on windows server without gui and hyper-v the same way as docker ee is installed?
