### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by ruidc** [docker/for-win#600]
... when pulling containers. All drives in windows still have space - what device is running

already tried:
- prune 
- image removal
- factory reset
- uninstall + reboot + reinstall

Diagnostic id:
  -  A9A0EDF3-69CD-4E05-B440-DC6D9080FE46/2017-03-21_18-17-41

**Comment by friism** [comment]
What image are you pulling and how much space is on your system drive?

**Comment by ruidc** [comment]
images are from our own registry and have tens of gigabytes free on all drives.

**Comment by principat** [comment]
The problem is that not the free storage of your physical drives is interesting, but the free storage of the vm.

Start hyper-V Manager, stop docker vm, increase the size of the virtual hard drive and restart docker. This should help

**Comment by aensidhe** [comment]
> Start hyper-V Manager, stop docker vm (MobyLinuxVm), increase the size of the virtual hard drive and restart docker. This should help

Does not help us.

We have CI and agents are constantly building, pulling and pushing images. Within 2 working days it is guaranteed that we'll have "no space left on device error".

**Comment by jasonbivins** [comment]
Hi @ruidc   @aensidhe 
The MobyLinuxVM is hard-coded for a 60gb drive.  You can change this by making a change to one of our startup scripts.
1. Stop Docker
2. Go to C:\Program Files\Docker\Docker\resources and find MobyLinux.ps1 line 86
3. Then find `$global:VhdSize = 60* 1024* 1024*1024`    Change the 60 to the drive size you'd like. 
4. Restart Docker 

Please keep in mind that this change will be reverted after upgrades or reinstalls.

Please let me know if this helps and I'll put it into a KB

**Comment by ruidc** [comment]
Sorry but I've gone back to toolbox where at least i have transparency into what is going on. But a KB would have been nice to have sry the time i was taking a decision. 
Regards, Rui 

-------- Original message --------

**Comment by principat** [comment]
Why was it closed without solution just a workaround?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.08.17, 23:29, Jason Bivins <notifications@github.com> schrieb:
Closed #600.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/docker/for-win","title":"docker/for-win","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/docker/for-win"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #600."}],"action":{"name":"View Issue","url":"https://github.com/docker/for-win/issues/600#event-1205564968"}}}

**Comment by marcelriegr** [comment]
This problem persisted since 3 years ago without any working solution introduced by the Docker team. Even with 500GB of vm storage this problem keeps occuring in our place.

`docker system prune` failed to clear data buildup in the vm and just shows `Total reclaimed space: 0B` everytime.

The only workaround is to create new vm by either resetting Docker to factory defaults or increasing the vm storage size.
