### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable - WIN10 Enterprise LTSB

### ISSUE THREAD

**Issue by jkutil** [docker/for-win#614]
### Expected behavior
Docker starts successfully.

### Actual behavior
Docker attempts to start, MobyLinuxVM successfully starts and is visible in Hyper-V, but stops/starts 2-3 times, and then Docker gives the error screen with:
```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information
Crash report:
1F0BC284-4721-450A-AF5C-7D4A5627CFE2/2017-03-31_15-11-29

Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/03/31 15:02:45.793
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise 2016 LTSB
Edition: EnterpriseS
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616

### Steps to reproduce the behavior

  1. Start Docker
  2. Wait
  3. Crash

**Comment by tomheinisch** [comment]
Same here:
```

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by friism** [comment]
@tomheinisch can you please also add a diagnostic ID.

@jeanlaurent can someone look into this?

**Comment by tomheinisch** [comment]
Diagnostic ID:
B490FB11-ADD4-4814-A71F-9ACB525F1A95/2017-04-12_10-23-58

**Comment by patrick-mota** [comment]
Same problem here but I think this problem exists in a ton of issues but no one find a solution.

Some people reported reinstalling hyper-v and docker made it works others just launch docker as administrator...

For me it worked for 1 week then suddently stop working with the same error.

**Comment by tomheinisch** [comment]
Probably related to #592.

**Comment by ptoonen** [comment]
Having the same issue but only when booting in Parallels PRO. When I use bootcamp, Docker runs fine. 
Diagnostics ID: B9D457CE-1BA5-407C-B913-E38836BB92C5/2017-05-17_11-56-03

**Comment by octomantis** [comment]
Diagnostics ID: 6530ECC5-C88E-40F5-9452-266737718FAD/2017-05-20_17-45-34

I am running Windows 10 Enterprise. Not in a VM. Very keen to know the root cause and fix.

**Comment by octomantis** [comment]
My issue got fixed when I quit the app and restarted. It automatically chose 'No proxy' in the settings.

**Comment by phibersirhack** [comment]
Some time docker works well but most of the the  time I get this  "Docker hv-sock proxy (vsudd) is not reachable" error.  Not sure why this is happening. 

Diagnostic ID: 1BBB2FA1-36E1-4F88-9963-453D52251713/2017-07-05_10-28-10

**Comment by rn** [comment]
@ptoonen Running Docker for Windows on in a Windows 10 VM is not supported (see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios). Your VM is hung when calibratrating the TSC which often happens with nested virt and something outside our control.

@jkutil @tomheinisch There is a Linux kernel crash in your logs, actually there are several different ones, they all look related to the context switch code.

It looks like you have a skylake processor, which Linux detects and then tries to use the appropriate context switch code for that processor. Unfortunately, the version of Hyper-V does not correctly handle this processor. We had several issues like this in the past.

I'm afraid the only solution is a Windows update. I don't know if this was fixed with a regular patch to build 14393 or if this requires an update to a newer Windows version.

I'm closing this issue as Won't fix as this is not something we (Docker) can fix, but please report back if an update did fix it.

Thanks
