### ISSUE TITLE
Please reopen #1580

### ISSUE THREAD

**Issue by davidmatson** [docker/for-win#6223]
#1580 is an acknowledged issue. Please re-open that one and close this one. (The robot incorrectly closed it despite a /remove-lifecycle stale comment.)

**Comment by stephen-turner** [comment]
Strange your first /remove-lifecycle stale didn't work. As you saw, it worked the second time, but that was after the bot had closed it.

In any case, as @mat007 commented, the problem is not in the Docker Desktop code but in the engine, so moby/moby would be the right place for it. Unfortunately we can't just move the issue as it's not in the docker org.
