### ISSUE TITLE
Filesharing failed when upgrading to 2.2.3.0

### ISSUE THREAD

**Issue by hantsy** [docker/for-win#6234]
Diagnose ID: 0E368F8D-D32C-4FD6-AB44-E4BAAC17AADA/20200405150458

Not changed the settings in the File Sharing, which is working in the formor 2.2.2.0, but failed after upgraded.

When I started docker by Docker Compose command, and got failure.

```
ERROR: for quarkus-sample_postgres_1  Cannot create container for service postgres: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled"}

ERROR: for postgres  Cannot create container for service postgres: status code not OK but 500: {"Message":"Unhandled exception: Filesharing has been cancelled"}
ERROR: Encountered errors while bringing up the project.
```

**Comment by akhzarjaved** [comment]
Got same issue.
any fix?

**Comment by dannypike** [comment]
For me, a workaround was to change Docker to use WSL 2. It won't help those who have to use existing data sitting inside a container but my database is not (yet) hard to regenerate from scratch.

Enabling WSL 2 required me to update to the Windows 10.0.19041.330 from [here](https://www.microsoft.com/en-in/software-download/windows10); I had been running Windows 10 build 18363.900. That took about 30 minutes, most of which was done in the background.

When Windows finished rebooting (two minutes of staring at a blank screen is scary!), I finally got to log and click the WSL 2 button in the Docker Desktop Settings panel. Docker then started prompting me to do a couple more things (such as running a PowerShell script) with appropriate reboots. After another 15 minutes of this, volume mounts started working.

I am now using Linux containers rather than Hyper-V images (the DockerDesktopVM in the Hyper-V Manager is "Off") and I can see the container using my shared Windows folder.

**Comment by hantsy** [comment]
@akhzarjaved I switched to WSL 2 backed and there is no need to set up **File sharing** there(no such an option at all).

**Comment by akhzarjaved** [comment]
> @akhzarjaved I switched to WSL 2 backed and overcame this barrier, and there is no need to set up **File sharing** there(no such an option when selecting WSL).

I have switched back to 2.1 version, this solved my issue.
WSL2 haven't released for me yet.
