### ISSUE TITLE
Enable multiprocessor decompression of layers

### ISSUE THREAD

**Issue by snorrk** [docker/for-win#6271]
Support was recently added to Moby to enable multiprocessor decompression of layers by leveraging the pigz tool instead of Go's single threaded gzip implementation:

https://github.com/moby/moby/pull/35697
https://github.com/moby/moby/commit/fd35494a251a497c359f706f61f33e689e2af678

Windows containers tend to be fairly large (gigabytes), which makes multiprocessor decompression of layers an especially important feature for the Windows version of dockerd.

The notes for the pull request say `This code is not vendored, but will be used
if it autodetected as part of the OS` but I was unable to find the `unpigz binary not found in PATH, falling back to go gzip library` log message during container pull, indicating that this code path is never executed when running dockerd on Windows

Since there is a Windows implementation of pigz (https://blog.kowalczyk.info/software/pigz-for-windows.html) I assume that support for multiprocessor layer decompression would be fairly straight forward to implement for the Windows version of dockerd?

My lack of Go skills prevent me from digging into this myself, but I would be happy to assist in any way I can (e.g. documentation, testing etc.)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
