### ISSUE TITLE
Not able to build the IoTEdge module on Windows container

### ISSUE THREAD

**Issue by sharadrumane** [docker/for-win#6287]
https://github.com/microsoft/DockerTools/issues/247
the above url is the issue previously i have open, but got suggestion to open new issue in the repo as it can be specific to windows container. Please go through above issue you will come to know what i am exactly facing.
 
Here is my Docker File

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1809 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "abcd.dll"]

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
