### ISSUE TITLE
kubernetes wont start

### ISSUE THREAD

**Issue by th3infamous18** [docker/for-win#6319]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by VBDotNetCoder** [comment]
Could be the same issue i was facing you can confirm this by looking in the Docker Log file 
C:\ProgramData\DockerDesktop

service.txt is your latest start , if you see the message 
"Error while setting up kubernetes: cannot expose the external port: listen tcp 127.0.0.1:6443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.. Retrying in 1s"

Then you encountered what i have experienced ..

My issue and the solution : 
https://github.com/docker/for-win/issues/6317

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
