### ISSUE TITLE
Docker got crashed when installing the Docker for Desktop windows pro 10

### ISSUE THREAD

**Issue by sriram474** [docker/for-win#6436]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows Pro10
  - Docker Desktop Version: Latest version coming from the download
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Azure cloud server VM

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sriram474** [comment]
Same Issue happened for me as well.

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
