### ISSUE TITLE
What's the future plan for LCOW?

### ISSUE THREAD

**Issue by 0x53A** [docker/for-win#6470]
LCOW is really neat to build windows and linux containers in parallel. Do one ``dotnet publish`` and two ``docker build``, and you can support both Docker on Win and on Linux.

At least in theory ...

I'm hitting https://github.com/docker/for-win/issues/2623 every second push, and there wasn't any response, or even acknowledgement of the issue.

Yes, I know it is experimental, but there isn't really any alternative, I don't want to maintain a linux buildserver just to build the docker images.

--------

Will LCOW stay in experimental forever? Will it be removed in a few weeks?

Will the LCOW backend be replaced with WSL2? As I understand it the WSL2 backend replaces the Moby VM, but you still have to explicitly switch between Windows Containers and Linux containers, not like with LCOW and the ``--platform`` flag.

-------

I could see that LCOW was moved from Moby to ContainerD: https://github.com/moby/moby/issues/33850

What does that mean? Is ContainerD a part of Docker Desktop (and/or EE), or is it something separate?

Thanks!

**Comment by nebuk89** [comment]
LCOW is an upstream component to us: we bundle it. As you note, it's still experimental, and has been for years now. To be honest, it has never reached the level of quality upstream that we felt we could label it as non-experimental in Docker Desktop.

Our attention has mostly moved onto WSL 2 now. It's a much better technology, and we're expecting it to be released by Microsoft in their Windows 2004 release. We haven't yet made any final decisions regarding the future of LCOW, but I would recommend WSL 2 as the long term solution.

The remaining part of your question is about switching between Linux and Windows container engines. We know this feature was one of the attractions of LCOW, and one of the main reasons people liked it despite other quality problems. It's a valid use case, but it turns out that we have only a very small proportion users using both Linux and Windows containers — it's usually one or the other — so we haven't prioritised as much as if we'd had more users wanting it. But I think it would make an excellent feature request for the docker roadmap: maybe you could submit it in the docker/roadmap repository.

Thanks!
Ben

**Comment by 0x53A** [comment]
Thanks for the response! For me the main feature is not _running_ them in parallel, but _building_ them in parallel.

**Comment by riverar** [comment]
Missing from this write up is Docker Enterprise. Docker-EE cannot utilize WSL2, so are they stuck now?

**Comment by stephen-turner** [comment]
This GitHub repository is only about Docker Desktop, not Docker EE. Docker EE is not even owned by Docker, Inc. any more, but by Mirantis, so you would need to ask them what their plans are with respect to LCOW. Sorry not to be more helpful, but we have no visibility into their plans.

**Comment by nebuk89** [comment]
@0x53A heard loud and clear. Are you doing this from a single compose file right now or is that your goal? (I have had this feedback from else where :) )

And @riverar as Stephen says, this is just for Desktop edition and doesn't reflect the conversation around  Engine or Enterprise Engine :)

**Comment by 0x53A** [comment]
> @0x53A heard loud and clear. Are you doing this from a single compose file right now or is that your goal? (I have had this feedback from else where :) )

Two dockerfiles for now, but if I changed the FROM line to use an ARG I could probably use just one.
