### ISSUE TITLE
docker for window not pull any image except hello-world

### ISSUE THREAD

**Issue by kashifsaeed79** [docker/for-win#6479]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:C02568D5-54EE-400B-B8CF-B85ED0366119/20200428104107

### Expected behavior
![docker-error](https://user-images.githubusercontent.com/31384726/80479767-f77d2780-8968-11ea-8759-d64b56fcfd73.JPG)

### Information

  - Windows Version: window 10 Pro N
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by thaJeztah** [comment]
Looks like you're trying to run a linux container, but your Docker Desktop is currently running in "windows containers" mode, so it tries to find a Windows image named `ubuntu`, which does not exist.

If you want to run Linux containers, read the [Switch between Windows and Linux containers](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers) section in the documentation.

I'll close this issue, because this doesn't look like a bug, but feel free to continue the conversation
