### ISSUE TITLE
ERRO npm install

### ISSUE THREAD

**Issue by Slender1808** [docker/for-win#6513]
`FROM node:current-alpine
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]`

**ERRO**

Step 4/7 : RUN npm install
 ---> Running in 75df1b8102b8
added 101 packages from 102 contributors and audited 230 packages in 7.208s
found 0 vulnerabilities

The command '/bin/sh -c npm install' returned a non-zero code: 4294967295: failed to shutdown container: container 75df1b8102b8fc3c6ec4606f627c9c36a3e70290efb734507eb377ade48e8257 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 75df1b8102b8fc3c6ec4606f627c9c36a3e70290efb734507eb377ade48e8257 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
