### ISSUE TITLE
Docker crashes when mounting a folder in a volume D

### ISSUE THREAD

**Issue by Siron777** [docker/for-win#6541]
Hi,

I have an image build on servercore:1909-amd64 with a volume D (VOLUME ["D:"]).

Whenever I start a container created with this image and a shared volume on the drive D (-v "XXX:D:\XXX"), it crashes with the error:
`docker: Error response from daemon: container 72a904654e95fc0935d5f9610662be17a2a18d8e448ab72750f8375867e763d7 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).`

This error is referenced by someone else in [https://forums.docker.com/t/how-to-mount-any-directory-on-windows-host-to-d-drive-inside-the-windows-container/67589]().

I have docker desktop community 2.2.0.5.

Simon

**Comment by stephen-turner** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in not in our org (it's `moby` not `docker`).

**Comment by Siron777** [comment]
Done: [https://github.com/moby/moby/issues/40899](url)
Thank you for the redirection, I was not really aware of the components involved in docker.
