### ISSUE TITLE
Archive/tar: invalid tar header message when export or import

### ISSUE THREAD

**Issue by swieczkowski** [docker/for-win#660]
### Expected behavior

Success import image.

### Actual behavior

"Error response from daemon: Error processing tar file(exit status 1): archive/tar: invalid tar header"

### Information

  - If we want to export container using **>** then we got wrong file/error on import. 
  - If we want to import image using **|** then we got error
  - Diagnostic ID: 65607FD9-95F8-4697-86E9-82CAC340FD2A/2017-04-20_21-49-26
  - Windows 10 Pro
  - Docker 17.05.0-ce-rc1-wind8 (11189) edge 73d01bb
  - **Temporary solution** for export is to use: docker export --output="export.tar" container_id
  - **Temporary solution** for import is to use: docker import export.tar

### Steps to reproduce the behavior

  1. docker export container_id > export.tar
  2. cat export.tar | docker import - exampleimagelocal:new

**Comment by snorrk** [comment]
This could be related to a PowerShell limitation: https://github.com/docker/for-win/issues/758

**Comment by mikebolland** [comment]
Is this related to https://github.com/moby/moby/issues/33586 ?

**Comment by danter** [comment]
I made some tests on my machine with the different ouput types (STDOUT or file output switch -i) and the sizes differs with a lo and when I opened the files in a diff-tool it complains about different carriage return types. Moving on I also opened the two files in a hex editor, and turns out the version that was created using STDOUT had a hex 0x00 character for every second character. My guess is that it might be the classical problem where carriage return differs between linux and windows, and also a problem where windows uses UTF-16 by default and not UTF-8. Effectively corrupting any form of character strings or binary data. My system is a windows 10 pro system and I also used powershell for generating the files.

**Comment by alpmarangoz** [comment]
Also files created with powershell are considerably larger. For example: 
- Valid Cassandra image file created with CMD: 323,032KB 
- Faulty Cassandra  image created with Powershell: 653,040KB

**Comment by andygarfield** [comment]
Use command prompt for loading the image instead. Powershell uses UTF-16 for everything, so that explains the doubling of the size.

**Comment by vegetazaiyyan** [comment]
**To export:**
docker container export <container_id> -o <image_name>.tar
**To import**
docker image import <image_name>.tar <custom_image_name>

Please note in Windows use -o instead of >. The export done with > works with Linux/MAC only.
