### ISSUE TITLE
Container hangs with 2.3.0.2 while compiling code shared from Windows host

### ISSUE THREAD

**Issue by Ezekiel-DA** [docker/for-win#6666]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C273B6F4-6AE6-4BDF-AC20-A38DD8430BA7/20200512222151

### Information

I maintain a Docker based dev environment at work to allow our developers (on Windows machines) to easily build and run our multiplatform code under Linux for testing.

Until Docker Desktop 2.1.0.5 (included), building code that lives on the host and is shared into a container used to work fine. Our toolchain is complex, proprietary and ancient unfortunately so it's hard to give an easily reproducible scenario.

Ever since the change to the new file sharing implementation, I've had recurring but seemingly random "file not found" errors for files that definitely exist on the host during builds. Reverting back to 2.1.0.5 always fixes these. Upgrading to 2.2.0.0, then various builds from other issues related to file sharing, always eventually broke again.

I'm currently evaluating 2.3.0.2 to see if I can tell my coworkers to migrate... and I'm running into similar issues.

I realize an issue that is essentially impossible to reproduce outside of my environment is a huge pain to look at but I was finally able to at least capture a Diagnostic while the container was hung (it should have been working on building C++ code and was just sitting there not responding to inputs, even attaching and trying to CTRL-C the compilation).

I'm hoping an expert can share what, if anything, this Diagnostic reveals!

Thanks!

**Comment by djs55** [comment]
@Ezekiel-DA thanks for the report. I've a few questions:

- Does your build happen inside one long-lived container or are there multiple temporary ones? I ask because there is a known race where cache flushing is handled asynchronously after a container exits, which might be too late if another container immediately restarts.
- Are the files which aren't found generated during the build or are they source code or assets that have been around since the beginning? I ask because a failure to find a file which was always present is probably in a different part of the code. A failure to find a recently created file is probably in the caching logic.
- Do some file operations happen outside the container or is it all inside the container? I ask because it takes a short time to propagate changes from the host to the container which could cause a "File does not exist" if a program inside the container assumes the file must exist because the host just created it. A workaround in this case would be to move all the file creation operations inside the container.

From the diagnostics logs there's a suspicious error:
```
 2020/05/12 22:16:17 can't convert error type: rpc error: code = Unknown desc = The handle is invalid.
```
-- this suggests that Linux sent a request to manipulate a file handle but the handle was already closed.

From the diagnostics filesystem trace (the same thing you can see yourself with `docker run -v /run:/run djs55/grpcfuse-control:2.2.0.5 stats calls --follow` or `--format=json` instead of `--follow`)
- at 2020-05-12T22:18:27.591847223Z a file called `.HeaderTable.file` was not found. Unfortunately the trace is limited in size so I can't see any previous mention of this one
- at 2020-05-12T22:18:27.60618522Z the `.HeaderTable.file` was checked for again
- at 2020-05-12T22:18:27.710138897Z a file called `HeaderDir.txt` was not found. Again the trace was too limited for me to see what happened earlier.

Thinking of possible workarounds in the meantime:
- you could write a `Dockerfile` for your project and build the project with `docker build`. This would be less incremental, but the file access would be much faster (since it would be local to Linux rather than remoted from Windows).
- I don't know how much flexibility you have about the Windows version you run, but Microsoft are about to release the 2004 update (the .iso is already available for download but it's not quite on Windows update yet). This version has full "WSL 2" support which would enable you to store your code on the Linux filesystem, but edit it seamlessly from Windows. Compiles would then be native and fast. The trick there is to switch Docker to the WSL 2 backend, use `wsl` to enter the Linux environment, switch to the Linux filesystem with `cd ~` then run `explorer.exe .` and `docker run -v ~/...` to see/edit/use the files in Windows.
- you could try a two-way filesystem sync tool. I would recommend https://mutagen.io/ which will perform a two-way sync between your host and your build container. Source code edits are copied into the container while build artifacts are copied out. The latency is pretty good and the build performance is excellent, since the files are built from the container.

**Comment by Ezekiel-DA** [comment]
@djs55 thank you for the response!

Let me see if I can provide some more info. I'm sorry this issue is such a mess of giant traces and a weird environment, I know I'm kind of abusing Docker to do something that would best be done by giving our developers actual Linux machines / VMs 😅 

* Our builds happen inside a long lived container. Said container packages our in house toolchain and dependencies and sets up access to pre-built code produced elsewhere in the company that our app relies on. After that it essentially just runs bash so devs can attach to it and build / run interactively
* The files that seem to error out are all build artifacts; I haven't seen missing files on actual source code so far
* Everything happens inside the container (but the entire source and artifacts tree is mapped in from the host); there should be no file operations going on outside the container (with the possible exception of real time scanning from the security software we can't turn off)

I'll give it another shot this week (I had to roll back to 2.1.0.5 to get work done), especially with the diagnostic output you recommended.

As far as workarounds go, unfortunately we don't have access to WSL2 yet (we're stuck on an older Windows release). I'll give Mutagen a shot but my big hope for the new file sharing implementation was to remove steps in our dev process (having to share the drives in Docker settings, and in our case having to manipulate local firewall settings to successfully do so) rather than add a steps that I bet my coworkers will not follow 😅 

Thanks!
