### ISSUE TITLE
Docker desktop cannot enable hyper-v service

### ISSUE THREAD

**Issue by williamzhao95** [docker/for-win#6675]
For me, I have open hypyer-v in windows10 18363.812, but when docker desktop start  it shows cannot enable hyper-v service

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
