### ISSUE TITLE
Host machine CAs not trusted in docker engine

### ISSUE THREAD

**Issue by damnlogin** [docker/for-win#6732]
Hello

I am using 2.3.0.2 (stable) version of Docker for Desktop on top of WSL2, Windows 10 version 10.0.19035.1.
When building docker image one of the steps is to download script from external site via https.
As in our company the web gateway decrypts traffic - I have corporate CA certificate installed to my Local Machine/Trusted Root Certificate Authorities cert store. I manually registered the CA in my Ubuntu WSL2 image with `update-ca-certificates`, so in Ubuntu console any `curl` to a valid external https endpoint succeeeds, but within `docker build` it does not recognise the corporate root cert.

### Expected Behaviour:

Any root certificate installed in local machine Trusted Root Certificate Authorities to be trusted withing `docker build` process as described in [docker docs](https://docs.docker.com/docker-for-windows/#how-do-i-add-custom-ca-certificates).

### Actual Behaviour:

Any https requests that go through corporate proxy and get certificate replaced fail with error 
`curl: (60) SSL certificate problem: unable to get local issuer certificate`

**Comment by simonferquel** [comment]
This is actually by design (and would do the same on Linux): each container has its own registry of trusted certificates isolated from the host.
Docker build runs each step in a container, so if you want to trust a cert that is not trusted by default, you need to add it to the container using whatever ca-management tools provided by the container base distro.

**Comment by damnlogin** [comment]
I see, thank you!
