### ISSUE TITLE
Docker containers keep hanging

### ISSUE THREAD

**Issue by Turtlehead13** [docker/for-win#6776]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 111B3444-E8BF-46F2-BB0E-E7E3FC732A9B/20200518031418 
Also caused a crash report with ID 111B3444-E8BF-46F2-BB0E-E7E3FC732A9B/20200518031859

### Expected behavior
Containers not to hang
### Actual behavior
Roughly every 10 minutes to an hour the containers hang. Sometimes restarting Docker fixes it. Sometimes rebooting host machine works.
### Information

  - Windows Version: win 10 1909
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by HeinDR** [comment]
I think I have the same issue. The containers become unresponsive and bringing them down (I use docker-compose) results in errors on certain containers. What helps for me is restarting docker for windows. After that bringing all containers down and then bring them up. If I dont bring them down the nginx container won't start.

It's hard to determine what is causing this. Sometimes I have the feeling that it's more likely to happen when I do multiple page refreshes in a short time.  But of course you would be more likely the discover unresponsive containers when you're busy refreshing the pages.

**Comment by ManfredLange** [comment]
This issue could be related to https://github.com/docker/for-win/issues/6847 or have the root cause.

**Comment by HeinDR** [comment]
I agree that #6847 could be the root cause. The errors that I'm getting when the containers become unresponsive seem to be quit random, but after a bit closer monitoring they all seem to be related to some service not being able to read the contents of a file. 
I also took a closer look to the nginx container that was not able to start. Turns out this time it was because of nginx not being able to read the certificate files.
The good news is that, with a bit of luck, WSL2 will be available this week and this will probably have a good change of fixing these file system issues.
