### ISSUE TITLE
FROM requires either one or three argument

### ISSUE THREAD

**Issue by admoca60** [docker/for-win#6845]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
In a Dockerfile, regarding documentation, FROM instruction should accept the platform, the image name, and the alias.
https://docs.docker.com/engine/reference/builder/#from

### Actual behavior
It seems that Docker interpret alias as two different arguments "AS" (first one), "aliasname" (second arg) so actually, the instruction FROM is receiving four parameters:

FROM platform (first param) imagename (second param) AS (third param) aliasname (fourth param).

Then I receive this error message in build time:  "Dockerfile parse error line 1: FROM requires either one or three argument"
### Information

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: personal laptop

### Steps to reproduce the behavior

  1. Try to create an image with the FROM instruction like this "FROM --platform=linux/arm/v7 arm32v7/openjdk:11.0.3-jre AS RaspberryPIArch"

**Comment by admoca60** [comment]
If I try to not use the alias, the problem now is that FROM receive only two args: platform and imagename so I have the same error.

**Comment by mat007** [comment]
This does not look like an issue with the Docker Desktop application itself but with the upstream docker windows container implementation so I'm closing this issue. Could you please open an issue on https://github.com/moby/moby instead as that is the more appropriate place?
Sorry, I would move it myself, but I can't because it's in a different org (it's `moby` not `docker`).
