### ISSUE TITLE
Docker Desktop error to run hello_word image

### ISSUE THREAD

**Issue by ashish202** [docker/for-win#6870]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?

**Comment by ashish202** [comment]
@mat007 Problem got sloved... Please upload one documentation " How to enable vitalization on windows 10"  I did already through some random search on Internet. but it will be helpful if its on official docker troubleshooting page. so others will save time of 2-3 hours which I lost. :)

**Comment by mat007** [comment]
Thanks @ashish202 for your feedback. Is https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization not enough? Anything we should add in there?

**Comment by ashish202** [comment]
@mat007 @....Yes it helped, but just to figure out/diagnose the problem. But "How to convert visualization disable to enable state" It requires another search outside the documentation. It will be helpful if you add that also in TOPIC - VIRTUALIZATION MUST BE ENABLED.
