### ISSUE TITLE
docker hangs, perhaps while creating a container (then crashes getting diagnostics)

### ISSUE THREAD

**Issue by rfay** [docker/for-win#6888]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A332CD75-9D61-49B5-97C6-F08D7F8B1B74/20200526201442

### Expected behavior

No hanging or crashing

### Actual behavior

My test runners (Docker Desktop for Windows v2.3.0.2) have been periodically hanging, it appears while creating a container.  I took a look at one of them today to see if I could get more information.

First, I took diagnostics.

Then I told it to upload the diagnostics. Docker Desktop crashed. It gave me the exact same description for the crash report (A332CD75-9D61-49B5-97C6-F08D7F8B1B74/20200526201442)

### Information

  - Windows Version: Win 10 Pro 1909 Build 18363
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

<img width="687" alt="testbot-dell-win10pro-1" src="https://user-images.githubusercontent.com/112444/82947300-0bfb1280-9f5d-11ea-91ba-209c77c6c3c4.png">

### Steps to reproduce the behavior

This is currently intermittent, although I do see it probably once a day.

**Comment by lehades** [comment]
I've been suffering something similar since the last update:
- Intermitently, once a day Docker freezes
- All my containers running in compose become unavailable
- System doesn't respond to any command (docker stats, etc... simply don't return anything)
- Trying to restart docker just crashes
- System reboot gets everything back up and running

One thing I've noticed is that when it freezes, my system drive usage spikes to 100% reads (500-600 mb/s sustained) and stays there for hours, last time the drive was HOT(90ºC according to aida64).

After exiting docker disk usage goes back to normal ¿have you noticed that?

**Comment by djs55** [comment]
Thanks for the report. I'm not sure why the diagnostics upload crashed (!) but at least the upload did work. I had a look through the filesharing logs and there are a bunch of anomalies:

1. the logs are full of these
```
level=error msg="ENOSYS: grpcFile.Chmod fd=1608 perms=420"
```
Several FUSE operations can be performed either on a file path, or on an open file descriptor. This is the open file descriptor version of `chmod`. Usually in FUSE `ENOSYS` means, "I don't know how to implement this, don't ask me again". I was expecting the `ENOSYS` to cause this never to be called again, and for the system to fall back to the file path version. However given the volume of log spam this is obviously incorrect for this particular call so I've implemented this function. At the very least this will avoid spamming the log file but it may also have been causing a bug (e.g. if the file is renamed and then the path re-used, the meaning of the two calls becomes different)

2. while examining the code I realised that the server was trusting the (Linux) client perhaps a little too much. If Linux were to reference a non-existent open file descriptor then the server would probably crash. I've guarded all the file descriptor lookups and returned `EBADF`. This may never have happened, but it's good to be safe.

3. the logs were also full of these
```
17:22:17 can't convert error type: rpc error: code = Unknown desc = The handle is invalid.
```
There are very suspicious because a "normal" filesystem error (like `EINVAL`, `ENOENT`, `EBADF` etc) is returned in a gRPC response message which looks like this:
```
message ChmodResponse {
    Status Status = 1;
}
message Status {
    int32 Code = 1;
}
```
 and returned to Linux. This error is actually a lower-level RPC failure, perhaps at the transport level. I checked the handling of these and discovered that we were converting them to FUSE errors with [fuse.ToStatus](https://github.com/hanwen/go-fuse/blob/730713460d4fc41afdc2533bd37ff60c94c0c586/fuse/misc.go#L40) in the library we're using. Unfortunately this will take "unknown" errors and convert them into `ENOSYS` which can cause problems -- often (but not always!) this tells Linux not to bother trying this call again. This was the cause of a recent bug where the Microsoft MSSQL image [wouldn't start](https://github.com/docker/for-win/issues/6646). I've corrected this by logging the error (since it's really unexpected, possibly a transport error) and returning a hopefully more harmless `EIO`. I'm hoping when this next triggers I'll get a better idea of what the root cause is, and hopefully avoid breaking the filesystem in the process. With any luck it'll be a transient error (and hopefully a fixable one)

Do you have any tips on how to reproduce these errors? I'd quite like to dig into them more.

In the meantime I've made a developer build with these minor fixes in case you want to try it: https://desktop-stage.docker.com/win/edge/45529/Docker%20Desktop%20Installer.exe

Thanks again for your help!

**Comment by rfay** [comment]
Thanks for the careful look. I'm reluctant to put a one-off version of docker desktop on my test runners, which is mostly where I've seen this happen.  Is this the same as 2.3.0.3 with just instrumentation changes? Can it be upgraded to the next stable? 

Unfortunately, I don't have a way to recreate the error, but the nearly 2-hour long ddev test run seems to bring it out on occasion.
