### ISSUE TITLE
upgrade to 2004 and enable wsl 2 failed

### ISSUE THREAD

**Issue by Diluka** [docker/for-win#6968]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 47A10DD9-CCC7-4F86-A58C-3E1C80017E2E/20200530093312

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by simonferquel** [comment]
Hi, you actually ran into 2 issues:
- first, we have a bug in handling the Windows Update (which is fixed in an upcoming patch): when windows is updated while docker desktop is running, it will restart the Docker Desktop Hyper-V VM automatically, leading on Hyper-V locking a few important files and making the first attempt to run Docker Desktop fail afterward.
- Second, I see in the logs many input/output errors, that I actually see when WSL 2 is in an unstable state (we don't know the root cause yet, but we are working with Microsoft to fix that).

Something you might want to try:
- Quit Docker Desktop
- Unregister docker-desktop and docker-desktop-data WSL distros (`wsl --unregister docker-desktop` and `wsl --unregister docker-desktop-data`).
- Restart the computer (to make sure WSL 2 get back to a good state)
- Start Docker desktop

**Comment by Diluka** [comment]
thx. unregister docker distros and restart works
