### ISSUE TITLE
Unable to Start Docker with Linux Containers on Windows 10

### ISSUE THREAD

**Issue by teafg** [docker/for-win#6976]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by cwhsu1984** [comment]
Usually, when I start a container, it returns the container id. However, after the latest update, it starts container without giving container id. Plus my terminal always stuck at the command that I execute to start the container

**Comment by mat007** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
