### ISSUE TITLE
Docker upgrade error on Windows 10 Pro

### ISSUE THREAD

**Issue by angelcramirez** [docker/for-win#7004]
Hello and thanks for the reply

OS: Windows 10 Pro

Recently I tried to update my Docker installation with a running container, and I ran it with normal privileges, this means I just double clicked the installer file, though the account that I executed with has Administrator access. The installer prompted me that I had an existing version and went over the uninstall process fine, but when it tried to upgrade to the newest Docker Desktop version it failed. 

I tried running again the same installer with "Run as Administrator" but got several lines of error that I couldn't understand and unfortunately didn't take note of any of these errors.

Then I tried restarting my machine, tried again running the installer with Administrator privileges, and it executed correctly.

My doubts are:

1. Could the first time when I tried upgrading my Docker version, was it related I had running containers, or is it I didn't run it with the highest privileges?

2. I noticed I recovered my recent Docker container, I assume that being because I am logged on to my Docker account where Docker is running. Would the attempt to upgrade Docker, leading to "errors" and then tried installing again upon restart could have potentially damaged my newer Docker installation or my existing container?

I've attached the Diagnostics file if that could point to something :)

Thanks for all of your insights.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A352B74D-B4F0-40FF-9F4F-B1958B7F532C/20200602062435

### Actual behavior
Docker performed upgrade with errors

### Information

  - Windows Version: Win 10 Pro
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ecow** [comment]
I confirm a problem on docker update to 2.3.0.3  in Windows 10.
I'm using automatic update. Docker shows the update popup (as usual) but if I press "install Update" nothing happens (o at least this is what I experience). On next docker start, the same popup is shown. 
![Annotazione 2020-06-02 094223](https://user-images.githubusercontent.com/5788689/83493666-647a6480-a4b5-11ea-839c-03d08a553834.png)

**Comment by pihalve** [comment]
I experience the same thing as @ecow. After digging a little around, I found an entry in Windows Event Log stating that a SoftwareRestrictionPolicy has blocked "Docker Desktop Installer.exe"

The thing is that in my company we have policies restricting exe-files running from the user's AppData\Local\Temp folder (and subfolders hereof). So if we need something to actually run from that location, we need the admins to make an exception to the policy, allowing the specific exe-file to run.

But even when they do that, it still doesn't work. I'm not sure why, but it looks like that when the installer is running it starts another process named with what looks like random characters. My suspicion is that this somehow conflicts with the software restriction policy, because when we disable the policy entirely everything works fine. The problem is though, that we can't make exceptions to the policy targeting process names with random characters.

Is it possible you could use another approach for the installer/updater, so it uses a more static naming approach? Or can you recommend other ways to solve the issue?

**Comment by pihalve** [comment]
/remove-lifecycle stale

This is still an issue.
