### ISSUE TITLE
hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by dAti** [docker/for-win#701]
### Expected behavior

Docker is running

### Actual behavior

Error : hv-sock proxy (vsudd) is not reachable

->Tried disabling Hyper-V and uninstalling Docker - > restart Windows -> Install Docker -> no effect

### Information

Diagnostic ID : 6CB81B89-A57F-420B-9288-A095769640D8/2017-05-03_17-52-36

### Steps to reproduce the behavior

  1. Start Docker

**Comment by sean-brandt** [comment]
Same issue.

EC87B7A6-0188-41AC-B323-ECA7E6375F35/2017-05-03_21-17-33

**Comment by l3nko** [comment]
Me too.

34FB04C0-16A9-4AB1-B3FA-40D1615B05F0/2017-05-09_09-19-07

**Comment by dAti** [comment]
Try this : 

Disable HyperV  

bcdedit /set hypervisorlaunchtype off
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V 
 
In registry: set EnableVirtualizationBasedSecurity to value 0 in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard

Restart and try again

**Comment by l3nko** [comment]
Today after windows update KB4019472 docker is back to running.

Thanks.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by rn** [comment]
@dAti There is a Linux kernel crash in your logs (see below), actually there are several different ones, they all look related to the context switch code.

It looks like you have a Kaby/skylake processor, which Linux detects and then tries to use the appropriate context switch code for that processor. Unfortunately, the version of Hyper-V does not correctly handle this processor. We had several issues like this in the past.

I'm afraid the only solution is a Windows update. I don't know if this was fixed with a regular patch to build 14393 or if this requires an update to a newer Windows version.

I'm closing this issue as Won't fix as this is not something we (Docker) can fix, but please report back if an update did fix it.

Thanks
