### ISSUE TITLE
Vmmem using over 10gb memory and around 50% CPU

### ISSUE THREAD

**Issue by DanielWhite21** [docker/for-win#7033]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: 4884BBF1-F512-480C-96CD-2F39954C36F7/20200603092132

### Expected behavior
To run docker jobs in a timely manner
### Actual behavior
Its taking over 2 hrs to build an R application, using over 10gb mem, and up to 50% CPU
I have to keep restarting my laptop in between build jobs and some of these are requiring minor tweaks to the R app.
I understand its a large build out but it takes around 20 mins on my Mac
### Information

  - Windows Version: Version 2004 (OS Build 19041.264)
  - Docker Desktop Version: 2.3.0.3(45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. docker run -it --rm \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
    -e AWS_DEFAULT_REGION=eu-west-1 \
    --name shinyvolcano \
    -p 127.0.0.1:80:3838 shinyvolcano # use http (80) or https (443)

**Comment by 4O4** [comment]
I have the same issue when running docker-compose setup on windows 10. CPU usage of vmmem is insane and It's also consuming tons of RAM, but somehow the task manager always shows 0 for RAM usage of vmmem. 

I can't provide diagnostics ID right now, because it takes forever to finish for some reason and my computer is burning hot during that. I also can't publish my docker-compose.yml right now and I don't know yet if this also happens when running some specific single container. I need to check it out yet.

However, what I can provide is my observation of some of the internals of the VM the docker stuff is running on. In the Hyper-V manager I've seen that the docker machine is eating up to 20% CPU (at least it was claiming so) and the usage was rapidly changing like there was a lot of intensive stuff running, then stopping for a very short time, then spinning up again. The normal CPU usage for my current setup should be 1% max. I am sure none of my apps are causing such usage spikes, so I've decided to dig into the VM to see what is it doing. 

I've done the following to gain access to the VM (found the commands somewhere on the internet):

```
docker run --privileged -it -v /var/run/docker.sock:/var/run/docker.sock jongallant/ubuntu-docker-client 
docker run --net=host --ipc=host --uts=host --pid=host -it --security-opt=seccomp=unconfined --privileged --rm -v /:/host alpine /bin/sh
chroot /host
```

then I've ran `top` to see what processes are running and what I've seen was `/usr/bin/lifecycle-server` being on top of the CPU and RAM usage stats, together with memlog daemon (although the values of the memlog were jumping a lot, lifecycle server was constantly on the top).  

I've killed the lifecycle-server process and everything turned back to normal, my CPU fans stopped spinning like crazy, the temperatures went back to normal. This problem comes back from time to time, sometimes after I reboot the computer, sometimes after restarting the docker engine. 

I'm repeating the steps described above every time this happens to kill the lifecycle-server and stop that massive heat generator. Everything in docker is working absolutely normal after that and my room becomes completely quiet with no fans spinning :)

My guess is that lifecycle-server is spamming a lot of error / warning/ debug / whatever logs, these logs are then filling lots of RAM and the intensity of writes causes lots of CPU usage too. Although that is only my blind guess since I have no idea what exactly is this process responsible for and sadly there is no source code available for Docker Desktop stuff.

I hope this helps to narrow down the problem a bit.

**Comment by prabaprakash** [comment]
It consumes memory. let be it. Once you done with POC. 

Turn off Windows Subsystem for Linux

To turn off Vmmem simply go into Powershell or whatever terminal you like to use under admin rights and enter the cmd 
```
wsl --shutdown
```
 when you done with playing in wsl1/2.

**Comment by soletan** [comment]
> It consumes memory. let be it.

Sorry, not an option. My containers are crashing due to OOM conditions, even host system is showing several strange behaviours because of low memory, my fan is going wild all the time ... and all that happens _while_ I'm using certain docker containers in WSL2 ... I don't think WSL2 is ready for production use because of this RAM issue unless WSL2 is preventing its Linux kernel from grabbing all memory for file caching. And I'd love to have Docker Desktop slowing down on promoting WSL2 as the preferred option right now.

**Comment by prashanthwagle** [comment]
Any remedy by installing Docker without WSL (like how you do it in Win8)?
Else instead of docker desktop, how about installing docker on wsl2 itself?

**Comment by unickq** [comment]
I was able to limit wsl resources by creating `C:\Users\YOUR_USER\.wslconfig`
```
[wsl2]
memory=4GB
processors=4
```

![image](https://user-images.githubusercontent.com/6696821/103652405-bfa09800-4f6b-11eb-96fd-c49b1bb2aea3.png)
