### ISSUE TITLE
HNS failed with error : Unspecified error

### ISSUE THREAD

**Issue by yanhua1012** [docker/for-win#704]
### Expected behavior
create container and start it

### Actual behavior
the container has been created successfully, but  one error appears
### Information

  -the Diagnostic ID is 32942DB2-6AED-4D46-8BE0-E8B3539FDE9B/2017-05-04_18-50-51
  -the version is Version 17.03.1-ce-win5 (10743) Channel: stable。
  -my OS is windows 10 professional 

### Steps to reproduce the behavior

  1. Enable Hyper-V feature in windows
  2. Install Docker for Windows 
  3. set  "graph" to "D:\\ProgramData\\Docker" in configuration file
  4. switch to windows container
  5. execute command such as "docker run --name MyIIS -d -p 8080:80 microsoft/iis"
  6. failed to create endpoint MyIIS on network nat: HNS failed with error : Unspecified error
Error: failed to start containers: MyIIS

**Comment by tapasudenia** [comment]
I am facing the same error since couple of days, the only thing is I am trying it through the TFS 2017 Relase definition to create the release.
I have the problem like, I have 2 containers, if one works the other will not work and throw the "on network nat: hns failed with error : unspecified error." error
