### ISSUE TITLE
Docker desktop missing shared drives and advanced options for linux containers

### ISSUE THREAD

**Issue by Heloise-Chauvel** [docker/for-win#7143]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 749679E0-45AC-48C7-B5FD-50CA103EE7BB/20200609173833

### Expected behavior
The "shared drives" and "Advanced" options should been visible on my docker desktop app, because this is the Linux containers conf.

### Actual behavior
They are missing. Please see my Diagnostics ID and Screenshot attached.

Note : I Don't see my VM in Hyper-V
Note 2 : I had to execute these lines in PowerShell to switch to Windows Containers (otherwise I got errors)
Disable-WindowsOptionalFeature -FeatureName microsoft-hyper-v -online
restart-computer
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
restart-computer
Enable-WindowsOptionalFeature -Online -FeatureName Containers -All

### Information

  - Windows Version: Windows 10 Professional
  - Docker Desktop Version: 2.3.0.3 (455119)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Download Docker Desktop from official page for Windows - stable (https://www.docker.com/products/docker-desktop)
  2. Install it
  3. Navigate to Dashboard > Resources : 2 options missing (shared drives ans Advanced)

**Comment by Heloise-Chauvel** [comment]
![image](https://user-images.githubusercontent.com/24738465/84183123-65813800-aa59-11ea-859c-7a74105f429c.png)

**Comment by Heloise-Chauvel** [comment]
![Issue7143](https://user-images.githubusercontent.com/24738465/84183557-14be0f00-aa5a-11ea-9f25-a59d2e5f8bcc.png)

**Comment by alverfernando** [comment]
![image](https://user-images.githubusercontent.com/53840869/84184406-a9793a80-aa63-11ea-8b3e-63214ce8e1f0.png)

**Comment by stephen-turner** [comment]
@Heloise-Chauvel Are you using the WSL 2 integration instead of Hyper-V for your Linux containers?

**Comment by julien-campbell** [comment]
Hi,

I am having the same problem as explained above where Shared Drives does not appear. However, I am running on Windows 10 Home so I do not have the option to unselect "Use the WSL 2 based engine" as in brackets it says "Windows Home can only run the WSL 2 backend". Is there a way to solve this?

My end goal is to share my c drive on my windows computer to a linux container I am trying to run called madslupe/hddm. This is because when I run my container with the command:

docker run -it --rm -v c:/school/2020_summer_research/analysis_data/dir_of_data_and_notebook/:/home/jovyan/data -p 8888:8888 madslupe/hddm jupyter notebook

I get a URL which I open to an interface of Jupyter Notebook (as expected) and the file folder I open called "data" is empty, where I am expecting it to contain all my data and analyzing scripts.

Is this due to the c drive not being shared? Or is this an error relating to mounting in my command line I typed out or something else?

**Comment by stephen-turner** [comment]
I answered this in #7199. I'm going to close this ticket now.
