### ISSUE TITLE
Docker crashing everytime on Windows Insider build 19640_mn_release_200530_1731

### ISSUE THREAD

**Issue by gagneet** [docker/for-win#7178]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
FFA1E65D-E740-47E1-AE7B-F0BCADE6744E/20200611064916

### Expected behavior
No crash expected.

### Actual behavior
![image](https://user-images.githubusercontent.com/203433/84354263-e7ad6000-ac03-11ea-8a28-d707cd3ebdda.png)

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

[log.txt](https://github.com/docker/for-win/files/4763112/log.txt)

**Comment by ranarn** [comment]
This is not an Docker issue, as your error message clearly says.
 I guess you didn't try to start WSL to check if it works on your machine first?

The error message clearly says that WSL 2 requires an update to its kernel component, and even gives you a link to follow. Did you follow it?

And since you are using windows insider build, you should have read the insider blog that says:

We changed the servicing model for the Linux kernel inside of Windows Subsystem for Linux 2 distributions. This build includes this change to remove the Linux kernel from the Windows image, and instead have it be serviced via Microsoft Update, the same way that 3rd party drivers (like graphics, or touchpad drivers) are installed and updated on your machine today.

So go ahead and install the WSL kernel, and i bet it is solved after that.

**Comment by gagneet** [comment]
Hi @ranarn, I have indeed read through the document and installed the WSL_Install_x64 package. I have tried by uninstalling Docker and keeping the WSL package installed and then reinstalling, and also vice-versa. I have even tried to do it on a new system with the same Insider build. 

I believe you are right on the Windows Insider build and it might actually be a Windows build issue and I have reported it to them also to work on it. 

The required WSL kernel has been installed already and I will check again later when they given out a new build. Just wanted to ensure that the issue is reported on all parties, hence the report.

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)
