### ISSUE TITLE
Permissions denied when calling chown on a host mounted directory or file in Windows Creator's Edition

### ISSUE THREAD

**Issue by JoeTortuga** [docker/for-win#733]
### Expected behavior
file or directory should have its ownership changed, and the process continue

### Actual behavior
getting error: 
 chown: changing ownership of '/var/lib/ghost': Permission denied

### Information
 Diagnostic ID:  EAE9842A-2782-4C62-8209-C672207965AA/2017-05-10_21-19-13

I'm building from the ghost dockerfile, using docker-compose, and trying to mount the directory /var/lib/ghost from a local directory on my windows machine.

Here is my docker-compose.yml file:
    version: '3'
   services:
     blog:
        image: ghost
     volumes:
         - ./blog:/var/lib/ghost
     ports:
      - "2368:2368"

Here is the ghost dockerfile
https://github.com/docker-library/ghost/blob/1e9307eb3642dd5fb2b8e9c25a15fa524ad0e219/debian/Dockerfile

### Steps to reproduce the behavior

  1. create above docker-compose.yml file
  2. create the blog directory
  3. run docker-compose up

If you do not do #2, and depend on docker to create the directory, that creates a different error:
ERROR: for blog Cannot start service blog: error while creating mount source path '/C/Users/joe/Projects/site/blog': mkdir /C/Users/joe/Projects/site/blog: permission denied ERROR: Encountered errors while bringing up the project.

I took this same docker-compose.yml and ran it at work, with the same version of docker (I can upload a diagonstic id from there as well, if that's needed) and the process worked (it created the directory, chown'd it, and copied files into it as expected by this image).

The only difference that I can see between the two is the windows version
the PC I'm having difficulty in has 
VERSION: 1703
OS Build: 15063.138

the PC that is currently working has
VERSION: 1607
OS Build: 14393.1066

**Comment by JoeTortuga** [comment]
Even though I uninstalled and reinstalled docker this did not work. In order to get it working, I had to reset credentials and then share the C drive again, at which point my issue went away.

Not sure what caused it, but my issue is fixed, so I'm closing this.

**Comment by JollyWizard** [comment]
Similar issue when using a compose project folder copied from a Linux Mint machine.

I had relative file mounts going into and out of the container.  Each one generated an error like:


`Cannot start service $SERVICE: error while creating mount source path '$EXTERNAL_PATH': chown: changing ownership of '$INTERNAL_PATH': Permission denied`

Solution indicated by Joe worked for me.

* Docker Tray (Right Click) -> Settings ->
* Reset Credentials
* Share `C`
* Apply

Then `docker-compose up` worked.  

No need to reboot system.  Was worried that might be necessary because of `Reset Credentials`

**Comment by SychevIgor** [comment]
reset didn't help me
