### ISSUE TITLE
Docker does not start because of port 2375 binding

### ISSUE THREAD

**Issue by djechelon** [docker/for-win#7360]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 71C92EEB-7D59-41A6-8E87-8B9B0108F0A8/20200622071528

### Actual behavior

Docker doesn't start. By checking the startup logs I found the following

```
[09:01:51.256][ApiProxy          ][Info   ] ðŸ€ socket server listening : \\\\.\\pipe\\dockerGuiToDriver
[09:01:51.257][ApiProxy          ][Info   ] adding mutagen rewriter
[09:01:51.259][ApiProxy          ][Fatal  ] listen tcp 127.0.0.1:2375: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
[09:01:51.260][ApiProxy          ][Error  ] Process died
[09:01:56.265][ApiProxy          ][Error  ] Auto restarting process
```

### Information

"Recently" upgraded to Windows 10 2004. All my troubles with Docker started there. A few days ago I posted and self-closed a similar issue with SQL Server port (1433) that was mitigated by simply wiping all Hyper-V related tools from my Windows installation

#7312 

### Additional information
I was able to **mitigate** by disabling insecure TCP in Settings window. Right now Docker is started

### Steps to reproduce the behavior
I think it's randomic, but these were two reboots in a row where the problem persisted

**Comment by PavelSosin-320** [comment]
The same happens to me - Docker doesn't start because during startup it itself checks the daemon status using URL localhost/status if insecure TLS less TCP communication is enabled. 
Diagnostics ID 
![image](https://user-images.githubusercontent.com/54495912/85298554-e81fe380-b4ac-11ea-8e4f-e4f522f97760.png)

Indeed, nothing is listening on port 2375 inside docker-desktop distro and neither port is propagated to the host. It breaks **WSL2 integration which worked OK for me until Docker stoped to start. I even got the valid responses on most of the status requests like when I used CURL from Windows Command prompt:**
CMD > curl localhost:2375/info
{"ID":"V5IS:GI5O:PBNF:66GO:JKPW:77XG:EZ4F:FQLZ:BSRD:QAIH:KAQ5:FLRU","Containers":71,"ContainersRunning":50,"ContainersP ....
and
curl localhost:2375/services 
[{"ID":"0m0sgnzkrhpptb9xj8oou5a66","Version":{"Index":18731451},"CreatedAt":"2020-05-17T05:28:45.6294418Z", .....

Maybe Microsoft hardened Firewall rules for WSL and Docker needs its own rules separated from WSL rule of  Microsoft?

**Comment by PavelSosin-320** [comment]
Maybe it is the same issue as [Docker proxy issue](https://github.com/docker/for-linux/issues/566)
I have IPV 6 Windows, IPV6 enabled Docker, IPV6 Home network. I use IPV6 external network. If IPV6 localhost is proxied via Docker Proxy installed with Docker Desktop it can be the root cause.

**Comment by stephen-turner** [comment]
In the latest Edge release, 2.3.2.0, we have improved this so that application startup is no longer blocked when port 2375 is in use, and a toast notification pops up instead.
