### ISSUE TITLE
Docker cannot switch back to wsl 2

### ISSUE THREAD

**Issue by osmanraifgunes** [docker/for-win#7405]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

https://stackoverflow.com/questions/62524256/docker-switch-back-to-wsl-2

**Comment by tobico** [comment]
I ran into this issue and had to reinstall Docker Desktop to continue.

## Steps

1. Install Docker for Windows with WSL2 mode enabled
2. Open settings and uncheck the option "Use the WSL 2 based engine"

## Expected behavior

Docker checks that Hyper-V is not available and refuses to disable the option

## Actual behavior

Docker switches to Hyper-V mode and immediately exits with a message that Hyper-V is not available. It is now no longer possible to start Docker Desktop without enabling Hyper-V or uninstalling and reinstalling.

**Comment by tobico** [comment]
Can this please be reopened? As far as I'm aware this is still an issue, and I've provided detailed steps to reproduce.
