### ISSUE TITLE
[Meta] Why auto-close stale issues that are still present?

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#7456]
`docker-desktop-robot`  adds a comment:
```
Issues go stale after 90d of inactivity.
Mark the issue as fresh with /remove-lifecycle stale comment.
Stale issues will be closed after an additional 30d of inactivity.

Prevent issues from auto-closing with an /lifecycle frozen comment.

If this issue is safe to close now please do so.

Send feedback to Docker Community Slack channels #docker-for-mac or #docker-for-windows.
/lifecycle stale
```
after 30d it auto-closes that issue. 
Example: https://github.com/docker/for-win/issues/4809#event-3488560766

If no one investigated that issue, then it may still be present. 
When someone finds that issue again, he will have to duplicate and create a new issue because he cannot reopen the auto-closed one.

Auto-closing issues that are not even investigated seems like a hack to reduce open issue number...
My suggestion is to use a priority mechanism (labels?) to prioritize issues and keep low priority issues open to be resolved later.

**Comment by cdalexndr** [comment]
Robot must hate this issue because it marked it as stale as soon as I opened it...

**Comment by StingyJack** [comment]
@cdalexndr  - The bot really hates being [criticized](https://github.com/docker/for-win/issues/2953). [This one](https://github.com/docker/for-win/issues/3445) too. 

To answer your post, as far as I can figure, Docker (the company) has created software that is wildly popular, but also so full of defects, confusion, and fragility/complexity that they dont have the staff to keep up with the issue reports. Instead, in addition to already suffering from one of those aforementioned problem types, they want us to play childish "bump" games for _all of eternity_ while we hope that someone at docker will eventually fix the problem with their product. 

If we happen to forget to bump one time, then the issue is closed and we have to open a new one. (FTR, I dont think the bot actually hates the issue, I think docker (the company) is just drowning in reports so bad that they have ratcheted up the bot's assault on users to try and keep the open issues manageable.)

Really what we need is a bot that just counters this one, finding every threat-post it makes and immediately posts `/remove-lifecycle stale` on the users' behalf. And then also have it open new issues if one was closed by a bot or just closed unsatisfactorily.

**Comment by stephen-turner** [comment]
Ha ha, it closed it immediately because it saw lifecycle stale in the text!

**Comment by stephen-turner** [comment]
To answer the actual question, you're right, we do not have capacity to investigate all the old issues. But we also know that when we do look at them, the majority have in fact been fixed, either by us changing the software or because they were user error and the user has figured out what to do. So the bot is a way for us to ping the old issues and see if anyone still cares about them. It's very easy for the reporter to keep the ticket open when they receive the message if it is still an issue.

Unfortunately this is a side effect of having (literally) millions of users and only a small team. Docker Desktop is free software (in the beer sense) so (1) the size of the team does not scale with the number of people using it and (2) support is on a "best effort" basis only. We are not the only free software taking this approach with old issues.

**Comment by StingyJack** [comment]
@stephen-turner - why do you guys bother with a corporate contact point like this open-to-the-public forum? It just seems to be an avenue destined only for <strike>customer</strike> **user** dissatisfaction.

**Comment by stephen-turner** [comment]
@StingyJack You've made your views very clear on this over a long period of time. However, if you look at our release notes, you'll see that we do fix dozens of bugs every release that were reported on this issue tracker. We acknowledge that there are some long standing issues that we have not been able to fix either because they are hard to reproduce (even an issue that affects hundreds of people is only 0.01% of our user base) or because they would require a complete rewrite/rearchitecting of a large part of the code (although in that category we have tackled filesystem rewrites on both Windows and Mac in the last few months, and are currently working on Mac CPU consumption).

**Comment by stephen-turner** [comment]
Closing this ticket. The question has been answered, even if you disagreed with the answer.
