### ISSUE TITLE
Docker failed to start on windows 10

### ISSUE THREAD

**Issue by unmarshall** [docker/for-win#748]
### Environment ###
**OS:** : Windows 10 enterprise 64 bit
**Version:** 1511
**OS Build:** 10586.633
Docker 
Hyper-V has been enabled.

### Expected behavior
The docker should run on windows 10
### Actual behavior
See the error information below. Docker does not start.

### Information
When docker starts then it throws the following exception:
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.
'MobyLinuxVM' failed to initialize.
'MobyLinuxVM' failed to start. (Virtual machine ID ACFCAB44-73E3-4CE0-AE3F-F519BC6FF42B)
'MobyLinuxVM' failed to initialize. (Virtual machine ID ACFCAB44-73E3-4CE0-AE3F-F519BC6FF42B)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

If we look at the hyper-V manager then we do not see any MobyLinuxVM.
I also tried:
cd 'C:\Program Files\Docker\Docker\resources'
.\MobyLinux.ps1 -Destroy
.\MobyLinux.ps1 -Create
.\MobyLinux.ps1 -Start
This only lists the MobyLinuxVm in the hyper-V manager but the start still fails.

I have attached the logs with this ticket.

### Steps to reproduce the behavior
  1. Enable Hyper-V and reboot.
  2. Install docker stable version and start.

**Comment by unmarshall** [comment]
[log.txt](https://github.com/docker/for-win/files/998794/log.txt)

**Comment by wikrie** [comment]
I have the exact same problem, docker works before last update, so it seams to be an issue of the actual version.

**Comment by Becold** [comment]
Same problem. This happens just after installing the last update.

# Environement
Docker Version: 17.03.1-ce-win12 (12058)
Channel: stable
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393

# Log
```
Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : L’objet existe déjà.


   à Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   à Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

and same as @unmarshall, my MobyLinuxVM got deleted in the hyper-v manager.

**Comment by KADacey** [comment]
I've run into the same problem. Diagnostic ID: 33090FE1-136B-4C30-B13B-B0FD22801C42/2017-05-22_15-49-33
Has there been any progress on this issue?

**Comment by sjbanner** [comment]
Same problem, but I will add that if I delete the directory "C:\Users\jbanner\AppData\Docker", it will start normally until I reboot. Of course then I have to tell it about local drives, etc. again because that's where the config files are. And when it starts, it will re-create the files again - exactly like the ones I deleted if I haven't re-enabled drive access.

**Comment by OrionDevelopment** [comment]
I hat a broken Hyper-V Network Switch active.
I manually removed the Moby VM in the Hyper-V Manager.
Then removed all the Docker-Switches manually in the Device Manager. And reran the commands listed above on the Moby Powershell script.

A note: The Docker Switches are listed as Hyper-V Network Adapters.

Hopefully this helps you guys.

**Comment by itpcc** [comment]
Same issue
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.27/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

Diag ID: B601A2DB-F23F-4D3B-8A74-85C44A5094D6/2017-06-07_15-51-53
System:
![System](https://i.imgur.com/PpJ4td8.png)

**Comment by wikrie** [comment]
since 1 month I'm not able to start docker for windows anymore, I used it to get a working linux system into my windows, is there anybody who can check this issue?

**Comment by OrionDevelopment** [comment]
Check your network cards. Are they setup properly?

**Comment by wikrie** [comment]
Really? 
if you mean if all other applications and systemtask are running fine and have a working network connection, then the answer is yes.
It is more a question of Hyper-V image will not created prober instead of Network issue.

ps: Mybe this issue is not a docker issue maybe this is a hyper-v issue, but I do not know how to find out

**Comment by OrionDevelopment** [comment]
Well mine produced the same issue, because virtual hyper switch was not configured properly and marked it as broken. I removed the switch re installed moby and it was fixed.

It was just a suggestion to how i fixed the same crash.

**Comment by OrionDevelopment** [comment]
I am not saying with that it is a docker issue, it might as well be a virtual switch issue. It was just a suggestion on how i fixed it, and it is worth a try.

**Comment by JohannesRudolph** [comment]
Had the same problem after an update of Docker.

Docker Tray Icon, context menu -> settings -> reset -> reset to factory defaults fixed it for me.

**Comment by nickpendleton** [comment]
Same issue here. Running 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 -Start', console output shows a message I'm curious about, relating to @OrionDevelopment's comment. Message is "Enabled workaround for Build 10586 VMSwitch issue". 

Looking at DockerNAT, the virtual switch that was created by MobyLinux.ps1 -Start, there's nothing special with it. has a Connection Type of Internal Network.

Docker is currently in an unusable state for me at the moment. Reset to factory settings didn't work. I tried fully uninstalling and reinstalling in the off chance that'd help something. Nope.

Anyone else figure out a workaround or a fix for this?

**Comment by josmitc** [comment]
@nickpendleton My issue looked almost exactly like yours and I was able to fix it (been messing with the issue all day). Here's what I did: 

1. Opened a cmd window _as an admin_ and navigated to %SYSTEMROOT%\System32

2. Ran MOFCOMP WindowsVirtualization.V2.mof 

3. Don't know if this step matters, but I opened the Hyper-V Manager and connected locally, just to make sure things were working there. It was. 

4. Restarted Docker and it worked immediately

**Comment by wikrie** [comment]
I Cold solve this issue. Oh was a Security update Form MS. Many thanks to Microsoft.  After uninstall one update all is running fine again.

**Comment by dopsy** [comment]
I tried everything possible (what was possible to find on google) and the only thing that helped, is @wikrie  comment about deleting windows security update. I don't remember the name of the update, but it's the last one that windows downloaded. Windows security update ****. So remove it, and it should start working :) Thanks @wikrie

**Comment by frqc** [comment]
@dopsy @wikrie I was able to use docker about 3 months ago but failed since one MS update. I think I've been experiencing the same situation with you and could you please check and share the name of update preventing dockers to start?

**Comment by mafshin** [comment]
Workaround suggested by @N-Andronopoulos in https://github.com/docker/for-win/issues/599 worked for me in Windows 10 Enterprise

**Comment by dopsy** [comment]
@frqc i cant find the name of that update but it was showing the last one which was installed/issued on my pc. Also it stoped working when i installed rsat, remote system administrative tools so i needed to uninstall it

**Comment by BEllis** [comment]
I had this problem recently after upgrading docker for windows. The issue was that my HyperV services were "stuck" so I restarted them and then everything was fine.

**Comment by RehanSaeed** [comment]
I've also been getting this error with the latest 17.09-CE update. I've tried all workarounds on this issue and tried reinstalling multiple times but to no avail as of yet. Docker is great but so many bugs...

**Comment by benpetsch** [comment]
Problem:
- disabled hyper-v from windows features.
- reboot
- docker can not start
- (tried adding DockerNAT virtual switch within the hyper-v manager -> error)

Solution for me:
- enable hyper-v (windows features)
- netcfg -d (powershell)
- reboot
- done.

**Comment by zetnet** [comment]
just netcfg -d (admin powershell) solved the issue for me.
Thanks for the suggestion @benpetsch

**Comment by taeram** [comment]
`netcfg -d` in powershell *also* solved this issue for me. Thanks @benpetsch and @zetnet.

**Comment by LordAlastair** [comment]
@sjbanner fix worked, Thank you :D

**Comment by Getitdan** [comment]
Nothing worked for me :(

This is my error when trying to start docker:

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID F118815E-713C-40E2-9E05-1C70BB14A0A9)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by jmnicoux** [comment]
I just got this "variation" of the error: 
`Unable to destroy: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Le fichier de pagination est insuffisant pour terminer cette opération.      à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36    à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 77    à Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 61    à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59`

the command: `netcfg -d` in admin powershell followed by a reboot solved my issue.

**Comment by elimn** [comment]
I had the same problem, but none of the above solutions worked for me. I tried tons of variations on them, running various steps as an admin, rebooting in between, uninstalling and reinstalling Hyper-V. Here's what finally worked:

1. Open Hyper-V Manager
2. Click Hyper-V Settings
3. Under Server: Virtual Hard Disks click "Browse", and select an appropriate folder
4. Under Server: Virtual Machines click "Browse", and select an appropriate folder
5. Click Apply, then retry running Docker.

The problem was that ages ago I had setup Hyper-V to use a custom folder for its files. Some time during the intervening years I had delete those folders, as I stopped using Hyper-V. Thus, I was getting the exact same error message as everyone else, but for a different reason.

**Comment by durgeshkumar14** [comment]
Following worked for me...
- Disable Hyper-V
- Enable Hyper-V

**Comment by francesco-taioli** [comment]
> Problem:
> 
> * disabled hyper-v from windows features.
> * reboot
> * docker can not start
> * (tried adding DockerNAT virtual switch within the hyper-v manager -> error)
> 
> Solution for me:
> 
> * enable hyper-v (windows features)
> * netcfg -d (powershell)
> * reboot
> * done.

work for me

**Comment by infernalsirius** [comment]
The issue seems to be with the service's right to logon that is given through a GPO policy. In some case, the right does not seems to be applied. 

http://ventej.blogspot.com/2013/09/hyperv-virtual-mahine-creation-error.html

One way to fix this is to restart the Hyper-V management service:
```
# Done from an admin shell 
net stop vmms
net start vmms
```
Restart Docker and it should be able to create the mobylinux VM now.

**Comment by maiorano84** [comment]
Enabling the "Control Flow Guard" setting in Defender corrected the issue for me, but I have no clue why.

**Comment by rajvasani** [comment]
> Problem:
> 
> * disabled hyper-v from windows features.
> * reboot
> * docker can not start
> * (tried adding DockerNAT virtual switch within the hyper-v manager -> error)
> 
> Solution for me:
> 
> * enable hyper-v (windows features)
> * netcfg -d (powershell)
> * reboot
> * done.



> Problem:
> 
> * disabled hyper-v from windows features.
> * reboot
> * docker can not start
> * (tried adding DockerNAT virtual switch within the hyper-v manager -> error)
> 
> Solution for me:
> 
> * enable hyper-v (windows features)
> * netcfg -d (powershell)
> * reboot
> * done.

Hey @benpetsch , I tried this command and its deleted my network adapter. I executed this command in remote windows server after executing this command. It disconnected me from remote window server and I am not able to connect my remote system at all. It shows me message system status unhealthy.

Very disappointed.

**Comment by Kamaropoulos** [comment]
> > Problem:
> > 
> > * disabled hyper-v from windows features.
> > * reboot
> > * docker can not start
> > * (tried adding DockerNAT virtual switch within the hyper-v manager -> error)
> > 
> > Solution for me:
> > 
> > * enable hyper-v (windows features)
> > * netcfg -d (powershell)
> > * reboot
> > * done.
> 
> Hey @benpetsch , I tried this command and its deleted my network adapter. I executed this command in remote windows server after executing this command. It disconnected me from remote window server and I am not able to connect my remote system at all. It shows me message system status unhealthy.

Yeah, be aware that if you are doing this on a remote system, it will lock you out as it is going to delete the network adapter...

**Comment by dar-trifork** [comment]
this worked for me

`net localgroup administrators SERVICE /delete`

**Comment by Asesjix** [comment]
I just had the same problem. I found out that my computer name (DESKTOP-SEBASTIAN) seems to be too long for Docker, because Docker always tries to start with "DESKTOP-SEBASTI". After I wrote an entry (192.168.178.29 DESKTOP-SEBASTI) in the HOSTS file, Docker runs without problems for me.
Hope this helps to solve the problem ;-)

**Comment by chitayta** [comment]
Solution by @josmitc fixed issue for me. Thanks so much.
