### ISSUE TITLE
WSL2 Failed to restart after set expose without TLS

### ISSUE THREAD

**Issue by stefanwendelmann** [docker/for-win#7501]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0FE97E1A-4988-4A8E-B00A-9DF5A5D8A461/20200630091354

### Expected behavior
Turning off TLS 
### Actual behavior
Failed to restart
### Information

  - Windows Version: 2004 (Build 19041.329)
  - Docker Desktop Version: 2.3.0.3 (45519) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: WSL2

### Steps to reproduce the behavior

  1. Settings -> General -> Turn on "Expose daemon on tcp://localhost2375 without TLS"

**Comment by ConfidenceYobo** [comment]
I am also having this issue on Docker Desktop Version: 2.3.0.3 (45519) stable when I make any change in the settings.

**Comment by PavelSosin-320** [comment]
I have found the root cause of this issue- checkbox "Expose daemon on tcp://localhost2375 without TLS" actually does nothing. To expose TCP port it is necessary to edit daemon.conf file and add Host 0.0.0.0:2375 to the hosts list as its explained in the dockerd documentation page.
But it didn't solve all the problems for me because of the bootstrap process involves vpnkit readiness test because the mentioned version doesn't create socket files for guest services and even folder for them. It looks like a regression.
Also communication via named pipes has been replaced with interop mechanism in the recent WSL 2.
