### ISSUE TITLE
NPM CI gets blocked and docker container is not responding

### ISSUE THREAD

**Issue by CaTaDeVoPs** [docker/for-win#7503]
- [x] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
I'm doing local development using docker on windows.
I created a docker compose where i bind a folder from my host inside docker container. When running npm ci from dockeer i'm expecting to work without issues.
### Actual behavior
Running npm ci from docker is slowly deleting files till is getting blocked. In this point i'm forced to restart docker in order to run other commands from container
### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? yes
  - Is the problem new? nope

  - Windows Version: 10
  - Docker Desktop Version: latest

### Steps to reproduce the behavior
  1. Install docker for windows
  2. docker-compose with bind volume from host containing node modules

**Comment by G-Rath** [comment]
I'm having this problem too - It didn't occur in the previous major version, so I think this is one of the bugs caused by the new permission management setup.

I've seen a number of bugs get fixed - this one seems to be the last one left that I'm hitting so would love to get it resolved, as I think the new version contains some great new features.

Docker version 2.3.0.5 (48029).
Engine: 19.03.12
Compose: 1.27.2

Running Windows 10 Pro 1009 (18363.1082), using WSLv1.

I can reproduce this in my private project, but so far not been able to on my smaller attempt-to-reproduce project - I suspect this might relate to the number of dependencies being installed/removed.

This is my Diagnose ID uploaded *before* reproducing this issue: 54AB4182-2EB4-4638-9A2B-26C8B8D9C64C/20200916124137

I find this happen as soon as I run `npm ci`, and it tries to remove `node_modules` - hitting Ctrl + C does nothing, and I eventually have to force kill the container. This actually doesn't work: the container continues to run, and all attempts to stop it fail.

Attempting to exec into it results in the following:

```
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown
```

It looks to me based on the log output that the container has done a sort of complete crash, meaning its now in a processless-start that means when it comes back up it doesn't actually run anything.

This is my Diagnose ID uploaded *after* reproducing this issue: 54AB4182-2EB4-4638-9A2B-26C8B8D9C64C/20200916124708

Let me know if I can do anything else to help with this - like I said, this seems to be the only bug left that I'm hitting :)
