### ISSUE TITLE
Containers shutdown unexpectedly (failed to shutdown container / The connection with the virtual machine or container was closed)

### ISSUE THREAD

**Issue by nickwesselman** [docker/for-win#7523]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 953333DF-EA30-47EC-A977-EEAE6AE356DE/20200701174115

### Expected behavior

Containers build and start consistently.

### Actual behavior

Seemingly random (but regular) container shutdown errors during build and run.

### Information

Regularly during container build, I will encounter the following error:
```
ERROR: Service 'solution' failed to build: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet publish -c $env:BUILD_CONFIGURATION -o /build/rendering --no-restore' returned a non-zero code: 4294967295: failed to shutdown container: container a4e376c7afba3a07ae4171353b3b02f5f589ad4b7204761eb65faac31465393f encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container a4e376c7afba3a07ae4171353b3b02f5f589ad4b7204761eb65faac31465393f encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)
```
Running the build again succeeds 90% of the time. 

I see the same error regularly during container startup:

```
    "State": {
        "Status": "exited",
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 4294967295,
        "Error": "failed to shutdown container: container b091312d3bddd4226273855266bfb785629a4e9f4378521dace18b63d20b1a9f encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container b091312d3bddd4226273855266bfb785629a4e9f4378521dace18b63d20b1a9f encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)",
        "StartedAt": "2020-07-01T17:05:16.83616Z",
        "FinishedAt": "2020-07-01T13:05:18.8046686-04:00"
    }
```

Restarting the container again works 90% of the time.

I have searched existing issues but cannot find any similar behaviors described. My coworkers report seeing the same issue as well.

  - Windows Version: Windows 10 Version 1909 (OS Build 18363.900)
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

I do not have consistent reproduction steps given the randomness of this issue. It's potentially a performance degradation issue -- after a reboot the issue seems to be happening less frequently.

**Comment by TI-asilva** [comment]
I am also having random container shutdowns with Docker Desktop 2.3.0.5 and Windows 10 Enterprise Version 2004. However, I do not see the error "State" JSON as shown in the OP.

I see an error similar to the following when the shutdowns happen:

`time="2020-09-23T15:03:14-07:00" level=error msg="Error waiting for container: failed to shutdown container: container 4a8920f74e13f342438cf3f2e46632fd1cf09aaad2aa4a885469bff28c0152a2 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container 4a8920f74e13f342438cf3f2e46632fd1cf09aaad2aa4a885469bff28c0152a2 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)"`

I am attempting to build the Unreal engine in the container and have given the container a max of 15 cpus and 32gb of memory (my system has 20 cores and 64gb). The shutdowns happen fairly frequently when running the most resource-intensive part of the build (i.e. all 15 cpus are in use and >15gb of memory is in use - although, notably, it never seems to cross the 16gb in use boundary, even though I am allowing it to take up to 32gb). Less taxing builds do not typically exhibit the issue.

**Comment by warrenspe** [comment]
I'm getting the same error while building containers, very intermittently.  I'll run a docker build and get the error while trying to install python, then I'll run it again immediately after (changing absolutely nothing in between runs) and it will happily proceed through and on to the rest of the dockerfile

`The command 'cmd /S /C C:\temp\python-3.7.9-amd64.exe /quiet TargetDir=C:\python InstallAllUsers=1 PrependPath=1 Include_test=0 Include_doc=0         Include_launcher=0 InstallLauncherAllUsers=0 Include_tcltk=0 include_tools=0' returned a non-zero code: 4294967295: failed to shutdown container: container 266626a3b737dea8336b1f4d0ed8a5e1f2b0e624ce531d9ce4228eff1290d488 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container 266626a3b737dea8336b1f4d0ed8a5e1f2b0e624ce531d9ce4228eff1290d488 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)`

(Building windows containers)
Docker version 2.4.0.0
Engine 19.0.13
Windows: Version	10.0.18363 Build 18363

**Comment by mjkkirschner** [comment]
I also experience this on docker 2.5.0.0
windows version 2004 OS build 19041.572 - running in a nested virtualization environment - it has started to occur on 90% of builds - though rather recently.

@TI-asilva any clues as to what windows updates fixed this for you?

**Comment by TI-asilva** [comment]
@mjkkirschner unfortunately, the windows update "fix" was short lived and I am back to the same issues. :-/

**Comment by mjkkirschner** [comment]
I believe in my case I resolved the issue by updating vmware tools to 11.0.6 - see the release notes resolved issues here:
https://docs.vmware.com/en/VMware-Tools/11.0/rn/VMware-Tools-1106-Release-Notes.html#resolvedissues

**Comment by isccha** [comment]
I think I solved the issue by following @mjkkirschner  suggestion. I did not upgrade my vmware tools to 11.0.6 though. Instead, I did the workaraound indicated [here](https://kb.vmware.com/s/article/78550), which sums to find your vmware tools installation and run 
`vmwaretoolboxcmd.exe config set appinfo disabled true.`

**Comment by nickwesselman** [comment]
Six months later and this still happens to me. I uploaded diagnostics, is there anything else I can provide to Docker to help diagnose/debug?

**Comment by nickwesselman** [comment]
/remove-lifecycle stale

Definitely still seeing this at times.

**Comment by Saibamen** [comment]
Happen to me today

**Comment by DeDixs** [comment]
Happening for us as well. We run a Jenkins build setup using a Windows build machine to execute Windows builds (using Windows containers). This allows us to easily use different VS versions without having to maintain it all on the build PC. The containers also contain other tools we use during the build (e.g. for static code analysis).

The Jenkins build server runs a CI/CD pipeline, components are only built when needed. This most of the time works fine, however if a low-level component is committed and many build jobs are started this problem typically occurs. In such a situation different jobs are running in parallel, all in their own workspace though.

If it fails the service.txt log file shows the same first error:
[14:50:34.525][WindowsDaemon     ][Info   ] debug: failed to shutdown container, terminating it [module=libcontainerd container=4eb40d1e11c9eca8f35a10b76533443ec63b7e434785c097bdb6f3980a32f01d namespace=moby error=container 4eb40d1e11c9eca8f35a10b76533443ec63b7e434785c097bdb6f3980a32f01d encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)]

The biggest downside is that it prevents the CI/CD setup to work properly, whenever this happens we have to manually restart the Jenkins job. Restarting the job usually leads to success.

**Comment by DeDixs** [comment]
After updating to Docker Desktop 3.4.0 the issue seems to have worsened, builds now fail much more often with the same error. At this rate this will become a showstopper issue.

**Comment by DeDixs** [comment]
Updated to Docker Desktop 3.5.1, still occurring. The host OS was updated from Windows 10 1809 to Windows 10 1909 hoping that would make a difference, unfortunately it does not.

The errors are still the same:

In container-events.csv:

"sending event [event=exit event-info={ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 init 1312 4294967295 2021-06-29 13:07:27.6466424 +0200 CEST m=+16724.995297301 false failed to shutdown container: container ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a)} container=ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 module=libcontainerd namespace=moby]","11",,"0","4","0",,"36028797018963968","28504","docker",,"Application",,,"SERVER.local",,"29-6-2021 13:07:27",,,"Application","System.UInt32[]","System.Diagnostics.Eventing.Reader.EventBookmark","Information","Info",,"System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]","System.Collections.Generic.List`1[System.Diagnostics.Eventing.Reader.EventProperty]"
"failed to shutdown container [process=init error=container ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 encountered an error during hcsshim::System::Shutdown: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a): subsequent terminate failed container ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a) module=libcontainerd namespace=moby container=ebc1544d305a76ab0cfe0a0ee2098a995502dd4984de19908759f2cb9849cc07]","11",,"0","3","0",,"36028797018963968","28503","docker",,"Application",,,"SERVER.local",,"29-6-2021 13:07:27",,,"Application","System.UInt32[]","System.Diagnostics.Eventing.Reader.EventBookmark","Warning","Info",,"System.Collections.ObjectModel.ReadOnlyCollection`1[System.String]","System.Collections.Generic.List`1[System.Diagnostics.Eventing.Reader.EventProperty]"

In service.txt:
[23:47:51.143][WindowsDaemon     ][Error  ] failed to shutdown container, and subsequent terminate also failed [namespace=moby module=libcontainerd error=container 3899663479a926f5da698957b8bf3ffc3d1b0d7c0e17dc413d54b622d9288340 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The connection with the virtual machine or container was closed. (0xc037010a) container=3899663479a926f5da698957b8bf3ffc3d1b0d7c0e17dc413d54b622d9288340]

Any insights on whether this issue is being looked in to?

**Comment by stephen-turner** [comment]
Sorry we missed this one. Yes, it should, hcsshim errors are always from the Windows container code.

**Comment by nickwesselman** [comment]
Moved to moby/moby#42804
