### ISSUE TITLE
Docker Desktop crashes - I researched the problem but no luck.

### ISSUE THREAD

**Issue by fbsolo** [docker/for-win#7665]
- [**X**] I have tried with the latest version of my channel (Stable or Edge)
  - [**X**] I have uploaded Diagnostics
  - Diagnostics ID: **8E18D4CD-DF98-402E-A196-C991838A9470/20200714222623**

### Expected behavior

Docker would say that this statement

**docker build -t docker101tutorial .**

worked. I just installed Docker Desktop on this device.

### Actual behavior

Error message:

docker : error during connect: Post https://192.168.99.100:2376/v1.40/build?bui
ldargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=
&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0
&networkmode=default&rm=1&session=x1rjtor6cgu65hcu4mo53mxng&shmsize=0&t=docker1
01tutorial&target=&ulimits=null&version=1: dial tcp 192.168.99.100:2376: 
connectex: A connection attempt failed because the connected party did not 
properly respond after a period of time, or established connection failed 
because connected host has failed to respond.

### Information

  - Windows Version: Windows 10 Education, Version 2004, Build 19041.329
  - Docker Desktop Version: 19.03.8, Build afacb8b
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

  In an Admin Powershell, run

  1. docker build -t ddocker101tutorial .
  2. docker run hello-world

and it returns these respective messages:

docker : error during connect: Post https://192.168.99.100:2376/v1.40/build?bui
ldargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=
&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0
&networkmode=default&rm=1&session=x1rjtor6cgu65hcu4mo53mxng&shmsize=0&t=docker1
01tutorial&target=&ulimits=null&version=1: dial tcp 192.168.99.100:2376: 
connectex: A connection attempt failed because the connected party did not 
properly respond after a period of time, or established connection failed 
because connected host has failed to respond.
____________________

docker : C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during 
connect: Post https://192.168.99.100:2376/v1.40/containers/create: dial tcp 
192.168.99.100:2376: connectex: A connection attempt failed because the 
connected party did not properly respond after a period of time, or 
established connection failed because connected host has failed to respond.

**Comment by deniercounter** [comment]
I secoond:

Windows Version: Windows 10 Home, Version 2004, Build 19041.388 .. with WSL 2 .. and Ubuntu 20.04 on terminal
Docker Desktop Version: 19.03.8, Build afacb8b
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

/******* BEGIN Ubuntu Shell 20.04 ****************/

My Ubuntu 20.04 terminal (from MS App Store) says:
**<myusername>@DESKTOP-S22E2AB:~$ docker -v**
Docker version 19.03.8, build afacb8b7f0 

AND

**$ docker run hello-world**
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:49a1c8800c94df04e9658809b006fd8a686cab8028d33cfba2cc049724254202
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

/******* END Ubuntu Shell 20.04 ****************/

/******* BEGIN Powershell as Administrator ****************/

My elevated Powershell says:
**PS C:\WINDOWS\system32> docker -v**
Docker version 19.03.8, build afacb8b

BUT 

**PS C:\WINDOWS\system32> docker run hello-world**
C:\Program Files\Docker\Docker\resources\bin\docker.exe: error during connect: Post https://192.168.99.101:2376/v1.40/containers/create: dial tcp 192.168.99.101:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
See 'C:\Program Files\Docker\Docker\resources\bin\docker.exe run --help'.

/******* END Powershell as Administrator ****************/
