### ISSUE TITLE
After Windows 2004 update and switch to WLS 2 docker crashed

### ISSUE THREAD

**Issue by MarioKahun** [docker/for-win#7676]
uploaded diagnostic id: 620A34AC-B090-43E1-BA26-77E3713346ED/20200715150131

**Comment by ITGuyDave** [comment]
I have the same issue, diagnostic ID: AA1CFD0E-0CF9-4B77-834C-1BF55855AED5/20200715215130

My PC updated itself last night to Windows version 2004 (19041.388), and Docker was working perfectly prior to the update with WSL2. After the update, and multiple reboots - Docker fails to start. I suspect the issue is probably a change due to GA release of WSL2, probably removing the configuration Docker made upon its installation.

I ended up uninstalling Docker, running the following procedure, then reinstalling the Edge Docker Desktop variant, now everything works again using WSL2: https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2

I suspect MS probably wasn't considering those of us like me who had installed early release (non-GA) variants of both WSL and Ubuntu/Bash for Windows/etc. After everything above, back to normal again - so I'd give that a try.
