### ISSUE TITLE
Unable to launch Docker Desktop

### ISSUE THREAD

**Issue by joeltonyc** [docker/for-win#7704]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:2F7761B8-9B1C-4337-8163-D61C99CE2C10/20200717060408

### Expected behavior
Docker service launches without an error.

### Actual behavior
As detailed below.
### Information

  - Windows Version: v2004 (Build: 19041.388)
  - Docker Desktop Version: I don't know. The version available for download for Windows as of 16/7/2020
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. The docker service launches on startup of windows, and gives me the error

**Comment by nikur** [comment]
Are you running Docker as a service or how do you launch Docker on Windows startup?

**Comment by joeltonyc** [comment]
I believe I am. I'm quite new to docker. So I'm willing to help the best I
can. Also, I hoped all the info you needed would be in the diagnostic.

**Comment by nikur** [comment]
I'm not a developer but I suppose that I have the same or at least a similar problem. I configured a task run on startup to start Docker automatically. Before the latest update, everything worked fine. But ever since, Docker doesn't start automatically any longer. However, if I start Docker through the desktop symbol, Docker launches normally. So I suppose this issue is related to Docker being started in headless mode, i.e. without user interaction.
Moreover, I noticed that Docker now always prompts me whether to start the Docker service when clicking the desktop symbol even when running it with admin privileges. Starting the Docker service manually via MMC doesn't work either.
