### ISSUE TITLE
Docker failing to start on Windows 10

### ISSUE THREAD

**Issue by drnybble** [docker/for-win#773]
I have previously had Docker running successfully on this system. I updated Docker and now it is not working.

I have uninstalled & reinstalled it -- same behaviour it fails to start.

The Error dialog shows:

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
Starting Linux containers:
3428D7CA-D3F3-473E-B804-62823CB673EB/2017-05-26_12-05-50

Starting Windows containers:
3428D7CA-D3F3-473E-B804-62823CB673EB/2017-05-29_15-24-44

I have installed the latest cumulative update for Windows 10 1607.

This is a Windows 10 VM with hardware virtualization enabled (under VMWare).

The Hyper-V VM is showing CPU activity up to the time Docker decides it has failed. Is there an issue running on slow systems?

**Comment by rn** [comment]
@drnybble you are running Docker for Windows in a Windows 10 VM on VMware. This configuration is not supported (see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios) primarily because we have no control over how you configure your VM, how much resources you allocate to it and what else is happening in on the host system. Closing
