### ISSUE TITLE
Expose daemon on tcp://localhost:2375 without TLS then cannot restart docker anymore

### ISSUE THREAD

**Issue by acaiee** [docker/for-win#7841]
- [Y] I have tried with the latest version of my channel (Stable or Edge)
  - [Y] I have uploaded Diagnostics
  - Diagnostics ID: 079B6153-A1D4-4D57-B459-628A752C59FD/20200727135116

  - Windows Version: Windows 10
  - Docker Desktop Version: 2.3.0.3(45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  1. docker desktop settings
  2. select Expose daemon on tcp://localhost:2375 without TLS
  3. apply&restart
      Then it never restart successfully.

**Comment by djs55** [comment]
Thanks for your report. I see your logs have
```
listen tcp 127.0.0.1:2375: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```
So it looks like you don't have permission to bind that port (for some reason).

Unfortunately there is a known issue where this can prevent Docker Desktop from starting. This bug is fixed in Edge. In the meantime you can revert the configuration change by opening the file `AppData\Roaming\Docker\settings.json` and changing
```
  "exposeDockerAPIOnTCP2375": true,
```
into
```
  "exposeDockerAPIOnTCP2375": false,
```
Let me know if this helps at all.

**Comment by sheponion** [comment]
I had the same problem (same repeating error in my logs) and the configuration change fixed it. Thanks!
Version: 2.3.0.4 (46911) stable - WSL2
