### ISSUE TITLE
[kind/bug, area/mounts, area/linux] volumes/bind mounts of windows directories appears to be broken in docker desktop wsl2 integration

### ISSUE THREAD

**Issue by jamesk-arlut** [docker/for-win#7905]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4C2F92CF-2A4E-4F5B-A920-D12D8ADE1786/20200731141308
My computer is on a domain network without internet access, so I can't upload the diagnostics in the normal manner.  I googled for how to upload them in this case and didn't find anything.  I can provide to the team if someone can tell me how to do so.

### Expected behavior
Windows directory is mounted as a volume or bind mount in docker container
### Actual behavior
Empty directory is mounted at target directory location in docker container
### Information
Update: I just updated to the latest version of Docker Desktop (2.3.0.4 (46911) stable) and still experience the same behavior.  I also tried disabling the Windows Firewall to ensure it wasn't an issue with the firewall blocking network traffic from the Plan 9 fileshare, but there was no change in behavior.  I do not have a firewall in my WSL 2 distro.

With command docker run -it --rm -v /c/Users/jamesk/Documents/temp:/data ubuntu:bionic, I am able to see the files in the /c/Users/jamesk/Documents/temp directory in the container at /data when I run it in WSL 1, but /data is an empty directory when I run that command in WSL 2.  Same behavior with --mount type=bind,source=/c/Users/jamesk/Documents/temp,target=/data, and if I use //c/... or /mnt/c...

My setup (including history): Before upgrading to Windows 10 20.04, I used the Ubuntu 18.04 LTS distribution in WSL 1 with a Docker Client installed, in conjunction with Docker Desktop, following the instructions at https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly, with the exception that I used /etc/fstab to make /mnt/c and /c both work instead of changing the automount root entry in /etc/wsl.conf or doing a bind mount in ~.bashrc.  Volumes and bind mounts of windows directories works flawlessly in WSL 1.  Once I was able to install Windows 10 20.04, I wanted to keep my WSL 1 environment, so I installed the Ubuntu 20.04 LTS distribution to be my WSL 2 distribution.  I initially installed Docker in my WSL 2 distro using apt install docker.io instead of doing the Docker Desktop integration, and that all worked fine (volumes and bind mounts of windows directories works flawlessly in WSL 2 as well with this setup since I made the same /etc/fstab entries in my WSL 2 distro), but I decided that I wanted to just have one docker on my computer to use in Windows, WSL 1, and WSL 2.  So I uninstalled docker.io using apt in WSL 2, and followed the instructions in https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/ to enable the WSL 2 docker desktop integration (not sure if it makes any difference, but I had also previously installed KIND using the instructions on that website, as well as installed podman and singularity).  I am now able to use docker in WSL 2, including starting a KIND cluster, however volumes/bind mounts of windows directories do not work in WSL 2.  They do still work fine in WSL 1.

  - Windows Version: Windows 10 20.04 OS Build 19041.388
  - Docker Desktop Version: 2.3.0.4 (46911) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

![terminals](https://user-images.githubusercontent.com/58954584/88956907-b1837880-d263-11ea-9e7e-b39f853674bb.png)

**Comment by dodeeric** [comment]
I confirm that I have the exact same problem.

**Comment by jamesk-arlut** [comment]
@dodeeric My issue is when I run the container from within my WSL 2 distro.  It looks from your comment like you are running the container in powershell.  I have no issues when running in powershell or my WSL 1 distro.

**Comment by gynnantonix** [comment]
I'm having the same issue.  Mounting windows volumes from within Docker Compose run via WSL2, none of the windows volumes are mounted -- only the docker volumes.

**Comment by gynnantonix** [comment]
Here's a diagnostics ID, if this helps: E242C281-F2D3-4D29-B970-9E83A461A9E8/20200814132417

**Comment by gynnantonix** [comment]
It appears that this issue was caused (at least on my machine) by WSL not properly mounting system volumes in `/mnt' after updating Windows.  The volume names were there, but only the content of the system volume was available.  The issue stated here was resolved for me after closing all WSL terminals/sessions and, in a PowerShell window, doing the following: `wsl --shutdown`.  Then, upon opening a WSL session, I found all volumes appropriately mounted in `/mnt`.

**Comment by jamesk-arlut** [comment]
What @gynnantonix describes does not appear to be the same issue.  My mounts in WSL work fine (as can be seen by my listing of the directory in WSL immediately prior to the unsuccessful attempt to mount it in docker), and nothing is fixed by any number of restarts of WSL (or reboots of the computer for that matter).

**Comment by pauloricardomg** [comment]
I'm also facing this issue. It's fixed when downgrading docker to work with WSL1.

**Comment by rossng** [comment]
Is the mounted drive encrypted when your machine boots? I've had a similar issue and it seems to be related to Docker mounting the drive in WSL before the drive is unlocked.

**Comment by jamesk-arlut** [comment]
@rossng I believe the drive is encrypted, however I am a bit skeptical that this is the issue; by the time docker is starting, I am logged into Windows, and the C: drive from which I am trying to mount files/directories is definitely unlocked and available to the operating system and to applications running.  In any case, turning off encryption of the drive is a non-starter; this is a work computer, and I can't disable encryption, even temporarily to try to test if turning it off would fix the problem.

**Comment by qzk** [comment]
So I'm having this exact issue and a couple of people hit the nail on the head.

I installed WSL2 with WSL distro ubuntu2004. If I run ubuntu2004 in command prompt and cd into /mnt and enter my BitLocker drive it's empty. 

If I run a docker command that modifies a non Bitlocker volume with the :consistent flag it works fine.

But if I try to repeat the above with a Bitlocker volume, docker doesn't propagate container file changes to host nor does original host data on the Bitlocker volume even show up in the container. The volume just shows up as blank inside the container. It creates a spooky 👻 shadow volume whose changes persist even if I kill the volume and recreate it but it just never gets written back to the Bitlocker drive.

But then I ran wsl --shutdown in powershell and had docker restart the WSL2 containers.

I then ran ubuntu2004 in command prompt, cd into /mnt and my Bitlocker drive now shows up. I reran the Docker containers that modify the Bitlocker volumes and it now works.

So it seems to be that we have to restart our WSL2 distro due to a race condition where WSL2 might start before the drive is decrypted.
