### ISSUE TITLE
Hyper-V behind Proxy can't pull any image

### ISSUE THREAD

**Issue by erikbgithub** [docker/for-win#799]
Please check out the detailed description in moby/moby#33543 for details. I opened this issue as a suggestion from them.

TL;DR: new Windows Docker installed. Docker thinks everything is fine, but docker pull simply doesn't download anything and just hangs forever. Logs don't contain error messages.

**Comment by jasonbivins** [comment]
Hi @erikbgithub 
You mentioned that you're behind a Proxy - have you gotten a chance to take a look at this document?
https://docs.docker.com/docker-for-windows/#proxies
Are you pulling Windows or Linux containers ?  Do you see the same problem with either?
What happens when you try the docker login command?

**Comment by erikbgithub** [comment]
Hi Jason,

thanks for looking into this.


> You mentioned that you're behind a Proxy - have you gotten a chance to take a look at this document?
> https://docs.docker.com/docker-for-windows/#proxies
yes

> Are you pulling Windows or Linux containers ? Do you see the same problem with both?
How can I check that? The last info I have is that docker only works with Linux and even windows-docker has some kind of linux running somewhere in a VM or something.


> What happens when you try the docker login command?
Same, how can I check that? I don't have an account at dockerhub and don't plan to.
