### ISSUE TITLE
[2.3.0.4] Docker desktop crash on window startup

### ISSUE THREAD

**Issue by SangNguyenTL** [docker/for-win#8219]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D03647C0-3FE4-44B8-86E7-932A85DAA636/20200825041411

### Information

  - Windows Version: Win 10 Pro - 20197.1000.amd64fre.rs_prerelease.200818-1420
  - Docker Desktop Version: 2.3.0.4 (46911)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

**Comment by PavelSosin-320** [comment]
I have the same issue - Docker desktop fails to start!
I suspect that the main component which causes Docker desktop instability is VPNKit. Does somebody know how to deactivate and remove VPNKit completely? I have no reason to use a VPN client installed on the Docker hosts because in my area I can purchase a WiFi router with pre-installed or pre-enabled for VPN clients in any shop as a discount product to hide all my home devices at once when I will need it.
VPNKit is a kind of bloatware delivered to my computer with Docker Desktop.

**Comment by SangNguyenTL** [comment]
My problem is related to WSL, it cannot mount the directory on WSL. As if WSL was not ready, docker was running and it crashed, normally I have to restart the computer once after opening it to work normally.
