### ISSUE TITLE
Waiting for SSH to be available... getting IPV6 address

### ISSUE THREAD

**Issue by hugo6** [docker/for-win#822]
### Expected behavior
Docker is up and running!
### Actual behavior
Waiting for SSH to be available...

### Steps to reproduce the behavior
  docker-machine create -d hyperv --hyperv-virtual-switch "myswitch" myvm1 (from https://docs.docker.com/get-started/part4/#set-up-your-swarm)

Hi All, I'm getting "waiting for SSH to be available" when I try to create a docker machine with hyperV driver but sometimes it's working and sometimes not so I got the following logs. The only thing that changes is the version of the IP address : the creation fail with an IPV6. The instruction "networkadapters[0]).ipaddresses[0]" got IPV6 address when the machine creation is failing.

- When the machine is created with no errors :

Waiting for SSH to be available...
(myvm1) DBG | [stderr =====>] :
Getting to WaitForSSH function...
(myvm1) Calling .GetSSHHostname
(myvm1) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM myvm1 ).state
(myvm1) DBG | [stdout =====>] : Running
(myvm1) DBG |
(myvm1) DBG | [stderr =====>] :
(myvm1) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM myvm1 ).networkadapters[0]).ipaddresses[0]
(myvm1) DBG | [stdout =====>] : 10.23.133.214
(myvm1) DBG |
(myvm1) DBG | [stderr =====>] :
(myvm1) Calling .GetSSHPort
(myvm1) Calling .GetSSHKeyPath
(myvm1) Calling .GetSSHKeyPath
(myvm1) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@10.23.133.214 -o IdentitiesOnly=yes -i C:\Users\Toto\.docker\machine\machines\myvm1\id_rsa -p 22] C:\Program Files\Git\usr\bin\ssh.exe <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting the provisioner...

- When the machine is created with error :

Waiting for SSH to be available...
Getting to WaitForSSH function...
(myvm2) Calling .GetSSHHostname
(myvm2) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM myvm2 ).state
(myvm2) DBG | [stdout =====>] : Running
(myvm2) DBG |
(myvm2) DBG | [stderr =====>] :
(myvm2) DBG | [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM myvm2 ).networkadapters[0]).ipaddresses[0]
(myvm2) DBG | [stdout =====>] : fe80::215:5dff:fe84:ac46
(myvm2) DBG |
(myvm2) DBG | [stderr =====>] :
(myvm2) Calling .GetSSHPort
(myvm2) Calling .GetSSHKeyPath
(myvm2) Calling .GetSSHKeyPath
(myvm2) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@fe80::215:5dff:fe84:ac46 -o IdentitiesOnly=yes -i C:\Users\Toto\.docker\machine\machines\myvm2\id_rsa -p 22] C:\Program Files\Git\usr\bin\ssh.exe <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  :
Getting to WaitForSSH function...

### Information
  - Diagnostic ID : 64F0C90F-2963-4B91-97A4-4E8B649571E2/2017-06-14_14-40-28
  - Version 17.03.1-ce-win12 (12058) Channel: stable d1db126
  - Windows 10 Entreprise

**Comment by jasonbivins** [comment]
Hi @hugo6   In your first script, you used a virtual switch called "myswitch"  - are you using the same switch for every VM you create?   I can recreate this error, but only by manually changing the connection type for my virtual switch in Hyper-V.   docker-machine requires the switch to have an External Network connection type.  
When I set my switch to Private (see below)  I get the same error you're seeing when I create vm's using your docker-machine command.  When I set it to Internal, the task completes, but then gives a connection warning.

![image](https://user-images.githubusercontent.com/28021664/27153773-be7d4d94-5120-11e7-9e6a-55c3aae75b47.png)

**Comment by hugo6** [comment]
Hi @jasonbivins I'm using the same custom switch for every VM that I want to create (see following sreenshot) and it's connected to my external network.
![image](https://user-images.githubusercontent.com/5903611/27170473-4ff60ec2-51ae-11e7-97d1-8e397e1be5bd.png)

If you go in Network and sharing center in windows settings what properties are ticked in the custom switch settings ?
I have Microsoft Network Adapter Multiplexor Protocol and Hyper-V Extensible Virtual Switch disabled.
When I try to change these properties I got this popup : and even if I click "Yes" it's impossible to change these properties.
![image](https://user-images.githubusercontent.com/5903611/27171236-2c889448-51b1-11e7-8881-dfc7eee74dca.png)

**Comment by jasonbivins** [comment]
Hi @hugo6   I have the same settings enabled - in this properties window, do you have file and printer sharing checked as well?

**Comment by hugo6** [comment]
yes.
![image](https://user-images.githubusercontent.com/5903611/27187348-461b29d6-51eb-11e7-9e7b-473a88c37790.png)

I don't understand why ".networkadapters[0]).ipaddresses[0]" in the stack trace is getting an ipv6 address when it fails

**Comment by jasonbivins** [comment]
Does it fail consistently?   Have you noticed any patterns in when it fails, or if it's always around the same time?    You can also try disabling IPv6 in this connection, at the very least it might give a more meaningful error if it fails again.

**Comment by hugo6** [comment]
I didn't mentioned the cases when it succeed to not influence people who read me. Is not every time the case but when I remove all the docker-machine and re-create the first it seems to work (but sometimes not). It's difficult to find a situation for a working docker-machine creation. The only thing I got when it fails is the difference IPV4/V6.

If I disable Internet protocol IPV6 it doesn't change anything..

Another weird thing is if I thick "Microsoft Network Adapter Multiplexor Protocol" or "Hyper-V Extensible Virtual Switch" : I got this popup, and finally it's impossible to tick it even if I click Yes.

![image](https://user-images.githubusercontent.com/5903611/27289582-bbd5a166-550a-11e7-9bc3-1338bd7cba52.png)

**Comment by emrahcetiner** [comment]
+1
I have exactly the same problem

**Comment by jbdhacf** [comment]
I have the exact problem as well, still no solution?

**Comment by jasonbivins** [comment]
Are you using DHCP ? I have recently run into this with a customer who was assigning all IP's manually and wasn't allocating one for the new VM

**Comment by jbdhacf** [comment]
@jasonbivins It´s all automatic, but..

PS C:\windows\system32> (get-vm -name myvm1).networkadapters

Name            IsManagementOs VMName SwitchName MacAddress   Status                      IPAddresses
----            -------------- ------ ---------- ----------   ------                      -----------
Network Adapter False          myvm1  myswitch   00155D200110 {Degraded, ProtocolVersion} {192.168.43.97, fe80::215:...


PS C:\windows\system32> docker-machine ls
NAME    ACTIVE   DRIVER   STATE     URL                          SWARM   DOCKER    ERRORS
myvm1   -        hyperv   Running   tcp://192.168.237.188:2376           Unknown   Unable to query docker version: Get https://192.168.237.188:2376/v1.15/version: x509: **certificate signed by unknown authority**

It´s like a unreachable loop. Can´t **regenerate certs** because it´s waiting for SSH.
when i create a VM with debug mode on: PS C:\windows\system32> docker-machine --debug create -d hyperv --hyperv-virtual-switch "myswitch" myvm2 
I get this message:

About to run SSH command:
exit 0
SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255
output  :
Getting to WaitForSSH function...
(myvm2) Calling .GetSSHHostname
(myvm2) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM myvm2 ).state
(myvm2) DBG | [stdout =====>] : Running
(myvm2) DBG |
(myvm2) DBG | [stderr =====>] :
(myvm2) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM myvm2 ).networkadapters[0]).ipaddresses[0]
(myvm2) DBG | [stdout =====>] : 192.168.237.189
(myvm2) DBG |
(myvm2) DBG | [stderr =====>] :
(myvm2) Calling .GetSSHPort
(myvm2) Calling .GetSSHKeyPath
(myvm2) Calling .GetSSHKeyPath
(myvm2) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.237.189 -o IdentitiesOnly=yes -i C:\Users\jens.bengtsson\.docker\machine\machines\myvm2\id_rsa -p 22] C:\windows\System32\OpenSSH\ssh.exe <nil>}
About to run SSH command:
exit 0

**Comment by beppler** [comment]
It appears to be a problem with native ssh client on Windows (C:\Windows\System32\OpenSSH\ssh.exe).

I included the --native-ssh on create command and it worked.

```
docker-machine --native-ssh create -d hyperv --hyperv-cpu-count 2 --hyperv-memory 4096 --hyperv-virtual-swi
tch "Default Switch" beppler-docker-machine

Running pre-create checks...
Creating machine...
(beppler-docker-machine) Copying C:\Users\carlos.beppler\.docker\machine\cache\boot2docker.iso to C:\Users\carlos.beppler\.docker\machine\machines\beppler-docker-machine\boot2docker.iso...
(beppler-docker-machine) Creating SSH key...
(beppler-docker-machine) Creating VM...
(beppler-docker-machine) Using switch "Default Switch"
(beppler-docker-machine) Creating VHD
(beppler-docker-machine) Starting VM...
(beppler-docker-machine) Waiting for host to start...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: C:\Tools\Bin\docker-machine.exe env beppler-docker-machine
```

**Comment by jbdhacf** [comment]
@beppler Yes, seems like it. I was just about to comment as well. Maybe permissions or whatnot. I uninstalled the OpenSSH that came with the Creators update in Fall last year and downloaded a normal binary of OpenSSH.

It all worked from there. All different errors solved at once. Would have been nice to figure out how to solve if with the Windows 10 OpenSSH feature options as well
