### ISSUE TITLE
Problem with COPY and wildcards in multi-stage builds

### ISSUE THREAD

**Issue by awdm** [docker/for-win#8333]
### Information
It seems like there is a problem when using wildcards to copy files between images in a multi-stage build. Consider the following Dockerfile:

```
FROM mcr.microsoft.com/windows AS build

COPY *.txt ./

FROM mcr.microsoft.com/windows

COPY --from=build *.txt ./
```

If you execute _docker build_, the first step works, provided you have a .txt file parallel to your Dockerfile. The second step however, fails with an invalid function error. If you replace the asterix with the name of the .txt file, it works.

**Comment by stephen-turner** [comment]
Thanks for the report, @awdm. It appears that this bug is not in Docker Desktop itself but in the upstream build command, so could you please file the ticket at https://github.com/moby/moby? Sorry, I would move the ticket if I could, but it's not possible because it's in a different org -- moby is not a docker project. Thank you.

**Comment by awdm** [comment]
This is the moby-ticket, in case someone stumbles upon this: https://github.com/moby/moby/issues/35604
