### ISSUE TITLE
Docker start a wsl process in an infinite loop

### ISSUE THREAD

**Issue by cortex93** [docker/for-win#8521]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 7F68294B-2FB3-4C1E-B075-8CB0F608B4DA/20200916204202

### Actual behavior
Since upgrade to 2.3.0.5 process are started every second after docker for desktop is running.
`wsl.exe -d Alpine -e docker serve --address unix:///home/cortex/.docker/run/docker-cli-api.sock`
It do so until memory exhaustion, windows starts swaping and host freezes when swaping occurs

### Information
  - Windows Version: 2004 (19041.508)
  - Docker Desktop Version: 2.3.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  No
  - Alpine is my default WSL distro and WSL integration is enabled only for default distro.
  - Disabling integration stops the process to pop but do not kill them
  - Reenabling integration starts new wsl process in loop again

### Steps to reproduce the behavior
  1. Start Docker for Desktop with WSL integration enabled
  2. In powershell prompt, get-process wsl | measure | Select Count
```
Count
-----
  102
```

**Comment by stephen-turner** [comment]
Thanks for the report, @cortex93. Assigned to @simonferquel.

**Comment by simonferquel** [comment]
Hi @cortex93 the root of the issue is that Docker Desktop WSL integration depends on glibc. You seem to have enabled integration with an Alpine distro (which does not ship glibc out of the box and is based on musl). Docker Desktop tries to start the integration every 1 sec, you're right (and we might change that in the future as something down the pipe seem to leak wsl processes). 

https://github.com/sgerrand/alpine-pkg-glibc provides a quick and easy way to install a glibc into your Alpine. Doing that should make it work.

**Comment by cortex93** [comment]
It was working well with version prior 2.3.0.5 and changelog didn't mention this new requirement.
Though, alpine-pkg-glibc make it works. Thanks.

**Comment by marbletravis** [comment]
Better documentation and or noting that Docker Desktop WSL is not compatible with Apline Distro (out of the box) would be appreciated. Or a list of compatible distros. 

It would also be great if Docker Desktop WSL supported musl libc, but that is probably a low priority at this point.

**Comment by simonferquel** [comment]
@marbletravis I thought it was documented publicly, but it does not seem so. Adding a ticket for that. (basically we have a dependency on glibc, that is why Alpine is not compatible out of the box.
