### ISSUE TITLE
Docker host becomes unreachable at times

### ISSUE THREAD

**Issue by hkoelewijn** [docker/for-win#861]
### Expected behavior
I should be able to execute docker commands from the command prompt

### Actual behavior
Any docker command times out with the error 'Error response from daemon: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'

### Information
After a while docker becomes responsive again

  - Diagnostic ID: 17F28038-B039-469E-9BE5-118D85A94A03/2017-06-28_15-38-18
  - host distribution and version Window 10 Pro

### Steps to reproduce the behavior
It is not consistently reproducible. While working with docker during a week, I encountered it three times.

  1. Spin up containers with a gateway of Ngnx, various dotnet core 1.1.1 services, each with their own Postgress database three RabbitMq message buses.
  2. ...

**Comment by jamestenglish** [comment]
I've been getting this like once an hour and it is very frustrating.

* Diagnostic ID: EF9888B1-18C0-4038-872D-796EC16BF93C/2017-07-18_14-04-51
* Windows 10 Enterprise v1703 build 15063.483

The containers appear to continue to run but you can no longer interact with them via the docker cli in powershell. The only solution is to restart docker.

**Comment by jkossis** [comment]
Any idea if there is a fix or work-around for this? I have been dealing with this problem for a while now. Very frustrating.

**Comment by gaelicgod** [comment]
I'm also getting this issue :|

- Diagnostic ID: 37A972A6-9CE0-4F38-BAB8-2214E927DC60/2018-02-07_10-51-18
- Windows 10 Professional v1709 build 16299

**Comment by retog** [comment]
While this issue is still unassigned I got a "how likely are you to recommend docker for windows to friend" survey.  I admin that on Linux Docker worked quite well for me, but docker for windows is super frustrating. I given up using it productively a while ago, but with this issue it is painful to use even for development and experimental pirposes.

**Comment by sfali16** [comment]
**_Potential_** Workaround below
I have been using docker for windows for a while, and recently encountered this issue for the first time, because a windows update tried to restart my computer and failed to shutdown due to open programs. My guess is the docker process was killed.
WorkAround: I rebooted, attempted to restart docker manually, didnt have success with that, so i reset docker to factory defaults and restarted docker again. This made me lose my downloaded images, but it kicked docker back into gear.

**Comment by Jonnyleezh** [comment]
I've been getting this when i'm installed firstly,frustrating!
