### ISSUE TITLE
BDACE932-048D-4951-ACD0-CE32EBEE9BF2/20200922021350

### ISSUE THREAD

**Issue by 1234gg-cid** [docker/for-win#8616]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by PavelSosin-320** [comment]
Me too  ! Diagnostics ID 
![image](https://user-images.githubusercontent.com/54495912/93883717-9de81180-fcea-11ea-82ce-030eab3f3bf0.png)
The same issue as in the previous attempt: VPN Kit can't connect to the daemon's socket.
VPNKit is a redundant feature for me. There is no chance that I will use it. Created by this plugin configuration for DNS will never work in the modern broadband internet home network because my DNS is not physical - it is virtual! All NSLookup requests should go to the gateway, i.e. my Router. OpenWRT OS running on my Router manages and optimizes DNS list to achieve best lookup time. All 4 DNS addresses in the list are Global infrastructures DNS's which resolve names to IPV4 or IPV6 addresses according my Home network preferences. They are not physical Hosts addresses too. All my Home devices are connected to the Home Networks managed by the Router. It gives me very short overall name resolution time. VPN client installed on my Laptop is uselless because my ISP can track my Router by IP address assigned by ISP. To hide my home devices VPN client has to run on the Router. There is no problem for VPN provider to install the client on the Router.
