### ISSUE TITLE
Wrong Windows version but I can’t update

### ISSUE THREAD

**Issue by awdm** [docker/for-win#8691]
Just wanted to install Docker Desktop for Windows Home. It says it needs Version 19018+. My system is on version 18362 but when I try to update it tells me my system is up-to-date.

**Comment by christianfosli** [comment]
18362 is Windows version 1903, [which recently got support for WSL2 through a backport](https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/).

This looks like a duplicate of #8169.
Not sure if it has been fixed in stable yet, so you might want to switch to edge for the time being.

**Comment by awdm** [comment]
Ok so what's the deal with these different versions? And how do I upgrade to 2004? Sorry for beeing of topic but this very much confuses me. I'm on my personal computer so no corporate stuff getting in the way. Also, what does Edge have to do with all of this?

**Comment by christianfosli** [comment]
Windows 2004 is the spring 2020 feature update of Windows 10 (2004 = 2020-April update, although it was actually released in may). It was the first stable Windows release with the WSL 2 feature, which basically made it possible to run Docker Desktop on Windows Home. Earlier versions required enabling Hyper-V which is only possible on Windows 10 Enterprise/Proffesional/Education.

Windows 1903 is the spring 2019 feature update of Windows 10. The WSL 2 feature was later backported to Windows version 1903 and 1909.

The standard way to upgrade your windows version is to click the "Check for updates" button in Windows Update in Windows Settings. I have no idea why that doesn't work for you..

Docker Desktop comes in two flavours; stable and edge. I meant to suggest trying the Edge version of Docker Desktop, since stable may not yet have been updated with regards to the WSL 2 backport, as you can see in the issue I linked. Not talking about web browsers here... Sorry if that was unclear 😅

**Comment by awdm** [comment]
Alright, got it. Thanks for taking the time and the detailed answer, At least I'm one step closer to the root cause of this issue now.
