### ISSUE TITLE
docker desktop hangs 

### ISSUE THREAD

**Issue by wanfuse123** [docker/for-win#8814]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

4CDD3BA5-A32F-4128-9561-6ADD93D1A1FD/20201004143408

**Comment by grickmarshall** [comment]
I have the same problem if I uncheck the "Start Docker Desktop when you login" box in the General tab of the Settings Panel of the Docker Desktop dashboard on Windows 10 Version 2004 (20H1?). As long as the checkbox is checked everything is fine. To allow me to start Docker Desktop for Windows, I have to execute these commands in a batch file (run as Administrator):

net stop com.docker.service
taskkill /IM "Docker Desktop.exe" /F
net start com.docker.service
"C:\Program Files\Docker\Docker\Docker Desktop.exe"

I have to close the window manually. I haven't figured out how to do that in the batch file. Everything works as normal. Please fix the checkbox so that I can launch Docker Desktop for Windows from the shortcut on my desktop that the installer placed there.


![image](https://user-images.githubusercontent.com/52606105/99686878-e09f3f00-2a38-11eb-81a0-736171d185d7.png)
