### ISSUE TITLE
Unified docker.host DNS entry

### ISSUE THREAD

**Issue by ktor** [docker/for-win#887]
### Expected behavior
Unified DNS entry for docker host on all OS implementations. E.g. **docker.host**

### Actual behavior
Separate DNS entries for docker host on different OS implementations:
- docker.for.win.localhost
- docker.for.mac.localhost

### Information

  - it'll be helpful to have one DNS entry for docker host because containers when used by developers run on macs or windows and on servers they run on linuxes. Benefit comes from having only one version of scripts/configurations that connect to docker host used in all OS implementations.

**Comment by friism** [comment]
The different hostnames for Mac and Windows were chosen on purpose. The problem is that taking a dependency on accessing network services on the host from a Docker container is, by definition, non-portable. If your containers or commands that run Docker rely on a particular service on the host, then those containers or scripts will only work on systems prepared in advance. 

I know it's not always possible, but it's better if you structure your apps to run fully in Docker containers so that they can be spun up (with docker-compose, for example) without users first having to start a bunch of other stuff on their machine.

This issue has lots more debate about this: https://github.com/moby/moby/issues/1143

**Comment by Rohaq** [comment]
I know this is old and closed, but I just wanted to add a note: There are certainly use cases for this.

In our case we do PHP development, running local development environments on our machines inside Docker. We use a cross-platform IDE supporting Xdebug, which runs a service on the host machine on port 9000 - this is the same, whether it's Windows, Mac or Linux.

Having a unified DNS entry for the host machine would allow us to have a single docker-compose configuration that would work across every single one of our platforms, without manually having to configure the host IP in an env_file on each setup, or any time that IP might change.

**Comment by jedwards1211** [comment]
@friism unfortunately Docker is so good at launching complex services that its utility extends beyond the use cases it was intended for.  Docker might as well embrace everything it's good at, not just its original purpose.  I've been using it to launch a selenium hub and chrome/firefox grid nodes on my local machine for webdriver testing, because doing that without docker would be a huge PITA.  But it remains more convenient during development to run the server I'm testing on my local machine instead of building it into a docker container and launching it (slow, no hot reloading).

> The problem is that taking a dependency on accessing network services on the host from a Docker container is, by definition, non-portable. If your containers or commands that run Docker rely on a particular service on the host, then those containers or scripts will only work on systems prepared in advance.

By this logic it was a mistake for Docker to give us *any* way, platform-specific or not, of determining the host system's IP address.  If the host machine IP is worth knowing in any case, it's worth knowing in a platform-independent way.

**Comment by christhomas** [comment]
@friism How is a hostname, which maps to an ip address, not portable?

If I ping docker.for.mac.localhost, it pings an ip address, which is that of my host, meaning if I am running a piece of desktop software, it'll access like normal cause its just an ip address.

if I ping docker.for.win.localhost, it pings an ip address, which is that or my host, meaning if I am running a piece of desktop software, it'll access like normal cause its just an ip address.

Sorry for the dumb question, but they look identical to me, and if I was running on linux? Then I guess docker.for.linux.localhost would resolve to my machines ip address too, again, I'm unclear on why this is not a portable solution? It appears any barriers here are in the mentality of the developers, not the technology.  A hostname is just mapped to an ip address, whats not portable about this?

**Comment by friism** [comment]
The hostname scheme to access services on the host _is_ portable, but depending on host services as a general paradigm _is not_. You might successfully run an app using a docker-compose.yml file (and that has a host service dependency) on your laptop that happens to work because you've configured that particular host service on your laptop. But if I check try to run the same `docker-compose.yml` file on my laptop (without the host service setup and configured) the app will fail in some obscure way.

**Comment by antanas-arvasevicius** [comment]
Workaround for this is to place these lines in Dockerfile:

> echo "\`getent hosts docker.for.mac.localhost docker.for.win.localhost docker.for.linux.localhost | awk '"'"'{print $1}'"'"'\` dockerhost" >> /etc/hosts

This will create "dockerhost" hostname which aliases either docker.for.mac.localhost or docker.for.win.localhost

One drawback that currently it doesn't work with linux as "docker.for.linux.localhost" not exists. 
Maybe someone could solve it for linux.
Don't know why they are doing these PLATFORM specific hostnames as they are useless in multi OS environment. Could be "docker.host.localhost" for all and everybody would be happy.

**Comment by christhomas** [comment]
@friism who is building these services though, me or you?  I seem to have this opinion that I'm probably in a better position to judge my current situational requirements and whether something is good or bad based on my knowledge of the specifics than you are.

Also, I didnt enable or touch my configuration to have access to those hosts across mac and windows platforms, I assume the hostname is also docker.for.linux.localhost.  I also reckon that this is not something configured by me, but something done automatically by my docker installation.

So if this is the case, there is nothing configured in my environment for that particular host service on my laptop, its all done for me.  So if these hostnames are provided, without any configuration by the user when installing the software, then why can't we just have something like docker.localhost or docker.local or whatever you want and then it would be cross platform.

Again, nothing in your answer speaks about technical problems, even the bogus ones you just mentioned, they're more political than technical and thats my problem, there is a solution which is for some unknowing reason specifically customised per environment yet provides the same functionality, why not just name it the same and have some common baseline for people who want to run an external cluster of services and just be done with it.  

It's not even that useful outside of development environments.  But perhaps some legacy applications would find this useful.

**Comment by Dolondro** [comment]
Thanks for your solution @antanas-arvasevicius 

With some additional hackiness I've got it (at least in my setup) so it handles Linux as well. It's gross but it seems to be working:
```
echo "172.17.0.1  docker.for.linux" >> /etc/hosts;
echo "`getent hosts docker.for.mac.localhost docker.for.win.localhost docker.for.linux | grep -ve '^\(127\|::\)' | head -n 1 | awk '{print $1}'` dockerhost" >> /etc/hosts;
```

**Comment by Muardin** [comment]
Since Docker Version 18.03 you can use:
**host.docker.internal**

I got it from this post: https://stackoverflow.com/a/40789612

**Comment by Rohaq** [comment]
Hm, I'm running 18.03, and that hostname fails to resolve from inside the container.

**Comment by Rohaq** [comment]
Just to add to the above, this now seems to be working in 18.03.1. Good stuff!
