### ISSUE TITLE
Stop infinite retry when WSL raised error

### ISSUE THREAD

**Issue by licanhua** [docker/for-win#8968]
Hello,

I'm from Microsoft and working on WSL, and from WSL measures, I found that likely Docker Desktop is doing infinite retry if WSL has problem on the user machines(For example, lxss manager crashes, have problem to create virtual networking, WSL bugs...) 
On specific devices, WSL is launched more than 50,000 times per day but always failing with error. And I guess it's because that docker desktop is retrying.
I'm not on that machine, but those machine should be very busy to try on an unrecoverable WSL error, and also complains that docker desktop doesn't work but don't know why.

If docker has infinite retry, I would suggest you to just retry a small number of times, if it reached the threshold, just raise a message that WSL have problem, and please fix it first

**Comment by stephen-turner** [comment]
@simonferquel Any comments?

**Comment by simonferquel** [comment]
This is actually something we recently fixed, but it is not yet released. 
It will be in next Edge. (not in next stable though. Should we consider cherry-picking the fix ?)

**Comment by licanhua** [comment]
how do you fixed it? re-try a limited number of times, re-try wait and re-try?
when the fix will be released? I'm happy to verify it in my side(I can make the lxss returns any error you like) to see if it fixed the problem or not.
I don't know what's the impact from user's view, but I really like this is fixed on stable too.

**Comment by simonferquel** [comment]
We previously had a limitation in our architecture that made it mandatory to have a retry loop there as the backend startup and distro integration logic where controlled from 2 different processes that did not communicate together. We changed all that, and thus we know exactly when to trigger the integration logic within the backend startup code. 
So now, if there is a failure, we know that it is not because of synchronization issues, but it is actually a real error where our integration logic fails to run within your distro. There are some known reasons while it would fail (e.g. distros without a glibc like Alpine), and we also had bugs in this area with exotic shells etc.

The fix will appear in next Edge version. When the integration process fail, you'll now have a native Windows notification asking you if you want to restart the integration process or not.

**Comment by simonferquel** [comment]
The issue has been fixed in Edge release 2.4.2.0, thank you for reporting it.

**Comment by Vankog** [comment]
@simonferquel 

Actually, I got this particular notification since the latest release and to be honest, I did not know how to fix this. There is no information visible on what to do.

I was lucky that I read the release notes to remember something like this restarting issue notification. This way I had a breadcrumb to follow into this issue and finally read the one information that actually helped:

> There are some known reasons while it would fail (e.g. distros without a glibc like Alpine)

I do use Alpine for by main WSL2 distro. So only **now** I know I should switch. 

Thus, I suggest the following:
If this issue arises and the notification triggers, could you somehow provide some further information to the user? Some troubleshooting or a known-problems page or such?
I mean, Docker does not complain about this in any visible way, except for this notification. So what's the impact? (Fallback to non WSL mode?)
Would be nice to be pushed to the right direction for troubleshooting. (I actually ran Diagnostics, but I couldn't make any sense out of the dump.)

Thanks! :-)
