### ISSUE TITLE
docker pull twice from remote registry mirrors

### ISSUE THREAD

**Issue by hantsy** [docker/for-win#8976]
I have already for posting the problem here.

https://stackoverflow.com/questions/63627389/docker-pull-twice-from-remote-registry/64311152#64311152

If the layers are not found in my configured mirrors, it will start a complete new request to restart the downloading from the official Docker hub, and discard the former downloaded layered from my configured mirrors.

My question is why it can not combine the found layers from different Docker mirrors and merge into a complete Docker image.

As I know, all layers are signed and can be verified. I think when an layer is not found from my configured mirrors,  it is possible just downloading the missing layers from the official Docker Hub.

**Comment by thaJeztah** [comment]
Thank you for opening;

If I understand your description correctly, the following happens;

Situation;

- your docker daemon is configured to use a registry mirror (e.g.`https://my-mirror.example.com`)
- two images exist on docker hub that either are the same image with different tags, or share the same layers (e.g., `some-image:latest` and `some-image:1.0.1`)
- the registry mirror only has one of those (for example, it only has `some-image:latest`, but does not have `some-image:1.0.1`)

In this situation;

- `docker pull some-image:latest` will try to pull from the registry mirror, find the image, and pull it from that registry
- `docker pull some-image:1.0.1` on the other hand, will try to pull from the registry mirror, doesn't find the manifest for the `1.0.1` tag, and will thus pull that manifest, _and all layers (blobs)_ directly from docker hub

Your proposal is to;

- running `docker pull some-image:1.0.1` will pull the _manifest_ from docker hub
- for each request following that (layers/blobs), first try to pull those from the configured mirror
- if not found on the mirror, fall back  to pull directly from docker hub

I think that's an interesting idea that's worth exploring. From the top of my head, I don't see why this would _not_ be possible, but I want to double check with some other people (mostly to verify if there would be an issue w.r.t. authentication in case the image you're pulling is private)

This issue is not specific to Docker Desktop / Docker for Windows, and would be better to be discussed in the upstream "moby" repository, where the code for the docker engine lives; https://github.com/moby/moby/issues could you perhaps open a ticket there?

**Comment by thaJeztah** [comment]
Also wondering how your registry-mirror is configured; did you configure it as a pull-through mirror? https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache

**Comment by hantsy** [comment]
I configured the registry mirrors in the Docker dashboard, *Settings* -> *Docker Engine*. Finally, it will write into *~/.docker/daemon.json*.

**Comment by hantsy** [comment]
>Also wondering how your registry-mirror is configured; did you configure it as a pull-through mirror? https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache

I am using a public registry mirror in China, so I can not modify the configuraiton of the registry itself.

**Comment by tao12345666333** [comment]
@hantsy  You can read this article for pull through cache https://zhuanlan.zhihu.com/p/256359308  (In Chinese)

**Comment by hantsy** [comment]
@tao12345666333 Not the same thing.

What happened in my case is the syncing of some images is not completed, but I ran a `docker pull` at that moment.
