### ISSUE TITLE
My docker not working - Error Occurred when updating WSL 2 Linux kernel

### ISSUE THREAD

**Issue by bhm1** [docker/for-win#9013]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by LanceTrahan** [comment]
Not sure why you posted this. It's going to get closed because it lacks any useful information.

To humor you a bit, it seems Docker Desktop for Windows 10 has some issues but it's because of WSL2 being buggy and shutting down. A reinstall of WSL and a re-patch of WSL2 usually gets things back up and running. Be sure to reboot after uninstall and after reinstall. It's no fault of Docker, so take the issue up with the WSL project.
