### ISSUE TITLE
How does this issues list work?

### ISSUE THREAD

**Issue by markoueis** [docker/for-win#9247]
Hello everyone,
First, I super appreciate all the work on docker desktop. It's honestly some of the best stuff happening to windows right now. Very excited about the future of this. So thank you

I'm also relatively new at contributing to this issue list (though have been using docker desktop very extensively for 2 years now). I'm wondering as users of docker desktop, what can we expect from this "forum".

For example I see that there are 1100 open issues. If I have an issue, is there a point in submitting it here? How can I tell if what i post will be looked at and when. There are what appear to be bugs, so I'm posting them here, but maybe the dockerhub docker for windows forum is more attended to? I'm not sure.

Anyways, thanks for all you do. Any help in pointing me in the right direction would be great

Issues i'm currently interested in for example are 
https://github.com/docker/for-win/issues/8861 and
https://github.com/docker/compose/issues/7273 (docker compose so not exactly here)

**Comment by stephen-turner** [comment]
Thanks for the question, @markoueis. As you would probably expect from a free product, it's on a best-effort basis. Much as we would like to answer everybody, with millions of users and over a hundred tickets submitted every week, we don't have time to get to the bottom of every issue. We tend to prioritise tickets that look like new bugs and those that have got a lot of users reporting them.

Additionally, we have today announced more formal support for Docker customers, so that's another route. https://www.docker.com/blog/pro-and-team-subscriptions-embrace-docker-desktop/
