### ISSUE TITLE
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:4449: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by worldzhang2010** [docker/for-win#9272]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:4449: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by adi-ch2019** [comment]
This is because your IIS or some other server is already running on port 4449.
Try this and it should work.

**Comment by adi-ch2019** [comment]
remove all instances of apps on IIS. Restart IIS by 'iisreset'
This worked

**Comment by satishautade** [comment]
I have encountered the same issue. I probably don't understand much of the ports ranges in Windows 10 but I was able to make it work when I used -P option for docker run command. Basically letting docker pick a port that works. 
Here is the full command that worked for me 
`docker run -d -P --name docker-tutorial docker101tutorial` 
then run docker ps to check which local port you should use in the URL.
`
docker ps
`

**Comment by cdalexndr** [comment]
In my case, `nestat -aon` showed that port was not in use, but running `netsh int ipv4 show excludedportrange protocol=tcp` showed a port exclusion range that included my port.

I have no ideea who and why is excluding the port range, and have opened a [stackexchange question](https://superuser.com/questions/1604199/find-who-excluded-port-range)

**Comment by cdalexndr** [comment]
Duplicate of https://github.com/docker/for-win/issues/3171

**Comment by cdalexndr** [comment]
Changing the dynamic port range with `netsh int ipv4 set dynamic tcp start=49152 num=16384` ([source](https://github.com/docker/for-win/issues/3171#issuecomment-554587817)) and after a restart excluded port ranges are ok.

**Comment by smoothumut** [comment]
stop iis, then run docker image,, then you can restart the iis if you want without a problem

**Comment by nosferatu-id** [comment]
may be `netcfg -d` and restart ?

**Comment by michael-freidgeim-webjet** [comment]
to stop IIS use either
iisreset  /STOP 
 (From <https://stackoverflow.com/questions/22084561/difference-between-iisreset-and-iis-stop-start-command> )
or 
net stop "W3SVC"
(From <https://stackoverflow.com/questions/49222911/how-to-fully-stop-iis-using-command-line-bat-file> )

**Comment by iEveQ** [comment]
> may be `netcfg -d` and restart ?
> alose try this
> `net stop winnat`
> `docker-compose up ...`
> `net start winnat`

It's working for me.
thinks!

**Comment by Heyuanfly** [comment]
in my case,the task manager show that a system process is occupy port 80.

**just open service list and stop the **_world wide web service_**,then everything will be ok**

the name of service maybe a little different, but should include keywords :world wide web

**Comment by newcanopies** [comment]
@Heyuanfly I found the same system process listed in WindowsDefenderFirewall, 

but none of services starting with letter w matched the keywords in TaskManager .. any idea how to trace the service via TaskManager process ID?

**Comment by naikrovek** [comment]
@newcanopies In Windows, use `netstat -aon` to match the listening port to the PID of the process, which is also visible in Task Manager (once you turn that column on.)

I get this issue and it is *definitely* not a "port in use" error.  Nothing else is using the port.  I can try any number of other ports, and most of them will fail, and then suddenly one port will work.  Every port I try previously will continue to fail.

This is a problem with Windows, and I think Docker is exposing this problem.  If I bind ports in Docker in WSL 2 to listen only on the WSL 2 eth0 interface address, binding always seems to work fine.  I'm fairly confident that it has something to do with Docker and WSL 2 and how Windows forwards "localhost" ports on WSL 2 to the hosting Windows machine, so that "localhost" addresses on Windows forward to WSL 2.

/remove-lifecycle stale

**Comment by OfficialDarkComet** [comment]
> 
> 
> to stop IIS use either
> iisreset /STOP
> (From https://stackoverflow.com/questions/22084561/difference-between-iisreset-and-iis-stop-start-command )
> or
> net stop "W3SVC"
> (From https://stackoverflow.com/questions/49222911/how-to-fully-stop-iis-using-command-line-bat-file )

Michael solution worked for me. 

S **net stop "W3SVG"**
$ **docker run -d -p 80:80 docker/getting-started**
$ **net start "W3SVC"**

**Comment by naikrovek** [comment]
For me, it was winnat holding a giant pile of port reservations.  Obviously you can't use a port if something else reserved it, and winnat had an insanely large number of reserve port ranges.  Clearing that and rebooting fixed *everything* for me.

[this comment](https://github.com/docker/for-win/issues/3171#issuecomment-788808021) on another bug about this issue contains the 4 commands I ran to fix this.  This broke networking in WSL 2 for me, so I needed to reboot, but after I came back up, all was well.

Best of luck!

**Comment by MoroccanGeek** [comment]
> > may be `netcfg -d` and restart ?
> > alose try this
> > `net stop winnat`
> > `docker-compose up ...`
> > `net start winnat`
> 
> It's working for me. thinks!

Worked for me as well. thank you

**Comment by alexx855** [comment]
> `netcfg -d` and restart ?

did the trick for me

**Comment by majidshakeelshawl** [comment]
Open IIS Software and on right side Click Stop and run the docker command (docker run) again. 

This Worked for me.

**Comment by Namwanza** [comment]
Well, the suggestions above did not solve my problem, 
I had to go to **docker-composer.yml** file in my **laravel project** and edited these two lines for the port from '`${APP_PORT:-80}:80`'  to  '`${APP_PORT:-89}:80`' and `${HMR_PORT:-808-}:8080`'     ----> '`${HMR_PORT:-8084}:8080`'  and everything worked like charming.

**Comment by shan-github-project** [comment]
@Namwanza 
why cannot we change mysql **FORWARD_DB_PORT** number in same **docker-composer.yml file** beacuse mysql is not running in my laravel project

**Comment by narkhis** [comment]
for me the solution was to stop  iis service , it work .

**Comment by aknessy** [comment]
Encountered something similar very recently while attempting to power up Laravel sail. Running `docker ps` I discovered `port 3306` was already up for a local `mysql` installation. Doing `net stop winnat` and running `ctrl+alt+del` to start the task manager and stop the `mysqld` instance and then running `net start winnat` before `./vendor/bin/sail up` solved it.

**Comment by lingme** [comment]
> > > may be `netcfg -d` and restart ?
> > > alose try this
> > > `net stop winnat`
> > > `docker-compose up ...`
> > > `net start winnat`
> > 
> > 
> > It's working for me. thinks!
> 
> Worked for me as well. thank you

**Comment by devluist** [comment]
Hi, I found a solution, but not the best to be honest...

-  `net stop winnat` and restarting commands did not solve my issue completely, since it turned off my ability to connect to the web from my wsl2 ubuntu console (try ping google.com and you will get timeout)

- also changing the port in the docker compose file or the run command is annoying


The real problem is that Docker is storing a bunch of ports on windows, you could check that with
`netsh int ipv4 show excludedportrange protocol=tcp`

so, if the port you try to use is in any of those ranges you are in trouble

1- one solution is to keep asking every restart of your machine what ports are available (ranges are reserved on every startup)
 so run the **netsh** command provided above and pick a port that **is not on the ranges** of that list 

2- or you could reserve the ports to avoid checking every time, pick a range that you see empty, and modify this command accordingly, for example, this will reserve ports from 10000 to 10999:

`netsh int ipv4 add excludedportrange protocol=tcp startport=10000 numberofports=1000 store=persistent`

**Comment by tharoosha** [comment]
This happens if you have already run a service on port 4449
you can check which service this currently running that port and disable it.
`netstat -aon | findstr :4449` to find the service running on the 4449 port and go to task manager and disable it.

**Comment by naikrovek** [comment]
"port already in use" or something like that is usually the error you will see when there is something already using that port and won't let go of it.  `winnat` is usually what causes the socket access error.

the winnat solutions listed in this issue work.
