### ISSUE TITLE
Container hangs if I hit two keys at the same time

### ISSUE THREAD

**Issue by ibechao** [docker/for-win#934]
### Expected behavior
stay in shell
### Actual behavior
shell hangs
### Information
OS: Windows 10 Pro 10.0.15063 
docker version:

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

### Steps to reproduce the behavior

  1. from powershell prompt: docker run -it ubuntu:latest bash
  2. from container prompt: hit any two keys at the same time
  3. result -- doesn't respond to keystroks; must hit control-c to exit container

**Comment by jasonbivins** [comment]
hi @ibechao 
I can reproduce this, so I'll go ahead and write it up as a bug.  Do you mind if I go ahead and close this issue?

**Comment by ibechao** [comment]
Ok. Thanks!

**Comment by azenned** [comment]
@ibechao @jasonbivins , this issue is closed.

**Comment by michaelkschmidt** [comment]
This issue seems to still be happening.  The workaround for me as been to use "winpty".  See https://github.com/docker/for-win/issues/199#issuecomment-361073655

**Comment by Enigmatum** [comment]
Please reopen this, the issue is still happening in windows docker, 19.03.2 version. 
It's very annoying. If I accidentally hit any two keys at the same time while in bash in a container, it exits the shell.

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           windows/amd64
 Experimental:      false
