### ISSUE TITLE
Container logs are not indented / missing whitespace

### ISSUE THREAD

**Issue by danielsamuels** [docker/for-win#9448]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 392467E4-C154-4873-B8EE-8797ABEAB48D/20201109150533

### Expected behavior

When viewing the logs of a Docker container, the indentation should match the output of `docker logs <container>`

### Actual behavior

The logs are missing all indentation and have squares appearing in some places

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes, every time
  - Windows Version: 10.0.18363.1139
  - Docker Desktop Version: 2.5.0.17
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Run `docker run --name repro alpine echo --help`
  2. Observe that the output is indented
  3. Run `docker logs repro`
  4. Observe that the output is indented
  5. Open Docker for Windows
  6. Click on the 'repro' container
  7. Observe that the output is **not** indented

![Docker_Desktop_2020-11-09T151303](https://user-images.githubusercontent.com/1781176/98559063-122c4380-229e-11eb-9d0b-e51720cf59aa.png)

**Comment by treygrainger** [comment]
This issue isn't unique to Windows. I see the exact same thing Docker Desktop for Mac. I'm running a program on Windows 10 Home (WSL2) and on Mac OS Catalina, and the output doesn't render whitespace correctly. Almost like doing a string replace of all multi-charachter whitespace with a single space (which would include indents on the left, like the reporter of this issue mentioned).

Have some Ascii Art on the startup and it looks atrocious. (just all aligned to the left due to missing whitespace ). Looks fine with docker logs [process], it's just the Logs interface on Docker Desktop that is messed up.

**Comment by treygrainger** [comment]
This issue is still outstanding (and quite annoying - forces use of a terminal instead of the docker desktop app), but was auto closed due to inactivity.
