### ISSUE TITLE
Symantec Web Security.cloud is not compatible with Docker for Win

### ISSUE THREAD

**Issue by rlaveycal** [docker/for-win#946]
I'm logging this for general info rather than the expectation of a fix.

We use [Symantec Web Security.cloud](https://resource.elq.symantec.com/campaigns-web-security-search) as our corporate web proxy. It's a cloud based HTTP proxy. 

When I configure D4W to use the proxy server then `docker pull` commands just hang during image download. Docker is able to connect to the registry and shows the various layers of the image. It starts to download those layers but will then just freeze at a random point per layer.

`docker login` commands succeed.

Thus this isn't a straight connectivity issue but a flow control one - the proxy is blocking traffic after download has started.

Changing D4W to use a local squid proxy resolves the issue.

We've raised this issue with Symantec and they have reproduced it but deem it a docker issue. We don't have any issues with http downloads via the proxy for any other applications.

There's obviously something happening at a low level between the docker engine requests and the proxy service but working out what is going to be difficult.

**Comment by kallie-b** [comment]
@rlaveycal -- Have you found any workarounds for this issue? Today, how are you configuring proxy settings for your containers with regard to the proxy settings on your host?

I am part of the Windows Core Networking team and right now I'm working on understanding our current support for proxy scenarios around containers--I'm researching the current gaps in our support, and trying to understand what kind of support users would like to see added to the Windows container platform, with regard to things like proxy and VPN.

In particular, I'm focused on understanding how we can strengthen our "default" networking experiences for containers. For instance, in the near future I'd like to see us validate support for propagating host and VPN settings from the host into container endpoints, so that by default containers have the same network connectivity as their host (at least for Windows 10, developer-focused scenarios). _Does this perspective jive with the kind of support that you would like to see in this space?_

**Comment by rlaveycal** [comment]
@kallie-b The work-around was to use a different proxy solution for our D4W VMs. Having the VM pick up the Windows host's proxy settings by default would be nice but I'd keep the option to override (or else we'd be stuffed!).

If you're able to diagnose what the problem is with Symantec I can put you in touch with our support rep who may be able to arrange some sort of test access to their service.
