### ISSUE TITLE
Context menu items in system tray menu are unclickable & menu fails to go away (Windows 10 Enterprise 20H2)

### ISSUE THREAD

**Issue by aairey** [docker/for-win#9481]
Exact same issue as in #1048.

### Expected behavior
Dialog is usable and accessible

### Actual behavior
https://user-images.githubusercontent.com/29718037/29831214-41f1f7c0-8c99-11e7-8553-df2cd5e2b2ff.png

None of those elements are clickable. The dialog does not disappear when clicking into another program -- it stays up

### Information
* Diagnostic ID from "Diagnose & Feedback" in the menu.
  * this is inaccessible
* a reproducible case if this is a bug, Dockerfiles FTW
  * N/A
* page URL if this is a docs issue or the name of a man page
  * N/A
* host distribution and version (Windows version, build number, etc)
  * Windows 10 Enterprise 20H2 Build 19042.630

### Steps to reproduce the behavior
1. Access system tray
2. Right click Docker
3. (Menu shows up)
4. Click away from the menu

### Workaround
Kill Docker Desktop from the Task Manager to make the always-on-top context menu to go away.

**Comment by kae36** [comment]
I have the same problem, but with Windows 10 Enterprise Version 1809 Build 17763.1518

Actually, all the members of my team have this problem.

I can't do anything with the system tray menu. The only thing that works is select (which brings up the Docker Dashboard.  I can only "restart Docker", Can't get a Diagnostic ID from system tray menu or from "Get Support" in the debug section of the dashboard.  Docker seems to be working, but it's annoying to have the menu permanently stuck (covering everything) in the bottom right.

Docker seems to still work, but everything has to be done with the Command Line Interface (CLI).  This has been a problem since we updated to 2.5.0.0 (2.4.0.0 was fine).  The update to 2.5.0.1 or whatever that version was (2.5.0.0.1) didn't fix it either.

**Comment by RMBloom** [comment]
I'm also having this issue on Docker Desktop Community edition 2.5.0.1 (49550) on Windows Home 2004.

**Comment by kae36** [comment]
I finally got it working when a coworker noticed that some Windows features had been turned off.  I'm not sure how these were turned off, but I started the **Turn Windows features on or off** and made sure the following were checked.

- Containers
- Hyper-V
- Virtual Machine Platform
- Windows Subsystem for Linux

I had to reboot, but after fixing this, everything worked again. I hope this helps someone.  I'm still not sure how these got turned off. I'm guessing it was our Computer Support organization that updates Group Policies, but it also seemed to occur at the same time I installed the new 2.5.0.0 version.  Also, this only affected a few people on my team, if it really was the Computer Support, it should have affected everyone in my team. So, I really don't know the cause.

Good Luck.  I hope this helps someone.

**Comment by pdowson** [comment]
I am experiencing the same issue.

Docker Desktop 2.5.0.1
Windows 10 18363.1198
Hyper-V and WSL are installed but docker is configured to use Hyper-V

The UI is accessible via the start menu, and can be interacted with. The menu icon is completely unusable.

**Comment by drspangle** [comment]
I'm also having the same problem using WSL2 on Windows 10. I can't click on any of the items in the right-click menu on the system tray, and it doesn't go away no matter what I do. I can double-click the system tray icon to bring up the Docker UI but that's it.


Docker:
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Windows:
Edition	Windows 10 Enterprise
Version	20H2
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by aairey** [comment]
This was solved for me once I upgrade to Docker Desktop 3.0.0 which suddenly arrived on my Desktop :)

**Comment by drspangle** [comment]
It turns out I'm using Docker Desktop 3.0.0 and the problem persists -- with a catch. Sometimes the system tray icon just gets stuck with "Docker is starting..." and the right-click context menu never opens. When I open the UI and restart docker, this goes away, but then the same problem where the items on the right-click context menu are not clickable happens.

**Comment by kae36** [comment]
I agree with @drspangle I thought it was fixed too, but I still have problems even after upgrading to Docker Desktop 3.0.0. When it gets stuck, I usually bring up Task Manager and kill the "stuck menu" and then restart Docker Desktop.  After that it usually works, but there is definitely something that it's waiting for that it never gets.  Sometimes there's no problem at all and it comes up without a problem.  So, there is a "catch", just don't know what it is yet.

**Comment by elmorekevin** [comment]
Same problem here. Icon shows it is still starting up, when it's all good. I'm afraid to right click the icon now, since usually I can't get the menu to disappear!

**Comment by leElvyn** [comment]
always the same problem since years, please fix it

**Comment by huxuan** [comment]
Seems it is fixed with the latest 3.2.0 version.

https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-320

**Comment by aairey** [comment]
I don't see any mention of this issue in these release notes.

**Comment by huxuan** [comment]
> I don't see any mention of this issue in these release notes.

Yep, it is not mentioned in the release notes, but that new version fixed the problem for me.

**Comment by drspangle** [comment]
Still having the same issue as of just now, running v3.1.0.

**Comment by drspangle** [comment]
Nope, we're back to the state where the right-click menu doesn't appear at all.

**Comment by elmorekevin** [comment]
@drspangle Same here on 3.2.0. 
![image](https://user-images.githubusercontent.com/31101710/109843074-b143c500-7c18-11eb-908d-2d2cf024dedb.png)

**Comment by MitchTalmadge** [comment]
Also having this problem, the menu is stuck and won't go away. Stays on top of all apps.

![image](https://user-images.githubusercontent.com/8848080/110189100-3971c800-7ddb-11eb-9c74-8074900a35c8.png)

**Comment by mike-loux-planview** [comment]
I just love it when Docker randomly stops working or behavior changes.  In my case, this morning:
* My images and containers all disappeared.
* I got the `error during connect: This error may indicate that the docker daemon is not running...The system cannot find the file specified.` issue.  
  * Running PS as Administrator did **not** solve the problem.  
  * I tried doing the SwitchDaemon thing and that made the above problem go away, but it did not bring my images back.
* Right-click on the context menu does absolutely nothing.
* Can't get into the Settings screen from the main UI (just hangs until I Cancel back to the UI).
Docker is very handy, but I have to do major troubleshooting on this frigging thing every 6 months or so, and it drives me up the f'kin wall.

**Comment by drspangle** [comment]
I finally discovered a solution for this problem.

My problem became worse as the GUI not only had the rightclick menu hang and be unable to interact with it, the settings menu in the GUI also hung and I couldn't change any of the settings. I tried resetting Docker for Windows to factory settings a zillion times, uninstalling and reinstalling it, deleting all the files I could find, nothing worked. When I reinstalled, I still saw the settings menu hanging, the right click menu hanging. I could only sometimes interact with the docker system from within my Ubuntu WSL2 console. It would randomly not be able to see the service running on the socket. I could find no explanation for the behavior, though resetting to factory settings again would fix it for a while. I must have done this over a dozen times.

Eventually once I completely uninstalled it and then also re-enabled the virtual machine platform feature using `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart` and reinstalled the latest (3.2.2), the GUI started working again. I could tell that this time it worked because I had received a notification that the WSL2 backend was starting when I rebooted, which had simply stopped happening before. Now the entire GUI works, so I was able to go into the settings and reenable WSL2 integration with my Ubuntu instance, and I no longer had problems communicating with the socket. Everything worked. Even the rightclick menu, I was able to click "check for updates" for the first time in over a year. 

I'm not sure why I had never considered re-running the `dism` command, but it seems this was the decisive factor. I hope this helps someone who was struggling as much as I was.

**Comment by drspangle** [comment]
I thought the issue was gone but it returned, and the right-click menu stopped functioning correctly again. It may have been due to a domain-enforced updating disabling the feature which was enabled with the dism command. Regardless of the cause, I terminated Docker Desktop and re-ran `dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart` and the problem has gone away again.

**Comment by drspangle** [comment]
The problem has returned in a new form. It seems the right-click menu has changed, as there are only two items in it now: "Dashboard" and "Settings". The right-click menu appears every time, and I can click on the items. Docker for Windows consistently appears, the dashboard appears, but the settings never finish loading. I can't interact with anything, or change any settings. Nothing seems to fix the problem. I've tried reinstalling, rebooting, re-running the `dism.exe` command as before, and all permutations/combinations of these, and now I'm out of ideas. Docker for Windows is now totally unusable. I've noticed that the notification about WSL2 backend starting also no longer appears.

**Comment by mike-loux-planview** [comment]
> The problem has returned in a new form. It seems the right-click menu has changed, as there are only two items in it now: "Dashboard" and "Settings". The right-click menu appears every time, and I can click on the items. Docker for Windows consistently appears, the dashboard appears, but the settings never finish loading. I can't interact with anything, or change any settings. Nothing seems to fix the problem. I've tried reinstalling, rebooting, re-running the `dism.exe` command as before, and all permutations/combinations of these, and now I'm out of ideas. Docker for Windows is now totally unusable. I've noticed that the notification about WSL2 backend starting also no longer appears. Because I can't access the settings, I also can't access Docker from the command line in WSL, since I can't enable the WSL integration anymore.
> 
> Edit: Doing a full "factory reset" seemed to work this time. I'm not sure what combination of actions made this work. I guess I'll leave this open in case I have more problems in the near future. Hopefully I'm not back to the workaround where I have to perform this reset every time I reboot or randomly throughout the day.

I ran into the very same thing, but going into the *Troubleshoot* screen and selecting *Clean / Purge* data usually fixes it up for me.  It also brings back the "WSL2 back-end starting" screen. 

However, it only lasts until I reboot.  Then we're back to the above borkage.

So, yeah, basically Docker Desktop is completely broken.  I've just been too lazy to set up Docker directly on one of my WSL2 distros, but will likely do that at some point, because this is just the latest fiasco in a long line of Docker Desktop fiascos that has finally rendered Docker Desktop dead to me.  I just don't have the time to fight with it every damn day (even though I can usually get up and running again in about 15 minutes due to a bunch of scripts I wrote to automate most of the crap - that's still 15 minutes spent yak-shaving, and it adds up).
