### ISSUE TITLE
Docker not starting after update using WSL2 on Win10 2004

### ISSUE THREAD

**Issue by koopa** [docker/for-win#9535]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **08F450AF-23AF-4790-A5FC-7AAA304A1CF9/20201117074807**

### Expected behavior
Docker should start.

### Actual behavior
Docker fails to start with System.InvalidOperationException:
Failed to deploy distro docker-desktop to AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff

### Information
  - Windows Version: Win 10 2004
  - Docker Desktop Version: 2.5.0.21
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Update Windows 10 to 2004, Update Docker to latest Version, enable WSL2

**Comment by koopa** [comment]
Problem seems to be acrylic DNS using port 53. When i stopped the acrylic service, things worked again. 
Any ideas how i can have a custom DNS server like that? Do i need to have a DNS server running via docker? Or is there a simple way of telling windows to use non-default port for DNS requests? Or are there any other ways around this? Thanks for any help.

**Comment by prime23-gareth** [comment]
I resolved this problem on my system. It turned out that the LxssManager Windows Service had become disabled (I think due to my AntiVirus system disabling it) and this was stopping the WSL system running correctly. Access was denied to restart it. To resolve this I uninstalled the Windows Subsystem for Linux, rebooted and re-installed. (I also uninstalled/re-installed Docker and the Windows Container feature for good measure).
After that it all started working again.

**Comment by koopa** [comment]
@prime23-gareth Hello and thanks for the info! May I ask you if you also have two LxssManager services listed, one named `LxssManagerUser_2cdc1` and another one just `LxssManager` and both are running?
Here `LxssManager` is running but `LxssManagerUser_2cdc1` is not. Cheers!

**Comment by prime23-gareth** [comment]
Yes I have two. The second one is similar with a different suffix. Its NOT running and its set to Manual (Trigger Start). Docker is working fine without it started.
