### ISSUE TITLE
Upgrade docker to 2.5.01 (49550) to report errors

### ISSUE THREAD

**Issue by tony88322** [docker/for-win#9545]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tony88322** [comment]
> * [ ]  I have tried with the latest version of my channel (Stable or Edge)
> * [ ]  I have uploaded Diagnostics
> * Diagnostics ID:     39C522CC-CCAD-41B2-9957-A76A4DF10344/20201118021807
> 
> ### Expected behavior
> ### Actual behavior
> ### Information
> * Windows Version:
> * Docker Desktop Version:
> * Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
> 
> ### Steps to reproduce the behavior
> 1. ...
> 2. ...

**Comment by stephen-turner** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.
If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and a diagnostic id, following the steps at https://docs.docker.com/docker-for-windows/troubleshoot?
