### ISSUE TITLE
Crash on every windows startup

### ISSUE THREAD

**Issue by minev05** [docker/for-win#9549]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Starting normally without crashing.

### Information

  - Windows Version: Windows 10 pro 20H2 build 19042.630
  - Docker Desktop Version:  19.03.13
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Use Docker for windows with WSL 2
  2. Docker crashes on every system boot up.

**Comment by prime23-gareth** [comment]
I resolved this problem on my system. It turned out that the LxssManager Windows Service had become disabled (I think due to my AntiVirus system disabling it) and this was stopping the WSL system running correctly. Access was denied to restart it. To resolve this I uninstalled the Windows Subsystem for Linux, rebooted and re-installed. (I also uninstalled/re-installed Docker and the Windows Container feature for good measure).
After that it all started working again.
