### ISSUE TITLE
Docker not working from Powershell or command promt

### ISSUE THREAD

**Issue by ioanna-tsak** [docker/for-win#9739]
### Problem description
I am using VScode and Docker containers. I open in VScode a project I have been working on for months and lately when I click `reopen in container` i get the following error:
```Docker returned an error. Make sure the docker daemon is running```

After looking further into it (see also [here](https://github.com/microsoft/vscode-remote-release/issues/4152) and [here](https://github.com/docker/for-win/issues/9721)), I found out that I can not run any docker-related cli command. Even though the docker path (`C:\Program Files\Docker\Docker\resources\bin`) is included in the systems' variables path I get the following:
#### Running docker related commands from _cmd_ results to:

```
The system cannot execute the specified program
```

#### Running docker related commands from _Powershell_ results to:
```Program 'docker.exe' failed to run: No application is associated with the specified file for this
operationAt line:1 char:1
+ docker
+ ~~~~~~.
At line:1 char:1
+ docker
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
``` 
### What I have tried

1. Uninstall and re-install docker
  
### Information
-  Windows Version: 10
- Docker Desktop: 2.5.0.1 (latest update installed 07/12/20)
- Problem started after 3/12/20
- The problem existed both before and after the last docker update

**Comment by srbrecker** [comment]
I believe I am having the same issue except I am a new docker user. The installation seems to go fine, but the program crashes when I try to initiate it from VS Code or bash. Also tried reinstalling without success.  This is what I get even though I configured the installation w/ Hyper-V enabled (the default): 

"The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 53E96AF3-168F-4118-9622-55316C4ACE5C)"
