### ISSUE TITLE
I am getting this error while running the docker image. How can I overcome  this.

### ISSUE THREAD

**Issue by MANOJKUMAR094** [docker/for-win#9741]
time="2020-12-09T18:49:25+05:30" level=error msg="Error waiting for container: failed to shutdown container: container 010af819823735f3a0a1cace04ed85d2c6dfa26a7fb08d9aab8c6d1418fcb845 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 010af819823735f3a0a1cace04ed85d2c6dfa26a7fb08d9aab8c6d1418fcb845 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)"

**Comment by stephen-turner** [comment]
If you have an hcsshim error, then the problem is in the upstream engine, that we only bundle. So could you file your ticket in the https://github.com/moby/moby repository instead please? (Sorry, I would move the ticket if I could, but it's not possible because the engine is not in the docker organisation and you can't move tickets across orgs).
