### ISSUE TITLE
Docker fails to run on Win10Pro - Lack of VT

### ISSUE THREAD

**Issue by rbarros-daitan** [docker/for-win#975]
Actual behavior
Na screen is shown with:

"An error occurred
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled"

I have double checked and Virtualization is enabled. Cannot get additional diagnostics.

![evidences](https://user-images.githubusercontent.com/7206819/28923212-9dfe8436-7833-11e7-92ad-a5818ec46f41.png)

**Comment by jasonbivins** [comment]
Hi @rbarros-daitan 

Can you please run the debug-containerHost script located here and share the results? 
https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by friism** [comment]
Can you [check that SLAT is enabled](https://www.howtogeek.com/73318/how-to-check-if-your-cpu-supports-second-level-address-translation-slat/)? 

Please also provide details on whether you're running in a VM, etc.

**Comment by weitzhandler** [comment]
@jasonbivins Although I'm not the original author of the issue, looks like it's been neglected by the OP and so, since I'm experiencing the same issue lemme share my _Debug-ContainerHost_ results:

PS D:\users\shimmy\downloads>  .\Debug-ContainerHost.ps1
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 384ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 77ms
 [+] Is not a build with blocking issues 13ms
 [-] Has 'Containers' feature installed 40.45s
   COMException: The requested operation requires elevation.
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 23
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  40ms
 [+] Service is running 13ms
 [+] Docker.exe is in path 2.06s
 [+] Docker is registered in the EventLog service 71ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 20ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 15ms
 [+] Do not have zz values set 11ms
 [+] Do not have FDVDenyWriteAccess set to 1 9ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the
docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 41ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 115
Describing Container network is created
 [+] At least one local container network is available 1.07s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 44ms
   Expected {0} to be greater than {0}
   206:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 206
 [-] NAT Network's vSwitch is internal 22ms
   Expected: {Internal}
   But was:  {}
   211:       $switchType | Should Be "Internal"
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 211
 [+] A Windows NAT is configured if a Docker NAT network exists 211ms
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 16ms
   Expected: value to not be empty
   225:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 225
 [-] NAT Network's internal prefix does not overlap with external IP' 12ms
   Expected {0} to be greater than {0}
   252:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, D:\users\shimmy\downloads\Debug-ContainerHost.ps1: line 252
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Getting Warnings & errors in the Windows event logs from the last 24 hours
Logs saved to D:\users\shimmy\downloads\logs_20170923-224619.csv


Getting Docker for Windows daemon logs from the last execution
    Note: More logs are available at C:\Users\Shimmy\AppData\Local\Docker. Only showing the latest.
PS D:\users\shimmy\downloads>
