### ISSUE TITLE
7498254C-8D5F-4BC7-959A-D2CCF09CA749/20201219002843

### ISSUE THREAD

**Issue by TheSpeedHero** [docker/for-win#9866]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tiborvass** [comment]
Hi, sorry but without explaining what your issue is, we cannot help you effectively. I have identified thanks to your diagnostics ID, that you may be hitting #9755 which now has a workaround. Hope this helps. Closing this now but if you're still hitting your issue, try providing more information please.
